SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_POLICY', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_POLICY (
      IDPOLICY INT IDENTITY(1,1) NOT NULL,
      SUC NVARCHAR(10) NOT NULL,
      IDDEPTO INT NULL,
      TIMEZONE VARCHAR(60) NOT NULL CONSTRAINT DF_ATT_POLICY_TIMEZONE DEFAULT ('America/Mexico_City'),
      ALLOW_EARLY_MIN INT NOT NULL CONSTRAINT DF_ATT_POLICY_ALLOW_EARLY DEFAULT (15),
      ALLOW_LATE_MIN INT NOT NULL CONSTRAINT DF_ATT_POLICY_ALLOW_LATE DEFAULT (15),
      REQUIRE_GPS BIT NOT NULL CONSTRAINT DF_ATT_POLICY_REQUIRE_GPS DEFAULT (0),
      GEOFENCE_LAT DECIMAL(10,7) NULL,
      GEOFENCE_LON DECIMAL(10,7) NULL,
      GEOFENCE_RADIUS_M INT NULL,
      GPS_MAX_ACCURACY_M INT NOT NULL CONSTRAINT DF_ATT_POLICY_GPS_ACC DEFAULT (50),
      REQUIRE_LIVENESS BIT NOT NULL CONSTRAINT DF_ATT_POLICY_REQUIRE_LIVE DEFAULT (0),
      SHIFT_START TIME NULL,
      SHIFT_END TIME NULL,
      LUNCH_START TIME NULL,
      LUNCH_END TIME NULL,
      ENFORCE_WINDOWS BIT NOT NULL CONSTRAINT DF_ATT_POLICY_ENFORCE_WINDOWS DEFAULT (0),
      OVERTIME_DAILY_LIMIT_HOURS DECIMAL(5,2) NOT NULL CONSTRAINT DF_ATT_POLICY_OT_DAILY DEFAULT (3.00),
      OVERTIME_WEEKLY_LIMIT_HOURS DECIMAL(5,2) NOT NULL CONSTRAINT DF_ATT_POLICY_OT_WEEKLY DEFAULT (9.00),
      ACTIVE BIT NOT NULL CONSTRAINT DF_ATT_POLICY_ACTIVE DEFAULT (1),
      FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_ATT_POLICY_FCNR DEFAULT (SYSUTCDATETIME()),
      CONSTRAINT PK_ATT_POLICY PRIMARY KEY CLUSTERED (IDPOLICY)
    );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_POLICY_SUC'
      AND parent_object_id = OBJECT_ID('dbo.ATT_POLICY')
  )
  BEGIN
    ALTER TABLE dbo.ATT_POLICY
      WITH CHECK ADD CONSTRAINT FK_ATT_POLICY_SUC
      FOREIGN KEY (SUC) REFERENCES dbo.DAT_SUC (SUC);
  END;

  IF OBJECT_ID('dbo.DEPARTAMENTO', 'U') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM sys.foreign_keys
       WHERE name = 'FK_ATT_POLICY_DEPTO'
         AND parent_object_id = OBJECT_ID('dbo.ATT_POLICY')
     )
  BEGIN
    ALTER TABLE dbo.ATT_POLICY
      WITH CHECK ADD CONSTRAINT FK_ATT_POLICY_DEPTO
      FOREIGN KEY (IDDEPTO) REFERENCES dbo.DEPARTAMENTO (IDDEPTO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_POLICY_WINDOWS_MINUTES'
      AND parent_object_id = OBJECT_ID('dbo.ATT_POLICY')
  )
  BEGIN
    ALTER TABLE dbo.ATT_POLICY
      ADD CONSTRAINT CK_ATT_POLICY_WINDOWS_MINUTES
      CHECK (ALLOW_EARLY_MIN >= 0 AND ALLOW_LATE_MIN >= 0 AND GPS_MAX_ACCURACY_M > 0);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_POLICY_OVERTIME_LIMITS'
      AND parent_object_id = OBJECT_ID('dbo.ATT_POLICY')
  )
  BEGIN
    ALTER TABLE dbo.ATT_POLICY
      ADD CONSTRAINT CK_ATT_POLICY_OVERTIME_LIMITS
      CHECK (OVERTIME_DAILY_LIMIT_HOURS >= 0 AND OVERTIME_WEEKLY_LIMIT_HOURS >= 0);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_POLICY_GEOFENCE'
      AND parent_object_id = OBJECT_ID('dbo.ATT_POLICY')
  )
  BEGIN
    ALTER TABLE dbo.ATT_POLICY
      ADD CONSTRAINT CK_ATT_POLICY_GEOFENCE
      CHECK (
        REQUIRE_GPS = 0
        OR (
          GEOFENCE_LAT IS NOT NULL
          AND GEOFENCE_LON IS NOT NULL
          AND GEOFENCE_RADIUS_M IS NOT NULL
          AND GEOFENCE_RADIUS_M > 0
        )
      );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_ATT_POLICY_SUC_DEPTO_ACTIVE'
      AND object_id = OBJECT_ID('dbo.ATT_POLICY')
  )
  BEGIN
    CREATE UNIQUE INDEX UX_ATT_POLICY_SUC_DEPTO_ACTIVE
      ON dbo.ATT_POLICY (SUC, IDDEPTO)
      WHERE ACTIVE = 1;
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_POLICY_SUC'
      AND object_id = OBJECT_ID('dbo.ATT_POLICY')
  )
  BEGIN
    CREATE INDEX IX_ATT_POLICY_SUC
      ON dbo.ATT_POLICY (SUC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO


