SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_TIME_LOG', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_TIME_LOG (
      IDTIMELOG BIGINT IDENTITY(1,1) NOT NULL,
      IDUSUARIO INT NOT NULL,
      SUC NVARCHAR(10) NOT NULL,
      TIPO VARCHAR(20) NOT NULL,
      FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_ATT_TIME_LOG_FCNR DEFAULT (SYSUTCDATETIME()),
      FCNR_DATE AS CONVERT(DATE, FCNR) PERSISTED,
      LAT DECIMAL(10,7) NULL,
      LON DECIMAL(10,7) NULL,
      GPS_ACCURACY_M INT NULL,
      WITHIN_GEOFENCE BIT NOT NULL CONSTRAINT DF_ATT_TIME_LOG_WITHIN DEFAULT (0),
      AUTH_METHOD VARCHAR(20) NOT NULL,
      LIVENESS_OK BIT NOT NULL CONSTRAINT DF_ATT_TIME_LOG_LIVENESS DEFAULT (0),
      DEVICE_ID VARCHAR(80) NULL,
      CLIENT_IP VARCHAR(45) NULL,
      NOTES VARCHAR(250) NULL,
      LOCKED BIT NOT NULL CONSTRAINT DF_ATT_TIME_LOG_LOCKED DEFAULT (1),
      CONSTRAINT PK_ATT_TIME_LOG PRIMARY KEY CLUSTERED (IDTIMELOG)
    );
  END;

  IF COL_LENGTH('dbo.ATT_TIME_LOG', 'FCNR_DATE') IS NULL
  BEGIN
    ALTER TABLE dbo.ATT_TIME_LOG
      ADD FCNR_DATE AS CONVERT(DATE, FCNR) PERSISTED;
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_TIME_LOG_USUARIO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    ALTER TABLE dbo.ATT_TIME_LOG
      WITH CHECK ADD CONSTRAINT FK_ATT_TIME_LOG_USUARIO
      FOREIGN KEY (IDUSUARIO) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_TIME_LOG_SUC'
      AND parent_object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    ALTER TABLE dbo.ATT_TIME_LOG
      WITH CHECK ADD CONSTRAINT FK_ATT_TIME_LOG_SUC
      FOREIGN KEY (SUC) REFERENCES dbo.DAT_SUC (SUC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_TIME_LOG_TIPO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    ALTER TABLE dbo.ATT_TIME_LOG
      ADD CONSTRAINT CK_ATT_TIME_LOG_TIPO
      CHECK (TIPO IN ('ENTRADA', 'SALIDA_COMER', 'REGRESO_COMER', 'SALIDA'));
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_TIME_LOG_AUTH_METHOD'
      AND parent_object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    ALTER TABLE dbo.ATT_TIME_LOG
      ADD CONSTRAINT CK_ATT_TIME_LOG_AUTH_METHOD
      CHECK (AUTH_METHOD IN ('FACE', 'FINGER', 'PIN'));
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_TIME_LOG_GPS_ACC'
      AND parent_object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    ALTER TABLE dbo.ATT_TIME_LOG
      ADD CONSTRAINT CK_ATT_TIME_LOG_GPS_ACC
      CHECK (GPS_ACCURACY_M IS NULL OR GPS_ACCURACY_M >= 0);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_TIME_LOG_USER_FC'
      AND object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    CREATE INDEX IX_ATT_TIME_LOG_USER_FC
      ON dbo.ATT_TIME_LOG (IDUSUARIO ASC, FCNR DESC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_TIME_LOG_SUC_FC'
      AND object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    CREATE INDEX IX_ATT_TIME_LOG_SUC_FC
      ON dbo.ATT_TIME_LOG (SUC ASC, FCNR DESC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_TIME_LOG_USER_DATE'
      AND object_id = OBJECT_ID('dbo.ATT_TIME_LOG')
  )
  BEGIN
    CREATE INDEX IX_ATT_TIME_LOG_USER_DATE
      ON dbo.ATT_TIME_LOG (IDUSUARIO ASC, FCNR_DATE ASC, FCNR DESC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO


