SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_BIOMETRIC_TEMPLATE', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_BIOMETRIC_TEMPLATE (
      IDBIO BIGINT IDENTITY(1,1) NOT NULL,
      IDUSUARIO INT NOT NULL,
      TIPO VARCHAR(20) NOT NULL,
      TEMPLATE VARBINARY(MAX) NOT NULL,
      HASH VARCHAR(64) NULL,
      ACTIVE BIT NOT NULL CONSTRAINT DF_ATT_BIOMETRIC_TEMPLATE_ACTIVE DEFAULT (1),
      FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_ATT_BIOMETRIC_TEMPLATE_FCNR DEFAULT (SYSUTCDATETIME()),
      CONSTRAINT PK_ATT_BIOMETRIC_TEMPLATE PRIMARY KEY CLUSTERED (IDBIO)
    );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_BIOMETRIC_TEMPLATE_USUARIO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_BIOMETRIC_TEMPLATE')
  )
  BEGIN
    ALTER TABLE dbo.ATT_BIOMETRIC_TEMPLATE
      WITH CHECK ADD CONSTRAINT FK_ATT_BIOMETRIC_TEMPLATE_USUARIO
      FOREIGN KEY (IDUSUARIO) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_BIOMETRIC_TEMPLATE_TIPO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_BIOMETRIC_TEMPLATE')
  )
  BEGIN
    ALTER TABLE dbo.ATT_BIOMETRIC_TEMPLATE
      ADD CONSTRAINT CK_ATT_BIOMETRIC_TEMPLATE_TIPO
      CHECK (TIPO IN ('FACE', 'FINGER'));
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_BIO_USER'
      AND object_id = OBJECT_ID('dbo.ATT_BIOMETRIC_TEMPLATE')
  )
  BEGIN
    CREATE INDEX IX_ATT_BIO_USER
      ON dbo.ATT_BIOMETRIC_TEMPLATE (IDUSUARIO ASC, TIPO ASC, ACTIVE ASC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
