SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_INCIDENCIA', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_INCIDENCIA (
      IDINC BIGINT IDENTITY(1,1) NOT NULL,
      IDUSUARIO INT NOT NULL,
      SUC NVARCHAR(10) NOT NULL,
      TIPO VARCHAR(30) NOT NULL,
      FECHA_INI DATE NOT NULL,
      FECHA_FIN DATE NOT NULL,
      MOTIVO NVARCHAR(250) NULL,
      ESTATUS VARCHAR(20) NOT NULL CONSTRAINT DF_ATT_INCIDENCIA_ESTATUS DEFAULT ('SOLICITADA'),
      APROBADA_POR INT NULL,
      FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_ATT_INCIDENCIA_FCNR DEFAULT (SYSUTCDATETIME()),
      CONSTRAINT PK_ATT_INCIDENCIA PRIMARY KEY CLUSTERED (IDINC)
    );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_INCIDENCIA_USUARIO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_INCIDENCIA
      WITH CHECK ADD CONSTRAINT FK_ATT_INCIDENCIA_USUARIO
      FOREIGN KEY (IDUSUARIO) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_INCIDENCIA_APROBADA_POR'
      AND parent_object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_INCIDENCIA
      WITH CHECK ADD CONSTRAINT FK_ATT_INCIDENCIA_APROBADA_POR
      FOREIGN KEY (APROBADA_POR) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_INCIDENCIA_SUC'
      AND parent_object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_INCIDENCIA
      WITH CHECK ADD CONSTRAINT FK_ATT_INCIDENCIA_SUC
      FOREIGN KEY (SUC) REFERENCES dbo.DAT_SUC (SUC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_INCIDENCIA_TIPO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_INCIDENCIA
      ADD CONSTRAINT CK_ATT_INCIDENCIA_TIPO
      CHECK (TIPO IN ('VACACIONES', 'PERMISO_GOCE', 'PERMISO_SIN_GOCE', 'INCAPACIDAD', 'FALTA', 'RETARDO', 'OTRO'));
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_INCIDENCIA_ESTATUS'
      AND parent_object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_INCIDENCIA
      ADD CONSTRAINT CK_ATT_INCIDENCIA_ESTATUS
      CHECK (ESTATUS IN ('SOLICITADA', 'APROBADA', 'RECHAZADA', 'CERRADA'));
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_INCIDENCIA_FECHAS'
      AND parent_object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_INCIDENCIA
      ADD CONSTRAINT CK_ATT_INCIDENCIA_FECHAS
      CHECK (FECHA_FIN >= FECHA_INI);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_INCIDENCIA_USER_FECHA'
      AND object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    CREATE INDEX IX_ATT_INCIDENCIA_USER_FECHA
      ON dbo.ATT_INCIDENCIA (IDUSUARIO ASC, FECHA_INI ASC, FECHA_FIN ASC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_INCIDENCIA_SUC_FECHA'
      AND object_id = OBJECT_ID('dbo.ATT_INCIDENCIA')
  )
  BEGIN
    CREATE INDEX IX_ATT_INCIDENCIA_SUC_FECHA
      ON dbo.ATT_INCIDENCIA (SUC ASC, FECHA_INI ASC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO


