SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_DOCUMENTO', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_DOCUMENTO (
      IDDOC BIGINT IDENTITY(1,1) NOT NULL,
      IDUSUARIO INT NOT NULL,
      IDINC BIGINT NULL,
      SUC NVARCHAR(10) NOT NULL,
      TIPO VARCHAR(30) NOT NULL,
      FILE_NAME NVARCHAR(160) NOT NULL,
      MIME_TYPE NVARCHAR(80) NOT NULL,
      FILE_SIZE INT NOT NULL,
      CONTENT VARBINARY(MAX) NOT NULL,
      SHA256 VARCHAR(64) NULL,
      FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_ATT_DOCUMENTO_FCNR DEFAULT (SYSUTCDATETIME()),
      CONSTRAINT PK_ATT_DOCUMENTO PRIMARY KEY CLUSTERED (IDDOC)
    );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_DOCUMENTO_USUARIO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_DOCUMENTO')
  )
  BEGIN
    ALTER TABLE dbo.ATT_DOCUMENTO
      WITH CHECK ADD CONSTRAINT FK_ATT_DOCUMENTO_USUARIO
      FOREIGN KEY (IDUSUARIO) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_DOCUMENTO_INCIDENCIA'
      AND parent_object_id = OBJECT_ID('dbo.ATT_DOCUMENTO')
  )
  BEGIN
    ALTER TABLE dbo.ATT_DOCUMENTO
      WITH CHECK ADD CONSTRAINT FK_ATT_DOCUMENTO_INCIDENCIA
      FOREIGN KEY (IDINC) REFERENCES dbo.ATT_INCIDENCIA (IDINC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_DOCUMENTO_SUC'
      AND parent_object_id = OBJECT_ID('dbo.ATT_DOCUMENTO')
  )
  BEGIN
    ALTER TABLE dbo.ATT_DOCUMENTO
      WITH CHECK ADD CONSTRAINT FK_ATT_DOCUMENTO_SUC
      FOREIGN KEY (SUC) REFERENCES dbo.DAT_SUC (SUC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_DOCUMENTO_TIPO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_DOCUMENTO')
  )
  BEGIN
    ALTER TABLE dbo.ATT_DOCUMENTO
      ADD CONSTRAINT CK_ATT_DOCUMENTO_TIPO
      CHECK (TIPO IN ('EXPEDIENTE', 'JUSTIFICANTE', 'INE', 'CONTRATO', 'OTRO'));
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_DOCUMENTO_FILE_SIZE'
      AND parent_object_id = OBJECT_ID('dbo.ATT_DOCUMENTO')
  )
  BEGIN
    ALTER TABLE dbo.ATT_DOCUMENTO
      ADD CONSTRAINT CK_ATT_DOCUMENTO_FILE_SIZE
      CHECK (FILE_SIZE > 0);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_DOC_USER'
      AND object_id = OBJECT_ID('dbo.ATT_DOCUMENTO')
  )
  BEGIN
    CREATE INDEX IX_ATT_DOC_USER
      ON dbo.ATT_DOCUMENTO (IDUSUARIO ASC, FCNR DESC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_DOC_INC'
      AND object_id = OBJECT_ID('dbo.ATT_DOCUMENTO')
  )
  BEGIN
    CREATE INDEX IX_ATT_DOC_INC
      ON dbo.ATT_DOCUMENTO (IDINC ASC, FCNR DESC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO


