SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_OVERRIDE', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_OVERRIDE (
      IDOVR BIGINT IDENTITY(1,1) NOT NULL,
      IDUSUARIO INT NOT NULL,
      SUC NVARCHAR(10) NOT NULL,
      TIPO VARCHAR(30) NOT NULL,
      REASON NVARCHAR(250) NOT NULL,
      AUTH_BY INT NOT NULL,
      VALID_UNTIL DATETIME2(0) NOT NULL,
      FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_ATT_OVERRIDE_FCNR DEFAULT (SYSUTCDATETIME()),
      CONSTRAINT PK_ATT_OVERRIDE PRIMARY KEY CLUSTERED (IDOVR)
    );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_OVERRIDE_USUARIO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_OVERRIDE')
  )
  BEGIN
    ALTER TABLE dbo.ATT_OVERRIDE
      WITH CHECK ADD CONSTRAINT FK_ATT_OVERRIDE_USUARIO
      FOREIGN KEY (IDUSUARIO) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_OVERRIDE_AUTH_BY'
      AND parent_object_id = OBJECT_ID('dbo.ATT_OVERRIDE')
  )
  BEGIN
    ALTER TABLE dbo.ATT_OVERRIDE
      WITH CHECK ADD CONSTRAINT FK_ATT_OVERRIDE_AUTH_BY
      FOREIGN KEY (AUTH_BY) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_OVERRIDE_SUC'
      AND parent_object_id = OBJECT_ID('dbo.ATT_OVERRIDE')
  )
  BEGIN
    ALTER TABLE dbo.ATT_OVERRIDE
      WITH CHECK ADD CONSTRAINT FK_ATT_OVERRIDE_SUC
      FOREIGN KEY (SUC) REFERENCES dbo.DAT_SUC (SUC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_ATT_OVERRIDE_TIPO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_OVERRIDE')
  )
  BEGIN
    ALTER TABLE dbo.ATT_OVERRIDE
      ADD CONSTRAINT CK_ATT_OVERRIDE_TIPO
      CHECK (TIPO IN ('OUT_OF_WINDOW', 'OUT_OF_GEOFENCE', 'SEQUENCE_OVERRIDE'));
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_OVERRIDE_USER_VALID'
      AND object_id = OBJECT_ID('dbo.ATT_OVERRIDE')
  )
  BEGIN
    CREATE INDEX IX_ATT_OVERRIDE_USER_VALID
      ON dbo.ATT_OVERRIDE (IDUSUARIO ASC, VALID_UNTIL ASC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO


