SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_ALERTA', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_ALERTA (
      IDALERTA BIGINT IDENTITY(1,1) NOT NULL,
      IDUSUARIO INT NOT NULL,
      SUC NVARCHAR(10) NOT NULL,
      TIPO VARCHAR(30) NOT NULL,
      MESSAGE NVARCHAR(250) NOT NULL,
      METADATA_JSON NVARCHAR(MAX) NULL,
      FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_ATT_ALERTA_FCNR DEFAULT (SYSUTCDATETIME()),
      CONSTRAINT PK_ATT_ALERTA PRIMARY KEY CLUSTERED (IDALERTA)
    );
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_ALERTA_USUARIO'
      AND parent_object_id = OBJECT_ID('dbo.ATT_ALERTA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_ALERTA
      WITH CHECK ADD CONSTRAINT FK_ATT_ALERTA_USUARIO
      FOREIGN KEY (IDUSUARIO) REFERENCES dbo.USUARIO (IDUSUARIO);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ATT_ALERTA_SUC'
      AND parent_object_id = OBJECT_ID('dbo.ATT_ALERTA')
  )
  BEGIN
    ALTER TABLE dbo.ATT_ALERTA
      WITH CHECK ADD CONSTRAINT FK_ATT_ALERTA_SUC
      FOREIGN KEY (SUC) REFERENCES dbo.DAT_SUC (SUC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ATT_ALERTA_USER_FC'
      AND object_id = OBJECT_ID('dbo.ATT_ALERTA')
  )
  BEGIN
    CREATE INDEX IX_ATT_ALERTA_USER_FC
      ON dbo.ATT_ALERTA (IDUSUARIO ASC, FCNR DESC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO


