CREATE OR ALTER PROCEDURE dbo.sp_att_policy_upsert
  @SUC NVARCHAR(10),
  @IDDEPTO INT = NULL,
  @TIMEZONE VARCHAR(60) = 'America/Mexico_City',
  @ALLOW_EARLY_MIN INT = 15,
  @ALLOW_LATE_MIN INT = 15,
  @REQUIRE_GPS BIT = 0,
  @GEOFENCE_LAT DECIMAL(10,7) = NULL,
  @GEOFENCE_LON DECIMAL(10,7) = NULL,
  @GEOFENCE_RADIUS_M INT = NULL,
  @GPS_MAX_ACCURACY_M INT = 50,
  @REQUIRE_LIVENESS BIT = 0,
  @SHIFT_START TIME = NULL,
  @SHIFT_END TIME = NULL,
  @LUNCH_START TIME = NULL,
  @LUNCH_END TIME = NULL,
  @ENFORCE_WINDOWS BIT = 0,
  @OVERTIME_DAILY_LIMIT_HOURS DECIMAL(5,2) = 3.00,
  @OVERTIME_WEEKLY_LIMIT_HOURS DECIMAL(5,2) = 9.00,
  @ACTIVE BIT = 1
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  DECLARE @idPolicy INT;
  DECLARE @sucNorm NVARCHAR(10) = LTRIM(RTRIM(ISNULL(@SUC, '')));

  IF @sucNorm = ''
    THROW 52001, 'SUC es requerido para la policy', 1;

  IF NOT EXISTS (SELECT 1 FROM dbo.DAT_SUC WHERE SUC = @sucNorm)
    THROW 52002, 'La SUC no existe en DAT_SUC', 1;

  IF @IDDEPTO IS NOT NULL
     AND OBJECT_ID('dbo.DEPARTAMENTO', 'U') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM dbo.DEPARTAMENTO WHERE IDDEPTO = @IDDEPTO)
    THROW 52003, 'El departamento indicado no existe', 1;

  BEGIN TRANSACTION;

  SELECT TOP 1
    @idPolicy = p.IDPOLICY
  FROM dbo.ATT_POLICY p WITH (UPDLOCK, HOLDLOCK)
  WHERE p.SUC = @sucNorm
    AND (
      (p.IDDEPTO = @IDDEPTO)
      OR (p.IDDEPTO IS NULL AND @IDDEPTO IS NULL)
    )
    AND p.ACTIVE = 1
  ORDER BY p.IDPOLICY DESC;

  IF @idPolicy IS NULL
  BEGIN
    INSERT INTO dbo.ATT_POLICY (
      SUC,
      IDDEPTO,
      TIMEZONE,
      ALLOW_EARLY_MIN,
      ALLOW_LATE_MIN,
      REQUIRE_GPS,
      GEOFENCE_LAT,
      GEOFENCE_LON,
      GEOFENCE_RADIUS_M,
      GPS_MAX_ACCURACY_M,
      REQUIRE_LIVENESS,
      SHIFT_START,
      SHIFT_END,
      LUNCH_START,
      LUNCH_END,
      ENFORCE_WINDOWS,
      OVERTIME_DAILY_LIMIT_HOURS,
      OVERTIME_WEEKLY_LIMIT_HOURS,
      ACTIVE
    )
    VALUES (
      @sucNorm,
      @IDDEPTO,
      COALESCE(NULLIF(LTRIM(RTRIM(@TIMEZONE)), ''), 'America/Mexico_City'),
      COALESCE(@ALLOW_EARLY_MIN, 15),
      COALESCE(@ALLOW_LATE_MIN, 15),
      COALESCE(@REQUIRE_GPS, 0),
      @GEOFENCE_LAT,
      @GEOFENCE_LON,
      @GEOFENCE_RADIUS_M,
      COALESCE(@GPS_MAX_ACCURACY_M, 50),
      COALESCE(@REQUIRE_LIVENESS, 0),
      @SHIFT_START,
      @SHIFT_END,
      @LUNCH_START,
      @LUNCH_END,
      COALESCE(@ENFORCE_WINDOWS, 0),
      COALESCE(@OVERTIME_DAILY_LIMIT_HOURS, 3.00),
      COALESCE(@OVERTIME_WEEKLY_LIMIT_HOURS, 9.00),
      COALESCE(@ACTIVE, 1)
    );

    SET @idPolicy = SCOPE_IDENTITY();
  END
  ELSE
  BEGIN
    UPDATE dbo.ATT_POLICY
    SET
      TIMEZONE = COALESCE(NULLIF(LTRIM(RTRIM(@TIMEZONE)), ''), TIMEZONE),
      ALLOW_EARLY_MIN = COALESCE(@ALLOW_EARLY_MIN, ALLOW_EARLY_MIN),
      ALLOW_LATE_MIN = COALESCE(@ALLOW_LATE_MIN, ALLOW_LATE_MIN),
      REQUIRE_GPS = COALESCE(@REQUIRE_GPS, REQUIRE_GPS),
      GEOFENCE_LAT = @GEOFENCE_LAT,
      GEOFENCE_LON = @GEOFENCE_LON,
      GEOFENCE_RADIUS_M = @GEOFENCE_RADIUS_M,
      GPS_MAX_ACCURACY_M = COALESCE(@GPS_MAX_ACCURACY_M, GPS_MAX_ACCURACY_M),
      REQUIRE_LIVENESS = COALESCE(@REQUIRE_LIVENESS, REQUIRE_LIVENESS),
      SHIFT_START = @SHIFT_START,
      SHIFT_END = @SHIFT_END,
      LUNCH_START = @LUNCH_START,
      LUNCH_END = @LUNCH_END,
      ENFORCE_WINDOWS = COALESCE(@ENFORCE_WINDOWS, ENFORCE_WINDOWS),
      OVERTIME_DAILY_LIMIT_HOURS = COALESCE(@OVERTIME_DAILY_LIMIT_HOURS, OVERTIME_DAILY_LIMIT_HOURS),
      OVERTIME_WEEKLY_LIMIT_HOURS = COALESCE(@OVERTIME_WEEKLY_LIMIT_HOURS, OVERTIME_WEEKLY_LIMIT_HOURS),
      ACTIVE = COALESCE(@ACTIVE, ACTIVE)
    WHERE IDPOLICY = @idPolicy;
  END;

  IF COALESCE(@ACTIVE, 1) = 1
  BEGIN
    UPDATE dbo.ATT_POLICY
    SET ACTIVE = 0
    WHERE IDPOLICY <> @idPolicy
      AND SUC = @sucNorm
      AND (
        (IDDEPTO = @IDDEPTO)
        OR (IDDEPTO IS NULL AND @IDDEPTO IS NULL)
      )
      AND ACTIVE = 1;
  END;

  COMMIT TRANSACTION;

  SELECT TOP 1
    IDPOLICY,
    SUC,
    IDDEPTO,
    TIMEZONE,
    ALLOW_EARLY_MIN,
    ALLOW_LATE_MIN,
    REQUIRE_GPS,
    GEOFENCE_LAT,
    GEOFENCE_LON,
    GEOFENCE_RADIUS_M,
    GPS_MAX_ACCURACY_M,
    REQUIRE_LIVENESS,
    SHIFT_START,
    SHIFT_END,
    LUNCH_START,
    LUNCH_END,
    ENFORCE_WINDOWS,
    OVERTIME_DAILY_LIMIT_HOURS,
    OVERTIME_WEEKLY_LIMIT_HOURS,
    ACTIVE,
    FCNR
  FROM dbo.ATT_POLICY
  WHERE IDPOLICY = @idPolicy;
END;
GO


