CREATE OR ALTER PROCEDURE dbo.sp_att_policy_get
  @SUC NVARCHAR(10),
  @IDDEPTO INT = NULL,
  @IDUSUARIO INT = NULL
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @sucNorm NVARCHAR(10) = LTRIM(RTRIM(ISNULL(@SUC, '')));
  DECLARE @deptoResolved INT = @IDDEPTO;

  IF @sucNorm = ''
    THROW 52011, 'SUC es requerido para consultar policy', 1;

  IF @deptoResolved IS NULL AND @IDUSUARIO IS NOT NULL
  BEGIN
    SELECT TOP 1
      @deptoResolved = TRY_CONVERT(INT, u.IDDEPTO)
    FROM dbo.USUARIO u
    WHERE u.IDUSUARIO = @IDUSUARIO;
  END;

  ;WITH EffectivePolicy AS (
    SELECT TOP 1
      p.IDPOLICY,
      p.SUC,
      p.IDDEPTO,
      p.TIMEZONE,
      p.ALLOW_EARLY_MIN,
      p.ALLOW_LATE_MIN,
      p.REQUIRE_GPS,
      p.GEOFENCE_LAT,
      p.GEOFENCE_LON,
      p.GEOFENCE_RADIUS_M,
      p.GPS_MAX_ACCURACY_M,
      p.REQUIRE_LIVENESS,
      p.SHIFT_START,
      p.SHIFT_END,
      p.LUNCH_START,
      p.LUNCH_END,
      p.ENFORCE_WINDOWS,
      p.OVERTIME_DAILY_LIMIT_HOURS,
      p.OVERTIME_WEEKLY_LIMIT_HOURS,
      p.ACTIVE,
      p.FCNR
    FROM dbo.ATT_POLICY p
    WHERE p.SUC = @sucNorm
      AND p.ACTIVE = 1
      AND (
        (@deptoResolved IS NOT NULL AND p.IDDEPTO = @deptoResolved)
        OR p.IDDEPTO IS NULL
      )
    ORDER BY CASE WHEN p.IDDEPTO = @deptoResolved THEN 0 ELSE 1 END, p.IDPOLICY DESC
  )
  SELECT
    IDPOLICY,
    SUC,
    IDDEPTO,
    TIMEZONE,
    ALLOW_EARLY_MIN,
    ALLOW_LATE_MIN,
    REQUIRE_GPS,
    GEOFENCE_LAT,
    GEOFENCE_LON,
    GEOFENCE_RADIUS_M,
    GPS_MAX_ACCURACY_M,
    REQUIRE_LIVENESS,
    SHIFT_START,
    SHIFT_END,
    LUNCH_START,
    LUNCH_END,
    ENFORCE_WINDOWS,
    OVERTIME_DAILY_LIMIT_HOURS,
    OVERTIME_WEEKLY_LIMIT_HOURS,
    ACTIVE,
    FCNR,
    1 AS IS_DB_POLICY
  FROM EffectivePolicy

  UNION ALL

  SELECT
    NULL AS IDPOLICY,
    @sucNorm AS SUC,
    @deptoResolved AS IDDEPTO,
    'America/Mexico_City' AS TIMEZONE,
    15 AS ALLOW_EARLY_MIN,
    15 AS ALLOW_LATE_MIN,
    0 AS REQUIRE_GPS,
    NULL AS GEOFENCE_LAT,
    NULL AS GEOFENCE_LON,
    NULL AS GEOFENCE_RADIUS_M,
    50 AS GPS_MAX_ACCURACY_M,
    0 AS REQUIRE_LIVENESS,
    NULL AS SHIFT_START,
    NULL AS SHIFT_END,
    NULL AS LUNCH_START,
    NULL AS LUNCH_END,
    0 AS ENFORCE_WINDOWS,
    CAST(3.00 AS DECIMAL(5,2)) AS OVERTIME_DAILY_LIMIT_HOURS,
    CAST(9.00 AS DECIMAL(5,2)) AS OVERTIME_WEEKLY_LIMIT_HOURS,
    1 AS ACTIVE,
    SYSUTCDATETIME() AS FCNR,
    0 AS IS_DB_POLICY
  WHERE NOT EXISTS (SELECT 1 FROM EffectivePolicy);
END;
GO


