CREATE OR ALTER PROCEDURE dbo.sp_att_timelog_list
  @SUC NVARCHAR(10) = NULL,
  @IDUSUARIO INT = NULL,
  @IDDEPTO INT = NULL,
  @DATE_FROM DATE = NULL,
  @DATE_TO DATE = NULL,
  @PAGE INT = 1,
  @LIMIT INT = 100
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @sucNorm NVARCHAR(10) = NULLIF(LTRIM(RTRIM(ISNULL(@SUC, ''))), '');
  DECLARE @safePage INT = CASE WHEN ISNULL(@PAGE, 0) < 1 THEN 1 ELSE @PAGE END;
  DECLARE @safeLimit INT = CASE
    WHEN ISNULL(@LIMIT, 0) < 1 THEN 100
    WHEN @LIMIT > 500 THEN 500
    ELSE @LIMIT
  END;

  SELECT
    tl.IDTIMELOG,
    tl.IDUSUARIO,
    u.IDDEPTO AS USER_IDDEPTO,
    u.USERNAME,
    LTRIM(RTRIM(CONCAT(ISNULL(u.NOMBRE, ''), ' ', ISNULL(u.APELLIDOS, '')))) AS NOMBRE_COMPLETO,
    tl.SUC,
    tl.TIPO,
    tl.FCNR,
    tl.LAT,
    tl.LON,
    tl.GPS_ACCURACY_M,
    tl.WITHIN_GEOFENCE,
    tl.AUTH_METHOD,
    tl.LIVENESS_OK,
    tl.DEVICE_ID,
    tl.CLIENT_IP,
    tl.NOTES,
    tl.LOCKED,
    COUNT(1) OVER() AS TOTAL_COUNT
  FROM dbo.ATT_TIME_LOG tl
  LEFT JOIN dbo.USUARIO u ON u.IDUSUARIO = tl.IDUSUARIO
  WHERE (@IDUSUARIO IS NULL OR tl.IDUSUARIO = @IDUSUARIO)
    AND (@IDDEPTO IS NULL OR TRY_CONVERT(INT, u.IDDEPTO) = @IDDEPTO)
    AND (@sucNorm IS NULL OR tl.SUC = @sucNorm)
    AND (@DATE_FROM IS NULL OR CONVERT(DATE, tl.FCNR) >= @DATE_FROM)
    AND (@DATE_TO IS NULL OR CONVERT(DATE, tl.FCNR) <= @DATE_TO)
  ORDER BY tl.FCNR DESC
  OFFSET (@safePage - 1) * @safeLimit ROWS
  FETCH NEXT @safeLimit ROWS ONLY;
END;
GO


