SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.SUCURSALES', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.SUCURSALES (
      id INT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_SUCURSALES PRIMARY KEY CLUSTERED,
      codigo VARCHAR(30) NOT NULL,
      nombre VARCHAR(160) NOT NULL,
      empresa VARCHAR(160) NOT NULL,
      estado BIT NOT NULL
        CONSTRAINT DF_SUCURSALES_estado DEFAULT (1)
    );

    CREATE UNIQUE INDEX UX_SUCURSALES_codigo
      ON dbo.SUCURSALES (codigo);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
