SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.LOGS_AUDITORIA', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.LOGS_AUDITORIA (
      id INT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_LOGS_AUDITORIA PRIMARY KEY CLUSTERED,
      admin_id INT NULL,
      accion VARCHAR(40) NOT NULL,
      modulo VARCHAR(100) NOT NULL,
      ip_origen VARCHAR(64) NULL,
      detalles VARCHAR(MAX) NULL,
      fecha DATETIME NOT NULL
        CONSTRAINT DF_LOGS_AUDITORIA_fecha DEFAULT (GETDATE())
    );

    CREATE INDEX IX_LOGS_AUDITORIA_fecha
      ON dbo.LOGS_AUDITORIA (fecha DESC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
