SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.COMANDOS_ADMS', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.COMANDOS_ADMS (
      id INT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_COMANDOS_ADMS PRIMARY KEY CLUSTERED,
      dispositivo_id VARCHAR(80) NOT NULL,
      comando VARCHAR(MAX) NOT NULL,
      estado VARCHAR(20) NOT NULL
        CONSTRAINT DF_COMANDOS_ADMS_estado DEFAULT ('PENDIENTE'),
      fecha_creacion DATETIME NOT NULL
        CONSTRAINT DF_COMANDOS_ADMS_fecha_creacion DEFAULT (GETDATE())
    );

    CREATE INDEX IX_COMANDOS_ADMS_estado_fecha
      ON dbo.COMANDOS_ADMS (estado ASC, fecha_creacion DESC);

    CREATE INDEX IX_COMANDOS_ADMS_dispositivo
      ON dbo.COMANDOS_ADMS (dispositivo_id ASC, fecha_creacion DESC);
  END;

  IF COL_LENGTH('dbo.SUCURSALES', 'latitud') IS NULL
  BEGIN
    ALTER TABLE dbo.SUCURSALES
      ADD latitud FLOAT NULL;
  END;

  IF COL_LENGTH('dbo.SUCURSALES', 'longitud') IS NULL
  BEGIN
    ALTER TABLE dbo.SUCURSALES
      ADD longitud FLOAT NULL;
  END;

  IF COL_LENGTH('dbo.SUCURSALES', 'radio_metros') IS NULL
  BEGIN
    ALTER TABLE dbo.SUCURSALES
      ADD radio_metros INT NULL;
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
