SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.ATT_ASISTENCIA_FOTO', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.ATT_ASISTENCIA_FOTO (
      id INT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_ATT_ASISTENCIA_FOTO PRIMARY KEY CLUSTERED,
      id_timelog BIGINT NULL,
      id_usuario INT NOT NULL,
      suc VARCHAR(10) NULL,
      ruta_archivo VARCHAR(500) NOT NULL,
      mime_type VARCHAR(100) NULL,
      sha256 VARCHAR(64) NULL,
      fecha_creacion DATETIME NOT NULL
        CONSTRAINT DF_ATT_ASISTENCIA_FOTO_fecha DEFAULT (GETDATE())
    );

    CREATE INDEX IX_ATT_ASISTENCIA_FOTO_fecha
      ON dbo.ATT_ASISTENCIA_FOTO (fecha_creacion DESC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
