SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.COMANDOS_ADMS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.COMANDOS_ADMS (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COMANDOS_ADMS PRIMARY KEY,
    dispositivo_id VARCHAR(100) NOT NULL,
    comando VARCHAR(500) NOT NULL,
    estado VARCHAR(20) NOT NULL CONSTRAINT DF_COMANDOS_ADMS_estado DEFAULT ('PENDIENTE'),
    fecha_creacion DATETIME NOT NULL CONSTRAINT DF_COMANDOS_ADMS_fecha DEFAULT (GETDATE())
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_COMANDOS_ADMS_estado_fecha'
    AND object_id = OBJECT_ID('dbo.COMANDOS_ADMS')
)
BEGIN
  CREATE INDEX IX_COMANDOS_ADMS_estado_fecha
    ON dbo.COMANDOS_ADMS (estado, fecha_creacion DESC);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_COMANDOS_ADMS_dispositivo'
    AND object_id = OBJECT_ID('dbo.COMANDOS_ADMS')
)
BEGIN
  CREATE INDEX IX_COMANDOS_ADMS_dispositivo
    ON dbo.COMANDOS_ADMS (dispositivo_id);
END;
GO

IF COL_LENGTH('dbo.SUCURSALES', 'latitud') IS NULL
BEGIN
  ALTER TABLE dbo.SUCURSALES ADD latitud FLOAT NULL;
END;
GO

IF COL_LENGTH('dbo.SUCURSALES', 'longitud') IS NULL
BEGIN
  ALTER TABLE dbo.SUCURSALES ADD longitud FLOAT NULL;
END;
GO

IF COL_LENGTH('dbo.SUCURSALES', 'radio_metros') IS NULL
BEGIN
  ALTER TABLE dbo.SUCURSALES ADD radio_metros INT NULL;
END;
GO

IF OBJECT_ID('dbo.ATT_ASISTENCIA_FOTO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ATT_ASISTENCIA_FOTO (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ATT_ASISTENCIA_FOTO PRIMARY KEY,
    id_timelog BIGINT NULL,
    id_usuario INT NOT NULL,
    suc VARCHAR(10) NOT NULL,
    ruta_archivo VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    fecha_creacion DATETIME NOT NULL CONSTRAINT DF_ATT_ASISTENCIA_FOTO_fecha DEFAULT (GETDATE())
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_ATT_ASISTENCIA_FOTO_fecha'
    AND object_id = OBJECT_ID('dbo.ATT_ASISTENCIA_FOTO')
)
BEGIN
  CREATE INDEX IX_ATT_ASISTENCIA_FOTO_fecha
    ON dbo.ATT_ASISTENCIA_FOTO (fecha_creacion DESC);
END;
GO
