SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.COLABORADORES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.COLABORADORES (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COLABORADORES PRIMARY KEY,
    pin VARCHAR(100) NOT NULL,
    secure_pin VARCHAR(100) NULL,
    nombre VARCHAR(120) NOT NULL,
    apellido VARCHAR(120) NOT NULL,
    sucursal_id INT NOT NULL,
    privilegio INT NOT NULL CONSTRAINT DF_COLABORADORES_privilegio DEFAULT (0),
    estado BIT NOT NULL CONSTRAINT DF_COLABORADORES_estado DEFAULT (1),
    app_access BIT NOT NULL CONSTRAINT DF_COLABORADORES_app_access DEFAULT (1),
    gps_allowed BIT NOT NULL CONSTRAINT DF_COLABORADORES_gps_allowed DEFAULT (0),
    qr_allowed BIT NOT NULL CONSTRAINT DF_COLABORADORES_qr_allowed DEFAULT (0)
  );
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'pin') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD pin VARCHAR(100) NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'pin') IS NOT NULL
BEGIN
  DECLARE @pinLengthSmall BIT = 0;
  SELECT TOP 1
    @pinLengthSmall = CASE WHEN c.max_length < 100 THEN 1 ELSE 0 END
  FROM sys.columns c
  INNER JOIN sys.objects o
    ON o.object_id = c.object_id
  WHERE o.object_id = OBJECT_ID('dbo.COLABORADORES')
    AND c.name = 'pin';

  IF @pinLengthSmall = 1
  BEGIN
    ALTER TABLE dbo.COLABORADORES ALTER COLUMN pin VARCHAR(100) NOT NULL;
  END;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'secure_pin') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD secure_pin VARCHAR(100) NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'secure_pin') IS NOT NULL
BEGIN
  DECLARE @securePinLengthSmall BIT = 0;
  SELECT TOP 1
    @securePinLengthSmall = CASE WHEN c.max_length < 100 THEN 1 ELSE 0 END
  FROM sys.columns c
  INNER JOIN sys.objects o
    ON o.object_id = c.object_id
  WHERE o.object_id = OBJECT_ID('dbo.COLABORADORES')
    AND c.name = 'secure_pin';

  IF @securePinLengthSmall = 1
  BEGIN
    ALTER TABLE dbo.COLABORADORES ALTER COLUMN secure_pin VARCHAR(100) NULL;
  END;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'nombre') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD nombre VARCHAR(120) NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'apellido') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD apellido VARCHAR(120) NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'sucursal_id') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD sucursal_id INT NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'privilegio') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD privilegio INT NOT NULL CONSTRAINT DF_COLABORADORES_privilegio DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'estado') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD estado BIT NOT NULL CONSTRAINT DF_COLABORADORES_estado DEFAULT (1);
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'app_access') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD app_access BIT NOT NULL CONSTRAINT DF_COLABORADORES_app_access DEFAULT (1);
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'gps_allowed') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD gps_allowed BIT NOT NULL CONSTRAINT DF_COLABORADORES_gps_allowed DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'qr_allowed') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD qr_allowed BIT NOT NULL CONSTRAINT DF_COLABORADORES_qr_allowed DEFAULT (0);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UQ_COLABORADORES_pin'
    AND object_id = OBJECT_ID('dbo.COLABORADORES')
)
BEGIN
  CREATE UNIQUE INDEX UQ_COLABORADORES_pin
    ON dbo.COLABORADORES (pin);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_COLABORADORES_SUCURSALES'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD CONSTRAINT FK_COLABORADORES_SUCURSALES
    FOREIGN KEY (sucursal_id)
    REFERENCES dbo.SUCURSALES (id);
END;
GO

IF OBJECT_ID('dbo.BIO_TEMPLATES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.BIO_TEMPLATES (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_BIO_TEMPLATES PRIMARY KEY,
    colaborador_id INT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    template VARBINARY(MAX) NOT NULL,
    fecha_actualizacion DATETIME NOT NULL CONSTRAINT DF_BIO_TEMPLATES_fecha DEFAULT (GETDATE())
  );
END;
GO

IF COL_LENGTH('dbo.BIO_TEMPLATES', 'colaborador_id') IS NULL
BEGIN
  ALTER TABLE dbo.BIO_TEMPLATES ADD colaborador_id INT NULL;
END;
GO

IF COL_LENGTH('dbo.BIO_TEMPLATES', 'tipo') IS NULL
BEGIN
  ALTER TABLE dbo.BIO_TEMPLATES ADD tipo VARCHAR(20) NULL;
END;
GO

IF COL_LENGTH('dbo.BIO_TEMPLATES', 'template') IS NULL
BEGIN
  ALTER TABLE dbo.BIO_TEMPLATES ADD template VARBINARY(MAX) NULL;
END;
GO

IF COL_LENGTH('dbo.BIO_TEMPLATES', 'fecha_actualizacion') IS NULL
BEGIN
  ALTER TABLE dbo.BIO_TEMPLATES
    ADD fecha_actualizacion DATETIME NOT NULL
      CONSTRAINT DF_BIO_TEMPLATES_fecha DEFAULT (GETDATE());
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_BIO_TEMPLATES_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.BIO_TEMPLATES')
)
BEGIN
  ALTER TABLE dbo.BIO_TEMPLATES
    ADD CONSTRAINT FK_BIO_TEMPLATES_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_BIO_TEMPLATES_colaborador'
    AND object_id = OBJECT_ID('dbo.BIO_TEMPLATES')
)
BEGIN
  CREATE INDEX IX_BIO_TEMPLATES_colaborador
    ON dbo.BIO_TEMPLATES (colaborador_id);
END;
GO
