SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.ATT_RULES_HORARIOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ATT_RULES_HORARIOS (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HORARIOS PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    hora_entrada TIME(0) NOT NULL,
    hora_salida TIME(0) NOT NULL,
    tolerancia_minutos INT NOT NULL CONSTRAINT DF_HORARIOS_tolerancia DEFAULT (0),
    dia_festivo BIT NOT NULL CONSTRAINT DF_HORARIOS_dia_festivo DEFAULT (0)
  );
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'horario_id') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD horario_id INT NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'vencimiento_contrato') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD vencimiento_contrato DATE NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'es_admin_dispositivo') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD es_admin_dispositivo BIT NOT NULL
      CONSTRAINT DF_COLABORADORES_es_admin_dispositivo DEFAULT (0);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_COLABORADORES_HORARIOS'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD CONSTRAINT FK_COLABORADORES_HORARIOS
    FOREIGN KEY (horario_id)
    REFERENCES dbo.ATT_RULES_HORARIOS (id);
END;
GO

IF OBJECT_ID('dbo.COLABORADORES_SUCURSALES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.COLABORADORES_SUCURSALES (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COLABORADORES_SUCURSALES PRIMARY KEY,
    colaborador_id INT NOT NULL,
    sucursal_id INT NOT NULL
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UQ_COLABORADORES_SUCURSALES_colab_suc'
    AND object_id = OBJECT_ID('dbo.COLABORADORES_SUCURSALES')
)
BEGIN
  CREATE UNIQUE INDEX UQ_COLABORADORES_SUCURSALES_colab_suc
    ON dbo.COLABORADORES_SUCURSALES (colaborador_id, sucursal_id);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_COLABORADORES_SUCURSALES_COLAB'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES_SUCURSALES')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES_SUCURSALES
    ADD CONSTRAINT FK_COLABORADORES_SUCURSALES_COLAB
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_COLABORADORES_SUCURSALES_SUC'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES_SUCURSALES')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES_SUCURSALES
    ADD CONSTRAINT FK_COLABORADORES_SUCURSALES_SUC
    FOREIGN KEY (sucursal_id)
    REFERENCES dbo.SUCURSALES (id)
    ON DELETE CASCADE;
END;
GO

