SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.NOTIFICACIONES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.NOTIFICACIONES (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_NOTIFICACIONES PRIMARY KEY,
    colaborador_id INT NULL,
    pin VARCHAR(30) NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    titulo VARCHAR(180) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    leida BIT NOT NULL CONSTRAINT DF_NOTIFICACIONES_leida DEFAULT (0),
    fecha_referencia DATE NULL,
    fecha_creacion DATETIME NOT NULL CONSTRAINT DF_NOTIFICACIONES_fecha_creacion DEFAULT (GETDATE()),
    fecha_leida DATETIME NULL
  );
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'colaborador_id') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES ADD colaborador_id INT NULL;
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'pin') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES ADD pin VARCHAR(30) NULL;
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'tipo') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES ADD tipo VARCHAR(40) NULL;
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'titulo') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES ADD titulo VARCHAR(180) NULL;
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'mensaje') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES ADD mensaje VARCHAR(500) NULL;
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'leida') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES
    ADD leida BIT NOT NULL
      CONSTRAINT DF_NOTIFICACIONES_leida DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'fecha_referencia') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES ADD fecha_referencia DATE NULL;
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'fecha_creacion') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES
    ADD fecha_creacion DATETIME NOT NULL
      CONSTRAINT DF_NOTIFICACIONES_fecha_creacion DEFAULT (GETDATE());
END;
GO

IF COL_LENGTH('dbo.NOTIFICACIONES', 'fecha_leida') IS NULL
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES ADD fecha_leida DATETIME NULL;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_NOTIFICACIONES_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.NOTIFICACIONES')
)
BEGIN
  ALTER TABLE dbo.NOTIFICACIONES
    ADD CONSTRAINT FK_NOTIFICACIONES_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE SET NULL;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_NOTIFICACIONES_pin_fecha'
    AND object_id = OBJECT_ID('dbo.NOTIFICACIONES')
)
BEGIN
  CREATE INDEX IX_NOTIFICACIONES_pin_fecha
    ON dbo.NOTIFICACIONES (pin, fecha_creacion DESC);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UQ_NOTIFICACIONES_pin_tipo_fecha_ref'
    AND object_id = OBJECT_ID('dbo.NOTIFICACIONES')
)
BEGIN
  CREATE UNIQUE INDEX UQ_NOTIFICACIONES_pin_tipo_fecha_ref
    ON dbo.NOTIFICACIONES (pin, tipo, fecha_referencia)
    WHERE fecha_referencia IS NOT NULL;
END;
GO
