SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.ATT_PERMISOS_TIPOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ATT_PERMISOS_TIPOS (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ATT_PERMISOS_TIPOS PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    goce_sueldo BIT NOT NULL CONSTRAINT DF_ATT_PERMISOS_TIPOS_goce DEFAULT (0),
    justifica_asistencia BIT NOT NULL CONSTRAINT DF_ATT_PERMISOS_TIPOS_justifica DEFAULT (0)
  );
END;
GO

IF COL_LENGTH('dbo.ATT_PERMISOS_TIPOS', 'nombre') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_PERMISOS_TIPOS ADD nombre VARCHAR(120) NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_PERMISOS_TIPOS', 'goce_sueldo') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_PERMISOS_TIPOS
    ADD goce_sueldo BIT NOT NULL
      CONSTRAINT DF_ATT_PERMISOS_TIPOS_goce DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.ATT_PERMISOS_TIPOS', 'justifica_asistencia') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_PERMISOS_TIPOS
    ADD justifica_asistencia BIT NOT NULL
      CONSTRAINT DF_ATT_PERMISOS_TIPOS_justifica DEFAULT (0);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UQ_ATT_PERMISOS_TIPOS_nombre'
    AND object_id = OBJECT_ID('dbo.ATT_PERMISOS_TIPOS')
)
BEGIN
  CREATE UNIQUE INDEX UQ_ATT_PERMISOS_TIPOS_nombre
    ON dbo.ATT_PERMISOS_TIPOS (nombre);
END;
GO

IF NOT EXISTS (
  SELECT 1 FROM dbo.ATT_PERMISOS_TIPOS WHERE UPPER(LTRIM(RTRIM(nombre))) = 'VACACIONES'
)
BEGIN
  INSERT INTO dbo.ATT_PERMISOS_TIPOS (nombre, goce_sueldo, justifica_asistencia)
  VALUES ('VACACIONES', 1, 1);
END;
GO

IF NOT EXISTS (
  SELECT 1 FROM dbo.ATT_PERMISOS_TIPOS WHERE UPPER(LTRIM(RTRIM(nombre))) = 'COMISIÓN'
     OR UPPER(LTRIM(RTRIM(nombre))) = 'COMISION'
)
BEGIN
  INSERT INTO dbo.ATT_PERMISOS_TIPOS (nombre, goce_sueldo, justifica_asistencia)
  VALUES ('COMISION', 1, 1);
END;
GO

IF NOT EXISTS (
  SELECT 1 FROM dbo.ATT_PERMISOS_TIPOS WHERE UPPER(LTRIM(RTRIM(nombre))) = 'TRABAJO CAMPO'
)
BEGIN
  INSERT INTO dbo.ATT_PERMISOS_TIPOS (nombre, goce_sueldo, justifica_asistencia)
  VALUES ('TRABAJO CAMPO', 1, 1);
END;
GO

IF OBJECT_ID('dbo.ATT_SOLICITUDES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ATT_SOLICITUDES (
    id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ATT_SOLICITUDES PRIMARY KEY,
    colaborador_id INT NOT NULL,
    tipo_id INT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    motivo VARCHAR(500) NULL,
    evidencia_url VARCHAR(500) NULL,
    estatus VARCHAR(20) NOT NULL CONSTRAINT DF_ATT_SOLICITUDES_estatus DEFAULT ('PENDIENTE'),
    aprobado_por INT NULL,
    creado_en DATETIME NOT NULL CONSTRAINT DF_ATT_SOLICITUDES_creado_en DEFAULT (GETDATE()),
    actualizado_en DATETIME NOT NULL CONSTRAINT DF_ATT_SOLICITUDES_actualizado_en DEFAULT (GETDATE())
  );
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'colaborador_id') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES ADD colaborador_id INT NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'tipo_id') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES ADD tipo_id INT NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'fecha_inicio') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES ADD fecha_inicio DATE NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'fecha_fin') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES ADD fecha_fin DATE NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'motivo') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES ADD motivo VARCHAR(500) NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'evidencia_url') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES ADD evidencia_url VARCHAR(500) NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'estatus') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES
    ADD estatus VARCHAR(20) NOT NULL
      CONSTRAINT DF_ATT_SOLICITUDES_estatus DEFAULT ('PENDIENTE');
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'aprobado_por') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES ADD aprobado_por INT NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'creado_en') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES
    ADD creado_en DATETIME NOT NULL
      CONSTRAINT DF_ATT_SOLICITUDES_creado_en DEFAULT (GETDATE());
END;
GO

IF COL_LENGTH('dbo.ATT_SOLICITUDES', 'actualizado_en') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES
    ADD actualizado_en DATETIME NOT NULL
      CONSTRAINT DF_ATT_SOLICITUDES_actualizado_en DEFAULT (GETDATE());
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_ATT_SOLICITUDES_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.ATT_SOLICITUDES')
)
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES
    ADD CONSTRAINT FK_ATT_SOLICITUDES_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_ATT_SOLICITUDES_PERMISO_TIPO'
    AND parent_object_id = OBJECT_ID('dbo.ATT_SOLICITUDES')
)
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES
    ADD CONSTRAINT FK_ATT_SOLICITUDES_PERMISO_TIPO
    FOREIGN KEY (tipo_id)
    REFERENCES dbo.ATT_PERMISOS_TIPOS (id);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_ATT_SOLICITUDES_ESTATUS'
    AND parent_object_id = OBJECT_ID('dbo.ATT_SOLICITUDES')
)
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES
    ADD CONSTRAINT CK_ATT_SOLICITUDES_ESTATUS
    CHECK (estatus IN ('PENDIENTE', 'APROBADO', 'RECHAZADO'));
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_ATT_SOLICITUDES_RANGO'
    AND parent_object_id = OBJECT_ID('dbo.ATT_SOLICITUDES')
)
BEGIN
  ALTER TABLE dbo.ATT_SOLICITUDES
    ADD CONSTRAINT CK_ATT_SOLICITUDES_RANGO
    CHECK (fecha_inicio <= fecha_fin);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_ATT_SOLICITUDES_colab_rango_estatus'
    AND object_id = OBJECT_ID('dbo.ATT_SOLICITUDES')
)
BEGIN
  CREATE INDEX IX_ATT_SOLICITUDES_colab_rango_estatus
    ON dbo.ATT_SOLICITUDES (colaborador_id, fecha_inicio, fecha_fin, estatus);
END;
GO

IF OBJECT_ID('dbo.ATT_VACACIONES_SALDOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ATT_VACACIONES_SALDOS (
    colaborador_id INT NOT NULL,
    anio INT NOT NULL,
    dias_totales INT NOT NULL CONSTRAINT DF_ATT_VACACIONES_SALDOS_dias_totales DEFAULT (0),
    dias_usados INT NOT NULL CONSTRAINT DF_ATT_VACACIONES_SALDOS_dias_usados DEFAULT (0),
    CONSTRAINT PK_ATT_VACACIONES_SALDOS PRIMARY KEY (colaborador_id, anio)
  );
END;
GO

IF COL_LENGTH('dbo.ATT_VACACIONES_SALDOS', 'colaborador_id') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_VACACIONES_SALDOS ADD colaborador_id INT NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_VACACIONES_SALDOS', 'anio') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_VACACIONES_SALDOS ADD anio INT NULL;
END;
GO

IF COL_LENGTH('dbo.ATT_VACACIONES_SALDOS', 'dias_totales') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_VACACIONES_SALDOS
    ADD dias_totales INT NOT NULL
      CONSTRAINT DF_ATT_VACACIONES_SALDOS_dias_totales DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.ATT_VACACIONES_SALDOS', 'dias_usados') IS NULL
BEGIN
  ALTER TABLE dbo.ATT_VACACIONES_SALDOS
    ADD dias_usados INT NOT NULL
      CONSTRAINT DF_ATT_VACACIONES_SALDOS_dias_usados DEFAULT (0);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_ATT_VACACIONES_SALDOS_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.ATT_VACACIONES_SALDOS')
)
BEGIN
  ALTER TABLE dbo.ATT_VACACIONES_SALDOS
    ADD CONSTRAINT FK_ATT_VACACIONES_SALDOS_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_ATT_VACACIONES_SALDOS_dias'
    AND parent_object_id = OBJECT_ID('dbo.ATT_VACACIONES_SALDOS')
)
BEGIN
  ALTER TABLE dbo.ATT_VACACIONES_SALDOS
    ADD CONSTRAINT CK_ATT_VACACIONES_SALDOS_dias
    CHECK (dias_totales >= 0 AND dias_usados >= 0 AND dias_usados <= dias_totales);
END;
GO

IF EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_ATT_ASISTENCIA_ESTATUS_estatus'
    AND parent_object_id = OBJECT_ID('dbo.ATT_ASISTENCIA_ESTATUS')
)
BEGIN
  ALTER TABLE dbo.ATT_ASISTENCIA_ESTATUS
    DROP CONSTRAINT CK_ATT_ASISTENCIA_ESTATUS_estatus;
END;
GO

IF OBJECT_ID('dbo.ATT_ASISTENCIA_ESTATUS', 'U') IS NOT NULL
   AND NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_ATT_ASISTENCIA_ESTATUS_estatus'
    AND parent_object_id = OBJECT_ID('dbo.ATT_ASISTENCIA_ESTATUS')
)
BEGIN
  ALTER TABLE dbo.ATT_ASISTENCIA_ESTATUS
    ADD CONSTRAINT CK_ATT_ASISTENCIA_ESTATUS_estatus
    CHECK (
      LEN(LTRIM(RTRIM(ISNULL(estatus, '')))) > 0
      AND LEN(estatus) <= 40
    );
END;
GO

