SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

/*
  128_LFT_NOM035_EXPEDIENTE.sql
  - Cumplimiento LFT México + NOM-035
  - Expediente digital de colaborador
*/

IF COL_LENGTH('dbo.COLABORADORES', 'rfc') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD rfc VARCHAR(13) NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'curp') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD curp VARCHAR(18) NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'nss') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ADD nss VARCHAR(11) NULL;
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'jornada_tipo') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD jornada_tipo VARCHAR(10) NOT NULL
      CONSTRAINT DF_COLABORADORES_jornada_tipo DEFAULT ('DIURNA');
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'estatus_contrato') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD estatus_contrato VARCHAR(20) NOT NULL
      CONSTRAINT DF_COLABORADORES_estatus_contrato DEFAULT ('PLANTA');
END;
GO

IF COL_LENGTH('dbo.COLABORADORES', 'documentacion_completa') IS NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD documentacion_completa BIT NOT NULL
      CONSTRAINT DF_COLABORADORES_documentacion_completa DEFAULT (0);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_COLABORADORES_jornada_tipo'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD CONSTRAINT CK_COLABORADORES_jornada_tipo
    CHECK (
      UPPER(LTRIM(RTRIM(ISNULL(jornada_tipo, ''))))
      IN ('DIURNA', 'NOCTURNA', 'MIXTA')
    );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_COLABORADORES_estatus_contrato'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES
    ADD CONSTRAINT CK_COLABORADORES_estatus_contrato
    CHECK (
      UPPER(LTRIM(RTRIM(ISNULL(estatus_contrato, ''))))
      IN ('PRUEBA_30', 'PRUEBA_90', 'PLANTA', 'BAJA')
    );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_COLABORADORES_rfc'
    AND object_id = OBJECT_ID('dbo.COLABORADORES')
)
BEGIN
  CREATE INDEX IX_COLABORADORES_rfc
    ON dbo.COLABORADORES (rfc)
    WHERE rfc IS NOT NULL;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_COLABORADORES_curp'
    AND object_id = OBJECT_ID('dbo.COLABORADORES')
)
BEGIN
  CREATE INDEX IX_COLABORADORES_curp
    ON dbo.COLABORADORES (curp)
    WHERE curp IS NOT NULL;
END;
GO

IF OBJECT_ID('dbo.ATT_NOM035_RESPUESTAS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ATT_NOM035_RESPUESTAS (
    id BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ATT_NOM035_RESPUESTAS PRIMARY KEY,
    colaborador_id INT NOT NULL,
    fecha DATETIME NOT NULL CONSTRAINT DF_ATT_NOM035_RESPUESTAS_fecha DEFAULT (GETDATE()),
    p1 NVARCHAR(400) NOT NULL,
    p2 NVARCHAR(400) NOT NULL,
    p3 NVARCHAR(400) NOT NULL,
    comentario NVARCHAR(MAX) NULL
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_ATT_NOM035_RESPUESTAS_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.ATT_NOM035_RESPUESTAS')
)
BEGIN
  ALTER TABLE dbo.ATT_NOM035_RESPUESTAS
    ADD CONSTRAINT FK_ATT_NOM035_RESPUESTAS_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_ATT_NOM035_RESPUESTAS_colab_fecha'
    AND object_id = OBJECT_ID('dbo.ATT_NOM035_RESPUESTAS')
)
BEGIN
  CREATE INDEX IX_ATT_NOM035_RESPUESTAS_colab_fecha
    ON dbo.ATT_NOM035_RESPUESTAS (colaborador_id, fecha DESC);
END;
GO

IF OBJECT_ID('dbo.HISTORICO_PUESTOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.HISTORICO_PUESTOS (
    id BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HISTORICO_PUESTOS PRIMARY KEY,
    colaborador_id INT NOT NULL,
    puesto VARCHAR(120) NOT NULL,
    sueldo DECIMAL(18,2) NOT NULL,
    fecha_cambio DATE NOT NULL
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_HISTORICO_PUESTOS_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.HISTORICO_PUESTOS')
)
BEGIN
  ALTER TABLE dbo.HISTORICO_PUESTOS
    ADD CONSTRAINT FK_HISTORICO_PUESTOS_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_HISTORICO_PUESTOS_colab_fecha'
    AND object_id = OBJECT_ID('dbo.HISTORICO_PUESTOS')
)
BEGIN
  CREATE INDEX IX_HISTORICO_PUESTOS_colab_fecha
    ON dbo.HISTORICO_PUESTOS (colaborador_id, fecha_cambio DESC);
END;
GO

IF OBJECT_ID('dbo.COLABORADORES_DOCUMENTOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.COLABORADORES_DOCUMENTOS (
    id BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COLABORADORES_DOCUMENTOS PRIMARY KEY,
    colaborador_id INT NOT NULL,
    tipo_doc VARCHAR(20) NOT NULL,
    file_name VARCHAR(260) NOT NULL,
    mime_type VARCHAR(120) NULL,
    file_url VARCHAR(500) NOT NULL,
    uploaded_by INT NULL,
    uploaded_at DATETIME NOT NULL CONSTRAINT DF_COLABORADORES_DOCUMENTOS_uploaded_at DEFAULT (GETDATE())
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_COLABORADORES_DOCUMENTOS_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES_DOCUMENTOS')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES_DOCUMENTOS
    ADD CONSTRAINT FK_COLABORADORES_DOCUMENTOS_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_COLABORADORES_DOCUMENTOS_tipo'
    AND parent_object_id = OBJECT_ID('dbo.COLABORADORES_DOCUMENTOS')
)
BEGIN
  ALTER TABLE dbo.COLABORADORES_DOCUMENTOS
    ADD CONSTRAINT CK_COLABORADORES_DOCUMENTOS_tipo
    CHECK (
      UPPER(LTRIM(RTRIM(ISNULL(tipo_doc, ''))))
      IN ('RFC', 'CURP', 'NSS')
    );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_COLABORADORES_DOCUMENTOS_colab_tipo'
    AND object_id = OBJECT_ID('dbo.COLABORADORES_DOCUMENTOS')
)
BEGIN
  CREATE INDEX IX_COLABORADORES_DOCUMENTOS_colab_tipo
    ON dbo.COLABORADORES_DOCUMENTOS (colaborador_id, tipo_doc, uploaded_at DESC);
END;
GO

IF OBJECT_ID('dbo.CONTRATOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.CONTRATOS (
    id BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CONTRATOS PRIMARY KEY,
    colaborador_id INT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    tipo_contrato VARCHAR(30) NOT NULL CONSTRAINT DF_CONTRATOS_tipo DEFAULT ('PRUEBA_30'),
    estatus VARCHAR(20) NOT NULL CONSTRAINT DF_CONTRATOS_estatus DEFAULT ('ACTIVO'),
    creado_en DATETIME NOT NULL CONSTRAINT DF_CONTRATOS_creado_en DEFAULT (GETDATE())
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_CONTRATOS_COLABORADORES'
    AND parent_object_id = OBJECT_ID('dbo.CONTRATOS')
)
BEGIN
  ALTER TABLE dbo.CONTRATOS
    ADD CONSTRAINT FK_CONTRATOS_COLABORADORES
    FOREIGN KEY (colaborador_id)
    REFERENCES dbo.COLABORADORES (id)
    ON DELETE CASCADE;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_CONTRATOS_vencimiento'
    AND object_id = OBJECT_ID('dbo.CONTRATOS')
)
BEGIN
  CREATE INDEX IX_CONTRATOS_vencimiento
    ON dbo.CONTRATOS (fecha_vencimiento, estatus, colaborador_id);
END;
GO
