SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.MARCAJES', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.MARCAJES (
      id BIGINT IDENTITY(1,1) NOT NULL,
      punch_time DATETIME2(0) NOT NULL,
      terminal_id VARCHAR(80) NULL,
      event_photo NVARCHAR(500) NULL,
      expediente_photo NVARCHAR(500) NULL,
      body_temp FLOAT NULL,
      verify_mode INT NULL,
      verify_mode_label VARCHAR(20) NULL,
      gps_location GEOGRAPHY NULL,
      is_offline BIT NOT NULL CONSTRAINT DF_MARCAJES_IS_OFFLINE DEFAULT (0),
      id_usuario INT NULL,
      suc NVARCHAR(10) NULL,
      tipo VARCHAR(30) NULL,
      id_timelog BIGINT NULL,
      requires_review BIT NOT NULL CONSTRAINT DF_MARCAJES_REQUIRES_REVIEW DEFAULT (0),
      silent_alert BIT NOT NULL CONSTRAINT DF_MARCAJES_SILENT_ALERT DEFAULT (0),
      source VARCHAR(30) NULL,
      created_at DATETIME2(0) NOT NULL CONSTRAINT DF_MARCAJES_CREATED_AT DEFAULT (GETDATE()),
      CONSTRAINT PK_MARCAJES PRIMARY KEY CLUSTERED (id)
    );
  END;

  IF COL_LENGTH('dbo.MARCAJES', 'punch_time') IS NULL
    ALTER TABLE dbo.MARCAJES ADD punch_time DATETIME2(0) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'terminal_id') IS NULL
    ALTER TABLE dbo.MARCAJES ADD terminal_id VARCHAR(80) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'event_photo') IS NULL
    ALTER TABLE dbo.MARCAJES ADD event_photo NVARCHAR(500) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'expediente_photo') IS NULL
    ALTER TABLE dbo.MARCAJES ADD expediente_photo NVARCHAR(500) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'body_temp') IS NULL
    ALTER TABLE dbo.MARCAJES ADD body_temp FLOAT NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'verify_mode') IS NULL
    ALTER TABLE dbo.MARCAJES ADD verify_mode INT NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'verify_mode_label') IS NULL
    ALTER TABLE dbo.MARCAJES ADD verify_mode_label VARCHAR(20) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'gps_location') IS NULL
    ALTER TABLE dbo.MARCAJES ADD gps_location GEOGRAPHY NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'is_offline') IS NULL
    ALTER TABLE dbo.MARCAJES ADD is_offline BIT NOT NULL CONSTRAINT DF_MARCAJES_IS_OFFLINE_PATCH DEFAULT (0);

  IF COL_LENGTH('dbo.MARCAJES', 'id_usuario') IS NULL
    ALTER TABLE dbo.MARCAJES ADD id_usuario INT NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'suc') IS NULL
    ALTER TABLE dbo.MARCAJES ADD suc NVARCHAR(10) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'tipo') IS NULL
    ALTER TABLE dbo.MARCAJES ADD tipo VARCHAR(30) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'id_timelog') IS NULL
    ALTER TABLE dbo.MARCAJES ADD id_timelog BIGINT NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'requires_review') IS NULL
    ALTER TABLE dbo.MARCAJES ADD requires_review BIT NOT NULL CONSTRAINT DF_MARCAJES_REQUIRES_REVIEW_PATCH DEFAULT (0);

  IF COL_LENGTH('dbo.MARCAJES', 'silent_alert') IS NULL
    ALTER TABLE dbo.MARCAJES ADD silent_alert BIT NOT NULL CONSTRAINT DF_MARCAJES_SILENT_ALERT_PATCH DEFAULT (0);

  IF COL_LENGTH('dbo.MARCAJES', 'source') IS NULL
    ALTER TABLE dbo.MARCAJES ADD source VARCHAR(30) NULL;

  IF COL_LENGTH('dbo.MARCAJES', 'created_at') IS NULL
    ALTER TABLE dbo.MARCAJES ADD created_at DATETIME2(0) NOT NULL CONSTRAINT DF_MARCAJES_CREATED_AT_PATCH DEFAULT (GETDATE());

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_MARCAJES_PUNCH_TIME'
      AND object_id = OBJECT_ID('dbo.MARCAJES')
  )
  BEGIN
    CREATE INDEX IX_MARCAJES_PUNCH_TIME
      ON dbo.MARCAJES (punch_time DESC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_MARCAJES_SUC_PUNCH'
      AND object_id = OBJECT_ID('dbo.MARCAJES')
  )
  BEGIN
    CREATE INDEX IX_MARCAJES_SUC_PUNCH
      ON dbo.MARCAJES (suc ASC, punch_time DESC);
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_MARCAJES_USUARIO_PUNCH'
      AND object_id = OBJECT_ID('dbo.MARCAJES')
  )
  BEGIN
    CREATE INDEX IX_MARCAJES_USUARIO_PUNCH
      ON dbo.MARCAJES (id_usuario ASC, punch_time DESC);
  END;

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO

