/*
  Proyecto IOE - Horarios Semanales y Turnos LFT
  Script idempotente
*/

SET NOCOUNT ON;

IF OBJECT_ID('dbo.TURNOS_CATALOGO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TURNOS_CATALOGO (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    hr_entrada TIME(0) NOT NULL,
    hr_salida_comida TIME(0) NOT NULL,
    hr_regreso_comida TIME(0) NOT NULL,
    hr_salida TIME(0) NOT NULL
  );
END;

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_TURNOS_CATALOGO_NOMBRE'
    AND object_id = OBJECT_ID('dbo.TURNOS_CATALOGO')
)
BEGIN
  CREATE UNIQUE INDEX UX_TURNOS_CATALOGO_NOMBRE
    ON dbo.TURNOS_CATALOGO(nombre);
END;

IF OBJECT_ID('dbo.HORARIOS_CONFIRMACION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.HORARIOS_CONFIRMACION (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    sucursal VARCHAR(40) NOT NULL,
    departamento VARCHAR(80) NOT NULL,
    semana DATE NOT NULL,
    estatus VARCHAR(20) NOT NULL CONSTRAINT DF_HORARIOS_CONFIRMACION_ESTATUS DEFAULT ('PENDIENTE'),
    fecha_actualizacion DATETIME NOT NULL CONSTRAINT DF_HORARIOS_CONFIRMACION_FECHA DEFAULT (GETDATE())
  );
END;

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_HORARIOS_CONFIRMACION_ESTATUS'
    AND parent_object_id = OBJECT_ID('dbo.HORARIOS_CONFIRMACION')
)
BEGIN
  ALTER TABLE dbo.HORARIOS_CONFIRMACION
  ADD CONSTRAINT CK_HORARIOS_CONFIRMACION_ESTATUS
  CHECK (UPPER(estatus) IN ('PENDIENTE', 'CONFIRMADO'));
END;

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_HORARIOS_CONFIRMACION_SCOPE'
    AND object_id = OBJECT_ID('dbo.HORARIOS_CONFIRMACION')
)
BEGIN
  CREATE UNIQUE INDEX UX_HORARIOS_CONFIRMACION_SCOPE
    ON dbo.HORARIOS_CONFIRMACION(sucursal, departamento, semana);
END;

