IF OBJECT_ID('dbo.COLABORADORES', 'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.COLABORADORES', 'pin') IS NOT NULL
    ALTER TABLE dbo.COLABORADORES ALTER COLUMN pin VARCHAR(255) NOT NULL;

  IF COL_LENGTH('dbo.COLABORADORES', 'nombre') IS NOT NULL
    ALTER TABLE dbo.COLABORADORES ALTER COLUMN nombre VARCHAR(150) NOT NULL;

  IF COL_LENGTH('dbo.COLABORADORES', 'apellido') IS NOT NULL
    ALTER TABLE dbo.COLABORADORES ALTER COLUMN apellido VARCHAR(150) NOT NULL;

  IF COL_LENGTH('dbo.COLABORADORES', 'cargo') IS NOT NULL
    ALTER TABLE dbo.COLABORADORES ALTER COLUMN cargo VARCHAR(150) NULL;
END;
