/* Prueba transaccional DAT_REC. No deja datos: todo se revierte al final. */
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

BEGIN TRY
  BEGIN TRANSACTION;
  DECLARE @SUC nvarchar(255),@ART nvarchar(255),@CTO money,@USR nvarchar(100),@NPROV int;
  SELECT TOP 1 @SUC=a.SUC,@ART=a.ART,@CTO=COALESCE(a.CTOP,1) FROM dbo.DAT_ART a WHERE ISNULL(a.BLOQ,0)<>-1 ORDER BY a.SUC,a.ART;
  SELECT TOP 1 @USR=u.USERNAME FROM dbo.USUARIO u WHERE u.ESTATUS='ACTIVO' ORDER BY CASE WHEN u.IDROL IN (0,1) THEN 0 ELSE 1 END,u.IDUSUARIO;
  SELECT TOP 1 @NPROV=ID FROM dbo.DAT_PROVD ORDER BY ID;
  IF @SUC IS NULL OR @ART IS NULL OR @USR IS NULL OR @NPROV IS NULL THROW 52000,'No hay catalogos suficientes para la prueba DAT_REC.',1;

  DECLARE @NPED nvarchar(255)=CONCAT('UTREC',@@SPID),@IDPED nvarchar(255);
  SET @IDPED=CONCAT('1-',@NPED);
  INSERT dbo.REC_CAB_PED(NPED,SUC,TIPO,NPROV,USR,FCNP,IMPP,NART,ESTATUS,SUG)
  VALUES(@NPED,@SUC,'PRUEBA',@NPROV,@USR,SYSDATETIME(),@CTO*2,1,'PROCESADO',0);
  INSERT dbo.REC_DET_PED(BLOQ,RECI,POS,IDPED,NPED,ART,CTO,CTDPED,UNCOM,CTDREC)
  VALUES(0,0,1,@IDPED,@NPED,@ART,@CTO,2,'PZA',0);

  DECLARE @out table(DOCREC nvarchar(255),NPED nvarchar(255),ESTATUS_REC nvarchar(30));
  DECLARE @items nvarchar(max)=CONCAT('[{"idped":"',STRING_ESCAPE(@IDPED,'json'),'","art":"',STRING_ESCAPE(@ART,'json'),'","cantidadRecibida":1,"cantidadAceptada":1,"calidadEstado":"APROBADO"}]');
  INSERT @out EXEC dbo.sp_rec_recepcion_fisica @NPED=@NPED,@USR=@USR,@TIPO_RECEPCION='DIFERENCIAS',@TIPO_DOC='NOTA',@FOLIO_DOC='UT-1',@ALMACEN='002',@OBSERVACIONES='SMOKE',@ITEMS_JSON=@items,@GUIAS_JSON='[{"guia":"UT-GUIA","cantidadPaquetes":1}]',@INCIDENCIAS_JSON='[]';
  DECLARE @DOCREC nvarchar(255)=(SELECT TOP 1 DOCREC FROM @out);
  IF EXISTS(SELECT 1 FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND IDREC NOT LIKE CONCAT('REC-',@DOCREC,'-%')) THROW 52000,'El IDREC no usa el identificador unico esperado.',1;
  IF EXISTS(SELECT 1 FROM dbo.DAT_MB51 WHERE DOCP=@DOCREC) THROW 52000,'La recepcion fisica afecto inventario antes de autorizar.',1;
  IF NOT EXISTS(SELECT 1 FROM dbo.REC_GUIA_PED WHERE DOCREC=@DOCREC) THROW 52000,'No se registro la guia.',1;
  IF NOT EXISTS(SELECT 1 FROM dbo.REC_INCI_PED WHERE DOCREC=@DOCREC AND TIPO='FALTANTE') THROW 52000,'No se genero incidencia por faltante.',1;

  EXEC dbo.sp_rec_recepcion_solicitar @DOCREC=@DOCREC,@USR=@USR,@MOTIVO=NULL;
  EXEC dbo.sp_rec_recepcion_autorizar @DOCREC=@DOCREC,@USR=@USR,@MOTIVO=NULL;
  IF NOT EXISTS(SELECT 1 FROM dbo.DAT_MB51 WHERE DOCP=@DOCREC AND CLSM=101 AND CTDA=1) THROW 52000,'No se genero movimiento 101.',1;
  IF (SELECT ESTATUS FROM dbo.REC_CAB_PED WHERE NPED=@NPED)<>'PARCIAL' THROW 52000,'No se conservo la orden parcial.',1;
  EXEC dbo.sp_rec_recepcion_autorizar @DOCREC=@DOCREC,@USR=@USR,@MOTIVO=NULL;
  IF (SELECT COUNT(*) FROM dbo.DAT_MB51 WHERE DOCP=@DOCREC)<>1 THROW 52000,'La reejecucion duplico el movimiento.',1;

  DELETE FROM @out;
  INSERT @out EXEC dbo.sp_rec_recepcion_fisica @NPED=@NPED,@USR=@USR,@TIPO_RECEPCION='TOTAL',@TIPO_DOC='FACTURA',@FOLIO_DOC='UT-2',@ALMACEN='002',@OBSERVACIONES='SMOKE 2',@ITEMS_JSON=@items,@GUIAS_JSON='[]',@INCIDENCIAS_JSON='[]';
  SET @DOCREC=(SELECT TOP 1 DOCREC FROM @out);
  EXEC dbo.sp_rec_recepcion_solicitar @DOCREC=@DOCREC,@USR=@USR,@MOTIVO=NULL;
  EXEC dbo.sp_rec_recepcion_autorizar @DOCREC=@DOCREC,@USR=@USR,@MOTIVO=NULL;
  IF (SELECT ESTATUS FROM dbo.REC_CAB_PED WHERE NPED=@NPED)<>'RECIBIDO' THROW 52000,'La segunda recepcion no cerro la orden.',1;
  IF (SELECT CTDREC FROM dbo.REC_DET_PED WHERE IDPED=@IDPED)<>2 THROW 52000,'El acumulado recibido es incorrecto.',1;

  DECLARE @NPED_R nvarchar(255)=CONCAT('UTRECR',@@SPID),@IDPED_R nvarchar(255);
  SET @IDPED_R=CONCAT('1-',@NPED_R);
  INSERT dbo.REC_CAB_PED(NPED,SUC,TIPO,NPROV,USR,FCNP,IMPP,NART,ESTATUS,SUG) VALUES(@NPED_R,@SUC,'PRUEBA',@NPROV,@USR,SYSDATETIME(),@CTO,1,'PROCESADO',0);
  INSERT dbo.REC_DET_PED(BLOQ,RECI,POS,IDPED,NPED,ART,CTO,CTDPED,UNCOM,CTDREC) VALUES(0,0,1,@IDPED_R,@NPED_R,@ART,@CTO,1,'PZA',0);
  SET @items=CONCAT('[{"idped":"',STRING_ESCAPE(@IDPED_R,'json'),'","art":"',STRING_ESCAPE(@ART,'json'),'","cantidadRecibida":1,"cantidadAceptada":0,"calidadEstado":"RECHAZADO"}]');
  DELETE FROM @out;
  INSERT @out EXEC dbo.sp_rec_recepcion_fisica @NPED=@NPED_R,@USR=@USR,@TIPO_RECEPCION='RECHAZO',@TIPO_DOC='PENDIENTE',@FOLIO_DOC=NULL,@ALMACEN='002',@OBSERVACIONES='SMOKE RECHAZO',@ITEMS_JSON=@items,@GUIAS_JSON='[]',@INCIDENCIAS_JSON='[]';
  SET @DOCREC=(SELECT TOP 1 DOCREC FROM @out);
  EXEC dbo.sp_rec_recepcion_rechazar @DOCREC=@DOCREC,@USR=@USR,@MOTIVO='PRUEBA';
  IF (SELECT ESTATUS_REC FROM dbo.REC_CTRL_DOC_REC WHERE DOCREC=@DOCREC)<>'RECHAZADO' THROW 52000,'No se registro el rechazo.',1;
  IF EXISTS(SELECT 1 FROM dbo.DAT_MB51 WHERE DOCP=@DOCREC) THROW 52000,'El rechazo genero inventario.',1;

  ROLLBACK;
  SELECT 'OK' RESULTADO,'identificadores unicos, total, parcial, multiples, faltante, guia, rechazo, inventario e idempotencia' CASOS;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT>0 ROLLBACK;
  THROW;
END CATCH;
