/*
  Reporte comercial por cliente - Version 4
  Cambio: hoja CreditosMesForma basada en consulta UPC CR% del usuario
*/
SET NOCOUNT ON;

DECLARE @fecha_inicio DATE = '2025-01-01';
DECLARE @fecha_fin DATE = CAST(GETDATE() AS DATE);

/* Hoja CreditosMesForma (consulta exacta solicitada) */
WITH T AS (
    SELECT DISTINCT
        IDFOL,
        UPC
    FROM dbo.PV_TICKET_LOG
    WHERE UPC LIKE 'CR%'
)
SELECT
    YEAR(A.FCN)  AS ANIO,
    MONTH(A.FCN) AS MES,
    T.UPC,
    SUM(CASE WHEN F.FORM = 'CHEQUE'        THEN ISNULL(F.IMPD, 0) ELSE 0 END) AS CHEQUE,
    SUM(CASE WHEN F.FORM = 'CREDITO'       THEN ISNULL(F.IMPD, 0) ELSE 0 END) AS CREDITO,
    SUM(CASE WHEN F.FORM = 'DEPOSITO 3RO'  THEN ISNULL(F.IMPD, 0) ELSE 0 END) AS [DEPOSITO 3RO],
    SUM(CASE WHEN F.FORM = 'EFECTIVO'      THEN ISNULL(F.IMPD, 0) ELSE 0 END) AS EFECTIVO,
    SUM(CASE WHEN F.FORM = 'TARJETA'       THEN ISNULL(F.IMPD, 0) ELSE 0 END) AS TARJETA,
    SUM(CASE WHEN F.FORM = 'TRANSFERENCIA' THEN ISNULL(F.IMPD, 0) ELSE 0 END) AS TRANSFERENCIA
FROM T
INNER JOIN dbo.PV_CTR_FOL_FORM AS F
    ON F.IDFOL = T.IDFOL
INNER JOIN dbo.PV_CTR_FOL_ASVR AS A
    ON A.IDFOL = T.IDFOL
WHERE A.FCN >= @fecha_inicio
  AND A.FCN < DATEADD(DAY, 1, CAST(GETDATE() AS date))
GROUP BY
    YEAR(A.FCN),
    MONTH(A.FCN),
    T.UPC
ORDER BY
    ANIO,
    MES,
    T.UPC;
