SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.VW_PV_FORM_TIPOTRAN_DISTINCT', 'V') IS NOT NULL
BEGIN
  DROP VIEW dbo.VW_PV_FORM_TIPOTRAN_DISTINCT;
END;
GO

CREATE VIEW dbo.VW_PV_FORM_TIPOTRAN_DISTINCT
AS
SELECT
  FORM,
  TIPOTRAN,
  MIN(ISNULL(BLOQ, 0)) AS BLOQ
FROM dbo.PV_FORM_TIPOTRAN
WHERE FORM IS NOT NULL
GROUP BY FORM, TIPOTRAN;
GO
