SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.PV_CTR_FOL_ASVR', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_PV_CTR_FOL_ASVR_FCN_AUT_OPVM_IDFOL'
    AND object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR')
)
BEGIN
  CREATE INDEX IX_PV_CTR_FOL_ASVR_FCN_AUT_OPVM_IDFOL
    ON dbo.PV_CTR_FOL_ASVR (FCN, AUT, OPVM, IDFOL);
END;
GO

IF OBJECT_ID('dbo.PV_CTR_FOL_FORM_SVR', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_PV_CTR_FOL_FORM_SVR_IDFOL_IDF_FORM'
    AND object_id = OBJECT_ID('dbo.PV_CTR_FOL_FORM_SVR')
)
BEGIN
  CREATE INDEX IX_PV_CTR_FOL_FORM_SVR_IDFOL_IDF_FORM
    ON dbo.PV_CTR_FOL_FORM_SVR (IDFOL, IDF, FORM);
END;
GO

IF OBJECT_ID('dbo.PV_FORM_TIPOTRAN', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_PV_FORM_TIPOTRAN_FORM_TIPOTRAN_BLOQ'
    AND object_id = OBJECT_ID('dbo.PV_FORM_TIPOTRAN')
)
BEGIN
  CREATE INDEX IX_PV_FORM_TIPOTRAN_FORM_TIPOTRAN_BLOQ
    ON dbo.PV_FORM_TIPOTRAN (FORM, TIPOTRAN, BLOQ);
END;
GO
