SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.AUDIT_LOG', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.AUDIT_LOG (
    IDAUDIT bigint IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    ACTION nvarchar(20) NOT NULL,
    MODULO nvarchar(100) NOT NULL,
    ENTIDAD nvarchar(150) NOT NULL,
    ENTIDAD_ID nvarchar(255) NOT NULL,
    METADATA_JSON nvarchar(max) NULL,
    FCNR datetime2(0) NOT NULL
      CONSTRAINT DF_AUDIT_LOG_FCNR DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID('dbo.AUDIT_LOG', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_AUDIT_LOG_MOD_ENTIDAD_ENTIDAD_ID_FCNR'
    AND object_id = OBJECT_ID('dbo.AUDIT_LOG')
)
BEGIN
  CREATE INDEX IX_AUDIT_LOG_MOD_ENTIDAD_ENTIDAD_ID_FCNR
    ON dbo.AUDIT_LOG (MODULO, ENTIDAD, ENTIDAD_ID, FCNR DESC);
END;
GO
