/*
Fase homologación PV/PS:
- AUT = tipo actual
- ESTA = estado operativo (PENDIENTE/PAGADO/TRANSMITIR)
- IDFOLINICIAL = identificador estable
- IDFOLORIG = referencia a documento origen
- ORIGEN_AUT = categoria operativa (CA/VF)
*/

SET NOCOUNT ON;

/* 1) Campos nuevos */
IF COL_LENGTH('dbo.PV_CTR_FOL_ASVR', 'IDFOLINICIAL') IS NULL
BEGIN
  ALTER TABLE dbo.PV_CTR_FOL_ASVR
    ADD IDFOLINICIAL VARCHAR(255) NULL;
END;

IF COL_LENGTH('dbo.PV_CTR_FOL_ASVR', 'ORIGEN_AUT') IS NULL
BEGIN
  ALTER TABLE dbo.PV_CTR_FOL_ASVR
    ADD ORIGEN_AUT VARCHAR(2) NULL;
END;

/* 2) Tabla consecutivos */
IF OBJECT_ID('dbo.DAT_FOLIOS_CONSEC', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DAT_FOLIOS_CONSEC (
    SUC           NVARCHAR(20) NOT NULL,
    FECHA         DATE         NOT NULL,
    TIPO_FOLIO    VARCHAR(2)   NOT NULL,
    ULTIMO_CONSEC INT          NOT NULL CONSTRAINT DF_DAT_FOLIOS_CONSEC_ULTIMO DEFAULT (0),
    FCNM          DATETIME     NOT NULL CONSTRAINT DF_DAT_FOLIOS_CONSEC_FCNM DEFAULT (GETDATE())
  );
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DAT_FOLIOS_CONSEC') AND name = 'UX_DAT_FOLIOS_CONSEC_SUC_FECHA_TIPO'
)
BEGIN
  CREATE UNIQUE INDEX UX_DAT_FOLIOS_CONSEC_SUC_FECHA_TIPO
  ON dbo.DAT_FOLIOS_CONSEC (SUC, FECHA, TIPO_FOLIO);
END;

/* 3) Regularización mínima historial */
UPDATE dbo.PV_CTR_FOL_ASVR
SET IDFOLINICIAL = ISNULL(NULLIF(LTRIM(RTRIM(IDFOLINICIAL)), ''), IDFOL)
WHERE ISNULL(LTRIM(RTRIM(IDFOLINICIAL)), '') = '';

UPDATE dbo.PV_CTR_FOL_ASVR
SET ORIGEN_AUT = CASE
  WHEN UPPER(LTRIM(RTRIM(ISNULL(AUT, '')))) IN ('DCA', 'CA', 'DC', 'DG') THEN 'CA'
  WHEN UPPER(LTRIM(RTRIM(ISNULL(AUT, '')))) IN ('DVF', 'VF') THEN 'VF'
  WHEN UPPER(LTRIM(RTRIM(ISNULL(AUT, '')))) = 'CP' THEN 'CA'
  WHEN UPPER(LTRIM(RTRIM(ISNULL(AUT, '')))) = 'PS' THEN 'CA'
  ELSE ISNULL(NULLIF(LTRIM(RTRIM(ORIGEN_AUT)), ''), 'CA')
END
WHERE ISNULL(LTRIM(RTRIM(ORIGEN_AUT)), '') = '';

UPDATE dbo.PV_CTR_FOL_ASVR
SET ESTA = CASE
  WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTA, '')))) IN ('EDITANDO', 'DEV PEND', 'PAGADO2', '') THEN 'PENDIENTE'
  WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTA, '')))) LIKE 'PAGADO%' THEN 'PAGADO'
  WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTA, '')))) LIKE 'TRANSMIT%' THEN 'TRANSMITIR'
  ELSE UPPER(LTRIM(RTRIM(ISNULL(ESTA, ''))))
END;

/* 4) Endurecer nulabilidad posterior a regularización */
IF EXISTS (
  SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR') AND name='IDFOLINICIAL' AND is_nullable=1
)
BEGIN
  ALTER TABLE dbo.PV_CTR_FOL_ASVR ALTER COLUMN IDFOLINICIAL VARCHAR(255) NOT NULL;
END;

IF EXISTS (
  SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR') AND name='ORIGEN_AUT' AND is_nullable=1
)
BEGIN
  ALTER TABLE dbo.PV_CTR_FOL_ASVR ALTER COLUMN ORIGEN_AUT VARCHAR(2) NOT NULL;
END;

/* 5) CHECKS */
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO')
BEGIN
  ALTER TABLE dbo.PV_CTR_FOL_ASVR WITH NOCHECK
    ADD CONSTRAINT CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO
      CHECK (ESTA IN ('PENDIENTE','PAGADO','TRANSMITIR'));
END;

IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_PV_CTR_FOL_ASVR_ORIGEN_AUT_HOMOLOGADO')
BEGIN
  ALTER TABLE dbo.PV_CTR_FOL_ASVR WITH NOCHECK
    ADD CONSTRAINT CK_PV_CTR_FOL_ASVR_ORIGEN_AUT_HOMOLOGADO
      CHECK (ORIGEN_AUT IN ('CA','VF'));
END;

/* 6) Índices */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR') AND name = 'IX_PV_CTR_FOL_ASVR_IDFOLINICIAL')
  CREATE INDEX IX_PV_CTR_FOL_ASVR_IDFOLINICIAL ON dbo.PV_CTR_FOL_ASVR (IDFOLINICIAL);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR') AND name = 'IX_PV_CTR_FOL_ASVR_IDFOLORIG')
  CREATE INDEX IX_PV_CTR_FOL_ASVR_IDFOLORIG ON dbo.PV_CTR_FOL_ASVR (IDFOLORIG);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR') AND name = 'IX_PV_CTR_FOL_ASVR_AUT_ESTA_ORIGEN')
  CREATE INDEX IX_PV_CTR_FOL_ASVR_AUT_ESTA_ORIGEN ON dbo.PV_CTR_FOL_ASVR (AUT, ESTA, ORIGEN_AUT);
GO
