SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER TRIGGER dbo.trg_pv_ctr_fol_asvr_homologacion
ON dbo.PV_CTR_FOL_ASVR
AFTER INSERT, UPDATE
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE t
  SET
    t.AUT = CASE WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT,''))))='PCR' THEN 'CR' ELSE UPPER(LTRIM(RTRIM(ISNULL(t.AUT,'CP')))) END,
    t.ESTA = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) IN ('EDITANDO', 'DEV PEND', 'PAGADO2', '') THEN 'PENDIENTE'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'PAGADO%' THEN 'PAGADO'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'TRANSMIT%' THEN 'TRANSMITIR'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) = 'MB51PROCES' THEN 'TRANSMITIR'
      ELSE UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, ''))))
    END,
    t.IDFOLINICIAL = ISNULL(NULLIF(LTRIM(RTRIM(t.IDFOLINICIAL)), ''), t.IDFOL),
    t.ORIGEN_AUT = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('DCA','CA','DC','DG') THEN 'CA'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('DVF','VF') THEN 'VF'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('PS','CP') THEN ISNULL(NULLIF(UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT,'')))),''), 'CA')
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('AD','AP','CR','PCR') THEN ISNULL(NULLIF(UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT,'')))),''), 'CA')
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT, '')))) IN ('CA','VF') THEN UPPER(LTRIM(RTRIM(t.ORIGEN_AUT)))
      ELSE 'CA'
    END
  FROM dbo.PV_CTR_FOL_ASVR t
  INNER JOIN inserted i ON i.IDFOL = t.IDFOL;
END;
GO

UPDATE dbo.PV_CTR_FOL_ASVR
SET
  AUT = 'CR',
  ESTA = CASE WHEN ESTA IN ('PENDIENTE','PAGADO','TRANSMITIR') THEN ESTA WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTA,''))))='MB51PROCES' THEN 'TRANSMITIR' ELSE 'PENDIENTE' END,
  IDFOLINICIAL = ISNULL(NULLIF(LTRIM(RTRIM(IDFOLINICIAL)), ''), IDFOL),
  ORIGEN_AUT = ISNULL(NULLIF(LTRIM(RTRIM(ORIGEN_AUT)), ''), 'CA')
WHERE UPPER(LTRIM(RTRIM(ISNULL(AUT,''))))='PCR';
GO
