SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

PRINT 'Validacion 1: alta CP y cierre CA con efectivo';
BEGIN TRANSACTION;

DECLARE @SUC_CA NVARCHAR(20) = 'DF10';
DECLARE @OPV_CA NVARCHAR(50) = 'CODEXVALCA';
DECLARE @IDFOL_CP_CA NVARCHAR(255);
DECLARE @TRA_CP_CA INT;
DECLARE @IDROW_CA NVARCHAR(255) = CONVERT(NVARCHAR(255), NEWID());
DECLARE @RESULT_CA TABLE (
  idfol NVARCHAR(255),
  tipotran NVARCHAR(10),
  rqfac BIT,
  subtotal MONEY,
  iva MONEY,
  total MONEY,
  totalBase MONEY,
  ivaIntegrado INT,
  sumPagos MONEY,
  cambio MONEY
);

EXEC dbo.sp_pvctrfolasvr_create
  @SUC = @SUC_CA,
  @OPV = @OPV_CA,
  @IDFOL_OUT = @IDFOL_CP_CA OUTPUT,
  @TRA_OUT = @TRA_CP_CA OUTPUT;

INSERT INTO dbo.PV_TICKET_LOG (
  ID,
  IDFOL,
  UPC,
  ART,
  DES,
  CTD,
  PVTA,
  PVTAT,
  ORD,
  updated_at
)
VALUES (
  @IDROW_CA,
  @IDFOL_CP_CA,
  'VAL-CP-CA',
  'VAL-ART-CA',
  'VALIDACION CA',
  1,
  100,
  100,
  NULL,
  GETDATE()
);

INSERT INTO @RESULT_CA
EXEC dbo.sp_pv_cotizacion_cerrar
  @IDFOL = @IDFOL_CP_CA,
  @SUC = @SUC_CA,
  @TIPOTRAN = 'CA',
  @RQFAC = 0,
  @IDOPV = @OPV_CA,
  @FORMAS_JSON = N'[{"form":"EFECTIVO","impp":100.00}]';

SELECT
  'CA' AS CASO,
  @IDFOL_CP_CA AS IDFOL_INICIAL,
  R.idfol AS IDFOL_FINAL,
  H.IDFOLINICIAL,
  H.AUT,
  H.ESTA,
  H.ORIGEN_AUT,
  H.TRA,
  T.IDFOL AS TICKET_IDFOL,
  C1.ULTIMO_CONSEC AS CP_CONSEC,
  C2.ULTIMO_CONSEC AS CA_CONSEC
FROM @RESULT_CA R
JOIN dbo.PV_CTR_FOL_ASVR H
  ON H.IDFOL = R.idfol
JOIN dbo.PV_TICKET_LOG T
  ON T.ID = @IDROW_CA
LEFT JOIN dbo.DAT_FOLIOS_CONSEC C1
  ON C1.SUC = @SUC_CA
 AND C1.FECHA = CONVERT(DATE, GETDATE())
 AND C1.TIPO_FOLIO = 'CP'
LEFT JOIN dbo.DAT_FOLIOS_CONSEC C2
  ON C2.SUC = @SUC_CA
 AND C2.FECHA = CONVERT(DATE, GETDATE())
 AND C2.TIPO_FOLIO = 'CA';

ROLLBACK TRANSACTION;
GO

PRINT 'Validacion 2: alta CP y cierre VF con referencia procesada';
BEGIN TRANSACTION;

DECLARE @SUC_VF NVARCHAR(20) = 'DF10';
DECLARE @OPV_VF NVARCHAR(50) = 'CODEXVALVF';
DECLARE @IDFOL_CP_VF NVARCHAR(255);
DECLARE @TRA_CP_VF INT;
DECLARE @IDROW_VF NVARCHAR(255) = CONVERT(NVARCHAR(255), NEWID());
DECLARE @CLIENT_VF FLOAT;
DECLARE @CLIENT_VF_INT INT;
DECLARE @IDREF_VF NVARCHAR(255) = CONCAT('VALREF-', REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', ''));
DECLARE @FORMAS_JSON_VF NVARCHAR(MAX);
DECLARE @RESULT_VF TABLE (
  idfol NVARCHAR(255),
  tipotran NVARCHAR(10),
  rqfac BIT,
  subtotal MONEY,
  iva MONEY,
  total MONEY,
  totalBase MONEY,
  ivaIntegrado INT,
  sumPagos MONEY,
  cambio MONEY
);

SELECT TOP 1 @CLIENT_VF = IDC
FROM dbo.FACT_CLIENT_SHP
WHERE SUC = @SUC_VF
  AND TRY_CONVERT(INT, IDC) <> 1
ORDER BY IDC;

IF @CLIENT_VF IS NULL
  THROW 57200, 'No existe cliente de validacion para cierre VF', 1;

SET @CLIENT_VF_INT = TRY_CONVERT(INT, @CLIENT_VF);
SET @FORMAS_JSON_VF = CONCAT(
  N'[{"form":"TRANSFERENCIA","impp":250.00,"aut":"',
  @IDREF_VF,
  N'"}]'
);

EXEC dbo.sp_pvctrfolasvr_create
  @SUC = @SUC_VF,
  @OPV = @OPV_VF,
  @CLIEN = @CLIENT_VF_INT,
  @IDFOL_OUT = @IDFOL_CP_VF OUTPUT,
  @TRA_OUT = @TRA_CP_VF OUTPUT;

UPDATE dbo.PV_CTR_FOL_ASVR
SET CLIEN = @CLIENT_VF
WHERE IDFOL = @IDFOL_CP_VF;

INSERT INTO dbo.PV_TICKET_LOG (
  ID,
  IDFOL,
  UPC,
  ART,
  DES,
  CTD,
  PVTA,
  PVTAT,
  ORD,
  updated_at
)
VALUES (
  @IDROW_VF,
  @IDFOL_CP_VF,
  'VAL-CP-VF',
  'VAL-ART-VF',
  'VALIDACION VF',
  1,
  250,
  250,
  NULL,
  GETDATE()
);

INSERT INTO dbo.REF_DETALLE (
  SUC,
  IDREF,
  FCNR,
  FCND,
  OPV,
  IDFOL,
  IDC,
  RfcEmisor,
  TIPO,
  IMPT,
  ESTATUS
)
VALUES (
  @SUC_VF,
  @IDREF_VF,
  GETDATE(),
  GETDATE(),
  @OPV_VF,
  @IDFOL_CP_VF,
  @CLIENT_VF,
  'RFCVALIDACION',
  'TRANSFERENCIA',
  250,
  'PROCESADO'
);

INSERT INTO @RESULT_VF
EXEC dbo.sp_pv_cotizacion_cerrar
  @IDFOL = @IDFOL_CP_VF,
  @SUC = @SUC_VF,
  @TIPOTRAN = 'VF',
  @RQFAC = 0,
  @IDOPV = @OPV_VF,
  @FORMAS_JSON = @FORMAS_JSON_VF;

SELECT
  'VF' AS CASO,
  @IDFOL_CP_VF AS IDFOL_INICIAL,
  R.idfol AS IDFOL_FINAL,
  H.IDFOLINICIAL,
  H.AUT,
  H.ESTA,
  H.ORIGEN_AUT,
  H.TRA,
  T.IDFOL AS TICKET_IDFOL,
  RD.IDFOL AS REF_IDFOL,
  C1.ULTIMO_CONSEC AS CP_CONSEC,
  C2.ULTIMO_CONSEC AS VF_CONSEC
FROM @RESULT_VF R
JOIN dbo.PV_CTR_FOL_ASVR H
  ON H.IDFOL = R.idfol
JOIN dbo.PV_TICKET_LOG T
  ON T.ID = @IDROW_VF
JOIN dbo.REF_DETALLE RD
  ON RD.IDREF = @IDREF_VF
LEFT JOIN dbo.DAT_FOLIOS_CONSEC C1
  ON C1.SUC = @SUC_VF
 AND C1.FECHA = CONVERT(DATE, GETDATE())
 AND C1.TIPO_FOLIO = 'CP'
LEFT JOIN dbo.DAT_FOLIOS_CONSEC C2
  ON C2.SUC = @SUC_VF
 AND C2.FECHA = CONVERT(DATE, GETDATE())
 AND C2.TIPO_FOLIO = 'VF';

ROLLBACK TRANSACTION;
GO
