SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/*
  DEV_PROVD - Devoluciones a proveedor.

  Reutiliza:
  - DAT_PROVD para proveedores;
  - DAT_ART para articulo, existencia, costo y jerarquias;
  - DAT_CMOV 102 para la salida administrativa;
  - DAT_CTR_DOC / DAT_MB51 para el movimiento oficial;
  - AUDIT_LOG para trazabilidad.

  La reserva no altera DAT_ART.STOCK. La salida se registra exclusivamente
  en sp_dev_provd_autorizar. El script es idempotente.
*/

IF OBJECT_ID('dbo.DEV_TIPO_PROVD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_TIPO_PROVD (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DEV_TIPO_PROVD PRIMARY KEY,
    CLAVE NVARCHAR(30) NOT NULL CONSTRAINT UQ_DEV_TIPO_PROVD_CLAVE UNIQUE,
    [DESC] NVARCHAR(150) NOT NULL,
    ACTIVO BIT NOT NULL CONSTRAINT DF_DEV_TIPO_PROVD_ACTIVO DEFAULT(1),
    FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_DEV_TIPO_PROVD_FCNR DEFAULT(SYSDATETIME())
  );
END;
GO

IF OBJECT_ID('dbo.DEV_MOTIVO_PROVD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_MOTIVO_PROVD (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DEV_MOTIVO_PROVD PRIMARY KEY,
    CODIGO NVARCHAR(20) NOT NULL CONSTRAINT UQ_DEV_MOTIVO_PROVD_CODIGO UNIQUE,
    [DESC] NVARCHAR(180) NOT NULL,
    REQUIERE_EVIDENCIA BIT NOT NULL CONSTRAINT DF_DEV_MOTIVO_EVID DEFAULT(0),
    REQUIERE_DOCUMENTO BIT NOT NULL CONSTRAINT DF_DEV_MOTIVO_DOC DEFAULT(0),
    PERMITE_PARCIAL BIT NOT NULL CONSTRAINT DF_DEV_MOTIVO_PARCIAL DEFAULT(1),
    ACTIVO BIT NOT NULL CONSTRAINT DF_DEV_MOTIVO_ACTIVO DEFAULT(1),
    FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_DEV_MOTIVO_FCNR DEFAULT(SYSDATETIME())
  );
END;
GO

IF OBJECT_ID('dbo.DEV_DOC_PROVD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_DOC_PROVD (
    ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DEV_DOC_PROVD PRIMARY KEY,
    DOC NVARCHAR(40) NOT NULL CONSTRAINT UQ_DEV_DOC_PROVD_DOC UNIQUE,
    SUC NVARCHAR(20) NOT NULL,
    ALMACEN VARCHAR(10) NOT NULL CONSTRAINT DF_DEV_DOC_ALMACEN DEFAULT('002'),
    PROVD INT NOT NULL,
    DOC_OC NVARCHAR(255) NULL,
    DOC_REC NVARCHAR(255) NULL,
    FCND DATETIME2(0) NOT NULL CONSTRAINT DF_DEV_DOC_FCND DEFAULT(SYSDATETIME()),
    TIPO_DEV INT NOT NULL,
    ESTATUS NVARCHAR(30) NOT NULL CONSTRAINT DF_DEV_DOC_ESTATUS DEFAULT('BORRADOR'),
    OBS NVARCHAR(1000) NULL,
    USR_CREA NVARCHAR(100) NOT NULL,
    FCNM DATETIME2(0) NULL,
    USR_SOLICITA NVARCHAR(100) NULL,
    FCN_SOLICITA DATETIME2(0) NULL,
    USR_AUTORIZA NVARCHAR(100) NULL,
    FCN_AUTORIZA DATETIME2(0) NULL,
    USR_RECHAZA NVARCHAR(100) NULL,
    FCN_RECHAZA DATETIME2(0) NULL,
    MOTIVO_RECHAZO NVARCHAR(1000) NULL,
    DOC_MB51 NVARCHAR(510) NULL,
    CONSTRAINT FK_DEV_DOC_PROVD_PROVD FOREIGN KEY(PROVD) REFERENCES dbo.DAT_PROVD(ID),
    CONSTRAINT FK_DEV_DOC_PROVD_TIPO FOREIGN KEY(TIPO_DEV) REFERENCES dbo.DEV_TIPO_PROVD(ID),
    CONSTRAINT CK_DEV_DOC_ESTATUS CHECK(ESTATUS IN ('BORRADOR','PENDIENTE','AUTORIZADA','RECHAZADA','CANCELADA','CONSOLIDADA','EN_TRANSITO','RECIBIDA'))
  );
END;
GO

IF OBJECT_ID('dbo.DEV_FOLIO_PROVD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_FOLIO_PROVD (
    SUC NVARCHAR(20) NOT NULL CONSTRAINT PK_DEV_FOLIO_PROVD PRIMARY KEY,
    ULTIMO BIGINT NOT NULL,
    FCNM DATETIME2(0) NOT NULL CONSTRAINT DF_DEV_FOLIO_FCNM DEFAULT(SYSDATETIME())
  );
  INSERT dbo.DEV_FOLIO_PROVD(SUC,ULTIMO)
  SELECT SUC,MAX(ISNULL(TRY_CONVERT(BIGINT,RIGHT(DOC,8)),0))
  FROM dbo.DEV_DOC_PROVD GROUP BY SUC;
END;
GO

IF OBJECT_ID('dbo.DEV_CTRL_PROVD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_CTRL_PROVD (
    IDPD BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DEV_CTRL_PROVD PRIMARY KEY,
    DOC NVARCHAR(40) NOT NULL,
    ART NVARCHAR(20) NOT NULL,
    CTDA_DEV DECIMAL(18,4) NOT NULL,
    CTDA_BLOQ DECIMAL(18,4) NOT NULL CONSTRAINT DF_DEV_CTRL_BLOQ DEFAULT(0),
    CTOP MONEY NOT NULL,
    IMPT MONEY NOT NULL,
    LOTE NVARCHAR(100) NULL,
    CADUCIDAD DATE NULL,
    MOV_DEV INT NOT NULL,
    OBS NVARCHAR(1000) NULL,
    ACTIVO BIT NOT NULL CONSTRAINT DF_DEV_CTRL_ACTIVO DEFAULT(1),
    USR_CREA NVARCHAR(100) NOT NULL,
    FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_DEV_CTRL_FCNR DEFAULT(SYSDATETIME()),
    FCNM DATETIME2(0) NULL,
    CONSTRAINT FK_DEV_CTRL_DOC FOREIGN KEY(DOC) REFERENCES dbo.DEV_DOC_PROVD(DOC),
    CONSTRAINT FK_DEV_CTRL_MOTIVO FOREIGN KEY(MOV_DEV) REFERENCES dbo.DEV_MOTIVO_PROVD(ID),
    CONSTRAINT CK_DEV_CTRL_CTD CHECK(CTDA_DEV > 0 AND CTDA_BLOQ >= 0),
    CONSTRAINT CK_DEV_CTRL_COSTO CHECK(CTOP >= 0 AND IMPT >= 0)
  );
END;
GO

IF OBJECT_ID('dbo.DEV_EVIDENCIA_PROVD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_EVIDENCIA_PROVD (
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DEV_EVIDENCIA_PROVD PRIMARY KEY CONSTRAINT DF_DEV_EVID_ID DEFAULT(NEWID()),
    IDPD BIGINT NOT NULL,
    NOMBRE_ARCHIVO NVARCHAR(255) NULL,
    MIME_TYPE NVARCHAR(100) NOT NULL,
    CONTENIDO NVARCHAR(MAX) NOT NULL,
    PESO_BYTES BIGINT NULL,
    USR_CREA NVARCHAR(100) NOT NULL,
    FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_DEV_EVID_FCNR DEFAULT(SYSDATETIME()),
    CONSTRAINT FK_DEV_EVID_DET FOREIGN KEY(IDPD) REFERENCES dbo.DEV_CTRL_PROVD(IDPD)
  );
END;
GO

IF OBJECT_ID('dbo.DEV_ENVIO_PROVD', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_ENVIO_PROVD (
    ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DEV_ENVIO_PROVD PRIMARY KEY,
    ENVIO NVARCHAR(40) NULL,
    PROVD INT NOT NULL,
    ESTATUS NVARCHAR(30) NOT NULL CONSTRAINT DF_DEV_ENVIO_ESTATUS DEFAULT('CONSOLIDADO'),
    TRANSPORTISTA NVARCHAR(120) NOT NULL,
    GUIA NVARCHAR(120) NOT NULL,
    CAJAS INT NOT NULL,
    RMA NVARCHAR(120) NULL,
    OBS NVARCHAR(1000) NULL,
    USR_CREA NVARCHAR(100) NOT NULL,
    FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_DEV_ENVIO_FCNR DEFAULT(SYSDATETIME()),
    USR_SALIDA NVARCHAR(100) NULL,
    FCN_SALIDA DATETIME2(0) NULL,
    CONSTRAINT FK_DEV_ENVIO_PROVD FOREIGN KEY(PROVD) REFERENCES dbo.DAT_PROVD(ID),
    CONSTRAINT CK_DEV_ENVIO_CAJAS CHECK(CAJAS > 0),
    CONSTRAINT CK_DEV_ENVIO_ESTATUS CHECK(ESTATUS IN ('CONSOLIDADO','EN_TRANSITO','RECIBIDA'))
  );
END;
GO

IF OBJECT_ID('dbo.DEV_ENVIO_DOC', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DEV_ENVIO_DOC (
    IDENVIO BIGINT NOT NULL,
    DOC NVARCHAR(40) NOT NULL,
    CONSTRAINT PK_DEV_ENVIO_DOC PRIMARY KEY(IDENVIO, DOC),
    CONSTRAINT UQ_DEV_ENVIO_DOC_DOC UNIQUE(DOC),
    CONSTRAINT FK_DEV_ENVIO_DOC_ENVIO FOREIGN KEY(IDENVIO) REFERENCES dbo.DEV_ENVIO_PROVD(ID),
    CONSTRAINT FK_DEV_ENVIO_DOC_DOC FOREIGN KEY(DOC) REFERENCES dbo.DEV_DOC_PROVD(DOC)
  );
END;
GO

MERGE dbo.DEV_TIPO_PROVD AS t
USING (VALUES
  ('DEFECTO_FABRICA', 'Defecto de fabrica'),
  ('ERROR_SURTIDO', 'Error de surtido'),
  ('DANO_TRANSITO', 'Dano en transito'),
  ('SOBRANTE_RECEPCION', 'Sobrante de recepcion'),
  ('CADUCIDAD', 'Caducidad'),
  ('COMERCIAL', 'Comercial u obsolescencia'),
  ('GARANTIA', 'Garantia')
) AS s(CLAVE, [DESC]) ON t.CLAVE=s.CLAVE
WHEN MATCHED THEN UPDATE SET [DESC]=s.[DESC]
WHEN NOT MATCHED THEN INSERT(CLAVE,[DESC]) VALUES(s.CLAVE,s.[DESC]);
GO

MERGE dbo.DEV_MOTIVO_PROVD AS t
USING (VALUES
  ('DEV-01','Defecto de material',1,0,1),
  ('DEV-02','Tratamiento incorrecto',1,0,1),
  ('DEV-03','Graduacion fuera de tolerancia',1,0,1),
  ('DEV-04','Curva o diametro incorrecto',1,0,1),
  ('DEV-05','Etiquetado o empaque incorrecto',1,0,1),
  ('DEV-06','Articulo distinto al solicitado',1,1,1),
  ('DEV-07','Cantidad excedente',0,1,1),
  ('DEV-08','Dano en transporte',1,1,1),
  ('DEV-09','Caducidad',1,0,1),
  ('DEV-10','Obsolescencia',0,0,1),
  ('DEV-11','Garantia de cliente',1,1,1)
) AS s(CODIGO,[DESC],REQUIERE_EVIDENCIA,REQUIERE_DOCUMENTO,PERMITE_PARCIAL)
ON t.CODIGO=s.CODIGO
WHEN MATCHED THEN UPDATE SET [DESC]=s.[DESC],REQUIERE_EVIDENCIA=s.REQUIERE_EVIDENCIA,REQUIERE_DOCUMENTO=s.REQUIERE_DOCUMENTO,PERMITE_PARCIAL=s.PERMITE_PARCIAL
WHEN NOT MATCHED THEN INSERT(CODIGO,[DESC],REQUIERE_EVIDENCIA,REQUIERE_DOCUMENTO,PERMITE_PARCIAL) VALUES(s.CODIGO,s.[DESC],s.REQUIERE_EVIDENCIA,s.REQUIERE_DOCUMENTO,s.PERMITE_PARCIAL);
GO

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.DEV_DOC_PROVD') AND name='IX_DEV_DOC_PROVD_LISTA')
  CREATE INDEX IX_DEV_DOC_PROVD_LISTA ON dbo.DEV_DOC_PROVD(ESTATUS, FCND DESC, PROVD, SUC);
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.DEV_CTRL_PROVD') AND name='IX_DEV_CTRL_PROVD_DOC')
  CREATE INDEX IX_DEV_CTRL_PROVD_DOC ON dbo.DEV_CTRL_PROVD(DOC, ACTIVO) INCLUDE(ART,CTDA_DEV,CTDA_BLOQ,CTOP,IMPT,MOV_DEV);
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.DEV_CTRL_PROVD') AND name='IX_DEV_CTRL_PROVD_RESERVA')
  CREATE INDEX IX_DEV_CTRL_PROVD_RESERVA ON dbo.DEV_CTRL_PROVD(ART, ACTIVO, CTDA_BLOQ) INCLUDE(DOC);
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.DEV_EVIDENCIA_PROVD') AND name='IX_DEV_EVIDENCIA_IDPD')
  CREATE INDEX IX_DEV_EVIDENCIA_IDPD ON dbo.DEV_EVIDENCIA_PROVD(IDPD, FCNR);
GO

CREATE OR ALTER TRIGGER dbo.trg_dat_art_dev_provd_reserva
ON dbo.DAT_ART
AFTER UPDATE
AS
BEGIN
  SET NOCOUNT ON;
  IF NOT UPDATE(STOCK) RETURN;

  IF EXISTS(
    SELECT 1
    FROM inserted i
    CROSS APPLY(
      SELECT SUM(d.CTDA_BLOQ) RESERVADO
      FROM dbo.DEV_CTRL_PROVD d
      JOIN dbo.DEV_DOC_PROVD h ON h.DOC=d.DOC
      WHERE h.SUC=i.SUC AND h.ESTATUS='PENDIENTE'
        AND d.ART=i.ART AND d.ACTIVO=1 AND d.CTDA_BLOQ>0
    ) r
    WHERE ISNULL(i.STOCK,0)<ISNULL(r.RESERVADO,0)
  )
    THROW 59280,'La operacion intenta consumir inventario reservado para devolucion a proveedor.',1;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_recalcular
  @DOC NVARCHAR(40)
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE d SET IMPT=CONVERT(MONEY,CTDA_DEV*CTOP),FCNM=SYSDATETIME()
  FROM dbo.DEV_CTRL_PROVD d WHERE d.DOC=@DOC AND d.ACTIVO=1;
  UPDATE h SET FCNM=SYSDATETIME() FROM dbo.DEV_DOC_PROVD h WHERE h.DOC=@DOC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_crear
  @SUC NVARCHAR(20), @ALMACEN VARCHAR(10)='002', @PROVD INT,
  @TIPO_DEV INT, @DOC_OC NVARCHAR(255)=NULL, @DOC_REC NVARCHAR(255)=NULL,
  @OBS NVARCHAR(1000)=NULL, @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    SET @SUC=UPPER(LTRIM(RTRIM(ISNULL(@SUC,''))));
    SET @ALMACEN=LTRIM(RTRIM(ISNULL(@ALMACEN,'002')));
    IF @SUC='' THROW 59200,'La sucursal es requerida.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DAT_SUC WHERE UPPER(LTRIM(RTRIM(SUC)))=@SUC) THROW 59201,'La sucursal no existe.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DAT_PROVD WHERE ID=@PROVD AND ISNULL(BLOQ,0)<>-1) THROW 59202,'El proveedor no existe o esta inactivo.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DEV_TIPO_PROVD WHERE ID=@TIPO_DEV AND ACTIVO=1) THROW 59203,'El tipo de devolucion no es valido.',1;

    DECLARE @FOLIOS TABLE(ULTIMO BIGINT);
    MERGE dbo.DEV_FOLIO_PROVD WITH(HOLDLOCK) AS target
    USING(SELECT @SUC SUC) AS source ON target.SUC=source.SUC
    WHEN MATCHED THEN UPDATE SET ULTIMO=target.ULTIMO+1,FCNM=SYSDATETIME()
    WHEN NOT MATCHED THEN INSERT(SUC,ULTIMO) VALUES(source.SUC,1)
    OUTPUT inserted.ULTIMO INTO @FOLIOS;
    DECLARE @FOLIO BIGINT=(SELECT ULTIMO FROM @FOLIOS), @DOC NVARCHAR(40);
    SET @DOC=CONCAT('DEV-',@SUC,'-',RIGHT(CONCAT('00000000',CONVERT(VARCHAR(20),@FOLIO)),8));
    INSERT dbo.DEV_DOC_PROVD(DOC,SUC,ALMACEN,PROVD,DOC_OC,DOC_REC,TIPO_DEV,ESTATUS,OBS,USR_CREA)
    VALUES(@DOC,@SUC,@ALMACEN,@PROVD,NULLIF(LTRIM(RTRIM(@DOC_OC)),''),NULLIF(LTRIM(RTRIM(@DOC_REC)),''),@TIPO_DEV,'BORRADOR',NULLIF(LTRIM(RTRIM(@OBS)),''),@USR);
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'CREAR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @DOC DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_agregar_articulo
  @DOC NVARCHAR(40), @ART NVARCHAR(20), @CTDA_DEV DECIMAL(18,4),
  @CTOP MONEY=NULL, @MOV_DEV INT, @LOTE NVARCHAR(100)=NULL,
  @CADUCIDAD DATE=NULL, @OBS NVARCHAR(1000)=NULL, @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SUC NVARCHAR(20),@ESTATUS NVARCHAR(30),@COSTO MONEY;
    SELECT @SUC=SUC,@ESTATUS=ESTATUS FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59210,'La devolucion no existe.',1;
    IF @ESTATUS<>'BORRADOR' THROW 59211,'Solo se editan articulos en BORRADOR.',1;
    IF @CTDA_DEV<=0 THROW 59212,'La cantidad debe ser mayor a cero.',1;
    SELECT @COSTO=COALESCE(NULLIF(@CTOP,0),CTOP,0) FROM dbo.DAT_ART WITH(UPDLOCK,HOLDLOCK) WHERE SUC=@SUC AND ART=@ART AND ISNULL(BLOQ,0)<>-1;
    IF @COSTO IS NULL THROW 59213,'El articulo no existe en la sucursal.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DEV_MOTIVO_PROVD WHERE ID=@MOV_DEV AND ACTIVO=1) THROW 59214,'El motivo no es valido.',1;

    INSERT dbo.DEV_CTRL_PROVD(DOC,ART,CTDA_DEV,CTDA_BLOQ,CTOP,IMPT,LOTE,CADUCIDAD,MOV_DEV,OBS,USR_CREA)
    VALUES(@DOC,@ART,@CTDA_DEV,0,@COSTO,CONVERT(MONEY,@CTDA_DEV*@COSTO),NULLIF(LTRIM(RTRIM(@LOTE)),''),@CADUCIDAD,@MOV_DEV,NULLIF(LTRIM(RTRIM(@OBS)),''),@USR);
    DECLARE @IDPD BIGINT=SCOPE_IDENTITY();
    EXEC dbo.sp_dev_provd_recalcular @DOC=@DOC;
    COMMIT;
    SELECT @IDPD IDPD;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_solicitar
  @DOC NVARCHAR(40), @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SUC NVARCHAR(20),@ESTATUS NVARCHAR(30),@LOCK INT,@LOCK_RESOURCE NVARCHAR(255);
    SELECT @SUC=SUC,@ESTATUS=ESTATUS FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59220,'La devolucion no existe.',1;
    IF @ESTATUS='PENDIENTE' BEGIN COMMIT; SELECT @DOC DOC,'PENDIENTE' ESTATUS; RETURN; END;
    IF @ESTATUS<>'BORRADOR' THROW 59221,'Solo se puede solicitar desde BORRADOR.',1;
    SET @LOCK_RESOURCE=CONCAT('DEV_PROVD_RESERVA_',@SUC);
    EXEC @LOCK=sys.sp_getapplock @Resource=@LOCK_RESOURCE,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
    IF @LOCK<0 THROW 59222,'No fue posible bloquear el inventario para validar.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DEV_CTRL_PROVD WHERE DOC=@DOC AND ACTIVO=1) THROW 59223,'La devolucion no tiene articulos.',1;
    IF NOT EXISTS(
      SELECT 1 FROM dbo.DEV_EVIDENCIA_PROVD e
      JOIN dbo.DEV_CTRL_PROVD d ON d.IDPD=e.IDPD
      WHERE d.DOC=@DOC AND d.ACTIVO=1
    ) THROW 59224,'La devolucion requiere una evidencia fotografica.',1;
    IF EXISTS(
      SELECT 1 FROM dbo.DEV_CTRL_PROVD d JOIN dbo.DEV_MOTIVO_PROVD m ON m.ID=d.MOV_DEV JOIN dbo.DEV_DOC_PROVD h ON h.DOC=d.DOC
      WHERE d.DOC=@DOC AND d.ACTIVO=1 AND m.REQUIERE_DOCUMENTO=1 AND NULLIF(LTRIM(RTRIM(COALESCE(h.DOC_REC,h.DOC_OC,''))),'') IS NULL
    ) THROW 59225,'El motivo requiere orden de compra o recepcion relacionada.',1;

    IF EXISTS(
      SELECT 1 FROM (SELECT ART,SUM(CTDA_DEV) CTD FROM dbo.DEV_CTRL_PROVD WHERE DOC=@DOC AND ACTIVO=1 GROUP BY ART) s
      LEFT JOIN dbo.DAT_ART a WITH(UPDLOCK,HOLDLOCK) ON a.SUC=@SUC AND a.ART=s.ART
      OUTER APPLY(SELECT SUM(x.CTDA_BLOQ) CTD FROM dbo.DEV_CTRL_PROVD x JOIN dbo.DEV_DOC_PROVD h ON h.DOC=x.DOC WHERE h.SUC=@SUC AND h.ESTATUS='PENDIENTE' AND x.ACTIVO=1 AND x.DOC<>@DOC AND x.ART=s.ART) r
      WHERE a.ART IS NULL OR ISNULL(a.STOCK,0)-ISNULL(r.CTD,0)<s.CTD
    ) THROW 59226,'Existencia disponible insuficiente para reservar.',1;

    UPDATE dbo.DEV_CTRL_PROVD SET CTDA_BLOQ=CTDA_DEV,FCNM=SYSDATETIME() WHERE DOC=@DOC AND ACTIVO=1;
    UPDATE dbo.DEV_DOC_PROVD SET ESTATUS='PENDIENTE',USR_SOLICITA=@USR,FCN_SOLICITA=SYSDATETIME(),FCNM=SYSDATETIME() WHERE DOC=@DOC;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'SOLICITAR_RESERVAR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @DOC DOC,'PENDIENTE' ESTATUS;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_autorizar
  @DOC NVARCHAR(40), @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SUC NVARCHAR(20),@ALMACEN VARCHAR(10),@ESTATUS NVARCHAR(30),@LOCK INT,@LOCK_RESOURCE NVARCHAR(255);
    SELECT @SUC=SUC,@ALMACEN=ALMACEN,@ESTATUS=ESTATUS FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59230,'La devolucion no existe.',1;
    IF @ESTATUS IN ('AUTORIZADA','CONSOLIDADA','EN_TRANSITO') BEGIN COMMIT; SELECT @DOC DOC,@ESTATUS ESTATUS; RETURN; END;
    IF @ESTATUS<>'PENDIENTE' THROW 59231,'Solo se autoriza una devolucion PENDIENTE.',1;
    SET @LOCK_RESOURCE=CONCAT('DEV_PROVD_RESERVA_',@SUC);
    EXEC @LOCK=sys.sp_getapplock @Resource=@LOCK_RESOURCE,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
    IF @LOCK<0 THROW 59232,'No fue posible bloquear el inventario para autorizar.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DAT_CMOV WHERE CMOV=102) THROW 59233,'DAT_CMOV no tiene configurado el movimiento 102.',1;
    IF EXISTS(
      SELECT 1 FROM (SELECT ART,SUM(CTDA_BLOQ) CTD FROM dbo.DEV_CTRL_PROVD WHERE DOC=@DOC AND ACTIVO=1 GROUP BY ART) q
      LEFT JOIN dbo.DAT_ART a WITH(UPDLOCK,HOLDLOCK) ON a.SUC=@SUC AND a.ART=q.ART
      WHERE a.ART IS NULL OR q.CTD<=0 OR ISNULL(a.STOCK,0)<q.CTD
    ) THROW 59234,'La existencia cambio y ya no permite autorizar la devolucion.',1;

    IF NOT EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC)
      INSERT dbo.DAT_CTR_DOC(DOC,CLSMOV,FCND,[USER],STAT) VALUES(@DOC,'102',SYSDATETIME(),@USR,'V');

    INSERT dbo.DAT_MB51(IDPD,[USER],CLSM,DOCP,ART,CTDA,CTOT,FCND,FCNC,TXT,ALMACEN,VTAESP,SUC)
    SELECT CONCAT('DEV-',d.DOC,'-',d.IDPD),@USR,102,d.DOC,d.ART,-ABS(CONVERT(FLOAT,d.CTDA_BLOQ)),-ABS(CONVERT(FLOAT,d.CTDA_BLOQ))*CONVERT(FLOAT,d.CTOP),SYSDATETIME(),SYSDATETIME(),CONCAT('DEVOLUCION A PROVEEDOR ',d.DOC),@ALMACEN,0,@SUC
    FROM dbo.DEV_CTRL_PROVD d WHERE d.DOC=@DOC AND d.ACTIVO=1 AND d.CTDA_BLOQ>0
      AND NOT EXISTS(SELECT 1 FROM dbo.DAT_MB51 m WHERE m.IDPD=CONCAT('DEV-',d.DOC,'-',d.IDPD));

    DECLARE @SALIDA TABLE(ART NVARCHAR(20) PRIMARY KEY,CTD DECIMAL(18,4));
    INSERT @SALIDA(ART,CTD) SELECT ART,SUM(CTDA_BLOQ) FROM dbo.DEV_CTRL_PROVD WHERE DOC=@DOC AND ACTIVO=1 GROUP BY ART;
    UPDATE dbo.DEV_CTRL_PROVD SET CTDA_BLOQ=0,FCNM=SYSDATETIME() WHERE DOC=@DOC AND ACTIVO=1;
    UPDATE a SET STOCK=ISNULL(a.STOCK,0)-q.CTD FROM dbo.DAT_ART a JOIN @SALIDA q ON q.ART=a.ART WHERE a.SUC=@SUC;
    UPDATE dbo.DEV_DOC_PROVD SET ESTATUS='AUTORIZADA',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME(),DOC_MB51=@DOC,FCNM=SYSDATETIME() WHERE DOC=@DOC;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'AUTORIZAR_CONTABILIZAR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,'{"movimiento":102}',SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @DOC DOC,'AUTORIZADA' ESTATUS;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_rechazar
  @DOC NVARCHAR(40), @USR NVARCHAR(100), @MOTIVO NVARCHAR(1000)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRANSACTION;
  DECLARE @SUC NVARCHAR(20),@ESTATUS NVARCHAR(30);
  SELECT @SUC=SUC,@ESTATUS=ESTATUS FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
  IF @ESTATUS IS NULL BEGIN ROLLBACK; THROW 59240,'La devolucion no existe.',1; END;
  IF @ESTATUS='RECHAZADA' BEGIN COMMIT; SELECT @DOC DOC,'RECHAZADA' ESTATUS; RETURN; END;
  IF @ESTATUS<>'PENDIENTE' BEGIN ROLLBACK; THROW 59241,'Solo se rechaza una devolucion PENDIENTE.',1; END;
  IF NULLIF(LTRIM(RTRIM(ISNULL(@MOTIVO,''))),'') IS NULL BEGIN ROLLBACK; THROW 59242,'El motivo de rechazo es requerido.',1; END;
  UPDATE dbo.DEV_CTRL_PROVD SET CTDA_BLOQ=0,FCNM=SYSDATETIME() WHERE DOC=@DOC AND ACTIVO=1;
  UPDATE dbo.DEV_DOC_PROVD SET ESTATUS='RECHAZADA',USR_RECHAZA=@USR,FCN_RECHAZA=SYSDATETIME(),MOTIVO_RECHAZO=@MOTIVO,FCNM=SYSDATETIME() WHERE DOC=@DOC;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'RECHAZAR_LIBERAR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,CONCAT('{"motivo":"',STRING_ESCAPE(@MOTIVO,'json'),'"}'),SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT;
  SELECT @DOC DOC,'RECHAZADA' ESTATUS;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_cancelar
  @DOC NVARCHAR(40), @USR NVARCHAR(100), @MOTIVO NVARCHAR(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRANSACTION;
  DECLARE @SUC NVARCHAR(20),@ESTATUS NVARCHAR(30);
  SELECT @SUC=SUC,@ESTATUS=ESTATUS FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
  IF @ESTATUS IS NULL BEGIN ROLLBACK; THROW 59250,'La devolucion no existe.',1; END;
  IF @ESTATUS='CANCELADA' BEGIN COMMIT; SELECT @DOC DOC,'CANCELADA' ESTATUS; RETURN; END;
  IF @ESTATUS NOT IN('BORRADOR','PENDIENTE') BEGIN ROLLBACK; THROW 59251,'La devolucion ya no se puede cancelar.',1; END;
  UPDATE dbo.DEV_CTRL_PROVD SET CTDA_BLOQ=0,FCNM=SYSDATETIME() WHERE DOC=@DOC AND ACTIVO=1;
  UPDATE dbo.DEV_DOC_PROVD SET ESTATUS='CANCELADA',OBS=COALESCE(NULLIF(LTRIM(RTRIM(@MOTIVO)),''),OBS),FCNM=SYSDATETIME() WHERE DOC=@DOC;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'CANCELAR_LIBERAR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT;
  SELECT @DOC DOC,'CANCELADA' ESTATUS;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_consolidar_envio
  @DOCUMENTOS NVARCHAR(MAX), @TRANSPORTISTA NVARCHAR(120), @GUIA NVARCHAR(120),
  @CAJAS INT, @RMA NVARCHAR(120)=NULL, @OBS NVARCHAR(1000)=NULL, @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    IF ISJSON(@DOCUMENTOS)<>1 THROW 59260,'La lista de documentos no es valida.',1;
    DECLARE @DOCS TABLE(DOC NVARCHAR(40) PRIMARY KEY);
    INSERT @DOCS(DOC) SELECT DISTINCT LTRIM(RTRIM(CONVERT(NVARCHAR(40),[value]))) FROM OPENJSON(@DOCUMENTOS) WHERE NULLIF(LTRIM(RTRIM(CONVERT(NVARCHAR(40),[value]))),'') IS NOT NULL;
    IF NOT EXISTS(SELECT 1 FROM @DOCS) THROW 59261,'Debe seleccionar al menos una devolucion.',1;
    IF @CAJAS<=0 THROW 59262,'El numero de cajas debe ser mayor a cero.',1;
    IF NULLIF(LTRIM(RTRIM(ISNULL(@TRANSPORTISTA,''))),'') IS NULL OR NULLIF(LTRIM(RTRIM(ISNULL(@GUIA,''))),'') IS NULL THROW 59263,'Transportista y guia son requeridos.',1;
    IF EXISTS(SELECT 1 FROM @DOCS x LEFT JOIN dbo.DEV_DOC_PROVD h WITH(UPDLOCK,HOLDLOCK) ON h.DOC=x.DOC WHERE h.DOC IS NULL OR h.ESTATUS<>'AUTORIZADA') THROW 59264,'Todas las devoluciones deben estar AUTORIZADAS.',1;
    IF (SELECT COUNT(DISTINCT h.PROVD) FROM @DOCS x JOIN dbo.DEV_DOC_PROVD h ON h.DOC=x.DOC)<>1 THROW 59265,'Solo se consolidan devoluciones del mismo proveedor.',1;
    IF EXISTS(SELECT 1 FROM @DOCS x JOIN dbo.DEV_ENVIO_DOC ed ON ed.DOC=x.DOC) THROW 59266,'Una devolucion ya pertenece a otro envio.',1;
    DECLARE @PROVD INT=(SELECT TOP(1) h.PROVD FROM @DOCS x JOIN dbo.DEV_DOC_PROVD h ON h.DOC=x.DOC);
    INSERT dbo.DEV_ENVIO_PROVD(ENVIO,PROVD,TRANSPORTISTA,GUIA,CAJAS,RMA,OBS,USR_CREA)
    VALUES(NULL,@PROVD,@TRANSPORTISTA,@GUIA,@CAJAS,NULLIF(LTRIM(RTRIM(@RMA)),''),NULLIF(LTRIM(RTRIM(@OBS)),''),@USR);
    DECLARE @ID BIGINT=SCOPE_IDENTITY(),@ENVIO NVARCHAR(40);
    SET @ENVIO=CONCAT('ENV-DEV-',RIGHT(CONCAT('00000000',CONVERT(VARCHAR(20),@ID)),8));
    UPDATE dbo.DEV_ENVIO_PROVD SET ENVIO=@ENVIO WHERE ID=@ID;
    INSERT dbo.DEV_ENVIO_DOC(IDENVIO,DOC) SELECT @ID,DOC FROM @DOCS;
    UPDATE h SET ESTATUS='CONSOLIDADA',FCNM=SYSDATETIME() FROM dbo.DEV_DOC_PROVD h JOIN @DOCS x ON x.DOC=h.DOC;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT u.IDUSUARIO,'CONSOLIDAR_ENVIO','DEV_PROVD','DEV_ENVIO_PROVD',@ENVIO,NULL,CONCAT('{"documentos":',@DOCUMENTOS,'}'),SYSDATETIME() FROM dbo.USUARIO u WHERE UPPER(u.USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @ENVIO ENVIO;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_salida_fisica
  @ENVIO NVARCHAR(40), @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRANSACTION;
  DECLARE @ID BIGINT,@ESTATUS NVARCHAR(30);
  SELECT @ID=ID,@ESTATUS=ESTATUS FROM dbo.DEV_ENVIO_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE ENVIO=@ENVIO;
  IF @ID IS NULL BEGIN ROLLBACK; THROW 59270,'El envio no existe.',1; END;
  IF @ESTATUS='EN_TRANSITO' BEGIN COMMIT; SELECT @ENVIO ENVIO,'EN_TRANSITO' ESTATUS; RETURN; END;
  IF @ESTATUS<>'CONSOLIDADO' BEGIN ROLLBACK; THROW 59271,'El envio no se puede registrar como salida.',1; END;
  UPDATE dbo.DEV_ENVIO_PROVD SET ESTATUS='EN_TRANSITO',USR_SALIDA=@USR,FCN_SALIDA=SYSDATETIME() WHERE ID=@ID;
  UPDATE h SET ESTATUS='EN_TRANSITO',FCNM=SYSDATETIME() FROM dbo.DEV_DOC_PROVD h JOIN dbo.DEV_ENVIO_DOC ed ON ed.DOC=h.DOC WHERE ed.IDENVIO=@ID;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'SALIDA_FISICA','DEV_PROVD','DEV_ENVIO_PROVD',@ENVIO,NULL,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT;
  SELECT @ENVIO ENVIO,'EN_TRANSITO' ESTATUS;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_enviar_transito
  @DOC NVARCHAR(40), @TRANSPORTISTA NVARCHAR(120), @GUIA NVARCHAR(120),
  @CAJAS INT, @RMA NVARCHAR(120)=NULL, @OBS NVARCHAR(1000)=NULL, @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @ESTATUS NVARCHAR(30),@PROVD INT,@SUC NVARCHAR(20),@ID BIGINT,@ENVIO NVARCHAR(40),@ESTATUS_ENVIO NVARCHAR(30);
    SELECT @ESTATUS=ESTATUS,@PROVD=PROVD,@SUC=SUC FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59272,'La devolucion no existe.',1;
    IF @ESTATUS='EN_TRANSITO'
    BEGIN
      SELECT TOP(1) @ENVIO=e.ENVIO FROM dbo.DEV_ENVIO_DOC ed JOIN dbo.DEV_ENVIO_PROVD e ON e.ID=ed.IDENVIO WHERE ed.DOC=@DOC;
      COMMIT; SELECT @ENVIO ENVIO,'EN_TRANSITO' ESTATUS; RETURN;
    END;
    IF @ESTATUS NOT IN('AUTORIZADA','CONSOLIDADA') THROW 59273,'Solo una devolucion autorizada puede enviarse a transito.',1;
    IF @CAJAS<=0 THROW 59274,'El numero de cajas debe ser mayor a cero.',1;
    IF NULLIF(LTRIM(RTRIM(ISNULL(@TRANSPORTISTA,''))),'') IS NULL OR NULLIF(LTRIM(RTRIM(ISNULL(@GUIA,''))),'') IS NULL THROW 59275,'Transportista y guia son requeridos.',1;

    SELECT TOP(1) @ID=e.ID,@ENVIO=e.ENVIO,@ESTATUS_ENVIO=e.ESTATUS
    FROM dbo.DEV_ENVIO_DOC ed JOIN dbo.DEV_ENVIO_PROVD e WITH(UPDLOCK,HOLDLOCK) ON e.ID=ed.IDENVIO WHERE ed.DOC=@DOC;
    IF @ID IS NULL
    BEGIN
      INSERT dbo.DEV_ENVIO_PROVD(ENVIO,PROVD,TRANSPORTISTA,GUIA,CAJAS,RMA,OBS,USR_CREA)
      VALUES(NULL,@PROVD,@TRANSPORTISTA,@GUIA,@CAJAS,NULLIF(LTRIM(RTRIM(@RMA)),''),NULLIF(LTRIM(RTRIM(@OBS)),''),@USR);
      SET @ID=SCOPE_IDENTITY();
      SET @ENVIO=CONCAT('ENV-DEV-',RIGHT(CONCAT('00000000',CONVERT(VARCHAR(20),@ID)),8));
      UPDATE dbo.DEV_ENVIO_PROVD SET ENVIO=@ENVIO WHERE ID=@ID;
      INSERT dbo.DEV_ENVIO_DOC(IDENVIO,DOC) VALUES(@ID,@DOC);
    END
    ELSE IF @ESTATUS_ENVIO<>'CONSOLIDADO' THROW 59276,'El envio relacionado no permite registrar la salida.',1;

    UPDATE dbo.DEV_ENVIO_PROVD SET ESTATUS='EN_TRANSITO',USR_SALIDA=@USR,FCN_SALIDA=SYSDATETIME() WHERE ID=@ID;
    UPDATE h SET ESTATUS='EN_TRANSITO',FCNM=SYSDATETIME() FROM dbo.DEV_DOC_PROVD h JOIN dbo.DEV_ENVIO_DOC ed ON ed.DOC=h.DOC WHERE ed.IDENVIO=@ID;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'SALIDA_FISICA','DEV_PROVD','DEV_ENVIO_PROVD',@ENVIO,@SUC,CONCAT('{"documento":"',STRING_ESCAPE(@DOC,'json'),'"}'),SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @ENVIO ENVIO,'EN_TRANSITO' ESTATUS;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_recibir
  @DOC NVARCHAR(40), @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @ESTATUS NVARCHAR(30),@SUC NVARCHAR(20),@IDENVIO BIGINT;
    SELECT @ESTATUS=ESTATUS,@SUC=SUC FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59277,'La devolucion no existe.',1;
    IF @ESTATUS='RECIBIDA' BEGIN COMMIT; SELECT @DOC DOC,'RECIBIDA' ESTATUS; RETURN; END;
    IF @ESTATUS<>'EN_TRANSITO' THROW 59278,'Solo una devolucion en transito puede marcarse como recibida.',1;
    UPDATE dbo.DEV_DOC_PROVD SET ESTATUS='RECIBIDA',FCNM=SYSDATETIME() WHERE DOC=@DOC;
    SELECT @IDENVIO=IDENVIO FROM dbo.DEV_ENVIO_DOC WHERE DOC=@DOC;
    IF @IDENVIO IS NOT NULL AND NOT EXISTS(
      SELECT 1 FROM dbo.DEV_ENVIO_DOC ed JOIN dbo.DEV_DOC_PROVD h ON h.DOC=ed.DOC
      WHERE ed.IDENVIO=@IDENVIO AND h.ESTATUS<>'RECIBIDA'
    ) UPDATE dbo.DEV_ENVIO_PROVD SET ESTATUS='RECIBIDA' WHERE ID=@IDENVIO;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'RECIBIR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @DOC DOC,'RECIBIDA' ESTATUS;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

IF OBJECT_ID('dbo.SEQ_DEV_PROVD', 'SO') IS NOT NULL
  DROP SEQUENCE dbo.SEQ_DEV_PROVD;
GO
