/*
  2026-04-23
  - Desactiva módulos legacy de ORDs anuladas/entregadas.
  - Crea el nuevo módulo de consulta de estado de ORD.
  - Lo asocia preferentemente a grupos Admin / Jefe Taller / Analista.
*/

SET NOCOUNT ON;

IF OBJECT_ID('dbo.MOD_FRONT', 'U') IS NULL
  OR OBJECT_ID('dbo.GRUPMOD_FRONT', 'U') IS NULL
  OR OBJECT_ID('dbo.GRUPMOD_FRONT_MOD', 'U') IS NULL
BEGIN
  PRINT 'WARN: Tablas MOD_FRONT/GRUPMOD_FRONT/GRUPMOD_FRONT_MOD no disponibles.';
  RETURN;
END;
GO

DECLARE @BaseId INT = (
  SELECT TOP 1 IDMOD_FRONT
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD'
);

IF @BaseId IS NULL
BEGIN
  PRINT 'WARN: No existe modulo base DAT_JAO_ORD. No se aplican inserciones.';
  RETURN;
END;

DECLARE @Depto NVARCHAR(100) = (
  SELECT TOP 1 DEPTO
  FROM dbo.MOD_FRONT
  WHERE IDMOD_FRONT = @BaseId
);

UPDATE dbo.MOD_FRONT
SET ACTIVO = 0
WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) IN (
  'DAT_JAO_ORD_ANULADAS',
  'DAT_JAO_ORD_ENTREGADAS'
);

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_ESTADO'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_ESTADO', 'Consulta estado de ORD', 1, GETDATE(), @Depto);
END;
ELSE
BEGIN
  UPDATE dbo.MOD_FRONT
  SET NOMBRE = 'Consulta estado de ORD',
      ACTIVO = 1,
      DEPTO = COALESCE(@Depto, DEPTO)
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_ESTADO';
END;

DECLARE @EstadoId INT = (
  SELECT TOP 1 IDMOD_FRONT
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_ESTADO'
);

DECLARE @TargetGroups TABLE (IDGRUPMOD_FRONT INT PRIMARY KEY);

INSERT INTO @TargetGroups (IDGRUPMOD_FRONT)
SELECT DISTINCT g.IDGRUPMOD_FRONT
FROM dbo.GRUPMOD_FRONT g
WHERE
  UPPER(LTRIM(RTRIM(ISNULL(g.NOMBRE, '')))) LIKE '%ADMIN%'
  OR (
    UPPER(LTRIM(RTRIM(ISNULL(g.NOMBRE, '')))) LIKE '%JEF%'
    AND UPPER(LTRIM(RTRIM(ISNULL(g.NOMBRE, '')))) LIKE '%TALLER%'
  )
  OR (
    UPPER(LTRIM(RTRIM(ISNULL(g.NOMBRE, '')))) LIKE '%ANALISTA%'
    AND UPPER(LTRIM(RTRIM(ISNULL(g.NOMBRE, '')))) NOT LIKE '%INV%'
  );

IF NOT EXISTS (SELECT 1 FROM @TargetGroups)
BEGIN
  INSERT INTO @TargetGroups (IDGRUPMOD_FRONT)
  SELECT DISTINCT gm.IDGRUPMOD_FRONT
  FROM dbo.GRUPMOD_FRONT_MOD gm
  WHERE gm.IDMOD_FRONT = @BaseId;
END;

IF @EstadoId IS NOT NULL
BEGIN
  INSERT INTO dbo.GRUPMOD_FRONT_MOD (IDGRUPMOD_FRONT, IDMOD_FRONT)
  SELECT tg.IDGRUPMOD_FRONT, @EstadoId
  FROM @TargetGroups tg
  WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.GRUPMOD_FRONT_MOD x
    WHERE x.IDGRUPMOD_FRONT = tg.IDGRUPMOD_FRONT
      AND x.IDMOD_FRONT = @EstadoId
  );
END;

PRINT 'OK: Modulo DAT_JAO_ORD_ESTADO verificado y módulos legacy de anuladas/entregadas desactivados.';
GO
