SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_actualizar_cantidad
  @DOCREC nvarchar(510),@IDREC nvarchar(510),@CANTIDAD float,@USR nvarchar(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC);
  EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  IF @CANTIDAD IS NULL OR @CANTIDAD<0 THROW 51000,'La cantidad fisica no es valida.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510);
  SELECT @ESTATUS=r.ESTATUS_REC,@NPED=r.NPED,@SUC=c.SUC FROM dbo.REC_CTRL_DOC_REC r WITH(UPDLOCK,HOLDLOCK) JOIN dbo.REC_CAB_PED c ON c.NPED=r.NPED WHERE r.DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS<>'VALIDADO' THROW 51000,'Solo se puede editar una recepcion validada.',1;
  DECLARE @IDPED nvarchar(510),@ART nvarchar(510),@ANTERIOR float,@PENDIENTE float,@CTO money;
  SELECT @IDPED=h.IDPED,@ART=h.ART,@ANTERIOR=h.CTD,@PENDIENTE=CASE WHEN h.IDPED IS NULL THEN 0 WHEN ISNULL(d.CTDPED,0)>ISNULL(d.CTDREC,0) THEN ISNULL(d.CTDPED,0)-ISNULL(d.CTDREC,0) ELSE 0 END,@CTO=COALESCE(d.CTO,a.CTOP,0)
  FROM dbo.REC_CTO_HIST h WITH(UPDLOCK,HOLDLOCK) LEFT JOIN dbo.REC_DET_PED d ON d.IDPED=h.IDPED LEFT JOIN dbo.DAT_ART a ON a.SUC=@SUC AND a.ART=h.ART WHERE h.DOCREC=@DOCREC AND h.IDREC=@IDREC;
  IF @ART IS NULL THROW 51000,'El articulo no pertenece a la recepcion.',1;
  UPDATE dbo.REC_CTO_HIST SET CTD=@CANTIDAD,CTD_ACEP=@CANTIDAD,CTDVTA=ISNULL(@CTO,0)*@CANTIDAD,CALIDAD_ESTATUS='APROBADO' WHERE DOCREC=@DOCREC AND IDREC=@IDREC;
  DELETE dbo.REC_INCI_PED WHERE DOCREC=@DOCREC AND IDREC=@IDREC AND TIPO IN ('FALTANTE','SOBRANTE','NO_SOLICITADO');
  IF @IDPED IS NULL OR @CANTIDAD<>@PENDIENTE
    INSERT dbo.REC_INCI_PED(DOCREC,IDREC,TIPO,ART,CTD_ESPERADA,CTD_RECIBIDA,DIFERENCIA,MOTIVO,ESTATUS,USR)
    VALUES(@DOCREC,@IDREC,CASE WHEN @IDPED IS NULL THEN 'NO_SOLICITADO' WHEN @CANTIDAD>@PENDIENTE THEN 'SOBRANTE' ELSE 'FALTANTE' END,@ART,@PENDIENTE,@CANTIDAD,@CANTIDAD-@PENDIENTE,'Ajuste por Jefe de Inventarios','ABIERTA',@USR);
  UPDATE r SET NART=(SELECT COUNT(*) FROM dbo.REC_CTO_HIST h WHERE h.DOCREC=@DOCREC AND ISNULL(h.CTD,0)>0),IMPT=(SELECT SUM(ISNULL(h.CTDVTA,0)) FROM dbo.REC_CTO_HIST h WHERE h.DOCREC=@DOCREC) FROM dbo.REC_CTRL_DOC_REC r WHERE r.DOCREC=@DOCREC;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'AJUSTAR_CANTIDAD_FISICA','DAT_REC','REC_CTO_HIST',@IDREC,@SUC,CONCAT('{"docrec":"',STRING_ESCAPE(@DOCREC,'json'),'","anterior":',COALESCE(CONVERT(varchar(50),@ANTERIOR),'null'),',"nueva":',CONVERT(varchar(50),@CANTIDAD),'}'),SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,@IDREC IDREC,@CANTIDAD CANTIDAD_FISICA;
END;
GO
