/*
  DAT_REC - Recepcion de mercancias.
  Cambio aditivo y compatible con Access:
  - reutiliza REC_CTRL_DOC_REC / REC_CTO_HIST;
  - contabiliza con DAT_CTR_DOC / DAT_MB51 y DAT_CMOV 101;
  - no modifica ni elimina historicos;
  - separa recepcion fisica de autorizacion/contabilizacion.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'ESTATUS_REC') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD ESTATUS_REC nvarchar(30) NOT NULL
    CONSTRAINT DF_REC_CTRL_DOC_REC_ESTATUS DEFAULT ('CONTABILIZADO');
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'TIPO_RECEPCION') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD TIPO_RECEPCION nvarchar(20) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'FCN_FISICA') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD FCN_FISICA datetime2(0) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'USR_RECEPCION') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD USR_RECEPCION nvarchar(100) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'FCN_AUTORIZA') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD FCN_AUTORIZA datetime2(0) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'USR_AUTORIZA') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD USR_AUTORIZA nvarchar(100) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'TIPO_DOC') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD TIPO_DOC nvarchar(20) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'FOLIO_DOC') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD FOLIO_DOC nvarchar(100) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'OBSERVACIONES') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD OBSERVACIONES nvarchar(1000) NULL;
IF COL_LENGTH('dbo.REC_CTRL_DOC_REC', 'ALMACEN') IS NULL
  ALTER TABLE dbo.REC_CTRL_DOC_REC ADD ALMACEN varchar(10) NULL;
GO

IF COL_LENGTH('dbo.REC_CTO_HIST', 'DOCREC') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD DOCREC nvarchar(255) NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'IDPED') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD IDPED nvarchar(255) NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'CTD_SOL') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD CTD_SOL float NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'CTD_ACEP') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD CTD_ACEP float NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'CALIDAD_ESTATUS') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD CALIDAD_ESTATUS nvarchar(20) NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'CALIDAD_JSON') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD CALIDAD_JSON nvarchar(max) NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'CADUCIDAD') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD CADUCIDAD date NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'OBSERVACIONES') IS NULL
  ALTER TABLE dbo.REC_CTO_HIST ADD OBSERVACIONES nvarchar(1000) NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'DOCREC') = 1020
  ALTER TABLE dbo.REC_CTO_HIST ALTER COLUMN DOCREC nvarchar(255) NULL;
IF COL_LENGTH('dbo.REC_CTO_HIST', 'IDPED') = 1020
  ALTER TABLE dbo.REC_CTO_HIST ALTER COLUMN IDPED nvarchar(255) NULL;
GO

IF OBJECT_ID('dbo.REC_GUIA_PED', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.REC_GUIA_PED (
    IDGUIA bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_REC_GUIA_PED PRIMARY KEY,
    DOCREC nvarchar(255) NOT NULL,
    GUIA nvarchar(100) NOT NULL,
    PAQUETERIA nvarchar(120) NULL,
    NPAQ int NULL,
    OBSERVACIONES nvarchar(500) NULL,
    FCNR datetime2(0) NOT NULL CONSTRAINT DF_REC_GUIA_PED_FCNR DEFAULT (SYSDATETIME()),
    USR nvarchar(100) NOT NULL,
    CONSTRAINT FK_REC_GUIA_PED_DOCREC FOREIGN KEY (DOCREC) REFERENCES dbo.REC_CTRL_DOC_REC(DOCREC),
    CONSTRAINT UQ_REC_GUIA_PED_DOCREC_GUIA UNIQUE (DOCREC, GUIA),
    CONSTRAINT CK_REC_GUIA_PED_NPAQ CHECK (NPAQ IS NULL OR NPAQ > 0)
  );
END;
GO

IF OBJECT_ID('dbo.REC_INCI_PED', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.REC_INCI_PED (
    IDINC bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_REC_INCI_PED PRIMARY KEY,
    DOCREC nvarchar(255) NOT NULL,
    IDREC nvarchar(255) NULL,
    TIPO nvarchar(30) NOT NULL,
    ART nvarchar(255) NULL,
    CTD_ESPERADA float NULL,
    CTD_RECIBIDA float NULL,
    DIFERENCIA float NULL,
    MOTIVO nvarchar(1000) NULL,
    ESTATUS nvarchar(30) NOT NULL CONSTRAINT DF_REC_INCI_PED_ESTATUS DEFAULT ('ABIERTA'),
    USR nvarchar(100) NOT NULL,
    FCNR datetime2(0) NOT NULL CONSTRAINT DF_REC_INCI_PED_FCNR DEFAULT (SYSDATETIME()),
    USR_AUTORIZA nvarchar(100) NULL,
    FCN_AUTORIZA datetime2(0) NULL,
    CONSTRAINT FK_REC_INCI_PED_DOCREC FOREIGN KEY (DOCREC) REFERENCES dbo.REC_CTRL_DOC_REC(DOCREC),
    CONSTRAINT CK_REC_INCI_PED_TIPO CHECK (TIPO IN ('FALTANTE','SOBRANTE','NO_SOLICITADO','COSTO','DANO','CALIDAD','OTRO')),
    CONSTRAINT CK_REC_INCI_PED_ESTATUS CHECK (ESTATUS IN ('ABIERTA','AUTORIZADA','RECHAZADA','CERRADA'))
  );
END;
GO

IF OBJECT_ID('dbo.REC_CALIDAD_CRITERIO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.REC_CALIDAD_CRITERIO (
    IDCRITERIO int IDENTITY(1,1) NOT NULL CONSTRAINT PK_REC_CALIDAD_CRITERIO PRIMARY KEY,
    NOMBRE nvarchar(120) NOT NULL,
    DESCRIPCION nvarchar(500) NULL,
    TIPO nvarchar(255) NULL,
    DEPA float NULL,
    SUBD float NULL,
    CLAS float NULL,
    SCLA float NULL,
    SCLA2 float NULL,
    REQUERIDO bit NOT NULL CONSTRAINT DF_REC_CALIDAD_REQUERIDO DEFAULT (1),
    ACTIVO bit NOT NULL CONSTRAINT DF_REC_CALIDAD_ACTIVO DEFAULT (1),
    ORDEN int NOT NULL CONSTRAINT DF_REC_CALIDAD_ORDEN DEFAULT (0),
    FCNR datetime2(0) NOT NULL CONSTRAINT DF_REC_CALIDAD_FCNR DEFAULT (SYSDATETIME())
  );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.REC_CTRL_DOC_REC') AND name='IX_REC_CTRL_DOC_REC_NPED_ESTATUS')
  CREATE INDEX IX_REC_CTRL_DOC_REC_NPED_ESTATUS ON dbo.REC_CTRL_DOC_REC(NPED,ESTATUS_REC,FCN_FISICA DESC) INCLUDE(DOCREC,USR_RECEPCION);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.REC_CTO_HIST') AND name='IX_REC_CTO_HIST_DOCREC')
  CREATE INDEX IX_REC_CTO_HIST_DOCREC ON dbo.REC_CTO_HIST(DOCREC,POS) INCLUDE(IDPED,ART,CTD,CTD_ACEP) WHERE DOCREC IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.REC_INCI_PED') AND name='IX_REC_INCI_PED_DOCREC_ESTATUS')
  CREATE INDEX IX_REC_INCI_PED_DOCREC_ESTATUS ON dbo.REC_INCI_PED(DOCREC,ESTATUS) INCLUDE(TIPO,ART,DIFERENCIA);
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_fisica
  @NPED nvarchar(510),
  @USR nvarchar(100),
  @TIPO_RECEPCION nvarchar(20),
  @TIPO_DOC nvarchar(20)=NULL,
  @FOLIO_DOC nvarchar(100)=NULL,
  @ALMACEN varchar(10)='002',
  @OBSERVACIONES nvarchar(1000)=NULL,
  @ITEMS_JSON nvarchar(max),
  @GUIAS_JSON nvarchar(max)=N'[]',
  @INCIDENCIAS_JSON nvarchar(max)=N'[]'
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;
  SET @TIPO_RECEPCION=UPPER(LTRIM(RTRIM(@TIPO_RECEPCION)));
  SET @TIPO_DOC=NULLIF(UPPER(LTRIM(RTRIM(ISNULL(@TIPO_DOC,'')))),'');
  SET @ALMACEN=COALESCE(NULLIF(LTRIM(RTRIM(@ALMACEN)),''),'002');
  IF @TIPO_RECEPCION NOT IN ('TOTAL','PARCIAL','DIFERENCIAS','RECHAZO') THROW 51000,'Tipo de recepcion invalido.',1;
  IF @TIPO_DOC IS NOT NULL AND @TIPO_DOC NOT IN ('FACTURA','NOTA','PENDIENTE','CONSIGNACION') THROW 51000,'Tipo documental invalido.',1;
  IF @TIPO_DOC IN ('FACTURA','NOTA') AND NULLIF(LTRIM(RTRIM(ISNULL(@FOLIO_DOC,''))),'') IS NULL THROW 51000,'El folio es obligatorio para factura o nota.',1;
  IF ISJSON(@ITEMS_JSON)<>1 THROW 51000,'El detalle de recepcion no es JSON valido.',1;

  DECLARE @items table(
    RN int IDENTITY(1,1),IDPED nvarchar(510),ART nvarchar(510),CTD_REC float,CTD_ACEP float,
    CALIDAD_ESTATUS nvarchar(20),CADUCIDAD date,OBSERVACIONES nvarchar(1000),CALIDAD_JSON nvarchar(max),
    POS int,CTD_SOL float,CTO money,PENDIENTE float
  );
  INSERT @items(IDPED,ART,CTD_REC,CTD_ACEP,CALIDAD_ESTATUS,CADUCIDAD,OBSERVACIONES,CALIDAD_JSON)
  SELECT NULLIF(LTRIM(RTRIM(IDPED)),''),LTRIM(RTRIM(ART)),CTD_REC,COALESCE(CTD_ACEP,CTD_REC),
         UPPER(NULLIF(LTRIM(RTRIM(CALIDAD_ESTATUS)),'')),CADUCIDAD,OBSERVACIONES,CALIDAD_JSON
  FROM OPENJSON(@ITEMS_JSON) WITH(
    IDPED nvarchar(510) '$.idped',ART nvarchar(510) '$.art',CTD_REC float '$.cantidadRecibida',
    CTD_ACEP float '$.cantidadAceptada',CALIDAD_ESTATUS nvarchar(20) '$.calidadEstado',
    CADUCIDAD date '$.caducidad',OBSERVACIONES nvarchar(1000) '$.observaciones',
    CALIDAD_JSON nvarchar(max) '$.calidad' AS JSON
  );
  IF NOT EXISTS(SELECT 1 FROM @items) THROW 51000,'Capture al menos un articulo.',1;
  IF EXISTS(SELECT 1 FROM @items WHERE ART='' OR CTD_REC<=0 OR CTD_ACEP<0 OR CTD_ACEP>CTD_REC) THROW 51000,'Cantidades o articulos invalidos en la recepcion.',1;
  IF EXISTS(SELECT IDPED FROM @items WHERE IDPED IS NOT NULL GROUP BY IDPED HAVING COUNT(*)>1) THROW 51000,'La recepcion contiene posiciones duplicadas.',1;

  BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_NPED_',@NPED);
  EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la orden para recepcion.',1;
  DECLARE @SUC nvarchar(510),@ESTATUS nvarchar(510);
  SELECT @SUC=SUC,@ESTATUS=UPPER(LTRIM(RTRIM(ISNULL(ESTATUS,'')))) FROM dbo.REC_CAB_PED WITH(UPDLOCK,HOLDLOCK) WHERE NPED=@NPED;
  IF @SUC IS NULL THROW 51000,'La orden de compra no existe.',1;
  IF @ESTATUS NOT IN ('PROCESADO','PARCIAL') THROW 51000,'La orden no esta disponible para recepcion.',1;
  IF EXISTS(SELECT 1 FROM dbo.REC_CTRL_DOC_REC WITH(UPDLOCK,HOLDLOCK) WHERE NPED=@NPED AND ESTATUS_REC IN ('RECEPCION_FISICA','VALIDADO','PENDIENTE_AUTORIZACION'))
    THROW 51000,'La orden ya tiene una recepcion activa.',1;

  UPDATE i SET POS=d.POS,CTD_SOL=d.CTDPED,CTO=d.CTO,PENDIENTE=CASE WHEN ISNULL(d.CTDPED,0)>ISNULL(d.CTDREC,0) THEN d.CTDPED-ISNULL(d.CTDREC,0) ELSE 0 END
  FROM @items i JOIN dbo.REC_DET_PED d ON d.NPED=@NPED AND d.IDPED=i.IDPED AND ISNULL(d.BLOQ,0)<>-1;
  IF EXISTS(SELECT 1 FROM @items WHERE IDPED IS NOT NULL AND POS IS NULL) THROW 51000,'Una posicion no pertenece a la orden.',1;
  IF EXISTS(SELECT 1 FROM @items WHERE IDPED IS NOT NULL AND PENDIENTE<=0) THROW 51000,'Una posicion ya no tiene cantidad pendiente.',1;
  IF EXISTS(SELECT 1 FROM @items i WHERE i.IDPED IS NOT NULL AND NOT EXISTS(SELECT 1 FROM dbo.REC_DET_PED d WHERE d.IDPED=i.IDPED AND d.ART=i.ART)) THROW 51000,'Articulo y posicion no coinciden.',1;
  IF EXISTS(SELECT 1 FROM @items i WHERE i.IDPED IS NULL AND NOT EXISTS(SELECT 1 FROM dbo.DAT_ART a WHERE a.SUC=@SUC AND a.ART=i.ART)) THROW 51000,'Un articulo no solicitado no existe en la sucursal.',1;
  IF @TIPO_RECEPCION='RECHAZO' AND EXISTS(SELECT 1 FROM @items WHERE CTD_ACEP<>0) THROW 51000,'Una recepcion rechazada no puede aceptar cantidades.',1;
  IF @TIPO_RECEPCION='TOTAL' AND EXISTS(
    SELECT 1 FROM dbo.REC_DET_PED d WHERE d.NPED=@NPED AND ISNULL(d.BLOQ,0)<>-1 AND ISNULL(d.CTDREC,0)<ISNULL(d.CTDPED,0)
      AND ISNULL((SELECT SUM(i.CTD_ACEP) FROM @items i WHERE i.IDPED=d.IDPED),0)<>(ISNULL(d.CTDPED,0)-ISNULL(d.CTDREC,0))
  ) THROW 51000,'Recepcion total requiere cubrir exactamente todo lo pendiente.',1;

  UPDATE i SET CALIDAD_ESTATUS=COALESCE(i.CALIDAD_ESTATUS,CASE WHEN EXISTS(
    SELECT 1 FROM dbo.DAT_ART a JOIN dbo.REC_CALIDAD_CRITERIO c ON c.ACTIVO=1
      AND (c.TIPO IS NULL OR c.TIPO=a.TIPO) AND (c.DEPA IS NULL OR c.DEPA=a.DEPA) AND (c.SUBD IS NULL OR c.SUBD=a.SUBD)
      AND (c.CLAS IS NULL OR c.CLAS=a.CLAS) AND (c.SCLA IS NULL OR c.SCLA=a.SCLA) AND (c.SCLA2 IS NULL OR c.SCLA2=a.SCLA2)
    WHERE a.SUC=@SUC AND a.ART=i.ART) THEN 'PENDIENTE' ELSE 'NO_APLICA' END)
  FROM @items i;
  UPDATE i SET CTO=COALESCE(i.CTO,a.CTOP,0)
  FROM @items i LEFT JOIN dbo.DAT_ART a ON a.SUC=@SUC AND a.ART=i.ART;

  EXEC @lock=sys.sp_getapplock @Resource='REC_CTRL_DOC_REC_DOCREC',@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible generar el documento de recepcion.',1;
  DECLARE @DOCREC nvarchar(510),@NEXT bigint;
  SELECT @NEXT=ISNULL(MAX(NUMERO),71000000)+1
  FROM (
    SELECT TRY_CONVERT(bigint,DOCREC) NUMERO FROM dbo.REC_CTRL_DOC_REC WITH(UPDLOCK,HOLDLOCK)
    UNION ALL SELECT TRY_CONVERT(bigint,DOC) FROM dbo.DAT_CTR_DOC WITH(UPDLOCK,HOLDLOCK)
    UNION ALL SELECT TRY_CONVERT(bigint,DOCP) FROM dbo.DAT_MB51 WITH(UPDLOCK,HOLDLOCK)
  ) documentos
  WHERE NUMERO IS NOT NULL;
  WHILE EXISTS(SELECT 1 FROM dbo.REC_CTRL_DOC_REC WHERE DOCREC=CONVERT(nvarchar(510),@NEXT))
     OR EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WHERE DOC=CONVERT(nvarchar(510),@NEXT))
     OR EXISTS(SELECT 1 FROM dbo.DAT_MB51 WHERE DOCP=CONVERT(nvarchar(510),@NEXT))
    SET @NEXT+=1;
  SET @DOCREC=CONVERT(nvarchar(510),@NEXT);
  DECLARE @MAXPOS int=(SELECT ISNULL(MAX(POS),0) FROM dbo.REC_DET_PED WHERE NPED=@NPED);
  DECLARE @NART int=(SELECT COUNT(*) FROM @items);
  DECLARE @IMPT money=(SELECT SUM(ISNULL(CTO,0)*CTD_ACEP) FROM @items);
  INSERT dbo.REC_CTRL_DOC_REC(DOCREC,NPED,FCNC,NART,IMPT,ESTATUS_REC,TIPO_RECEPCION,FCN_FISICA,USR_RECEPCION,TIPO_DOC,FOLIO_DOC,OBSERVACIONES,ALMACEN)
  VALUES(@DOCREC,@NPED,SYSDATETIME(),@NART,@IMPT,'RECEPCION_FISICA',@TIPO_RECEPCION,SYSDATETIME(),@USR,@TIPO_DOC,NULLIF(LTRIM(RTRIM(ISNULL(@FOLIO_DOC,''))),''),@OBSERVACIONES,@ALMACEN);

  INSERT dbo.REC_CTO_HIST(IDREC,POS,ART,FCN,CTD,CTDVTA,DOCREC,IDPED,CTD_SOL,CTD_ACEP,CALIDAD_ESTATUS,CALIDAD_JSON,CADUCIDAD,OBSERVACIONES)
  SELECT CONCAT('REC-',@DOCREC,'-',CONVERT(varchar(12),RN)),COALESCE(POS,@MAXPOS+RN),ART,SYSDATETIME(),CTD_REC,
         ISNULL(CTO,0)*CTD_ACEP,
         @DOCREC,IDPED,COALESCE(CTD_SOL,0),CTD_ACEP,CALIDAD_ESTATUS,CALIDAD_JSON,CADUCIDAD,OBSERVACIONES
  FROM @items i;

  IF ISJSON(@GUIAS_JSON)=1
    INSERT dbo.REC_GUIA_PED(DOCREC,GUIA,PAQUETERIA,NPAQ,OBSERVACIONES,USR)
    SELECT @DOCREC,LTRIM(RTRIM(GUIA)),NULLIF(LTRIM(RTRIM(PAQUETERIA)),''),NPAQ,OBSERVACIONES,@USR
    FROM OPENJSON(@GUIAS_JSON) WITH(GUIA nvarchar(100) '$.guia',PAQUETERIA nvarchar(120) '$.paqueteria',NPAQ int '$.cantidadPaquetes',OBSERVACIONES nvarchar(500) '$.observaciones')
    WHERE NULLIF(LTRIM(RTRIM(GUIA)),'') IS NOT NULL;

  INSERT dbo.REC_INCI_PED(DOCREC,IDREC,TIPO,ART,CTD_ESPERADA,CTD_RECIBIDA,DIFERENCIA,MOTIVO,USR)
  SELECT @DOCREC,h.IDREC,
         CASE WHEN i.IDPED IS NULL THEN 'NO_SOLICITADO' WHEN i.CTD_ACEP>i.PENDIENTE THEN 'SOBRANTE' WHEN i.CTD_ACEP<i.PENDIENTE THEN 'FALTANTE' ELSE 'CALIDAD' END,
         i.ART,COALESCE(i.PENDIENTE,0),i.CTD_REC,i.CTD_ACEP-COALESCE(i.PENDIENTE,0),i.OBSERVACIONES,@USR
  FROM @items i JOIN dbo.REC_CTO_HIST h ON h.DOCREC=@DOCREC AND h.ART=i.ART
    AND (h.IDPED=i.IDPED OR (h.IDPED IS NULL AND i.IDPED IS NULL))
  WHERE i.IDPED IS NULL OR i.CTD_ACEP<>i.PENDIENTE OR i.CTD_ACEP<i.CTD_REC OR i.CALIDAD_ESTATUS='RECHAZADO';

  IF ISJSON(@INCIDENCIAS_JSON)=1
    INSERT dbo.REC_INCI_PED(DOCREC,TIPO,ART,CTD_ESPERADA,CTD_RECIBIDA,DIFERENCIA,MOTIVO,USR)
    SELECT @DOCREC,UPPER(TIPO),NULLIF(LTRIM(RTRIM(ART)),''),CTD_ESPERADA,CTD_RECIBIDA,COALESCE(CTD_RECIBIDA,0)-COALESCE(CTD_ESPERADA,0),MOTIVO,@USR
    FROM OPENJSON(@INCIDENCIAS_JSON) WITH(TIPO nvarchar(30) '$.tipo',ART nvarchar(510) '$.art',CTD_ESPERADA float '$.cantidadEsperada',CTD_RECIBIDA float '$.cantidadRecibida',MOTIVO nvarchar(1000) '$.motivo')
    WHERE UPPER(TIPO) IN ('FALTANTE','SOBRANTE','NO_SOLICITADO','COSTO','DANO','CALIDAD','OTRO');

  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT u.IDUSUARIO,'RECEPCION_FISICA','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,
         CONCAT('{"nped":"',STRING_ESCAPE(@NPED,'json'),'","tipo":"',@TIPO_RECEPCION,'"}'),SYSDATETIME()
  FROM dbo.USUARIO u WHERE UPPER(u.USERNAME)=UPPER(@USR);
  COMMIT;
  SELECT @DOCREC DOCREC,@NPED NPED,'RECEPCION_FISICA' ESTATUS_REC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_solicitar
  @DOCREC nvarchar(510),@USR nvarchar(100),@MOTIVO nvarchar(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC); EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510),@TIPO nvarchar(20);
  SELECT @ESTATUS=ESTATUS_REC,@NPED=NPED,@TIPO=TIPO_RECEPCION FROM dbo.REC_CTRL_DOC_REC WITH(UPDLOCK,HOLDLOCK) WHERE DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS='VALIDADO' BEGIN COMMIT; SELECT @DOCREC DOCREC,@ESTATUS ESTATUS_REC; RETURN; END;
  IF @ESTATUS<>'RECEPCION_FISICA' THROW 51000,'La recepcion no se puede enviar en su estado actual.',1;
  IF @TIPO<>'RECHAZO' AND NOT EXISTS(SELECT 1 FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND ISNULL(CTD_ACEP,CTD)>0) THROW 51000,'No hay cantidades aceptadas.',1;
  IF EXISTS(SELECT 1 FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND CALIDAD_ESTATUS='PENDIENTE') THROW 51000,'Existen validaciones de calidad pendientes.',1;
  UPDATE dbo.REC_CTRL_DOC_REC SET ESTATUS_REC='VALIDADO' WHERE DOCREC=@DOCREC;
  SELECT @SUC=h.SUC FROM dbo.REC_CAB_PED h WHERE h.NPED=@NPED;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'VALIDAR_RECEPCION','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,'VALIDADO' ESTATUS_REC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_autorizar
  @DOCREC nvarchar(510),@USR nvarchar(100),@MOTIVO nvarchar(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC); EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510),@ALMACEN varchar(10),@TIPO nvarchar(20);
  SELECT @ESTATUS=r.ESTATUS_REC,@NPED=r.NPED,@ALMACEN=COALESCE(NULLIF(r.ALMACEN,''),'002'),@TIPO=r.TIPO_RECEPCION,@SUC=h.SUC
  FROM dbo.REC_CTRL_DOC_REC r WITH(UPDLOCK,HOLDLOCK) JOIN dbo.REC_CAB_PED h WITH(UPDLOCK,HOLDLOCK) ON h.NPED=r.NPED WHERE r.DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS='CONTABILIZADO' BEGIN COMMIT; SELECT @DOCREC DOCREC,@ESTATUS ESTATUS_REC; RETURN; END;
  IF @ESTATUS NOT IN ('VALIDADO','PENDIENTE_AUTORIZACION') THROW 51000,'La recepcion no esta validada para autorizacion.',1;
  IF @TIPO='RECHAZO' THROW 51000,'Una recepcion rechazada no puede contabilizarse.',1;
  IF EXISTS(SELECT 1 FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND CALIDAD_ESTATUS IN ('PENDIENTE','RECHAZADO') AND ISNULL(CTD_ACEP,CTD)>0) THROW 51000,'La calidad no permite contabilizar la recepcion.',1;

  IF NOT EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOCREC)
    INSERT dbo.DAT_CTR_DOC(DOC,CLSMOV,FCND,[USER],STAT) VALUES(@DOCREC,'101',SYSDATETIME(),@USR,'V');

  INSERT dbo.DAT_MB51(IDPD,[USER],CLSM,DOCP,ART,CTDA,CTOT,FCND,FCNC,TXT,ALMACEN,VTAESP,SUC)
  SELECT x.IDREC,@USR,101,@DOCREC,x.ART,ISNULL(x.CTD_ACEP,x.CTD),
         ISNULL(x.CTD_ACEP,x.CTD)*COALESCE(d.CTO,a.CTOP,0),SYSDATETIME(),SYSDATETIME(),@NPED,@ALMACEN,0,@SUC
  FROM dbo.REC_CTO_HIST x
  LEFT JOIN dbo.REC_DET_PED d ON d.IDPED=x.IDPED
  LEFT JOIN dbo.DAT_ART a ON a.SUC=@SUC AND a.ART=x.ART
  WHERE x.DOCREC=@DOCREC AND ISNULL(x.CTD_ACEP,x.CTD)>0 AND NOT EXISTS(SELECT 1 FROM dbo.DAT_MB51 m WHERE m.IDPD=x.IDREC);

  ;WITH qty AS(SELECT ART,SUM(ISNULL(CTD_ACEP,CTD)) CTD FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND ISNULL(CTD_ACEP,CTD)>0 GROUP BY ART)
  UPDATE a SET STOCK=ISNULL(a.STOCK,0)+q.CTD FROM dbo.DAT_ART a JOIN qty q ON q.ART=a.ART WHERE a.SUC=@SUC;

  ;WITH qty AS(SELECT IDPED,SUM(ISNULL(CTD_ACEP,CTD)) CTD FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND IDPED IS NOT NULL GROUP BY IDPED)
  UPDATE d SET CTDREC=ISNULL(d.CTDREC,0)+q.CTD,RECI=CASE WHEN ISNULL(d.CTDREC,0)+q.CTD>=ISNULL(d.CTDPED,0) THEN -1 ELSE 0 END,DREC=@DOCREC
  FROM dbo.REC_DET_PED d JOIN qty q ON q.IDPED=d.IDPED;

  UPDATE dbo.REC_INCI_PED SET ESTATUS='AUTORIZADA',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME() WHERE DOCREC=@DOCREC AND ESTATUS='ABIERTA';
  UPDATE dbo.REC_CTRL_DOC_REC SET ESTATUS_REC='CONTABILIZADO',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME() WHERE DOCREC=@DOCREC;
  UPDATE dbo.REC_CAB_PED SET ESTATUS=CASE WHEN EXISTS(SELECT 1 FROM dbo.REC_DET_PED d WHERE d.NPED=@NPED AND ISNULL(d.BLOQ,0)<>-1 AND ISNULL(d.CTDREC,0)<ISNULL(d.CTDPED,0)) THEN 'PARCIAL' ELSE 'RECIBIDO' END,
    FCNR=CASE WHEN EXISTS(SELECT 1 FROM dbo.REC_DET_PED d WHERE d.NPED=@NPED AND ISNULL(d.BLOQ,0)<>-1 AND ISNULL(d.CTDREC,0)<ISNULL(d.CTDPED,0)) THEN FCNR ELSE SYSDATETIME() END
  WHERE NPED=@NPED;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'AUTORIZAR_CONTABILIZAR','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,CONCAT('{"movimiento":101,"almacen":"',STRING_ESCAPE(@ALMACEN,'json'),'"}'),SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,'CONTABILIZADO' ESTATUS_REC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_rechazar
  @DOCREC nvarchar(510),@USR nvarchar(100),@MOTIVO nvarchar(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC); EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510);
  SELECT @ESTATUS=r.ESTATUS_REC,@NPED=r.NPED,@SUC=h.SUC FROM dbo.REC_CTRL_DOC_REC r WITH(UPDLOCK,HOLDLOCK) JOIN dbo.REC_CAB_PED h ON h.NPED=r.NPED WHERE r.DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS='RECHAZADO' BEGIN COMMIT; SELECT @DOCREC DOCREC,@ESTATUS ESTATUS_REC; RETURN; END;
  IF @ESTATUS NOT IN ('RECEPCION_FISICA','VALIDADO','PENDIENTE_AUTORIZACION') THROW 51000,'La recepcion no se puede rechazar en su estado actual.',1;
  UPDATE dbo.REC_CTRL_DOC_REC SET ESTATUS_REC='RECHAZADO',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME(),OBSERVACIONES=COALESCE(NULLIF(@MOTIVO,''),OBSERVACIONES) WHERE DOCREC=@DOCREC;
  UPDATE dbo.REC_INCI_PED SET ESTATUS='RECHAZADA',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME() WHERE DOCREC=@DOCREC AND ESTATUS='ABIERTA';
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'RECHAZAR','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,CASE WHEN @MOTIVO IS NULL THEN NULL ELSE CONCAT('{"motivo":"',STRING_ESCAPE(@MOTIVO,'json'),'"}') END,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,'RECHAZADO' ESTATUS_REC;
END;
GO
