/*
  DEV_PROVD - Corrige importes en cero creados por importaciones sin costo.
  El costo cero o NULL se resuelve desde DAT_ART.CTOP.
*/
SET XACT_ABORT ON;
BEGIN TRANSACTION;

UPDATE d
SET d.CTOP = a.CTOP,
    d.IMPT = CONVERT(MONEY, d.CTDA_DEV * a.CTOP),
    d.FCNM = SYSDATETIME()
FROM dbo.DEV_CTRL_PROVD d
JOIN dbo.DEV_DOC_PROVD h ON h.DOC = d.DOC
JOIN dbo.DAT_ART a ON a.SUC = h.SUC AND a.ART = d.ART
WHERE d.ACTIVO = 1
  AND ISNULL(d.CTOP, 0) = 0
  AND ISNULL(a.CTOP, 0) > 0;

UPDATE h
SET h.FCNM = SYSDATETIME()
FROM dbo.DEV_DOC_PROVD h
WHERE EXISTS (
  SELECT 1
  FROM dbo.DEV_CTRL_PROVD d
  WHERE d.DOC = h.DOC AND d.ACTIVO = 1
);

COMMIT TRANSACTION;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_agregar_articulo
  @DOC NVARCHAR(40), @ART NVARCHAR(20), @CTDA_DEV DECIMAL(18,4),
  @CTOP MONEY=NULL, @MOV_DEV INT, @LOTE NVARCHAR(100)=NULL,
  @CADUCIDAD DATE=NULL, @OBS NVARCHAR(1000)=NULL, @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SUC NVARCHAR(20),@ESTATUS NVARCHAR(30),@COSTO MONEY;
    SELECT @SUC=SUC,@ESTATUS=ESTATUS FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59210,'La devolucion no existe.',1;
    IF @ESTATUS<>'BORRADOR' THROW 59211,'Solo se editan articulos en BORRADOR.',1;
    IF @CTDA_DEV<=0 THROW 59212,'La cantidad debe ser mayor a cero.',1;
    SELECT @COSTO=COALESCE(NULLIF(@CTOP,0),CTOP,0) FROM dbo.DAT_ART WITH(UPDLOCK,HOLDLOCK) WHERE SUC=@SUC AND ART=@ART AND ISNULL(BLOQ,0)<>-1;
    IF @COSTO IS NULL THROW 59213,'El articulo no existe en la sucursal.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DEV_MOTIVO_PROVD WHERE ID=@MOV_DEV AND ACTIVO=1) THROW 59214,'El motivo no es valido.',1;

    INSERT dbo.DEV_CTRL_PROVD(DOC,ART,CTDA_DEV,CTDA_BLOQ,CTOP,IMPT,LOTE,CADUCIDAD,MOV_DEV,OBS,USR_CREA)
    VALUES(@DOC,@ART,@CTDA_DEV,0,@COSTO,CONVERT(MONEY,@CTDA_DEV*@COSTO),NULLIF(LTRIM(RTRIM(@LOTE)),''),@CADUCIDAD,@MOV_DEV,NULLIF(LTRIM(RTRIM(@OBS)),''),@USR);
    DECLARE @IDPD BIGINT=SCOPE_IDENTITY();
    EXEC dbo.sp_dev_provd_recalcular @DOC=@DOC;
    COMMIT;
    SELECT @IDPD IDPD;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO
