/*
  CFDI tracking fields for FAC_SVR_SHAP
  Run in IOELOCAL (SQL Server) after backup.
*/

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_UUID') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_UUID NVARCHAR(64) NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_STATUS') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_STATUS NVARCHAR(40) NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_CANCEL_STATUS') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_CANCEL_STATUS NVARCHAR(40) NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_XML_PATH') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_XML_PATH NVARCHAR(500) NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_PDF_PATH') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_PDF_PATH NVARCHAR(500) NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_FACTURIFY_JOB_ID') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_FACTURIFY_JOB_ID NVARCHAR(120) NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_F_TIMBRADO') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_F_TIMBRADO DATETIME NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_F_CANCELACION') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_F_CANCELACION DATETIME NULL;
GO

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_ERROR_MSG') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD CFDI_ERROR_MSG NVARCHAR(1000) NULL;
GO
