/*
  2026-04-27
  Home ORDs:
  - Crea/activa modulo DAT_JAO_ORD_TRABAJO_TERMINADO en MOD_FRONT.
  - Lo enlaza a los mismos grupos front del modulo base DAT_JAO_ORD.
*/

SET NOCOUNT ON;

IF OBJECT_ID('dbo.MOD_FRONT', 'U') IS NULL
OR OBJECT_ID('dbo.GRUPMOD_FRONT', 'U') IS NULL
OR OBJECT_ID('dbo.GRUPMOD_FRONT_MOD', 'U') IS NULL
BEGIN
  PRINT 'WARN: Tablas MOD_FRONT/GRUPMOD_FRONT/GRUPMOD_FRONT_MOD no disponibles.';
  RETURN;
END;
GO

DECLARE @BaseId INT = NULL;
DECLARE @Depto NVARCHAR(100) = NULL;

SELECT TOP 1
  @BaseId = IDMOD_FRONT,
  @Depto = LTRIM(RTRIM(ISNULL(DEPTO, '')))
FROM dbo.MOD_FRONT
WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD'
ORDER BY IDMOD_FRONT;

IF @BaseId IS NULL
BEGIN
  PRINT 'WARN: No existe modulo base DAT_JAO_ORD. No se aplica alta de trabajo terminado.';
  RETURN;
END;

SET @Depto = NULLIF(@Depto, '');
IF @Depto IS NULL SET @Depto = 'TALLER';

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_TRABAJO_TERMINADO'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_TRABAJO_TERMINADO', 'TRABAJO TERMINADO', 1, GETDATE(), @Depto);
END;
ELSE
BEGIN
  UPDATE dbo.MOD_FRONT
  SET
    NOMBRE = 'TRABAJO TERMINADO',
    ACTIVO = 1,
    DEPTO = COALESCE(NULLIF(LTRIM(RTRIM(ISNULL(DEPTO, ''))), ''), @Depto)
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_TRABAJO_TERMINADO';
END;

DECLARE @TrabajoTerminadoId INT = NULL;
SELECT TOP 1 @TrabajoTerminadoId = IDMOD_FRONT
FROM dbo.MOD_FRONT
WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_TRABAJO_TERMINADO'
ORDER BY IDMOD_FRONT;

IF @TrabajoTerminadoId IS NULL
BEGIN
  PRINT 'WARN: No se pudo resolver ID de DAT_JAO_ORD_TRABAJO_TERMINADO.';
  RETURN;
END;

DECLARE @TargetGroups TABLE (IDGRUPMOD_FRONT INT PRIMARY KEY);

INSERT INTO @TargetGroups (IDGRUPMOD_FRONT)
SELECT DISTINCT g.IDGRUPMOD_FRONT
FROM dbo.GRUPMOD_FRONT g
INNER JOIN dbo.GRUPMOD_FRONT_MOD gm
  ON gm.IDGRUPMOD_FRONT = g.IDGRUPMOD_FRONT
WHERE gm.IDMOD_FRONT = @BaseId
  AND ISNULL(g.ACTIVO, 0) = 1;

IF NOT EXISTS (SELECT 1 FROM @TargetGroups)
BEGIN
  INSERT INTO @TargetGroups (IDGRUPMOD_FRONT)
  SELECT DISTINCT gm.IDGRUPMOD_FRONT
  FROM dbo.GRUPMOD_FRONT_MOD gm
  WHERE gm.IDMOD_FRONT = @BaseId;
END;

INSERT INTO dbo.GRUPMOD_FRONT_MOD (IDGRUPMOD_FRONT, IDMOD_FRONT)
SELECT tg.IDGRUPMOD_FRONT, @TrabajoTerminadoId
FROM @TargetGroups tg
WHERE NOT EXISTS (
  SELECT 1
  FROM dbo.GRUPMOD_FRONT_MOD x
  WHERE x.IDGRUPMOD_FRONT = tg.IDGRUPMOD_FRONT
    AND x.IDMOD_FRONT = @TrabajoTerminadoId
);

PRINT 'OK: Modulo DAT_JAO_ORD_TRABAJO_TERMINADO verificado y enrolado en grupos del modulo base.';
GO
