/*
  Consecutivo global para devoluciones a proveedor.
  El folio numérico ya no depende de la sucursal; el prefijo conserva la sucursal.
*/
SET XACT_ABORT ON;
BEGIN TRANSACTION;

DECLARE @MAX_FOLIO BIGINT = ISNULL((
  SELECT MAX(ISNULL(TRY_CONVERT(BIGINT, RIGHT(DOC, 8)), 0))
  FROM dbo.DEV_DOC_PROVD
), 0);

IF EXISTS (SELECT 1 FROM dbo.DEV_FOLIO_PROVD WHERE SUC='__GLOBAL__')
  UPDATE dbo.DEV_FOLIO_PROVD SET ULTIMO=@MAX_FOLIO,FCNM=SYSDATETIME() WHERE SUC='__GLOBAL__';
ELSE
  INSERT dbo.DEV_FOLIO_PROVD(SUC,ULTIMO) VALUES('__GLOBAL__',@MAX_FOLIO);

COMMIT;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_crear
  @SUC NVARCHAR(20), @ALMACEN NVARCHAR(20), @PROVD INT,
  @TIPO_DEV INT, @DOC_OC NVARCHAR(255)=NULL, @DOC_REC NVARCHAR(255)=NULL,
  @OBS NVARCHAR(1000)=NULL, @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    SET @SUC=UPPER(LTRIM(RTRIM(ISNULL(@SUC,''))));
    SET @ALMACEN=LTRIM(RTRIM(ISNULL(@ALMACEN,'002')));
    IF @SUC='' THROW 59200,'La sucursal es requerida.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DAT_SUC WHERE UPPER(LTRIM(RTRIM(SUC)))=@SUC) THROW 59201,'La sucursal no existe.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DAT_PROVD WHERE ID=@PROVD AND ISNULL(BLOQ,0)<>-1) THROW 59202,'El proveedor no existe o esta inactivo.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DEV_TIPO_PROVD WHERE ID=@TIPO_DEV AND ACTIVO=1) THROW 59203,'El tipo de devolucion no es valido.',1;

    DECLARE @FOLIOS TABLE(ULTIMO BIGINT);
    MERGE dbo.DEV_FOLIO_PROVD WITH(HOLDLOCK) AS target
    USING(SELECT '__GLOBAL__' SUC) AS source ON target.SUC=source.SUC
    WHEN MATCHED THEN UPDATE SET ULTIMO=target.ULTIMO+1,FCNM=SYSDATETIME()
    WHEN NOT MATCHED THEN INSERT(SUC,ULTIMO) VALUES(source.SUC,1)
    OUTPUT inserted.ULTIMO INTO @FOLIOS;
    DECLARE @FOLIO BIGINT=(SELECT ULTIMO FROM @FOLIOS), @DOC NVARCHAR(40);
    SET @DOC=CONCAT('DEV-',@SUC,'-',RIGHT(CONCAT('00000000',CONVERT(VARCHAR(20),@FOLIO)),8));
    INSERT dbo.DEV_DOC_PROVD(DOC,SUC,ALMACEN,PROVD,DOC_OC,DOC_REC,TIPO_DEV,ESTATUS,OBS,USR_CREA)
    VALUES(@DOC,@SUC,@ALMACEN,@PROVD,NULLIF(LTRIM(RTRIM(@DOC_OC)),''),NULLIF(LTRIM(RTRIM(@DOC_REC)),''),@TIPO_DEV,'BORRADOR',NULLIF(LTRIM(RTRIM(@OBS)),''),@USR);
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'CREAR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @DOC DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO
