SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRAN;

  IF OBJECT_ID('dbo.FK_USR_MOD_SUC_USUARIO', 'F') IS NOT NULL
  BEGIN
    ALTER TABLE dbo.USR_MOD_SUC DROP CONSTRAINT FK_USR_MOD_SUC_USUARIO;
  END;

  ALTER TABLE dbo.USR_MOD_SUC WITH CHECK
    ADD CONSTRAINT FK_USR_MOD_SUC_USUARIO
    FOREIGN KEY (USUARIO)
    REFERENCES dbo.USUARIO(USERNAME)
    ON UPDATE CASCADE;

  ALTER TABLE dbo.USR_MOD_SUC CHECK CONSTRAINT FK_USR_MOD_SUC_USUARIO;

  COMMIT TRAN;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRAN;
  THROW;
END CATCH;
