USE IOELOCAL;
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @checkDefinition NVARCHAR(MAX);

SELECT @checkDefinition = cc.definition
FROM sys.check_constraints AS cc
WHERE cc.name = 'CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO'
  AND cc.parent_object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR');

IF @checkDefinition IS NULL
  OR @checkDefinition NOT LIKE '%CERRADO_PS%'
BEGIN
  IF @checkDefinition IS NOT NULL
  BEGIN
    ALTER TABLE dbo.PV_CTR_FOL_ASVR
    DROP CONSTRAINT CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO;
  END;

  ALTER TABLE dbo.PV_CTR_FOL_ASVR WITH NOCHECK
  ADD CONSTRAINT CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO
  CHECK (ESTA IN ('PENDIENTE', 'PAGADO', 'CERRADO_PS', 'MB51PROCES', 'TRANSMITIR', 'ANULADO'));
END;

GO

CREATE OR ALTER TRIGGER dbo.trg_pv_ctr_fol_asvr_homologacion
ON dbo.PV_CTR_FOL_ASVR
AFTER INSERT, UPDATE
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE t
  SET
    t.AUT = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) = 'PCR' THEN 'CR'
      ELSE UPPER(LTRIM(RTRIM(ISNULL(t.AUT, 'CP'))))
    END,
    t.ESTA = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) IN ('EDITANDO', 'DEV PEND', 'PAGADO2', '') THEN 'PENDIENTE'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'PAGADO%' THEN 'PAGADO'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) IN ('CERRADOPS', 'CERRADO PS') THEN 'CERRADO_PS'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'CERRADO_PS%' THEN 'CERRADO_PS'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'TRANSMIT%' THEN 'TRANSMITIR'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) = 'MB51PROCES' THEN 'MB51PROCES'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'ANULA%' THEN 'ANULADO'
      ELSE UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, ''))))
    END,
    t.IDFOLINICIAL = ISNULL(NULLIF(LTRIM(RTRIM(t.IDFOLINICIAL)), ''), t.IDFOL),
    t.ORIGEN_AUT = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('DCA', 'CA', 'DC', 'DG') THEN 'CA'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('DVF', 'VF') THEN 'VF'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('PS', 'CP') THEN ISNULL(NULLIF(UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT, '')))), ''), 'CA')
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('AD', 'AP', 'CR', 'PCR') THEN ISNULL(NULLIF(UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT, '')))), ''), 'CA')
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT, '')))) IN ('CA', 'VF') THEN UPPER(LTRIM(RTRIM(t.ORIGEN_AUT)))
      ELSE 'CA'
    END
  FROM dbo.PV_CTR_FOL_ASVR t
  INNER JOIN inserted i ON i.IDFOL = t.IDFOL;
END;

GO

CREATE OR ALTER PROCEDURE dbo.sp_ps_terminar
  @IDFOL NVARCHAR(255),
  @USER NVARCHAR(255) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  DECLARE @startedTran BIT = 0;
  DECLARE @idfolNorm NVARCHAR(255) = LTRIM(RTRIM(ISNULL(@IDFOL, '')));

  IF @idfolNorm = ''
    THROW 57110, 'IDFOL es requerido', 1;

  BEGIN TRY
    IF @@TRANCOUNT = 0
    BEGIN
      SET @startedTran = 1;
      BEGIN TRANSACTION;
    END;

    UPDATE dbo.PV_CTR_FOL_ASVR
    SET ESTA = 'CERRADO_PS',
        FCNM = GETDATE()
    WHERE IDFOL = @idfolNorm;

    IF @@ROWCOUNT = 0
      THROW 57111, 'El folio no existe', 1;

    IF OBJECT_ID('dbo.PV_CTR_FOL_FORMTMP', 'U') IS NOT NULL
    BEGIN
      DELETE FROM dbo.PV_CTR_FOL_FORMTMP
      WHERE IDFOL = @idfolNorm;
    END;

    IF @startedTran = 1 AND @@TRANCOUNT > 0
      COMMIT TRANSACTION;

    SELECT
      @idfolNorm AS IDFOL,
      'CERRADO_PS' AS ESTA,
      CAST(1 AS BIT) AS OK;
  END TRY
  BEGIN CATCH
    IF @startedTran = 1 AND @@TRANCOUNT > 0
      ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;

GO

UPDATE h
SET
  h.ESTA = 'CERRADO_PS',
  h.FCNM = COALESCE(h.FCNM, GETDATE())
FROM dbo.PV_CTR_FOL_ASVR h
WHERE UPPER(LTRIM(RTRIM(ISNULL(h.ESTA, '')))) = 'TRANSMITIR'
  AND (
    UPPER(LTRIM(RTRIM(ISNULL(h.AUT, '')))) IN ('AD', 'AP', 'CR', 'DC', 'DG', 'DP', 'PS')
    OR EXISTS (
      SELECT 1
      FROM dbo.PV_TICKET_LOG t
      WHERE (
        t.IDFOL = h.IDFOL
        OR (
          LTRIM(RTRIM(ISNULL(h.IDFOLINICIAL, ''))) <> ''
          AND t.IDFOL = h.IDFOLINICIAL
        )
      )
        AND UPPER(LTRIM(RTRIM(ISNULL(t.UPC, '')))) IN ('AD', 'AP', 'CR', 'DC', 'DG', 'DP')
    )
  );

SELECT @@ROWCOUNT AS MigratedPsFoliosToCerradoPs;

GO
