/*
  2026-05-03
  Matriz persistente de visibilidad de flujos ORDs por rol y panel.
  Tabla vinculada a modulo DAT_JAO_ORD.
*/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.DAT_JAO_ORD_FLUJO_VIS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DAT_JAO_ORD_FLUJO_VIS (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    MODULO NVARCHAR(50) NOT NULL,
    PANEL_MODE NVARCHAR(20) NOT NULL,
    ROLE_CODE NVARCHAR(50) NOT NULL,
    ESTA FLOAT NOT NULL,
    SOLO_EXTERNO BIT NOT NULL CONSTRAINT DF_DAT_JAO_ORD_FLUJO_VIS_SOLO_EXTERNO DEFAULT (0),
    ACTIVO BIT NOT NULL CONSTRAINT DF_DAT_JAO_ORD_FLUJO_VIS_ACTIVO DEFAULT (1),
    ORDEN INT NULL,
    FCREG DATETIME NOT NULL CONSTRAINT DF_DAT_JAO_ORD_FLUJO_VIS_FCREG DEFAULT (GETDATE()),
    FCMOD DATETIME NULL
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.DAT_JAO_ORD_FLUJO_VIS')
    AND name = 'UX_DAT_JAO_ORD_FLUJO_VIS_UNQ'
)
BEGIN
  CREATE UNIQUE INDEX UX_DAT_JAO_ORD_FLUJO_VIS_UNQ
    ON dbo.DAT_JAO_ORD_FLUJO_VIS (MODULO, PANEL_MODE, ROLE_CODE, ESTA);
END;
GO

;WITH seed AS (
  SELECT * FROM (VALUES
    -- PANEL OPERATIVO: JEFE TALLER Y ADMIN
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 2),   CONVERT(BIT, 0),  20),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 3),   CONVERT(BIT, 0),  30),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 3.1), CONVERT(BIT, 0),  31),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 5),   CONVERT(BIT, 0),  50),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 7),   CONVERT(BIT, 0),  70),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 8),   CONVERT(BIT, 0),  80),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 9),   CONVERT(BIT, 0),  90),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 9.1), CONVERT(BIT, 0),  91),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 9.2), CONVERT(BIT, 0),  92),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 10),  CONVERT(BIT, 0), 100),
    ('DAT_JAO_ORD', 'operativo', 'ADMIN',      CONVERT(FLOAT, 12),  CONVERT(BIT, 0), 120),

    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 2),   CONVERT(BIT, 0),  20),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 3),   CONVERT(BIT, 0),  30),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 3.1), CONVERT(BIT, 0),  31),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 5),   CONVERT(BIT, 0),  50),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 7),   CONVERT(BIT, 0),  70),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 8),   CONVERT(BIT, 0),  80),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 9),   CONVERT(BIT, 0),  90),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 9.1), CONVERT(BIT, 0),  91),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 9.2), CONVERT(BIT, 0),  92),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 10),  CONVERT(BIT, 0), 100),
    ('DAT_JAO_ORD', 'operativo', 'JEF_TALLER', CONVERT(FLOAT, 12),  CONVERT(BIT, 0), 120),

    -- PANEL OPERATIVO: ANALISTA (9 solo externo)
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 2),   CONVERT(BIT, 0),  20),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 3),   CONVERT(BIT, 0),  30),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 3.1), CONVERT(BIT, 0),  31),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 5),   CONVERT(BIT, 0),  50),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 9),   CONVERT(BIT, 1),  90),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 9.1), CONVERT(BIT, 0),  91),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 9.2), CONVERT(BIT, 0),  92),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 10),  CONVERT(BIT, 0), 100),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA',     CONVERT(FLOAT, 12),  CONVERT(BIT, 0), 120),

    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 2),   CONVERT(BIT, 0),  20),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 3),   CONVERT(BIT, 0),  30),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 3.1), CONVERT(BIT, 0),  31),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 5),   CONVERT(BIT, 0),  50),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 9),   CONVERT(BIT, 1),  90),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 9.1), CONVERT(BIT, 0),  91),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 9.2), CONVERT(BIT, 0),  92),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 10),  CONVERT(BIT, 0), 100),
    ('DAT_JAO_ORD', 'operativo', 'ANALISTA_ORD', CONVERT(FLOAT, 12),  CONVERT(BIT, 0), 120),

    -- PANEL OPERATIVO: ENCARGADOS MAQUILA/BISELADO
    ('DAT_JAO_ORD', 'operativo', 'ENC_MAQUILA',         CONVERT(FLOAT, 7), CONVERT(BIT, 0), 70),
    ('DAT_JAO_ORD', 'operativo', 'ENC_MAQUILA',         CONVERT(FLOAT, 8), CONVERT(BIT, 0), 80),
    ('DAT_JAO_ORD', 'operativo', 'ENC_MAQUILA',         CONVERT(FLOAT, 9), CONVERT(BIT, 0), 90),
    ('DAT_JAO_ORD', 'operativo', 'ENCARGADO_MAQUILA',   CONVERT(FLOAT, 7), CONVERT(BIT, 0), 70),
    ('DAT_JAO_ORD', 'operativo', 'ENCARGADO_MAQUILA',   CONVERT(FLOAT, 8), CONVERT(BIT, 0), 80),
    ('DAT_JAO_ORD', 'operativo', 'ENCARGADO_MAQUILA',   CONVERT(FLOAT, 9), CONVERT(BIT, 0), 90),
    ('DAT_JAO_ORD', 'operativo', 'ENC_BISEL',           CONVERT(FLOAT, 7), CONVERT(BIT, 0), 70),
    ('DAT_JAO_ORD', 'operativo', 'ENC_BISEL',           CONVERT(FLOAT, 8), CONVERT(BIT, 0), 80),
    ('DAT_JAO_ORD', 'operativo', 'ENC_BISEL',           CONVERT(FLOAT, 9), CONVERT(BIT, 0), 90),
    ('DAT_JAO_ORD', 'operativo', 'ENCARGADO_BISELADO',  CONVERT(FLOAT, 7), CONVERT(BIT, 0), 70),
    ('DAT_JAO_ORD', 'operativo', 'ENCARGADO_BISELADO',  CONVERT(FLOAT, 8), CONVERT(BIT, 0), 80),
    ('DAT_JAO_ORD', 'operativo', 'ENCARGADO_BISELADO',  CONVERT(FLOAT, 9), CONVERT(BIT, 0), 90),

    -- Visualizacion en otros paneles
    ('DAT_JAO_ORD', 'anulados',   'ADMIN',      CONVERT(FLOAT, 4),  CONVERT(BIT, 0),  40),
    ('DAT_JAO_ORD', 'anulados',   'JEF_TALLER', CONVERT(FLOAT, 4),  CONVERT(BIT, 0),  40),
    ('DAT_JAO_ORD', 'entregadas', 'ADMIN',      CONVERT(FLOAT, 11), CONVERT(BIT, 0), 110),
    ('DAT_JAO_ORD', 'entregadas', 'JEF_TALLER', CONVERT(FLOAT, 11), CONVERT(BIT, 0), 110)
  ) s(MODULO, PANEL_MODE, ROLE_CODE, ESTA, SOLO_EXTERNO, ORDEN)
)
MERGE dbo.DAT_JAO_ORD_FLUJO_VIS AS tgt
USING seed AS src
  ON UPPER(LTRIM(RTRIM(ISNULL(tgt.MODULO, '')))) = UPPER(src.MODULO)
 AND UPPER(LTRIM(RTRIM(ISNULL(tgt.PANEL_MODE, '')))) = UPPER(src.PANEL_MODE)
 AND UPPER(LTRIM(RTRIM(ISNULL(tgt.ROLE_CODE, '')))) = UPPER(src.ROLE_CODE)
 AND TRY_CONVERT(FLOAT, tgt.ESTA) = TRY_CONVERT(FLOAT, src.ESTA)
WHEN MATCHED THEN
  UPDATE SET
    tgt.SOLO_EXTERNO = src.SOLO_EXTERNO,
    tgt.ACTIVO = 1,
    tgt.ORDEN = src.ORDEN,
    tgt.FCMOD = GETDATE()
WHEN NOT MATCHED BY TARGET THEN
  INSERT (MODULO, PANEL_MODE, ROLE_CODE, ESTA, SOLO_EXTERNO, ACTIVO, ORDEN, FCREG)
  VALUES (src.MODULO, src.PANEL_MODE, src.ROLE_CODE, src.ESTA, src.SOLO_EXTERNO, 1, src.ORDEN, GETDATE())
WHEN NOT MATCHED BY SOURCE
  AND UPPER(LTRIM(RTRIM(ISNULL(tgt.MODULO, '')))) = 'DAT_JAO_ORD'
  AND UPPER(LTRIM(RTRIM(ISNULL(tgt.PANEL_MODE, '')))) IN ('OPERATIVO', 'ANULADOS', 'ENTREGADAS')
THEN
  UPDATE SET
    tgt.ACTIVO = 0,
    tgt.FCMOD = GETDATE();
GO

