/*
  2026-05-09_promociones_descuentos_base.sql
  Base para gestión de promociones/descuentos en cotizaciones.
*/
SET NOCOUNT ON;

BEGIN TRY
  BEGIN TRAN;

  IF OBJECT_ID('dbo.PROMO_CAB', 'U') IS NULL
    THROW 50000, 'No existe dbo.PROMO_CAB', 1;

  IF COL_LENGTH('dbo.PROMO_CAB', 'TIPO_DESC') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD TIPO_DESC NVARCHAR(30) NULL;

  IF COL_LENGTH('dbo.PROMO_CAB', 'PRC_DESC') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD PRC_DESC DECIMAL(9,4) NULL;

  IF COL_LENGTH('dbo.PROMO_CAB', 'IMP_DESC') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD IMP_DESC MONEY NULL;

  IF COL_LENGTH('dbo.PROMO_CAB', 'PRIORIDAD') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD PRIORIDAD INT NOT NULL CONSTRAINT DF_PROMO_CAB_PRIORIDAD DEFAULT (100);

  IF COL_LENGTH('dbo.PROMO_CAB', 'COMBINABLE') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD COMBINABLE INT NOT NULL CONSTRAINT DF_PROMO_CAB_COMBINABLE DEFAULT (0);

  IF COL_LENGTH('dbo.PROMO_CAB', 'MAX_APLI_FOLIO') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD MAX_APLI_FOLIO INT NULL;

  IF COL_LENGTH('dbo.PROMO_CAB', 'CREADO_POR') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD CREADO_POR INT NULL;

  IF COL_LENGTH('dbo.PROMO_CAB', 'FCNR') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_CAB_FCNR DEFAULT (GETDATE());

  IF COL_LENGTH('dbo.PROMO_CAB', 'MOD_POR') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD MOD_POR INT NULL;

  IF COL_LENGTH('dbo.PROMO_CAB', 'FCMOD') IS NULL
    ALTER TABLE dbo.PROMO_CAB ADD FCMOD DATETIME NULL;

  IF OBJECT_ID('dbo.PROMO_REGLA_CRITERIO', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_REGLA_CRITERIO (
      ID_CRITERIO BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_REGLA_CRITERIO PRIMARY KEY,
      ID_PROM INT NOT NULL,
      SUC NVARCHAR(10) NULL,
      CLIENTE FLOAT NULL,
      DEPA FLOAT NULL,
      SUBD FLOAT NULL,
      CLAS FLOAT NULL,
      SCLA FLOAT NULL,
      SCLA2 FLOAT NULL,
      GUIA NVARCHAR(50) NULL,
      ART NVARCHAR(50) NULL,
      UPC NVARCHAR(50) NULL,
      EST INT NOT NULL CONSTRAINT DF_PROMO_REGLA_CRITERIO_EST DEFAULT (1),
      FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_REGLA_CRITERIO_FCNR DEFAULT (GETDATE())
    );

    ALTER TABLE dbo.PROMO_REGLA_CRITERIO
      ADD CONSTRAINT FK_PROMO_REGLA_CRITERIO_PROMO_CAB
      FOREIGN KEY (ID_PROM) REFERENCES dbo.PROMO_CAB(ID_PROM);
  END;

  IF OBJECT_ID('dbo.PROMO_REGLA_BENEFICIO', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_REGLA_BENEFICIO (
      ID_BENEFICIO BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_REGLA_BENEFICIO PRIMARY KEY,
      ID_PROM INT NOT NULL,
      T_BENEFICIO NVARCHAR(30) NOT NULL,
      PRC_DESC DECIMAL(9,4) NULL,
      IMP_DESC MONEY NULL,
      ART_GRATIS NVARCHAR(50) NULL,
      UPC_GRATIS NVARCHAR(50) NULL,
      CANT_GRATIS FLOAT NULL,
      PRECIO_GRATIS MONEY NOT NULL CONSTRAINT DF_PROMO_REGLA_BENEFICIO_PRECIO_GRATIS DEFAULT (0.01),
      PRIORIDAD INT NOT NULL CONSTRAINT DF_PROMO_REGLA_BENEFICIO_PRIORIDAD DEFAULT (100),
      ACUMULABLE INT NOT NULL CONSTRAINT DF_PROMO_REGLA_BENEFICIO_ACUM DEFAULT (0),
      EST INT NOT NULL CONSTRAINT DF_PROMO_REGLA_BENEFICIO_EST DEFAULT (1),
      FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_REGLA_BENEFICIO_FCNR DEFAULT (GETDATE())
    );

    ALTER TABLE dbo.PROMO_REGLA_BENEFICIO
      ADD CONSTRAINT FK_PROMO_REGLA_BENEFICIO_PROMO_CAB
      FOREIGN KEY (ID_PROM) REFERENCES dbo.PROMO_CAB(ID_PROM);
  END;

  IF OBJECT_ID('dbo.PROMO_TICKET_DESC_APLI', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_TICKET_DESC_APLI (
      ID_APLI BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_TICKET_DESC_APLI PRIMARY KEY,
      ID NVARCHAR(255) NOT NULL,
      IDFOL NVARCHAR(255) NOT NULL,
      UPC NVARCHAR(255) NULL,
      ART NVARCHAR(255) NULL,
      IDDESC INT NOT NULL,
      IMPTDESC MONEY NOT NULL,
      FCNDES DATETIME NOT NULL CONSTRAINT DF_PROMO_TICKET_DESC_APLI_FCNDES DEFAULT (GETDATE()),
      PVTAT_ORIG MONEY NULL,
      PVTAT_FIN MONEY NULL,
      IDUSUARIO INT NULL
    );

    ALTER TABLE dbo.PROMO_TICKET_DESC_APLI
      ADD CONSTRAINT FK_PROMO_TICKET_DESC_APLI_PROMO_CAB
      FOREIGN KEY (IDDESC) REFERENCES dbo.PROMO_CAB(ID_PROM);

    ALTER TABLE dbo.PROMO_TICKET_DESC_APLI
      ADD CONSTRAINT FK_PROMO_TICKET_DESC_APLI_PV_TICKET_LOG
      FOREIGN KEY (ID) REFERENCES dbo.PV_TICKET_LOG(ID);

    CREATE UNIQUE INDEX UX_PROMO_TICKET_DESC_APLI_ID_IDDESC
      ON dbo.PROMO_TICKET_DESC_APLI(ID, IDDESC);
  END;

  IF OBJECT_ID('dbo.PROMO_TICKET_GRATIS_REL', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_TICKET_GRATIS_REL (
      ID_REL BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_TICKET_GRATIS_REL PRIMARY KEY,
      IDFOL_ORIG NVARCHAR(255) NOT NULL,
      IDFOL_GRATIS NVARCHAR(255) NULL,
      IDDESC INT NOT NULL,
      ESTATUS NVARCHAR(30) NOT NULL CONSTRAINT DF_PROMO_TICKET_GRATIS_REL_ESTATUS DEFAULT ('PENDIENTE'),
      FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_TICKET_GRATIS_REL_FCNR DEFAULT (GETDATE()),
      IDUSUARIO INT NULL
    );

    ALTER TABLE dbo.PROMO_TICKET_GRATIS_REL
      ADD CONSTRAINT FK_PROMO_TICKET_GRATIS_REL_PROMO_CAB
      FOREIGN KEY (IDDESC) REFERENCES dbo.PROMO_CAB(ID_PROM);
  END;

  IF OBJECT_ID('dbo.PROMO_TICKET_GRATIS_DET', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_TICKET_GRATIS_DET (
      ID_DET BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_TICKET_GRATIS_DET PRIMARY KEY,
      ID_REL BIGINT NOT NULL,
      ART NVARCHAR(255) NULL,
      UPC NVARCHAR(255) NULL,
      CTD FLOAT NOT NULL CONSTRAINT DF_PROMO_TICKET_GRATIS_DET_CTD DEFAULT (1),
      PVTA MONEY NOT NULL CONSTRAINT DF_PROMO_TICKET_GRATIS_DET_PVTA DEFAULT (0.01),
      ESTATUS NVARCHAR(30) NOT NULL CONSTRAINT DF_PROMO_TICKET_GRATIS_DET_ESTATUS DEFAULT ('PENDIENTE')
    );

    ALTER TABLE dbo.PROMO_TICKET_GRATIS_DET
      ADD CONSTRAINT FK_PROMO_TICKET_GRATIS_DET_REL
      FOREIGN KEY (ID_REL) REFERENCES dbo.PROMO_TICKET_GRATIS_REL(ID_REL);
  END;

  IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PROMO_CAB_VIGENCIA_EST' AND object_id = OBJECT_ID('dbo.PROMO_CAB'))
    CREATE INDEX IX_PROMO_CAB_VIGENCIA_EST ON dbo.PROMO_CAB(EST, FCN_INI, FCN_TER, SUC);

  IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PROMO_REGLA_CRITERIO_IDPROM' AND object_id = OBJECT_ID('dbo.PROMO_REGLA_CRITERIO'))
    CREATE INDEX IX_PROMO_REGLA_CRITERIO_IDPROM ON dbo.PROMO_REGLA_CRITERIO(ID_PROM, EST);

  IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PROMO_REGLA_BENEFICIO_IDPROM' AND object_id = OBJECT_ID('dbo.PROMO_REGLA_BENEFICIO'))
    CREATE INDEX IX_PROMO_REGLA_BENEFICIO_IDPROM ON dbo.PROMO_REGLA_BENEFICIO(ID_PROM, EST, PRIORIDAD);

  IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PROMO_TICKET_DESC_APLI_IDFOL' AND object_id = OBJECT_ID('dbo.PROMO_TICKET_DESC_APLI'))
    CREATE INDEX IX_PROMO_TICKET_DESC_APLI_IDFOL ON dbo.PROMO_TICKET_DESC_APLI(IDFOL, FCNDES);

  IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PROMO_TICKET_GRATIS_REL_IDFOL' AND object_id = OBJECT_ID('dbo.PROMO_TICKET_GRATIS_REL'))
    CREATE INDEX IX_PROMO_TICKET_GRATIS_REL_IDFOL ON dbo.PROMO_TICKET_GRATIS_REL(IDFOL_ORIG, FCNR);

  COMMIT;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0 ROLLBACK;
  THROW;
END CATCH;
GO

CREATE OR ALTER PROCEDURE dbo.sp_promo_desc_aplicadas_folio
  @IDFOL NVARCHAR(255)
AS
BEGIN
  SET NOCOUNT ON;

  SELECT
    a.ID_APLI,
    a.ID,
    a.IDFOL,
    a.UPC,
    a.ART,
    a.IDDESC,
    c.DESC_PROMO,
    c.T_PROM,
    a.IMPTDESC,
    a.PVTAT_ORIG,
    a.PVTAT_FIN,
    a.FCNDES,
    a.IDUSUARIO
  FROM dbo.PROMO_TICKET_DESC_APLI a
  INNER JOIN dbo.PROMO_CAB c
    ON c.ID_PROM = a.IDDESC
  WHERE a.IDFOL = @IDFOL
  ORDER BY a.FCNDES DESC, a.ID_APLI DESC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_promo_evaluar_folio
  @IDFOL NVARCHAR(255)
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @SUC NVARCHAR(255) = '';
  DECLARE @CLIENTE FLOAT = NULL;

  SELECT TOP 1
    @SUC = LTRIM(RTRIM(ISNULL(f.SUC, ''))),
    @CLIENTE = TRY_CONVERT(FLOAT, f.CLIEN)
  FROM dbo.PV_CTR_FOL_ASVR f
  WHERE f.IDFOL = @IDFOL OR f.IDFOLINICIAL = @IDFOL
  ORDER BY CASE WHEN f.IDFOL = @IDFOL THEN 0 ELSE 1 END, ISNULL(f.FCNM, f.FCN) DESC;

  IF @SUC = ''
  BEGIN
    SELECT CAST(0 AS INT) AS total_registros WHERE 1 = 0;
    RETURN;
  END;

  ;WITH base AS (
    SELECT
      t.ID,
      t.IDFOL,
      t.ART,
      t.UPC,
      ISNULL(TRY_CONVERT(MONEY, t.PVTAT), ISNULL(TRY_CONVERT(FLOAT, t.CTD), 0) * ISNULL(TRY_CONVERT(MONEY, t.PVTA), 0)) AS PVTAT,
      a.DEPA,
      a.SUBD,
      a.CLAS,
      a.SCLA,
      a.SCLA2,
      jr.GUIA
    FROM dbo.PV_TICKET_LOG t
    LEFT JOIN dbo.DAT_ART a
      ON a.SUC = @SUC
     AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(t.ART, '')))
    OUTER APPLY (
      SELECT TOP 1 j.GUIA
      FROM dbo.DAT_DET_JRQ_SVR j
      WHERE LTRIM(RTRIM(ISNULL(j.ART, ''))) = LTRIM(RTRIM(ISNULL(t.ART, '')))
        AND (LTRIM(RTRIM(ISNULL(j.SUC, ''))) = @SUC OR ISNULL(j.SUC, '') = '')
      ORDER BY CASE WHEN LTRIM(RTRIM(ISNULL(j.SUC, ''))) = @SUC THEN 0 ELSE 1 END
    ) jr
    WHERE t.IDFOL = @IDFOL
  )
  SELECT
    b.ID,
    b.IDFOL,
    b.ART,
    b.UPC,
    b.PVTAT,
    c.ID_PROM,
    c.DESC_PROMO,
    c.T_PROM,
    rb.ID_BENEFICIO,
    rb.T_BENEFICIO,
    rb.PRC_DESC,
    rb.IMP_DESC,
    rb.ART_GRATIS,
    rb.UPC_GRATIS,
    rb.CANT_GRATIS,
    rb.PRECIO_GRATIS,
    rb.PRIORIDAD,
    rb.ACUMULABLE
  FROM base b
  INNER JOIN dbo.PROMO_CAB c
    ON (c.EST IN (1, -1) OR c.EST IS NULL)
   AND (c.FCN_INI IS NULL OR CONVERT(DATE, c.FCN_INI) <= CONVERT(DATE, GETDATE()))
   AND (c.FCN_TER IS NULL OR CONVERT(DATE, c.FCN_TER) >= CONVERT(DATE, GETDATE()))
   AND (
        LTRIM(RTRIM(ISNULL(c.SUC, ''))) = ''
        OR LTRIM(RTRIM(ISNULL(c.SUC, ''))) = '*'
        OR CHARINDEX(
             ',' + UPPER(@SUC) + ',',
             ',' + REPLACE(REPLACE(UPPER(LTRIM(RTRIM(ISNULL(c.SUC, '')))), ' ', ''), ';', ',') + ','
           ) > 0
       )
  INNER JOIN dbo.PROMO_REGLA_BENEFICIO rb
    ON rb.ID_PROM = c.ID_PROM
   AND rb.EST = 1
  WHERE EXISTS (
    SELECT 1
    FROM dbo.PROMO_REGLA_CRITERIO rc
    WHERE rc.ID_PROM = c.ID_PROM
      AND rc.EST = 1
      AND (
           LTRIM(RTRIM(ISNULL(rc.SUC, ''))) = ''
           OR LTRIM(RTRIM(ISNULL(rc.SUC, ''))) = '*'
           OR CHARINDEX(
                ',' + UPPER(@SUC) + ',',
                ',' + REPLACE(REPLACE(UPPER(LTRIM(RTRIM(ISNULL(rc.SUC, '')))), ' ', ''), ';', ',') + ','
              ) > 0
          )
      AND (rc.CLIENTE IS NULL OR rc.CLIENTE = @CLIENTE)
      AND (rc.DEPA IS NULL OR rc.DEPA = b.DEPA)
      AND (rc.SUBD IS NULL OR rc.SUBD = b.SUBD)
      AND (rc.CLAS IS NULL OR rc.CLAS = b.CLAS)
      AND (rc.SCLA IS NULL OR rc.SCLA = b.SCLA)
      AND (rc.SCLA2 IS NULL OR rc.SCLA2 = b.SCLA2)
      AND (LTRIM(RTRIM(ISNULL(rc.GUIA, ''))) = '' OR LTRIM(RTRIM(ISNULL(rc.GUIA, ''))) = LTRIM(RTRIM(ISNULL(b.GUIA, ''))))
      AND (LTRIM(RTRIM(ISNULL(rc.ART, ''))) = '' OR LTRIM(RTRIM(ISNULL(rc.ART, ''))) = LTRIM(RTRIM(ISNULL(b.ART, ''))))
      AND (LTRIM(RTRIM(ISNULL(rc.UPC, ''))) = '' OR LTRIM(RTRIM(ISNULL(rc.UPC, ''))) = LTRIM(RTRIM(ISNULL(b.UPC, ''))))
  )
  ORDER BY rb.PRIORIDAD ASC, c.PRIORIDAD ASC, c.ID_PROM ASC;
END;
GO
