/*
  Relacion venta anterior en cotizaciones / nueva ORD
  - Agrega TICKET_REL a PV_CTR_ORDS y PV_TICKET_LOG
  - Registra clases MB51 206 / 207 en DAT_CMOV
  Nota:
    - Desplegar tambien el SP actualizado en sql/mb51transmicion.sql
*/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF COL_LENGTH('dbo.PV_CTR_ORDS', 'TICKET_REL') IS NULL
BEGIN
  ALTER TABLE dbo.PV_CTR_ORDS
  ADD TICKET_REL NVARCHAR(255) NULL;
END;
GO

IF COL_LENGTH('dbo.PV_TICKET_LOG', 'TICKET_REL') IS NULL
BEGIN
  ALTER TABLE dbo.PV_TICKET_LOG
  ADD TICKET_REL NVARCHAR(255) NULL;
END;
GO

IF OBJECT_ID('dbo.DAT_CMOV', 'U') IS NOT NULL
  AND COL_LENGTH('dbo.DAT_CMOV', 'CMOV') IS NOT NULL
  AND COL_LENGTH('dbo.DAT_CMOV', 'TXTM') IS NOT NULL
  AND COL_LENGTH('dbo.DAT_CMOV', 'MODULO') IS NOT NULL
  AND COL_LENGTH('dbo.DAT_CMOV', 'RELACION') IS NOT NULL
  AND COL_LENGTH('dbo.DAT_CMOV', 'TIPO') IS NOT NULL
  AND COL_LENGTH('dbo.DAT_CMOV', 'NDOC') IS NOT NULL
  AND COL_LENGTH('dbo.DAT_CMOV', 'BLOQ') IS NOT NULL
BEGIN
  UPDATE dbo.DAT_CMOV
  SET
    TXTM = 'VENTA TICKET RELACIONADO',
    MODULO = 'PUNTOV',
    RELACION = '',
    TIPO = 'CARGO',
    NDOC = NULL,
    BLOQ = 'VTAYDEV'
  WHERE CMOV = 206;

  IF @@ROWCOUNT = 0
  BEGIN
    INSERT INTO dbo.DAT_CMOV (CMOV, TXTM, MODULO, RELACION, TIPO, NDOC, BLOQ)
    VALUES (206, 'VENTA TICKET RELACIONADO', 'PUNTOV', '', 'CARGO', NULL, 'VTAYDEV');
  END;

  UPDATE dbo.DAT_CMOV
  SET
    TXTM = 'DESCUENTO TICKET RELACIONADO',
    MODULO = 'PUNTOV',
    RELACION = '',
    TIPO = 'ABONO',
    NDOC = NULL,
    BLOQ = 'VTAYDEV'
  WHERE CMOV = 207;

  IF @@ROWCOUNT = 0
  BEGIN
    INSERT INTO dbo.DAT_CMOV (CMOV, TXTM, MODULO, RELACION, TIPO, NDOC, BLOQ)
    VALUES (207, 'DESCUENTO TICKET RELACIONADO', 'PUNTOV', '', 'ABONO', NULL, 'VTAYDEV');
  END;
END;
GO
