/*
  2026-06-25
  Ajuste de detalle de folio de entrega
  - Cambia PK de PV_CTR_ORDS_ENTREGA_DET de IORD a ID_ENTREGA_DET
  - Permite que una ORD vuelva a tener otra entrega en otro folio
  - Mantiene unicidad por folio + ORD
*/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID('dbo.PV_CTR_ORDS_ENTREGA_DET', 'U') IS NULL
  THROW 58300, 'No existe PV_CTR_ORDS_ENTREGA_DET', 1;

IF COL_LENGTH('dbo.PV_CTR_ORDS_ENTREGA_DET', 'ID_ENTREGA_DET') IS NULL
BEGIN
  ALTER TABLE dbo.PV_CTR_ORDS_ENTREGA_DET
    ADD ID_ENTREGA_DET BIGINT IDENTITY(1,1) NOT NULL;
END;
GO

IF EXISTS (
  SELECT 1
  FROM sys.key_constraints
  WHERE [parent_object_id] = OBJECT_ID('dbo.PV_CTR_ORDS_ENTREGA_DET')
    AND [type] = 'PK'
    AND [name] = 'PK_PV_CTR_ORDS_ENTREGA_DET'
)
BEGIN
  ALTER TABLE dbo.PV_CTR_ORDS_ENTREGA_DET DROP CONSTRAINT PK_PV_CTR_ORDS_ENTREGA_DET;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.key_constraints
  WHERE [parent_object_id] = OBJECT_ID('dbo.PV_CTR_ORDS_ENTREGA_DET')
    AND [type] = 'PK'
    AND [name] = 'PK_PV_CTR_ORDS_ENTREGA_DET'
)
BEGIN
  ALTER TABLE dbo.PV_CTR_ORDS_ENTREGA_DET
    ADD CONSTRAINT PK_PV_CTR_ORDS_ENTREGA_DET
    PRIMARY KEY CLUSTERED (ID_ENTREGA_DET);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE [object_id] = OBJECT_ID('dbo.PV_CTR_ORDS_ENTREGA_DET')
    AND [name] = 'UQ_PV_CTR_ORDS_ENTREGA_DET_ENTREGA_ORD'
)
BEGIN
  CREATE UNIQUE NONCLUSTERED INDEX UQ_PV_CTR_ORDS_ENTREGA_DET_ENTREGA_ORD
    ON dbo.PV_CTR_ORDS_ENTREGA_DET (ID_ENTREGA, IORD);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE [object_id] = OBJECT_ID('dbo.PV_CTR_ORDS_ENTREGA_DET')
    AND [name] = 'IX_PV_CTR_ORDS_ENTREGA_DET_IORD'
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_PV_CTR_ORDS_ENTREGA_DET_IORD
    ON dbo.PV_CTR_ORDS_ENTREGA_DET (IORD);
END;
GO
