/* DEV_PROVD - Acciones operativas del listado: transito y recepcion. */
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF EXISTS(SELECT 1 FROM sys.check_constraints WHERE name='CK_DEV_DOC_ESTATUS' AND parent_object_id=OBJECT_ID('dbo.DEV_DOC_PROVD'))
  ALTER TABLE dbo.DEV_DOC_PROVD DROP CONSTRAINT CK_DEV_DOC_ESTATUS;
GO
ALTER TABLE dbo.DEV_DOC_PROVD WITH CHECK ADD CONSTRAINT CK_DEV_DOC_ESTATUS
  CHECK(ESTATUS IN ('BORRADOR','PENDIENTE','AUTORIZADA','RECHAZADA','CANCELADA','CONSOLIDADA','EN_TRANSITO','RECIBIDA'));
GO

IF EXISTS(SELECT 1 FROM sys.check_constraints WHERE name='CK_DEV_ENVIO_ESTATUS' AND parent_object_id=OBJECT_ID('dbo.DEV_ENVIO_PROVD'))
  ALTER TABLE dbo.DEV_ENVIO_PROVD DROP CONSTRAINT CK_DEV_ENVIO_ESTATUS;
GO
ALTER TABLE dbo.DEV_ENVIO_PROVD WITH CHECK ADD CONSTRAINT CK_DEV_ENVIO_ESTATUS
  CHECK(ESTATUS IN ('CONSOLIDADO','EN_TRANSITO','RECIBIDA'));
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_enviar_transito
  @DOC NVARCHAR(40), @TRANSPORTISTA NVARCHAR(120), @GUIA NVARCHAR(120),
  @CAJAS INT, @RMA NVARCHAR(120)=NULL, @OBS NVARCHAR(1000)=NULL, @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @ESTATUS NVARCHAR(30),@PROVD INT,@SUC NVARCHAR(20),@ID BIGINT,@ENVIO NVARCHAR(40),@ESTATUS_ENVIO NVARCHAR(30);
    SELECT @ESTATUS=ESTATUS,@PROVD=PROVD,@SUC=SUC FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59272,'La devolucion no existe.',1;
    IF @ESTATUS='EN_TRANSITO'
    BEGIN
      SELECT TOP(1) @ENVIO=e.ENVIO FROM dbo.DEV_ENVIO_DOC ed JOIN dbo.DEV_ENVIO_PROVD e ON e.ID=ed.IDENVIO WHERE ed.DOC=@DOC;
      COMMIT; SELECT @ENVIO ENVIO,'EN_TRANSITO' ESTATUS; RETURN;
    END;
    IF @ESTATUS NOT IN('AUTORIZADA','CONSOLIDADA') THROW 59273,'Solo una devolucion autorizada puede enviarse a transito.',1;
    IF @CAJAS<=0 THROW 59274,'El numero de cajas debe ser mayor a cero.',1;
    IF NULLIF(LTRIM(RTRIM(ISNULL(@TRANSPORTISTA,''))),'') IS NULL OR NULLIF(LTRIM(RTRIM(ISNULL(@GUIA,''))),'') IS NULL THROW 59275,'Transportista y guia son requeridos.',1;
    SELECT TOP(1) @ID=e.ID,@ENVIO=e.ENVIO,@ESTATUS_ENVIO=e.ESTATUS
    FROM dbo.DEV_ENVIO_DOC ed JOIN dbo.DEV_ENVIO_PROVD e WITH(UPDLOCK,HOLDLOCK) ON e.ID=ed.IDENVIO WHERE ed.DOC=@DOC;
    IF @ID IS NULL
    BEGIN
      INSERT dbo.DEV_ENVIO_PROVD(ENVIO,PROVD,TRANSPORTISTA,GUIA,CAJAS,RMA,OBS,USR_CREA)
      VALUES(NULL,@PROVD,@TRANSPORTISTA,@GUIA,@CAJAS,NULLIF(LTRIM(RTRIM(@RMA)),''),NULLIF(LTRIM(RTRIM(@OBS)),''),@USR);
      SET @ID=SCOPE_IDENTITY();
      SET @ENVIO=CONCAT('ENV-DEV-',RIGHT(CONCAT('00000000',CONVERT(VARCHAR(20),@ID)),8));
      UPDATE dbo.DEV_ENVIO_PROVD SET ENVIO=@ENVIO WHERE ID=@ID;
      INSERT dbo.DEV_ENVIO_DOC(IDENVIO,DOC) VALUES(@ID,@DOC);
    END
    ELSE IF @ESTATUS_ENVIO<>'CONSOLIDADO' THROW 59276,'El envio relacionado no permite registrar la salida.',1;
    UPDATE dbo.DEV_ENVIO_PROVD SET ESTATUS='EN_TRANSITO',USR_SALIDA=@USR,FCN_SALIDA=SYSDATETIME() WHERE ID=@ID;
    UPDATE h SET ESTATUS='EN_TRANSITO',FCNM=SYSDATETIME() FROM dbo.DEV_DOC_PROVD h JOIN dbo.DEV_ENVIO_DOC ed ON ed.DOC=h.DOC WHERE ed.IDENVIO=@ID;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'SALIDA_FISICA','DEV_PROVD','DEV_ENVIO_PROVD',@ENVIO,@SUC,CONCAT('{"documento":"',STRING_ESCAPE(@DOC,'json'),'"}'),SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @ENVIO ENVIO,'EN_TRANSITO' ESTATUS;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_recibir
  @DOC NVARCHAR(40), @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @ESTATUS NVARCHAR(30),@SUC NVARCHAR(20),@IDENVIO BIGINT;
    SELECT @ESTATUS=ESTATUS,@SUC=SUC FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59277,'La devolucion no existe.',1;
    IF @ESTATUS='RECIBIDA' BEGIN COMMIT; SELECT @DOC DOC,'RECIBIDA' ESTATUS; RETURN; END;
    IF @ESTATUS<>'EN_TRANSITO' THROW 59278,'Solo una devolucion en transito puede marcarse como recibida.',1;
    UPDATE dbo.DEV_DOC_PROVD SET ESTATUS='RECIBIDA',FCNM=SYSDATETIME() WHERE DOC=@DOC;
    SELECT @IDENVIO=IDENVIO FROM dbo.DEV_ENVIO_DOC WHERE DOC=@DOC;
    IF @IDENVIO IS NOT NULL AND NOT EXISTS(
      SELECT 1 FROM dbo.DEV_ENVIO_DOC ed JOIN dbo.DEV_DOC_PROVD h ON h.DOC=ed.DOC
      WHERE ed.IDENVIO=@IDENVIO AND h.ESTATUS<>'RECIBIDA'
    ) UPDATE dbo.DEV_ENVIO_PROVD SET ESTATUS='RECIBIDA' WHERE ID=@IDENVIO;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'RECIBIR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @DOC DOC,'RECIBIDA' ESTATUS;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO
