/* Ajuste 2026-03-26:
   - Crea en MOD_FRONT los módulos front faltantes para accesos directos de ORD.
   - No asigna grupos ni roles; esa relación se administra desde Accesos.
*/

SET NOCOUNT ON;

IF OBJECT_ID('dbo.MOD_FRONT', 'U') IS NULL
BEGIN
  PRINT 'WARN: Tabla dbo.MOD_FRONT no disponible.';
  RETURN;
END;
GO

DECLARE @Depto NVARCHAR(100) = (
  SELECT TOP 1 LTRIM(RTRIM(ISNULL(DEPTO, '')))
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD'
);

IF NULLIF(@Depto, '') IS NULL
BEGIN
  SET @Depto = 'TALLER';
END;

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_ENVIAR'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_ENVIAR', 'ENVIAR A TALLER', 1, GETDATE(), @Depto);
END;

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_ASIGNAR'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_ASIGNAR', 'ASIGNAR A COLABORADOR', 1, GETDATE(), @Depto);
END;

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_RECIBIR'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_RECIBIR', 'RECIBIR EN TALLER', 1, GETDATE(), @Depto);
END;

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_REGRESAR_TIENDA'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_REGRESAR_TIENDA', 'RECIBIR EN TIENDA', 1, GETDATE(), @Depto);
END;

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CODIGO, '')))) = 'DAT_JAO_ORD_ENTREGAR'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_ENTREGAR', 'ENTREGAR A CLIENTE', 1, GETDATE(), @Depto);
END;

PRINT 'OK: Módulos front de accesos directos ORD verificados/creados en MOD_FRONT.';
GO
