/*
  2026-05-10_promociones_precio_gratis_patch.sql
*/
SET NOCOUNT ON;

IF OBJECT_ID('dbo.PROMO_CONFIG', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.PROMO_CONFIG', 'PRECIO_GRATIS') IS NULL
BEGIN
  ALTER TABLE dbo.PROMO_CONFIG
    ADD PRECIO_GRATIS MONEY NULL;
END;
GO

IF OBJECT_ID('dbo.PROMO_CONFIG', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.PROMO_CONFIG', 'PRECIO_GRATIS') IS NOT NULL
BEGIN
  UPDATE dbo.PROMO_CONFIG
    SET PRECIO_GRATIS = 0.01
  WHERE PRECIO_GRATIS IS NULL;
END;
GO

IF OBJECT_ID('dbo.PROMO_CAT_T_BENEFICIO', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM dbo.PROMO_CAT_T_BENEFICIO WHERE CLAVE = 'ART_GRATIS')
BEGIN
  INSERT INTO dbo.PROMO_CAT_T_BENEFICIO (CLAVE, DESCRIPCION, EST, FCNR)
  VALUES ('ART_GRATIS', 'Articulo gratis', 1, GETDATE());
END;
GO

IF OBJECT_ID('dbo.PROMO_CAT_TIPO_DESC', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM dbo.PROMO_CAT_TIPO_DESC WHERE CLAVE = 'ART_GRATIS')
BEGIN
  INSERT INTO dbo.PROMO_CAT_TIPO_DESC (CLAVE, DESCRIPCION, EST, FCNR)
  VALUES ('ART_GRATIS', 'Articulo gratis', 1, GETDATE());
END;
GO
