SET NOCOUNT ON;

IF OBJECT_ID('dbo.DAT_LAB_ACCESO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DAT_LAB_ACCESO (
    ID INT IDENTITY(1,1) NOT NULL,
    SUC VARCHAR(10) NOT NULL,
    LAB_ACCESO INT NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    ESTADO BIT NOT NULL
      CONSTRAINT DF_DAT_LAB_ACCESO_ESTADO DEFAULT (1),
    CONSTRAINT PK_DAT_LAB_ACCESO PRIMARY KEY CLUSTERED (ID)
  );
END;

UPDATE dbo.DAT_LAB_ACCESO
SET
  SUC = UPPER(LTRIM(RTRIM(ISNULL(SUC, '')))),
  TIPO = UPPER(LTRIM(RTRIM(ISNULL(TIPO, '')))),
  ESTADO = ISNULL(ESTADO, 1)
WHERE
  SUC <> UPPER(LTRIM(RTRIM(ISNULL(SUC, ''))))
  OR TIPO <> UPPER(LTRIM(RTRIM(ISNULL(TIPO, ''))))
  OR ESTADO IS NULL;

;WITH dedupe AS (
  SELECT
    ID,
    ROW_NUMBER() OVER (
      PARTITION BY
        UPPER(LTRIM(RTRIM(ISNULL(SUC, '')))),
        TRY_CONVERT(INT, LAB_ACCESO),
        UPPER(LTRIM(RTRIM(ISNULL(TIPO, ''))))
      ORDER BY ID
    ) AS RN
  FROM dbo.DAT_LAB_ACCESO
)
DELETE FROM dedupe WHERE RN > 1;

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.DAT_LAB_ACCESO')
    AND name = 'UX_DAT_LAB_ACCESO_SUC_LAB_TIPO'
)
BEGIN
  CREATE UNIQUE NONCLUSTERED INDEX UX_DAT_LAB_ACCESO_SUC_LAB_TIPO
    ON dbo.DAT_LAB_ACCESO (SUC, LAB_ACCESO, TIPO);
END;

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.DAT_LAB_ACCESO')
    AND name = 'IX_DAT_LAB_ACCESO_LAB_ESTADO'
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_DAT_LAB_ACCESO_LAB_ESTADO
    ON dbo.DAT_LAB_ACCESO (LAB_ACCESO, ESTADO)
    INCLUDE (SUC, TIPO);
END;

IF OBJECT_ID('dbo.DAT_LAB', 'U') IS NOT NULL
BEGIN
  ;WITH seed AS (
    SELECT DISTINCT
      UPPER(LTRIM(RTRIM(ISNULL(l.SUC, '')))) AS SUC,
      TRY_CONVERT(INT, l.ID) AS LAB_ACCESO,
      UPPER(LTRIM(RTRIM(ISNULL(l.TIPOLAB, '')))) AS TIPO
    FROM dbo.DAT_LAB l
    WHERE
      TRY_CONVERT(INT, l.ID) IS NOT NULL
      AND TRY_CONVERT(INT, l.ID) > 0
      AND LTRIM(RTRIM(ISNULL(l.SUC, ''))) <> ''
      AND LTRIM(RTRIM(ISNULL(l.TIPOLAB, ''))) <> ''
      AND ISNULL(l.BLOQ, 0) = 0
  )
  INSERT INTO dbo.DAT_LAB_ACCESO (SUC, LAB_ACCESO, TIPO, ESTADO)
  SELECT
    s.SUC,
    s.LAB_ACCESO,
    s.TIPO,
    1
  FROM seed s
  WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.DAT_LAB_ACCESO a
    WHERE a.SUC = s.SUC
      AND a.LAB_ACCESO = s.LAB_ACCESO
      AND a.TIPO = s.TIPO
  );
END;

SELECT
  ID,
  SUC,
  LAB_ACCESO,
  TIPO,
  ESTADO
FROM dbo.DAT_LAB_ACCESO
ORDER BY SUC, TIPO, LAB_ACCESO, ID;
