SET XACT_ABORT ON;
GO

IF OBJECT_ID('dbo.ESTATUS_SUG', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ESTATUS_SUG (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ESTATUS_SUG PRIMARY KEY,
    [DESC] NVARCHAR(80) NOT NULL CONSTRAINT UQ_ESTATUS_SUG_DESC UNIQUE,
    ACTIVO BIT NOT NULL CONSTRAINT DF_ESTATUS_SUG_ACTIVO DEFAULT (1),
    ORDEN INT NOT NULL CONSTRAINT DF_ESTATUS_SUG_ORDEN DEFAULT (0)
  );
END;
GO

MERGE dbo.ESTATUS_SUG AS target
USING (VALUES
  (N'ABIERTO', 10),
  (N'PENDIENTE', 20),
  (N'PROCESADO', 30),
  (N'PARCIAL', 40),
  (N'RECIBIDO', 50),
  (N'CERRADO', 60),
  (N'ANULADO', 90)
) AS source([DESC], ORDEN)
ON target.[DESC] = source.[DESC]
WHEN MATCHED THEN
  UPDATE SET ACTIVO = 1, ORDEN = source.ORDEN
WHEN NOT MATCHED THEN
  INSERT ([DESC], ACTIVO, ORDEN) VALUES (source.[DESC], 1, source.ORDEN);
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_REC_CAB_PED_SUC_ESTATUS_FCNP'
    AND object_id = OBJECT_ID('dbo.REC_CAB_PED')
)
BEGIN
  CREATE INDEX IX_REC_CAB_PED_SUC_ESTATUS_FCNP
  ON dbo.REC_CAB_PED (SUC, ESTATUS, FCNP DESC)
  INCLUDE (NPED, NPROV, USR, IMPP, NART, SUG, TIPO);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_REC_DET_PED_NPED_BLOQ'
    AND object_id = OBJECT_ID('dbo.REC_DET_PED')
)
BEGIN
  CREATE INDEX IX_REC_DET_PED_NPED_BLOQ
  ON dbo.REC_DET_PED (NPED, BLOQ)
  INCLUDE (IDPED, POS, ART, CTO, CTDPED, UNCOM, CTDREC, RECI);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_DAT_MB51_SUC_ART_FCND_CLSM'
    AND object_id = OBJECT_ID('dbo.DAT_MB51')
)
BEGIN
  CREATE INDEX IX_DAT_MB51_SUC_ART_FCND_CLSM
  ON dbo.DAT_MB51 (SUC, ART, FCND, CLSM)
  INCLUDE (CTDA, ALMACEN);
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_sugeridos_calcular
  @SUC NVARCHAR(20),
  @PROV INT = NULL,
  @MARCA NVARCHAR(100) = NULL,
  @TIPO NVARCHAR(80) = NULL,
  @DEPA FLOAT = NULL,
  @SUBD FLOAT = NULL,
  @CLAS FLOAT = NULL,
  @SCLA FLOAT = NULL,
  @SCLA2 FLOAT = NULL,
  @DIAS INT = 90
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @sucNorm NVARCHAR(20) = UPPER(LTRIM(RTRIM(ISNULL(@SUC, N''))));
  IF @sucNorm = N''
  BEGIN
    THROW 51000, 'La sucursal es requerida para calcular sugeridos.', 1;
  END;

  IF @DIAS IS NULL OR @DIAS <= 0 SET @DIAS = 90;

  DECLARE @fechaHasta DATE = DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1);
  DECLARE @fechaDesde DATE = DATEADD(DAY, -@DIAS, @fechaHasta);

  ;WITH cmov_vtas AS (
    SELECT DISTINCT TRY_CONVERT(FLOAT, CMOV) AS CLSM
    FROM dbo.DAT_CMOV
    WHERE UPPER(LTRIM(RTRIM(ISNULL(RELACION, '')))) = 'VTAS'
      AND TRY_CONVERT(FLOAT, CMOV) IS NOT NULL
  ),
  stock AS (
    SELECT
      UPPER(LTRIM(RTRIM(ISNULL(SUC, '')))) AS SUC,
      LTRIM(RTRIM(ISNULL(ART, ''))) AS ART,
      SUM(TRY_CONVERT(FLOAT, ISNULL(CTDA, 0))) AS STOCK
    FROM dbo.DAT_MB51
    WHERE UPPER(LTRIM(RTRIM(ISNULL(SUC, '')))) = @sucNorm
    GROUP BY UPPER(LTRIM(RTRIM(ISNULL(SUC, '')))), LTRIM(RTRIM(ISNULL(ART, '')))
  ),
  ventas AS (
    SELECT
      UPPER(LTRIM(RTRIM(ISNULL(m.SUC, '')))) AS SUC,
      LTRIM(RTRIM(ISNULL(m.ART, ''))) AS ART,
      SUM(TRY_CONVERT(FLOAT, ISNULL(m.CTDA, 0)) * -1) AS VTA_90
    FROM dbo.DAT_MB51 m
    INNER JOIN cmov_vtas v ON v.CLSM = TRY_CONVERT(FLOAT, m.CLSM)
    WHERE UPPER(LTRIM(RTRIM(ISNULL(m.SUC, '')))) = @sucNorm
      AND CONVERT(DATE, m.FCND) >= @fechaDesde
      AND CONVERT(DATE, m.FCND) < @fechaHasta
    GROUP BY UPPER(LTRIM(RTRIM(ISNULL(m.SUC, '')))), LTRIM(RTRIM(ISNULL(m.ART, '')))
  ),
  base AS (
    SELECT
      LTRIM(RTRIM(CONCAT(
        ISNULL(NULLIF(LTRIM(RTRIM(jd.DDEPA)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(js.DSUBD)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(jc.DCLAS)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(jsc.DSCLA)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(js2.DSCLA2)), N''), N'')
      ))) AS DESCRIPCION_LARGA_JERARQUIA,
      a.SUC,
      a.TIPO,
      a.ART,
      a.UPC,
      a.DES,
      a.BASE,
      TRY_CONVERT(FLOAT, a.SPH) AS SPH,
      TRY_CONVERT(FLOAT, a.CYL) AS CYL,
      TRY_CONVERT(FLOAT, a.ADIC) AS ADIC,
      ISNULL(s.STOCK, 0) AS STOCK,
      ISNULL(TRY_CONVERT(FLOAT, a.STOCK_MIN), 0) AS STOCK_MIN,
      UPPER(LTRIM(RTRIM(ISNULL(a.ESTATUS, '')))) AS ESTATUS,
      ISNULL(TRY_CONVERT(FLOAT, a.DIA_REABASTO), 0) AS DIA_REABASTO,
      TRY_CONVERT(MONEY, a.PVTA) AS PVTA,
      TRY_CONVERT(MONEY, a.CTOP) AS CTOP,
      TRY_CONVERT(FLOAT, a.PROV_1) AS PROV_1,
      TRY_CONVERT(MONEY, a.CTO_PROV1) AS CTO_PROV1,
      TRY_CONVERT(FLOAT, a.PROV_2) AS PROV_2,
      TRY_CONVERT(MONEY, a.CTO_PROV2) AS CTO_PROV2,
      TRY_CONVERT(FLOAT, a.PROV_3) AS PROV_3,
      TRY_CONVERT(MONEY, a.CTO_PROV3) AS CTO_PROV3,
      a.UN_COMP,
      CASE WHEN ISNULL(TRY_CONVERT(FLOAT, a.FACT_COMP), 0) <= 0 THEN 1 ELSE TRY_CONVERT(FLOAT, a.FACT_COMP) END AS FACT_COMP,
      ISNULL(v.VTA_90, 0) AS VTA_90,
      a.MARCA,
      a.DEPA,
      a.SUBD,
      a.CLAS,
      a.SCLA,
      a.SCLA2
    FROM dbo.DAT_ART a
    LEFT JOIN stock s
      ON s.SUC = UPPER(LTRIM(RTRIM(ISNULL(a.SUC, ''))))
     AND s.ART = LTRIM(RTRIM(ISNULL(a.ART, '')))
    LEFT JOIN ventas v
      ON v.SUC = UPPER(LTRIM(RTRIM(ISNULL(a.SUC, ''))))
     AND v.ART = LTRIM(RTRIM(ISNULL(a.ART, '')))
    LEFT JOIN dbo.JRQ_DEPA jd
      ON TRY_CONVERT(FLOAT, jd.DEPA) = TRY_CONVERT(FLOAT, a.DEPA)
    LEFT JOIN dbo.JRQ_SUBD js
      ON TRY_CONVERT(FLOAT, js.SUBD) = TRY_CONVERT(FLOAT, a.SUBD)
     AND TRY_CONVERT(FLOAT, js.DEPA) = TRY_CONVERT(FLOAT, a.DEPA)
    LEFT JOIN dbo.JRQ_CLAS jc
      ON TRY_CONVERT(FLOAT, jc.CLAS) = TRY_CONVERT(FLOAT, a.CLAS)
     AND TRY_CONVERT(FLOAT, jc.SUBD) = TRY_CONVERT(FLOAT, a.SUBD)
    LEFT JOIN dbo.JRQ_SCLA jsc
      ON TRY_CONVERT(FLOAT, jsc.SCLA) = TRY_CONVERT(FLOAT, a.SCLA)
     AND TRY_CONVERT(FLOAT, jsc.CLAS) = TRY_CONVERT(FLOAT, a.CLAS)
    LEFT JOIN dbo.JRQ_SCLA2 js2
      ON TRY_CONVERT(FLOAT, js2.SCLA2) = TRY_CONVERT(FLOAT, a.SCLA2)
     AND TRY_CONVERT(FLOAT, js2.SCLA) = TRY_CONVERT(FLOAT, a.SCLA)
    WHERE UPPER(LTRIM(RTRIM(ISNULL(a.SUC, '')))) = @sucNorm
      AND (@MARCA IS NULL OR @MARCA = N'' OR UPPER(LTRIM(RTRIM(ISNULL(a.MARCA, '')))) LIKE '%' + UPPER(LTRIM(RTRIM(@MARCA))) + '%')
      AND (@TIPO IS NULL OR @TIPO = N'' OR UPPER(LTRIM(RTRIM(ISNULL(a.TIPO, '')))) = UPPER(LTRIM(RTRIM(@TIPO))))
      AND (@DEPA IS NULL OR TRY_CONVERT(FLOAT, a.DEPA) = @DEPA)
      AND (@SUBD IS NULL OR TRY_CONVERT(FLOAT, a.SUBD) = @SUBD)
      AND (@CLAS IS NULL OR TRY_CONVERT(FLOAT, a.CLAS) = @CLAS)
      AND (@SCLA IS NULL OR TRY_CONVERT(FLOAT, a.SCLA) = @SCLA)
      AND (@SCLA2 IS NULL OR TRY_CONVERT(FLOAT, a.SCLA2) = @SCLA2)
      AND ISNULL(a.BLOQ, 0) <> -1
  ),
  proveedor AS (
    SELECT b.*, p.NIVEL_PROV, p.NPROV, p.CTO
    FROM base b
    CROSS APPLY (VALUES
      (1, TRY_CONVERT(INT, b.PROV_1), b.CTO_PROV1),
      (2, TRY_CONVERT(INT, b.PROV_2), b.CTO_PROV2),
      (3, TRY_CONVERT(INT, b.PROV_3), b.CTO_PROV3)
    ) p(NIVEL_PROV, NPROV, CTO)
    WHERE p.NPROV IS NOT NULL
      AND p.CTO IS NOT NULL
      AND (@PROV IS NULL OR p.NPROV = @PROV)
  ),
  calc AS (
    SELECT
      p.*,
      ROUND(p.VTA_90 / @DIAS, 4) AS FACT_VTA_P_D,
      CASE WHEN p.VTA_90 <= 0 THEN 0 ELSE ROUND(p.STOCK / NULLIF(p.VTA_90 / @DIAS, 0), 2) END AS DIAS_INV
    FROM proveedor p
  ),
  sugerido AS (
    SELECT
      c.*,
      ROUND(c.DIA_REABASTO - c.DIAS_INV, 2) AS FAC_REAB,
      ROUND(CASE WHEN c.DIA_REABASTO - c.DIAS_INV <= 0 THEN 0 ELSE ((c.DIA_REABASTO - c.DIAS_INV) * c.FACT_VTA_P_D) / c.FACT_COMP END, 2) AS SUG
    FROM calc c
  )
  SELECT
    DESCRIPCION_LARGA_JERARQUIA,
    SUC,
    TIPO,
    ART,
    UPC,
    DES,
    BASE,
    SPH,
    CYL,
    ADIC,
    STOCK,
    STOCK_MIN,
    ESTATUS,
    DIA_REABASTO,
    PVTA,
    CTOP,
    NPROV,
    NIVEL_PROV,
    CTO,
    UN_COMP,
    FACT_COMP,
    VTA_90,
    FACT_VTA_P_D,
    DIAS_INV,
    FAC_REAB,
    SUG,
    CASE WHEN STOCK_MIN - STOCK <= 0 THEN 0 ELSE CEILING(STOCK_MIN - STOCK) / FACT_COMP END AS PEDIDO,
    CASE
      WHEN ESTATUS = 'NO RESURTIBLE' THEN 0
      WHEN ESTATUS = 'FIJO' THEN CASE WHEN STOCK_MIN - (STOCK / FACT_COMP) <= 0 THEN 0 ELSE CEILING(STOCK_MIN - (STOCK / FACT_COMP)) END
      WHEN FAC_REAB <= 0 THEN 0
      WHEN SUG <= 0 THEN CASE WHEN STOCK >= STOCK_MIN THEN 0 ELSE CEILING(STOCK_MIN - STOCK) END
      ELSE CEILING(SUG)
    END AS PED,
    CASE
      WHEN ESTATUS = 'NO RESURTIBLE' THEN 0
      WHEN ESTATUS = 'FIJO' THEN CASE WHEN STOCK_MIN - (STOCK / FACT_COMP) <= 0 THEN 0 ELSE CEILING(STOCK_MIN - (STOCK / FACT_COMP)) END
      WHEN FAC_REAB <= 0 THEN 0
      WHEN SUG <= 0 THEN CASE WHEN STOCK >= STOCK_MIN THEN 0 ELSE CEILING(STOCK_MIN - STOCK) END
      ELSE CEILING(SUG)
    END AS CANT_FINAL_COMPRA,
    TRY_CONVERT(MONEY, (CASE
      WHEN ESTATUS = 'NO RESURTIBLE' THEN 0
      WHEN ESTATUS = 'FIJO' THEN CASE WHEN STOCK_MIN - (STOCK / FACT_COMP) <= 0 THEN 0 ELSE CEILING(STOCK_MIN - (STOCK / FACT_COMP)) END
      WHEN FAC_REAB <= 0 THEN 0
      WHEN SUG <= 0 THEN CASE WHEN STOCK >= STOCK_MIN THEN 0 ELSE CEILING(STOCK_MIN - STOCK) END
      ELSE CEILING(SUG)
    END) * CTO) AS IMPORTE
  FROM sugerido
  WHERE (CASE
      WHEN ESTATUS = 'NO RESURTIBLE' THEN 0
      WHEN ESTATUS = 'FIJO' THEN CASE WHEN STOCK_MIN - (STOCK / FACT_COMP) <= 0 THEN 0 ELSE CEILING(STOCK_MIN - (STOCK / FACT_COMP)) END
      WHEN FAC_REAB <= 0 THEN 0
      WHEN SUG <= 0 THEN CASE WHEN STOCK >= STOCK_MIN THEN 0 ELSE CEILING(STOCK_MIN - STOCK) END
      ELSE CEILING(SUG)
    END) > 0
  ORDER BY NPROV, DES, ART;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_sugeridos_crear_oc
  @SUC NVARCHAR(20),
  @NPROV INT,
  @USR NVARCHAR(100),
  @TIPO NVARCHAR(80) = N'NORMAL',
  @SUG BIT = 1,
  @ITEMS_JSON NVARCHAR(MAX)
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @sucNorm NVARCHAR(20) = UPPER(LTRIM(RTRIM(ISNULL(@SUC, N''))));
  DECLARE @usrNorm NVARCHAR(100) = LTRIM(RTRIM(ISNULL(@USR, N'')));
  IF @sucNorm = N'' THROW 51001, 'La sucursal es requerida para crear la orden.', 1;
  IF @NPROV IS NULL THROW 51002, 'El proveedor es requerido para crear la orden.', 1;
  IF @usrNorm = N'' THROW 51003, 'El usuario es requerido para crear la orden.', 1;
  IF ISJSON(@ITEMS_JSON) <> 1 THROW 51004, 'El detalle de articulos no es JSON valido.', 1;

  DECLARE @items TABLE (
    POS INT IDENTITY(1,1) NOT NULL,
    ART NVARCHAR(50) NOT NULL,
    CTO MONEY NOT NULL,
    CTDPED FLOAT NOT NULL,
    UNCOM NVARCHAR(80) NULL
  );

  INSERT INTO @items (ART, CTO, CTDPED, UNCOM)
  SELECT
    LTRIM(RTRIM(JSON_VALUE(value, '$.art'))),
    TRY_CONVERT(MONEY, JSON_VALUE(value, '$.cto')),
    TRY_CONVERT(FLOAT, JSON_VALUE(value, '$.ctdped')),
    NULLIF(LTRIM(RTRIM(JSON_VALUE(value, '$.uncom'))), N'')
  FROM OPENJSON(@ITEMS_JSON)
  WHERE LTRIM(RTRIM(ISNULL(JSON_VALUE(value, '$.art'), N''))) <> N''
    AND TRY_CONVERT(FLOAT, JSON_VALUE(value, '$.ctdped')) > 0
    AND TRY_CONVERT(MONEY, JSON_VALUE(value, '$.cto')) IS NOT NULL;

  IF NOT EXISTS (SELECT 1 FROM @items)
  BEGIN
    THROW 51005, 'La orden debe contener al menos un articulo con cantidad y costo validos.', 1;
  END;

  DECLARE @NPED NVARCHAR(50);

  BEGIN TRANSACTION;

  EXEC sys.sp_getapplock
    @Resource = 'REC_CAB_PED_NPED',
    @LockMode = 'Exclusive',
    @LockOwner = 'Transaction',
    @LockTimeout = 15000;

  SELECT @NPED = CONVERT(NVARCHAR(50), ISNULL(MAX(TRY_CONVERT(BIGINT, NPED)), 450000000) + 1)
  FROM dbo.REC_CAB_PED WITH (UPDLOCK, HOLDLOCK)
  WHERE TRY_CONVERT(BIGINT, NPED) IS NOT NULL;

  INSERT INTO dbo.REC_CAB_PED (NPED, SUC, TIPO, NPROV, USR, FCNP, FCNC, IMPP, NART, FCNR, ESTATUS, SUG)
  SELECT
    @NPED,
    @sucNorm,
    NULLIF(LTRIM(RTRIM(@TIPO)), N''),
    @NPROV,
    @usrNorm,
    GETDATE(),
    NULL,
    SUM(CTO * CTDPED),
    COUNT(1),
    NULL,
    N'ABIERTO',
    CASE WHEN @SUG = 1 THEN -1 ELSE 0 END
  FROM @items;

  INSERT INTO dbo.REC_DET_PED (BLOQ, RECI, POS, DREC, IDPED, NPED, ART, CTO, CTDPED, UNCOM, CTDREC)
  SELECT
    0,
    0,
    POS,
    NULL,
    CONCAT(POS, N'-', @NPED),
    @NPED,
    ART,
    CTO,
    CTDPED,
    UNCOM,
    NULL
  FROM @items
  ORDER BY POS;

  COMMIT TRANSACTION;

  SELECT @NPED AS NPED;
END;
GO
