SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'SUC_ENT') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD SUC_ENT NVARCHAR(20) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'SUC_SAL') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD SUC_SAL NVARCHAR(20) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'MTV') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD MTV NVARCHAR(20) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'PRIO') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD PRIO NVARCHAR(20) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'FCNM') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD FCNM DATETIME NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'USR_L') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD USR_L NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'USR_R') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD USR_R NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'USR_E') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD USR_E NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'DOC_MB51_SAL') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD DOC_MB51_SAL NVARCHAR(50) NULL;
GO
IF COL_LENGTH('dbo.TRAN_CTR_DOCPRE', 'DOC_MB51_ENT') IS NULL
  ALTER TABLE dbo.TRAN_CTR_DOCPRE ADD DOC_MB51_ENT NVARCHAR(50) NULL;
GO

IF COL_LENGTH('dbo.TRAN_DET_ART', 'DESC') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD [DESC] NVARCHAR(255) NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'EXIS_S') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD EXIS_S FLOAT NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'EXIS_D') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD EXIS_D FLOAT NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'CTD_LIB') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD CTD_LIB FLOAT NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'CTOTAL') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD CTOTAL MONEY NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'CTOLIB') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD CTOLIB MONEY NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'CTD_R') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD CTD_R FLOAT NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'CTO_R') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD CTO_R MONEY NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'DIF_R') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD DIF_R FLOAT NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'DIFCTO_R') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD DIFCTO_R MONEY NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'TXT') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD TXT NVARCHAR(255) NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'USR_L') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD USR_L NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.TRAN_DET_ART', 'USR_E') IS NULL
  ALTER TABLE dbo.TRAN_DET_ART ADD USR_E NVARCHAR(100) NULL;
GO

IF OBJECT_ID('dbo.MOV_TRAN', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.MOV_TRAN (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MOV_TRAN PRIMARY KEY,
    CLAVE NVARCHAR(20) NOT NULL CONSTRAINT UQ_MOV_TRAN_CLAVE UNIQUE,
    [DESC] NVARCHAR(120) NOT NULL
  );
END
GO

IF OBJECT_ID('dbo.PRIO_TRAN', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRIO_TRAN (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PRIO_TRAN PRIMARY KEY,
    [DESC] NVARCHAR(20) NOT NULL CONSTRAINT UQ_PRIO_TRAN_DESC UNIQUE
  );
END
GO

IF OBJECT_ID('dbo.ESTATUS_TRAN', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ESTATUS_TRAN (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ESTATUS_TRAN PRIMARY KEY,
    [DESC] NVARCHAR(30) NOT NULL CONSTRAINT UQ_ESTATUS_TRAN_DESC UNIQUE,
    ORDEN INT NOT NULL
  );
END
GO

IF OBJECT_ID('dbo.TRAN_EVID', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TRAN_EVID (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRAN_EVID PRIMARY KEY,
    IDPD NVARCHAR(255) NOT NULL,
    IMG_EVI NVARCHAR(MAX) NOT NULL,
    TIPO NVARCHAR(30) NULL,
    USR NVARCHAR(100) NULL,
    FCN DATETIME NOT NULL CONSTRAINT DF_TRAN_EVID_FCN DEFAULT(GETDATE())
  );
END
GO

IF OBJECT_ID('dbo.TRAN_PAQ_ENV', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TRAN_PAQ_ENV (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRAN_PAQ_ENV PRIMARY KEY,
    DOC NVARCHAR(255) NOT NULL,
    EMP NVARCHAR(120) NULL,
    NUM_GUIA NVARCHAR(120) NULL,
    FENV DATETIME NULL,
    RESP NVARCHAR(120) NULL,
    TXT NVARCHAR(255) NULL,
    USR NVARCHAR(100) NULL,
    FCN DATETIME NOT NULL CONSTRAINT DF_TRAN_PAQ_ENV_FCN DEFAULT(GETDATE())
  );
END
GO

IF OBJECT_ID('dbo.TRAN_INCIDN', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TRAN_INCIDN (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRAN_INCIDN PRIMARY KEY,
    [DESC] NVARCHAR(80) NOT NULL CONSTRAINT UQ_TRAN_INCIDN_DESC UNIQUE
  );
END
GO

MERGE dbo.MOV_TRAN AS target
USING (VALUES
  ('TF', 'Transferencia por faltante'),
  ('TVE', 'Transferencia por mercancia especial'),
  ('TRD', 'Transferencia por redistribucion')
) AS source(CLAVE, [DESC])
ON target.CLAVE = source.CLAVE
WHEN NOT MATCHED THEN INSERT (CLAVE, [DESC]) VALUES (source.CLAVE, source.[DESC]);
GO

MERGE dbo.PRIO_TRAN AS target
USING (VALUES ('NORMAL'), ('ALTA')) AS source([DESC])
ON target.[DESC] = source.[DESC]
WHEN NOT MATCHED THEN INSERT ([DESC]) VALUES (source.[DESC]);
GO

MERGE dbo.ESTATUS_TRAN AS target
USING (VALUES
  ('BORRADOR', 10),
  ('PENDIENTE', 20),
  ('LIBERADA', 30),
  ('RECHAZADA', 40),
  ('PREPARACION', 50),
  ('TRANSITO', 60),
  ('REVISANDO', 70),
  ('CONTABILIZADO', 80),
  ('INCIDENCIA', 90)
) AS source([DESC], ORDEN)
ON target.[DESC] = source.[DESC]
WHEN MATCHED THEN UPDATE SET ORDEN = source.ORDEN
WHEN NOT MATCHED THEN INSERT ([DESC], ORDEN) VALUES (source.[DESC], source.ORDEN);
GO

MERGE dbo.TRAN_INCIDN AS target
USING (VALUES
  ('Faltante'),
  ('Sobrante'),
  ('Dañado'),
  ('Mercancia Incorrecta'),
  ('Paquete Extraviado')
) AS source([DESC])
ON target.[DESC] = source.[DESC]
WHEN NOT MATCHED THEN INSERT ([DESC]) VALUES (source.[DESC]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TRAN_CTR_DOCPRE_ESTATUS' AND object_id = OBJECT_ID('dbo.TRAN_CTR_DOCPRE'))
  CREATE INDEX IX_TRAN_CTR_DOCPRE_ESTATUS ON dbo.TRAN_CTR_DOCPRE(ESTATUS, SUC_ENT, SUC_SAL, FCND);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TRAN_DET_ART_DOC' AND object_id = OBJECT_ID('dbo.TRAN_DET_ART'))
  CREATE INDEX IX_TRAN_DET_ART_DOC ON dbo.TRAN_DET_ART(DOC, ART);
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_recalcular
  @DOC NVARCHAR(255)
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE h
  SET h.CTD = ISNULL(calc.CTD, 0),
      h.IMP = ISNULL(calc.IMP, 0),
      h.FCNC = COALESCE(h.FCNC, GETDATE()),
      h.FCNM = GETDATE()
  FROM dbo.TRAN_CTR_DOCPRE h
  OUTER APPLY (
    SELECT
      SUM(CASE WHEN ISNULL(d.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(TRY_CONVERT(FLOAT, d.CTD), 0) END) AS CTD,
      SUM(CASE WHEN ISNULL(d.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(TRY_CONVERT(FLOAT, d.CTD), 0) * ISNULL(a.CTOP, 0) END) AS IMP
    FROM dbo.TRAN_DET_ART d
    LEFT JOIN dbo.DAT_ART a
      ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = LTRIM(RTRIM(ISNULL(h.SUC_SAL, h.ALM_SAL)))
     AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    WHERE d.DOC = h.DOC
  ) calc
  WHERE h.DOC = @DOC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_crear
  @SUC_ENT NVARCHAR(20),
  @SUC_SAL NVARCHAR(20),
  @MTV NVARCHAR(20),
  @PRIO NVARCHAR(20),
  @TXT NVARCHAR(255) = NULL,
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  BEGIN TRY
    BEGIN TRANSACTION;

    SET @SUC_ENT = UPPER(LTRIM(RTRIM(ISNULL(@SUC_ENT, ''))));
    SET @SUC_SAL = UPPER(LTRIM(RTRIM(ISNULL(@SUC_SAL, ''))));
    SET @MTV = UPPER(LTRIM(RTRIM(ISNULL(@MTV, ''))));
    SET @PRIO = UPPER(LTRIM(RTRIM(ISNULL(@PRIO, 'NORMAL'))));

    IF @SUC_ENT = '' OR @SUC_SAL = ''
      THROW 59100, 'Sucursal solicitante y origen son requeridas.', 1;
    IF @SUC_ENT = @SUC_SAL
      THROW 59101, 'Sucursal solicitante y origen no pueden ser iguales.', 1;
    IF NOT EXISTS (SELECT 1 FROM dbo.DAT_SUC WHERE UPPER(LTRIM(RTRIM(SUC))) = @SUC_ENT)
      THROW 59102, 'Sucursal solicitante no existe.', 1;
    IF NOT EXISTS (SELECT 1 FROM dbo.DAT_SUC WHERE UPPER(LTRIM(RTRIM(SUC))) = @SUC_SAL)
      THROW 59103, 'Sucursal origen no existe.', 1;
    IF NOT EXISTS (SELECT 1 FROM dbo.MOV_TRAN WHERE CLAVE = @MTV)
      THROW 59104, 'Motivo de transferencia invalido.', 1;
    IF NOT EXISTS (SELECT 1 FROM dbo.PRIO_TRAN WHERE [DESC] = @PRIO)
      THROW 59105, 'Prioridad invalida.', 1;

    DECLARE @next BIGINT;
    SELECT @next = ISNULL(MAX(TRY_CONVERT(BIGINT, DOC)), 1000) + 1
    FROM dbo.TRAN_CTR_DOCPRE WITH (UPDLOCK, HOLDLOCK);

    DECLARE @DOC NVARCHAR(255) = CONVERT(NVARCHAR(255), @next);
    INSERT INTO dbo.TRAN_CTR_DOCPRE
      (DOC, FCND, FCNC, CTD, IMP, ESTATUS, TXT, ALM_SAL, ALM_ENT, USR, SUC_ENT, SUC_SAL, MTV, PRIO)
    VALUES
      (@DOC, GETDATE(), NULL, 0, 0, 'BORRADOR', @TXT, '001', '001', @USER, @SUC_ENT, @SUC_SAL, @MTV, @PRIO);

    COMMIT TRANSACTION;

    SELECT @DOC AS DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_enviar
  @DOC NVARCHAR(255),
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @estatus NVARCHAR(30);
    SELECT @estatus = UPPER(LTRIM(RTRIM(ISNULL(ESTATUS, ''))))
    FROM dbo.TRAN_CTR_DOCPRE WITH (UPDLOCK, HOLDLOCK)
    WHERE DOC = @DOC;

    IF @estatus IS NULL THROW 59110, 'Documento no existe.', 1;
    IF @estatus <> 'BORRADOR' THROW 59111, 'Solo se puede enviar desde BORRADOR.', 1;
    IF NOT EXISTS (SELECT 1 FROM dbo.TRAN_DET_ART WHERE DOC = @DOC AND ISNULL(BLOQ, 0) <> -1)
      THROW 59112, 'Documento sin articulos activos.', 1;
    IF EXISTS (
      SELECT 1 FROM dbo.TRAN_DET_ART
      WHERE DOC = @DOC AND ISNULL(BLOQ, 0) <> -1 AND ISNULL(TRY_CONVERT(FLOAT, CTD), 0) <= 0
    )
      THROW 59113, 'Todos los articulos deben tener cantidad solicitada mayor a cero.', 1;

    EXEC dbo.sp_trans_recalcular @DOC = @DOC;

    UPDATE dbo.TRAN_CTR_DOCPRE
    SET ESTATUS = 'PENDIENTE',
        FCNM = GETDATE()
    WHERE DOC = @DOC;

    COMMIT TRANSACTION;
    SELECT DOC, ESTATUS FROM dbo.TRAN_CTR_DOCPRE WHERE DOC = @DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_liberar
  @DOC NVARCHAR(255),
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @sucSal NVARCHAR(20), @estatus NVARCHAR(30);
    SELECT
      @sucSal = LTRIM(RTRIM(ISNULL(SUC_SAL, ALM_SAL))),
      @estatus = UPPER(LTRIM(RTRIM(ISNULL(ESTATUS, ''))))
    FROM dbo.TRAN_CTR_DOCPRE WITH (UPDLOCK, HOLDLOCK)
    WHERE DOC = @DOC;

    IF @estatus IS NULL THROW 59120, 'Documento no existe.', 1;
    IF @estatus <> 'PENDIENTE' THROW 59121, 'Solo se puede liberar desde PENDIENTE.', 1;

    UPDATE d
    SET d.CTD_LIB = CASE WHEN d.CTD_LIB IS NULL THEN ISNULL(TRY_CONVERT(FLOAT, d.CTD), 0) ELSE d.CTD_LIB END,
        d.CTOLIB = CASE WHEN d.CTD_LIB IS NULL THEN ISNULL(TRY_CONVERT(FLOAT, d.CTD), 0) ELSE d.CTD_LIB END * ISNULL(a.CTOP, 0),
        d.CTOTAL = ISNULL(TRY_CONVERT(FLOAT, d.CTD), 0) * ISNULL(a.CTOP, 0),
        d.USR_L = @USER
    FROM dbo.TRAN_DET_ART d
    LEFT JOIN dbo.DAT_ART a
      ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
     AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    WHERE d.DOC = @DOC AND ISNULL(d.BLOQ, 0) <> -1;

    IF EXISTS (
      SELECT 1
      FROM dbo.TRAN_DET_ART d
      JOIN dbo.DAT_ART a
        ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
       AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
      WHERE d.DOC = @DOC
        AND ISNULL(d.BLOQ, 0) <> -1
        AND ISNULL(d.CTD_LIB, 0) < 0
    )
      THROW 59122, 'La cantidad liberada no puede ser negativa.', 1;

    IF EXISTS (
      SELECT 1
      FROM dbo.TRAN_DET_ART d
      JOIN dbo.DAT_ART a
        ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
       AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
      WHERE d.DOC = @DOC
        AND ISNULL(d.BLOQ, 0) <> -1
        AND ISNULL(a.STOCK, 0) - ISNULL(d.CTD_LIB, 0) < ISNULL(a.STOCK_MIN, 0)
    )
      THROW 59123, 'La liberacion compromete stock minimo en sucursal origen.', 1;

    UPDATE h
    SET h.CTD = calc.CTD,
        h.IMP = calc.IMP,
        h.ESTATUS = 'LIBERADA',
        h.USR_L = @USER,
        h.FCNM = GETDATE()
    FROM dbo.TRAN_CTR_DOCPRE h
    CROSS APPLY (
      SELECT
        SUM(CASE WHEN ISNULL(d.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(d.CTD_LIB, 0) END) AS CTD,
        SUM(CASE WHEN ISNULL(d.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(d.CTOLIB, 0) END) AS IMP
      FROM dbo.TRAN_DET_ART d
      WHERE d.DOC = h.DOC
    ) calc
    WHERE h.DOC = @DOC;

    COMMIT TRANSACTION;
    SELECT DOC, ESTATUS FROM dbo.TRAN_CTR_DOCPRE WHERE DOC = @DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_rechazar
  @DOC NVARCHAR(255),
  @USER NVARCHAR(100),
  @TXT NVARCHAR(255) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE dbo.TRAN_CTR_DOCPRE
  SET ESTATUS = 'RECHAZADA',
      TXT = COALESCE(@TXT, TXT),
      USR_L = @USER,
      FCNM = GETDATE()
  WHERE DOC = @DOC
    AND UPPER(LTRIM(RTRIM(ISNULL(ESTATUS, '')))) = 'PENDIENTE';

  IF @@ROWCOUNT = 0 THROW 59130, 'Solo se puede rechazar desde PENDIENTE.', 1;
  SELECT DOC, ESTATUS FROM dbo.TRAN_CTR_DOCPRE WHERE DOC = @DOC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_preparar
  @DOC NVARCHAR(255),
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;
  UPDATE dbo.TRAN_CTR_DOCPRE
  SET ESTATUS = 'PREPARACION',
      USR_E = @USER,
      FCNM = GETDATE()
  WHERE DOC = @DOC
    AND UPPER(LTRIM(RTRIM(ISNULL(ESTATUS, '')))) = 'LIBERADA';

  IF @@ROWCOUNT = 0 THROW 59140, 'Solo se puede preparar desde LIBERADA.', 1;
  SELECT DOC, ESTATUS FROM dbo.TRAN_CTR_DOCPRE WHERE DOC = @DOC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_transito
  @DOC NVARCHAR(255),
  @USER NVARCHAR(100),
  @EMP NVARCHAR(120) = NULL,
  @NUM_GUIA NVARCHAR(120) = NULL,
  @RESP NVARCHAR(120) = NULL,
  @TXT NVARCHAR(255) = NULL
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @sucSal NVARCHAR(20), @estatus NVARCHAR(30), @docBase BIGINT;
    SELECT
      @sucSal = LTRIM(RTRIM(ISNULL(SUC_SAL, ALM_SAL))),
      @estatus = UPPER(LTRIM(RTRIM(ISNULL(ESTATUS, ''))))
    FROM dbo.TRAN_CTR_DOCPRE WITH (UPDLOCK, HOLDLOCK)
    WHERE DOC = @DOC;

    IF @estatus IS NULL THROW 59150, 'Documento no existe.', 1;
    IF @estatus <> 'PREPARACION' THROW 59151, 'Solo se puede enviar a transito desde PREPARACION.', 1;
    IF NOT EXISTS (SELECT 1 FROM dbo.DAT_CMOV WHERE CMOV = 121)
      THROW 59152, 'DAT_CMOV no tiene configurado el movimiento 121.', 1;

    SELECT @docBase = TRY_CONVERT(BIGINT, NDOC)
    FROM dbo.DAT_CMOV WITH (UPDLOCK, HOLDLOCK)
    WHERE CMOV = 121;
    IF @docBase IS NULL SET @docBase = 121000000;
    SET @docBase = @docBase + 1;
    UPDATE dbo.DAT_CMOV SET NDOC = @docBase WHERE CMOV = 121;

    INSERT INTO dbo.DAT_MB51
      (IDPD, [USER], CLSM, DOCP, ART, CTDA, CTOT, FCND, FCNC, TXT, ALMACEN, VTAESP, SUC)
    SELECT
      CONVERT(NVARCHAR(36), NEWID()), @USER, 121, @DOC, d.ART,
      ISNULL(d.CTD_LIB, 0),
      ISNULL(d.CTD_LIB, 0) * ISNULL(a.CTOP, 0),
      GETDATE(), GETDATE(), CONCAT('TRANSFERENCIA SALIDA DOC ', @DOC),
      '001', 0, @sucSal
    FROM dbo.TRAN_DET_ART d
    LEFT JOIN dbo.DAT_ART a
      ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
     AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(d.CTD_LIB, 0) > 0;

    UPDATE a
    SET a.STOCK = ISNULL(a.STOCK, 0) - ISNULL(d.CTD_LIB, 0)
    FROM dbo.DAT_ART a
    JOIN dbo.TRAN_DET_ART d
      ON LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
     AND LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1;

    INSERT INTO dbo.TRAN_PAQ_ENV (DOC, EMP, NUM_GUIA, FENV, RESP, TXT, USR)
    VALUES (@DOC, @EMP, @NUM_GUIA, GETDATE(), @RESP, @TXT, @USER);

    UPDATE dbo.TRAN_CTR_DOCPRE
    SET ESTATUS = 'TRANSITO',
        DOC_MB51_SAL = CONVERT(NVARCHAR(50), @docBase),
        USR_E = @USER,
        FCNM = GETDATE()
    WHERE DOC = @DOC;

    COMMIT TRANSACTION;
    SELECT DOC, ESTATUS, DOC_MB51_SAL FROM dbo.TRAN_CTR_DOCPRE WHERE DOC = @DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_recibir
  @DOC NVARCHAR(255),
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @estatus NVARCHAR(30);
    SELECT @estatus = UPPER(LTRIM(RTRIM(ISNULL(ESTATUS, ''))))
    FROM dbo.TRAN_CTR_DOCPRE WITH (UPDLOCK, HOLDLOCK)
    WHERE DOC = @DOC;

    IF @estatus IS NULL THROW 59160, 'Documento no existe.', 1;
    IF @estatus <> 'TRANSITO' THROW 59161, 'Solo se puede recibir desde TRANSITO.', 1;

    UPDATE d
    SET d.CTD_R = CASE WHEN d.CTD_R IS NULL THEN ISNULL(d.CTD_LIB, 0) ELSE d.CTD_R END,
        d.CTO_R = CASE WHEN d.CTD_R IS NULL THEN ISNULL(d.CTD_LIB, 0) ELSE d.CTD_R END * ISNULL(a.CTOP, 0),
        d.DIF_R = ISNULL(d.CTD_LIB, 0) - CASE WHEN d.CTD_R IS NULL THEN ISNULL(d.CTD_LIB, 0) ELSE d.CTD_R END,
        d.DIFCTO_R = (ISNULL(d.CTD_LIB, 0) - CASE WHEN d.CTD_R IS NULL THEN ISNULL(d.CTD_LIB, 0) ELSE d.CTD_R END) * ISNULL(a.CTOP, 0)
    FROM dbo.TRAN_DET_ART d
    LEFT JOIN dbo.TRAN_CTR_DOCPRE h ON h.DOC = d.DOC
    LEFT JOIN dbo.DAT_ART a
      ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = LTRIM(RTRIM(ISNULL(h.SUC_SAL, h.ALM_SAL)))
     AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    WHERE d.DOC = @DOC AND ISNULL(d.BLOQ, 0) <> -1;

    UPDATE dbo.TRAN_CTR_DOCPRE
    SET ESTATUS = CASE
          WHEN EXISTS (
            SELECT 1 FROM dbo.TRAN_DET_ART
            WHERE DOC = @DOC AND ISNULL(BLOQ, 0) <> -1 AND ABS(ISNULL(DIF_R, 0)) > 0.00001
          ) THEN 'INCIDENCIA'
          ELSE 'REVISANDO'
        END,
        USR_R = @USER,
        FCNM = GETDATE()
    WHERE DOC = @DOC;

    COMMIT TRANSACTION;
    SELECT DOC, ESTATUS FROM dbo.TRAN_CTR_DOCPRE WHERE DOC = @DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_trans_contabilizar
  @DOC NVARCHAR(255),
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @sucSal NVARCHAR(20), @sucEnt NVARCHAR(20), @estatus NVARCHAR(30), @docBase BIGINT;
    SELECT
      @sucSal = LTRIM(RTRIM(ISNULL(SUC_SAL, ALM_SAL))),
      @sucEnt = LTRIM(RTRIM(ISNULL(SUC_ENT, ALM_ENT))),
      @estatus = UPPER(LTRIM(RTRIM(ISNULL(ESTATUS, ''))))
    FROM dbo.TRAN_CTR_DOCPRE WITH (UPDLOCK, HOLDLOCK)
    WHERE DOC = @DOC;

    IF @estatus IS NULL THROW 59170, 'Documento no existe.', 1;
    IF @estatus NOT IN ('REVISANDO', 'INCIDENCIA') THROW 59171, 'Solo se puede contabilizar desde REVISANDO o INCIDENCIA.', 1;
    IF NOT EXISTS (SELECT 1 FROM dbo.DAT_CMOV WHERE CMOV IN (122, 123, 124) HAVING COUNT(*) = 3)
      THROW 59172, 'DAT_CMOV no tiene configurados los movimientos 122, 123 y 124.', 1;

    SELECT @docBase = TRY_CONVERT(BIGINT, NDOC)
    FROM dbo.DAT_CMOV WITH (UPDLOCK, HOLDLOCK)
    WHERE CMOV = 123;
    IF @docBase IS NULL SET @docBase = 123000000;
    SET @docBase = @docBase + 1;
    UPDATE dbo.DAT_CMOV SET NDOC = @docBase WHERE CMOV = 123;

    INSERT INTO dbo.DAT_MB51
      (IDPD, [USER], CLSM, DOCP, ART, CTDA, CTOT, FCND, FCNC, TXT, ALMACEN, VTAESP, SUC)
    SELECT
      CONVERT(NVARCHAR(36), NEWID()), @USER, 123, @DOC, d.ART,
      ISNULL(d.CTD_R, 0),
      ISNULL(d.CTD_R, 0) * ISNULL(aDest.CTOP, aOrig.CTOP),
      GETDATE(), GETDATE(), CONCAT('TRANSFERENCIA ENTRADA DOC ', @DOC),
      '001', 0, @sucEnt
    FROM dbo.TRAN_DET_ART d
    LEFT JOIN dbo.DAT_ART aDest
      ON LTRIM(RTRIM(ISNULL(aDest.SUC, ''))) = @sucEnt
     AND LTRIM(RTRIM(ISNULL(aDest.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    LEFT JOIN dbo.DAT_ART aOrig
      ON LTRIM(RTRIM(ISNULL(aOrig.SUC, ''))) = @sucSal
     AND LTRIM(RTRIM(ISNULL(aOrig.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(d.CTD_R, 0) > 0;

    UPDATE a
    SET a.STOCK = ISNULL(a.STOCK, 0) + ISNULL(d.CTD_R, 0)
    FROM dbo.DAT_ART a
    JOIN dbo.TRAN_DET_ART d
      ON LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
     AND LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucEnt
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1;

    INSERT INTO dbo.DAT_MB51
      (IDPD, [USER], CLSM, DOCP, ART, CTDA, CTOT, FCND, FCNC, TXT, ALMACEN, VTAESP, SUC)
    SELECT
      CONVERT(NVARCHAR(36), NEWID()), @USER, 122, @DOC, d.ART,
      ISNULL(d.DIF_R, 0),
      ISNULL(d.DIF_R, 0) * ISNULL(a.CTOP, 0),
      GETDATE(), GETDATE(), CONCAT('TRANSFERENCIA FALTANTE DOC ', @DOC),
      '001', 0, @sucSal
    FROM dbo.TRAN_DET_ART d
    LEFT JOIN dbo.DAT_ART a
      ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
     AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(d.DIF_R, 0) > 0;

    UPDATE a
    SET a.STOCK = ISNULL(a.STOCK, 0) + ISNULL(d.DIF_R, 0)
    FROM dbo.DAT_ART a
    JOIN dbo.TRAN_DET_ART d
      ON LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
     AND LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(d.DIF_R, 0) > 0;

    INSERT INTO dbo.DAT_MB51
      (IDPD, [USER], CLSM, DOCP, ART, CTDA, CTOT, FCND, FCNC, TXT, ALMACEN, VTAESP, SUC)
    SELECT
      CONVERT(NVARCHAR(36), NEWID()), @USER, 124, @DOC, d.ART,
      ABS(ISNULL(d.DIF_R, 0)),
      ABS(ISNULL(d.DIF_R, 0)) * ISNULL(a.CTOP, 0),
      GETDATE(), GETDATE(), CONCAT('TRANSFERENCIA SOBRANTE DOC ', @DOC),
      '001', 0, @sucSal
    FROM dbo.TRAN_DET_ART d
    LEFT JOIN dbo.DAT_ART a
      ON LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
     AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(d.DIF_R, 0) < 0;

    UPDATE a
    SET a.STOCK = ISNULL(a.STOCK, 0) - ABS(ISNULL(d.DIF_R, 0))
    FROM dbo.DAT_ART a
    JOIN dbo.TRAN_DET_ART d
      ON LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
     AND LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @sucSal
    WHERE d.DOC = @DOC
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(d.DIF_R, 0) < 0;

    UPDATE h
    SET h.ESTATUS = 'CONTABILIZADO',
        h.DOC_MB51_ENT = CONVERT(NVARCHAR(50), @docBase),
        h.CTD = calc.CTD,
        h.IMP = calc.IMP,
        h.FCNC = GETDATE(),
        h.FCNM = GETDATE()
    FROM dbo.TRAN_CTR_DOCPRE h
    CROSS APPLY (
      SELECT
        SUM(CASE WHEN ISNULL(d.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(d.CTD_R, 0) END) AS CTD,
        SUM(CASE WHEN ISNULL(d.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(d.CTO_R, 0) END) AS IMP
      FROM dbo.TRAN_DET_ART d
      WHERE d.DOC = h.DOC
    ) calc
    WHERE h.DOC = @DOC;

    COMMIT TRANSACTION;
    SELECT DOC, ESTATUS, DOC_MB51_ENT FROM dbo.TRAN_CTR_DOCPRE WHERE DOC = @DOC;
  END TRY
  BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;
GO
