IF OBJECT_ID('dbo.DAT_SUC_COLAB_ACCESO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DAT_SUC_COLAB_ACCESO (
    ID INT IDENTITY(1,1) NOT NULL,
    SUC_DESTINO NVARCHAR(10) NOT NULL,
    SUC_ORIGEN NVARCHAR(10) NOT NULL,
    ACTIVO BIT NOT NULL CONSTRAINT DF_DAT_SUC_COLAB_ACCESO_ACTIVO DEFAULT (1),
    OBSERVACION NVARCHAR(250) NULL,
    FCREG DATETIME2(0) NOT NULL CONSTRAINT DF_DAT_SUC_COLAB_ACCESO_FCREG DEFAULT (SYSDATETIME()),
    FCMOD DATETIME2(0) NULL,
    CONSTRAINT PK_DAT_SUC_COLAB_ACCESO PRIMARY KEY CLUSTERED (ID),
    CONSTRAINT CK_DAT_SUC_COLAB_ACCESO_DISTINCT CHECK (UPPER(LTRIM(RTRIM(ISNULL(SUC_DESTINO, '')))) <> UPPER(LTRIM(RTRIM(ISNULL(SUC_ORIGEN, '')))))
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_DAT_SUC_COLAB_ACCESO'
    AND object_id = OBJECT_ID('dbo.DAT_SUC_COLAB_ACCESO')
)
BEGIN
  CREATE UNIQUE INDEX UX_DAT_SUC_COLAB_ACCESO
    ON dbo.DAT_SUC_COLAB_ACCESO (SUC_DESTINO, SUC_ORIGEN);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_DAT_SUC_COLAB_ACCESO_SUC_DESTINO'
)
BEGIN
  ALTER TABLE dbo.DAT_SUC_COLAB_ACCESO
    ADD CONSTRAINT FK_DAT_SUC_COLAB_ACCESO_SUC_DESTINO
      FOREIGN KEY (SUC_DESTINO) REFERENCES dbo.DAT_SUC (SUC);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.foreign_keys
  WHERE name = 'FK_DAT_SUC_COLAB_ACCESO_SUC_ORIGEN'
)
BEGIN
  ALTER TABLE dbo.DAT_SUC_COLAB_ACCESO
    ADD CONSTRAINT FK_DAT_SUC_COLAB_ACCESO_SUC_ORIGEN
      FOREIGN KEY (SUC_ORIGEN) REFERENCES dbo.DAT_SUC (SUC);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM dbo.DAT_SUC_COLAB_ACCESO
  WHERE UPPER(LTRIM(RTRIM(ISNULL(SUC_DESTINO, '')))) = 'DF14'
    AND UPPER(LTRIM(RTRIM(ISNULL(SUC_ORIGEN, '')))) = 'DF04'
)
BEGIN
  INSERT INTO dbo.DAT_SUC_COLAB_ACCESO (
    SUC_DESTINO,
    SUC_ORIGEN,
    ACTIVO,
    OBSERVACION,
    FCREG,
    FCMOD
  )
  VALUES (
    'DF14',
    'DF04',
    1,
    'Configuracion inicial de sucursales gemelas DF14 -> DF04',
    SYSDATETIME(),
    NULL
  );
END;
GO
