/*
  2026-05-15 - Modulo de merma (gestion/auditoria/consulta/reportes)
  Script incremental compatible con esquema actual IOELOCAL.
*/
SET NOCOUNT ON;

IF OBJECT_ID('dbo.CLAS_MERMA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.CLAS_MERMA (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLAS_MERMA PRIMARY KEY,
    [DESC] NVARCHAR(150) NOT NULL
  );
END;

IF OBJECT_ID('dbo.MOT_MERMA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.MOT_MERMA (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MOT_MERMA PRIMARY KEY,
    [DESC] NVARCHAR(200) NOT NULL,
    ID_CLAS INT NOT NULL,
    REQUIERE_EVIDENCIA BIT NOT NULL CONSTRAINT DF_MOT_MERMA_REQUIERE_EVIDENCIA DEFAULT(0)
  );
END;

IF OBJECT_ID('dbo.ESTATUS_MERMA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ESTATUS_MERMA (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ESTATUS_MERMA PRIMARY KEY,
    [DESC] NVARCHAR(100) NOT NULL
  );
END;

IF OBJECT_ID('dbo.MERMA_EVIDENCIA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.MERMA_EVIDENCIA (
    ID UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_MERMA_EVIDENCIA PRIMARY KEY DEFAULT NEWID(),
    IDPD NVARCHAR(510) NOT NULL,
    NOMBRE_ARCHIVO NVARCHAR(255) NULL,
    EXTENSION NVARCHAR(20) NULL,
    MIME_TYPE NVARCHAR(100) NULL,
    URL_ARCHIVO NVARCHAR(500) NULL,
    PESO_BYTES BIGINT NULL,
    FCN DATETIME NOT NULL CONSTRAINT DF_MERMA_EVIDENCIA_FCN DEFAULT GETDATE(),
    USER_CREA NVARCHAR(100) NULL
  );
END;

IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'AREAM') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD AREAM INT NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'USER_A') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD USER_A NVARCHAR(100) NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'USER_R') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD USER_R NVARCHAR(100) NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'OBS_AUDIT') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD OBS_AUDIT NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'ID_ESTATUS') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD ID_ESTATUS INT NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'FCNAUD') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD FCNAUD DATETIME NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'USER_AUD') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD USER_AUD NVARCHAR(100) NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'OBS_REV') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD OBS_REV NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'OBS_ANUL') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD OBS_ANUL NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.DOC_CTRL_MERMA', 'FCNM') IS NULL
  ALTER TABLE dbo.DOC_CTRL_MERMA ADD FCNM DATETIME NULL;

IF COL_LENGTH('dbo.DET_ART_MERMA', 'CTO') IS NULL
  ALTER TABLE dbo.DET_ART_MERMA ADD CTO DECIMAL(18,4) NULL;
IF COL_LENGTH('dbo.DET_ART_MERMA', 'MOT_M') IS NULL
  ALTER TABLE dbo.DET_ART_MERMA ADD MOT_M INT NULL;
IF COL_LENGTH('dbo.DET_ART_MERMA', 'RESP_M') IS NULL
  ALTER TABLE dbo.DET_ART_MERMA ADD RESP_M NVARCHAR(150) NULL;
IF COL_LENGTH('dbo.DET_ART_MERMA', 'OBS_M') IS NULL
  ALTER TABLE dbo.DET_ART_MERMA ADD OBS_M NVARCHAR(MAX) NULL;
GO
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_MOT_MERMA_CLAS')
BEGIN
  ALTER TABLE dbo.MOT_MERMA WITH NOCHECK
    ADD CONSTRAINT FK_MOT_MERMA_CLAS
    FOREIGN KEY (ID_CLAS) REFERENCES dbo.CLAS_MERMA(ID);
END;

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DOC_CTRL_MERMA_ID_ESTATUS')
BEGIN
  ALTER TABLE dbo.DOC_CTRL_MERMA WITH NOCHECK
    ADD CONSTRAINT FK_DOC_CTRL_MERMA_ID_ESTATUS
    FOREIGN KEY (ID_ESTATUS) REFERENCES dbo.ESTATUS_MERMA(ID);
END;

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DET_ART_MERMA_MOT_M')
BEGIN
  ALTER TABLE dbo.DET_ART_MERMA WITH NOCHECK
    ADD CONSTRAINT FK_DET_ART_MERMA_MOT_M
    FOREIGN KEY (MOT_M) REFERENCES dbo.MOT_MERMA(ID);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DOC_CTRL_MERMA') AND name = 'IX_DOC_CTRL_MERMA_ESTATS')
  CREATE INDEX IX_DOC_CTRL_MERMA_ESTATS ON dbo.DOC_CTRL_MERMA(ESTATS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DOC_CTRL_MERMA') AND name = 'IX_DOC_CTRL_MERMA_FCND')
  CREATE INDEX IX_DOC_CTRL_MERMA_FCND ON dbo.DOC_CTRL_MERMA(FCND);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DOC_CTRL_MERMA') AND name = 'IX_DOC_CTRL_MERMA_SUC')
  CREATE INDEX IX_DOC_CTRL_MERMA_SUC ON dbo.DOC_CTRL_MERMA(SUC);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DOC_CTRL_MERMA') AND name = 'IX_DOC_CTRL_MERMA_ID_ESTATUS')
  CREATE INDEX IX_DOC_CTRL_MERMA_ID_ESTATUS ON dbo.DOC_CTRL_MERMA(ID_ESTATUS);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DET_ART_MERMA') AND name = 'IX_DET_ART_MERMA_DOCMER')
  CREATE INDEX IX_DET_ART_MERMA_DOCMER ON dbo.DET_ART_MERMA(DOCMER);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DET_ART_MERMA') AND name = 'IX_DET_ART_MERMA_ART')
  CREATE INDEX IX_DET_ART_MERMA_ART ON dbo.DET_ART_MERMA(ART);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.DET_ART_MERMA') AND name = 'IX_DET_ART_MERMA_MOT_M')
  CREATE INDEX IX_DET_ART_MERMA_MOT_M ON dbo.DET_ART_MERMA(MOT_M);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.MERMA_EVIDENCIA') AND name = 'IX_MERMA_EVIDENCIA_IDPD')
  CREATE INDEX IX_MERMA_EVIDENCIA_IDPD ON dbo.MERMA_EVIDENCIA(IDPD);

IF EXISTS (
  SELECT 1
  WHERE NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 1)
     OR NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 2)
     OR NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 3)
     OR NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 4)
     OR NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 5)
     OR NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 6)
)
BEGIN
  SET IDENTITY_INSERT dbo.ESTATUS_MERMA ON;
  IF NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 1)
    INSERT INTO dbo.ESTATUS_MERMA (ID, [DESC]) VALUES (1, 'ABIERTO');
  IF NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 2)
    INSERT INTO dbo.ESTATUS_MERMA (ID, [DESC]) VALUES (2, 'PENDIENTE');
  IF NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 3)
    INSERT INTO dbo.ESTATUS_MERMA (ID, [DESC]) VALUES (3, 'ANULADO');
  IF NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 4)
    INSERT INTO dbo.ESTATUS_MERMA (ID, [DESC]) VALUES (4, 'REVISAR');
  IF NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 5)
    INSERT INTO dbo.ESTATUS_MERMA (ID, [DESC]) VALUES (5, 'CONTABILIZADO');
  IF NOT EXISTS (SELECT 1 FROM dbo.ESTATUS_MERMA WHERE ID = 6)
    INSERT INTO dbo.ESTATUS_MERMA (ID, [DESC]) VALUES (6, 'AUDITADO');
  SET IDENTITY_INSERT dbo.ESTATUS_MERMA OFF;
END;

IF NOT EXISTS (SELECT 1 FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'OPERATIVA')
  INSERT INTO dbo.CLAS_MERMA([DESC]) VALUES ('OPERATIVA');
IF NOT EXISTS (SELECT 1 FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'CADUCIDAD')
  INSERT INTO dbo.CLAS_MERMA([DESC]) VALUES ('CADUCIDAD');
IF NOT EXISTS (SELECT 1 FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'DANIO')
  INSERT INTO dbo.CLAS_MERMA([DESC]) VALUES ('DANIO');
IF NOT EXISTS (SELECT 1 FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'DEVOLUCION')
  INSERT INTO dbo.CLAS_MERMA([DESC]) VALUES ('DEVOLUCION');
IF NOT EXISTS (SELECT 1 FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'TALLER')
  INSERT INTO dbo.CLAS_MERMA([DESC]) VALUES ('TALLER');

DECLARE @clasOperativa INT = (SELECT TOP 1 ID FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'OPERATIVA');
DECLARE @clasDanio INT = (SELECT TOP 1 ID FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'DANIO');
DECLARE @clasCad INT = (SELECT TOP 1 ID FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'CADUCIDAD');
DECLARE @clasTaller INT = (SELECT TOP 1 ID FROM dbo.CLAS_MERMA WHERE UPPER(LTRIM(RTRIM([DESC]))) = 'TALLER');

IF @clasOperativa IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.MOT_MERMA WHERE UPPER([DESC]) = 'DESPERFECTO OPERATIVO')
  INSERT INTO dbo.MOT_MERMA([DESC], ID_CLAS, REQUIERE_EVIDENCIA) VALUES ('DESPERFECTO OPERATIVO', @clasOperativa, 0);
IF @clasDanio IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.MOT_MERMA WHERE UPPER([DESC]) = 'ROTO')
  INSERT INTO dbo.MOT_MERMA([DESC], ID_CLAS, REQUIERE_EVIDENCIA) VALUES ('ROTO', @clasDanio, 1);
IF @clasDanio IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.MOT_MERMA WHERE UPPER([DESC]) = 'RAYADA')
  INSERT INTO dbo.MOT_MERMA([DESC], ID_CLAS, REQUIERE_EVIDENCIA) VALUES ('RAYADA', @clasDanio, 1);
IF @clasCad IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.MOT_MERMA WHERE UPPER([DESC]) = 'CADUCADO')
  INSERT INTO dbo.MOT_MERMA([DESC], ID_CLAS, REQUIERE_EVIDENCIA) VALUES ('CADUCADO', @clasCad, 0);
IF @clasTaller IS NOT NULL AND NOT EXISTS (SELECT 1 FROM dbo.MOT_MERMA WHERE UPPER([DESC]) = 'DANIO DE TALLER')
  INSERT INTO dbo.MOT_MERMA([DESC], ID_CLAS, REQUIERE_EVIDENCIA) VALUES ('DANIO DE TALLER', @clasTaller, 1);

UPDATE m
SET m.ID_ESTATUS = CASE
  WHEN UPPER(LTRIM(RTRIM(ISNULL(m.ESTATS, '')))) IN ('ABIERTO') THEN 1
  WHEN UPPER(LTRIM(RTRIM(ISNULL(m.ESTATS, '')))) IN ('PENDIENTE', 'AUTORIZADO') THEN 2
  WHEN UPPER(LTRIM(RTRIM(ISNULL(m.ESTATS, '')))) IN ('ANULADO', 'CANCELADO') THEN 3
  WHEN UPPER(LTRIM(RTRIM(ISNULL(m.ESTATS, '')))) IN ('REVISAR', 'REVISION') THEN 4
  WHEN UPPER(LTRIM(RTRIM(ISNULL(m.ESTATS, '')))) IN ('CONTABILIZADO', 'COTABILIZADO', 'COTIBILIZADO', 'PROCESADO') THEN 5
  WHEN UPPER(LTRIM(RTRIM(ISNULL(m.ESTATS, '')))) IN ('AUDITADO') THEN 6
  ELSE m.ID_ESTATUS
END
FROM dbo.DOC_CTRL_MERMA m
WHERE m.ID_ESTATUS IS NULL;
GO

CREATE OR ALTER PROCEDURE dbo.sp_merma_crear
  @SUC NVARCHAR(50),
  @USER NVARCHAR(100),
  @AREAM INT = NULL,
  @TXT NVARCHAR(200) = NULL
AS
BEGIN
  SET NOCOUNT ON;

  IF LTRIM(RTRIM(ISNULL(@SUC, ''))) = ''
    THROW 59001, 'SUC es requerida.', 1;
  IF LTRIM(RTRIM(ISNULL(@USER, ''))) = ''
    THROW 59002, 'USER es requerido.', 1;

  DECLARE @nextDoc BIGINT;

  SELECT @nextDoc = ISNULL(MAX(TRY_CONVERT(BIGINT, DOCMER)), 20000000) + 1
  FROM dbo.DOC_CTRL_MERMA
  WHERE TRY_CONVERT(BIGINT, DOCMER) IS NOT NULL;

  DECLARE @docmer NVARCHAR(50) = CONVERT(NVARCHAR(50), @nextDoc);

  INSERT INTO dbo.DOC_CTRL_MERMA
    (DOCMER, [USER], FCND, FCNC, ESTATS, ID_ESTATUS, NARTS, TOTAL, SUC, TXT, AREAM)
  VALUES
    (@docmer, @USER, GETDATE(), NULL, 'ABIERTO', 1, 0, 0, @SUC, @TXT, @AREAM);

  SELECT DOCMER, SUC, [USER], FCND, FCNC, ESTATS, ID_ESTATUS, NARTS, TOTAL, TXT, AREAM
  FROM dbo.DOC_CTRL_MERMA
  WHERE DOCMER = @docmer;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_merma_agregar_articulo
  @DOCMER NVARCHAR(50),
  @ART NVARCHAR(100),
  @CTD FLOAT,
  @MOT_M INT,
  @RESP_M NVARCHAR(150) = NULL,
  @OBS_M NVARCHAR(MAX) = NULL,
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;

  IF LTRIM(RTRIM(ISNULL(@DOCMER, ''))) = ''
    THROW 59010, 'DOCMER es requerido.', 1;
  IF LTRIM(RTRIM(ISNULL(@ART, ''))) = ''
    THROW 59011, 'ART es requerido.', 1;
  IF ISNULL(@CTD, 0) <= 0
    THROW 59012, 'CTD debe ser mayor a 0.', 1;

  DECLARE @docSuc NVARCHAR(50);
  DECLARE @docEst INT;

  SELECT TOP 1
    @docSuc = LTRIM(RTRIM(ISNULL(SUC, ''))),
    @docEst = ISNULL(ID_ESTATUS, CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) = 'ABIERTO' THEN 1
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) IN ('REVISION', 'REVISAR') THEN 4
      ELSE -1
    END)
  FROM dbo.DOC_CTRL_MERMA
  WHERE DOCMER = @DOCMER;

  IF @docSuc IS NULL
    THROW 59013, 'Documento no existe.', 1;

  IF @docEst NOT IN (1, 4)
    THROW 59014, 'Solo se pueden agregar articulos en ABIERTO o REVISAR.', 1;

  IF NOT EXISTS (SELECT 1 FROM dbo.MOT_MERMA WHERE ID = @MOT_M)
    THROW 59015, 'MOT_M no existe en catalogo de motivos.', 1;

  IF EXISTS (
    SELECT 1
    FROM dbo.DET_ART_MERMA d
    WHERE d.DOCMER = @DOCMER
      AND LTRIM(RTRIM(ISNULL(d.ART, ''))) = LTRIM(RTRIM(ISNULL(@ART, '')))
      AND ISNULL(d.MOT_M, 0) = ISNULL(@MOT_M, 0)
      AND ISNULL(d.BLOQ, 0) <> -1
  )
    THROW 59016, 'No se permite articulo duplicado con el mismo motivo en el mismo documento.', 1;

  IF NOT EXISTS (
    SELECT 1
    FROM dbo.DAT_ART a
    WHERE LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @docSuc
      AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(@ART, '')))
  )
    THROW 59017, 'Articulo no existe para la sucursal del documento.', 1;

  DECLARE @cto DECIMAL(18,4);
  DECLARE @mtv NVARCHAR(510);

  SELECT TOP 1 @cto = TRY_CONVERT(DECIMAL(18,4), ISNULL(a.CTOP, 0))
  FROM dbo.DAT_ART a
  WHERE LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @docSuc
    AND LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(@ART, '')));

  SELECT TOP 1 @mtv = [DESC]
  FROM dbo.MOT_MERMA
  WHERE ID = @MOT_M;

  DECLARE @idpd NVARCHAR(510) = CONVERT(NVARCHAR(36), NEWID());

  INSERT INTO dbo.DET_ART_MERMA
    (SEL, IDPD, DOCMER, ART, CTD, BLOQ, MTVMER, REV, DOCREV, SUC, CTO, MOT_M, RESP_M, OBS_M)
  VALUES
    (0, @idpd, @DOCMER, @ART, @CTD, 0, @mtv, 0, NULL, @docSuc, ISNULL(@cto, 0), @MOT_M, @RESP_M, @OBS_M);

  UPDATE d
  SET d.NARTS = agg.narts,
      d.TOTAL = agg.total,
      d.FCNM = GETDATE()
  FROM dbo.DOC_CTRL_MERMA d
  CROSS APPLY (
    SELECT
      SUM(CASE WHEN ISNULL(x.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(x.CTD, 0) END) AS narts,
      SUM(CASE WHEN ISNULL(x.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(x.CTD, 0) * ISNULL(x.CTO, 0) END) AS total
    FROM dbo.DET_ART_MERMA x
    WHERE x.DOCMER = d.DOCMER
  ) agg
  WHERE d.DOCMER = @DOCMER;

  SELECT TOP 1 *
  FROM dbo.DET_ART_MERMA
  WHERE IDPD = @idpd;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_merma_solicitar_autorizacion
  @DOCMER NVARCHAR(50),
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @docEst INT;

  SELECT TOP 1 @docEst = ISNULL(ID_ESTATUS, CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) = 'ABIERTO' THEN 1
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) IN ('REVISION', 'REVISAR') THEN 4
      ELSE -1
    END)
  FROM dbo.DOC_CTRL_MERMA
  WHERE DOCMER = @DOCMER;

  IF @docEst IS NULL
    THROW 59020, 'Documento no existe.', 1;

  IF @docEst NOT IN (1, 4)
    THROW 59021, 'Solo se puede solicitar autorizacion desde ABIERTO o REVISAR.', 1;

  IF NOT EXISTS (
    SELECT 1
    FROM dbo.DET_ART_MERMA d
    WHERE d.DOCMER = @DOCMER
      AND ISNULL(d.BLOQ, 0) <> -1
  )
    THROW 59022, 'Documento sin articulos activos.', 1;

  IF EXISTS (
    SELECT 1
    FROM dbo.DET_ART_MERMA d
    WHERE d.DOCMER = @DOCMER
      AND ISNULL(d.BLOQ, 0) <> -1
      AND (ISNULL(d.CTD, 0) <= 0 OR d.MOT_M IS NULL)
  )
    THROW 59023, 'Todos los articulos deben tener cantidad > 0 y motivo.', 1;

  IF EXISTS (
    SELECT 1
    FROM dbo.DET_ART_MERMA d
    JOIN dbo.MOT_MERMA m ON m.ID = d.MOT_M
    WHERE d.DOCMER = @DOCMER
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(m.REQUIERE_EVIDENCIA, 0) = 1
      AND NOT EXISTS (
        SELECT 1 FROM dbo.MERMA_EVIDENCIA e
        WHERE LTRIM(RTRIM(ISNULL(e.IDPD, ''))) = LTRIM(RTRIM(ISNULL(d.IDPD, '')))
      )
  )
    THROW 59024, 'Existen articulos con motivo que requiere evidencia.', 1;

  UPDATE dbo.DOC_CTRL_MERMA
  SET ESTATS = 'PENDIENTE',
      ID_ESTATUS = 2,
      USER_R = @USER,
      FCNM = GETDATE()
  WHERE DOCMER = @DOCMER;

  SELECT TOP 1 * FROM dbo.DOC_CTRL_MERMA WHERE DOCMER = @DOCMER;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_merma_revisar
  @DOCMER NVARCHAR(50),
  @USER NVARCHAR(100),
  @OBS NVARCHAR(MAX)
AS
BEGIN
  SET NOCOUNT ON;

  IF LTRIM(RTRIM(ISNULL(@OBS, ''))) = ''
    THROW 59030, 'Observacion de revision es obligatoria.', 1;

  DECLARE @docEst INT;
  SELECT TOP 1 @docEst = ISNULL(ID_ESTATUS, CASE WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) IN ('PENDIENTE', 'AUTORIZADO') THEN 2 ELSE -1 END)
  FROM dbo.DOC_CTRL_MERMA
  WHERE DOCMER = @DOCMER;

  IF @docEst IS NULL
    THROW 59031, 'Documento no existe.', 1;
  IF @docEst <> 2
    THROW 59032, 'Solo se puede revisar un documento PENDIENTE.', 1;

  UPDATE dbo.DOC_CTRL_MERMA
  SET ESTATS = 'REVISAR',
      ID_ESTATUS = 4,
      USER_R = @USER,
      OBS_REV = @OBS,
      FCNM = GETDATE()
  WHERE DOCMER = @DOCMER;

  SELECT TOP 1 * FROM dbo.DOC_CTRL_MERMA WHERE DOCMER = @DOCMER;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_merma_contabilizar
  @DOCMER NVARCHAR(50),
  @USER NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  BEGIN TRY
    BEGIN TRANSACTION;

    DECLARE @docEst INT;
    DECLARE @docSuc NVARCHAR(50);
    DECLARE @docFND DATETIME;

    SELECT TOP 1
      @docEst = ISNULL(ID_ESTATUS, CASE WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) IN ('PENDIENTE', 'AUTORIZADO') THEN 2 ELSE -1 END),
      @docSuc = LTRIM(RTRIM(ISNULL(SUC, ''))),
      @docFND = FCND
    FROM dbo.DOC_CTRL_MERMA WITH (UPDLOCK, HOLDLOCK)
    WHERE DOCMER = @DOCMER;

    IF @docEst IS NULL
      THROW 59040, 'Documento no existe.', 1;

    IF @docEst <> 2
      THROW 59041, 'Solo se puede contabilizar un documento PENDIENTE.', 1;

    IF NOT EXISTS (
      SELECT 1 FROM dbo.DET_ART_MERMA
      WHERE DOCMER = @DOCMER
        AND ISNULL(BLOQ, 0) <> -1
    )
      THROW 59042, 'Documento sin articulos activos.', 1;

    DECLARE @clsm FLOAT;
    SELECT TOP 1 @clsm = CMOV
    FROM dbo.DAT_CMOV
    WHERE UPPER(LTRIM(RTRIM(ISNULL(RELACION, '')))) = 'MERMA'
      AND UPPER(LTRIM(RTRIM(ISNULL(MODULO, '')))) = 'INVENTARIO'
      AND UPPER(LTRIM(RTRIM(ISNULL(TIPO, '')))) = 'CARGO'
    ORDER BY CMOV ASC;

    IF @clsm IS NULL
      SET @clsm = 555;

    DECLARE @docMb51 BIGINT;
    SELECT @docMb51 = TRY_CONVERT(BIGINT, NDOC)
    FROM dbo.DAT_CMOV WITH (UPDLOCK, HOLDLOCK)
    WHERE CMOV = @clsm;

    IF @docMb51 IS NULL SET @docMb51 = 300000000;
    SET @docMb51 = @docMb51 + 1;

    UPDATE dbo.DAT_CMOV
    SET NDOC = @docMb51
    WHERE CMOV = @clsm;

    INSERT INTO dbo.DAT_MB51
      (IDPD, [USER], CLSM, DOCP, ART, CTDA, CTOT, FCND, FCNC, TXT, ALMACEN, VTAESP, SUC)
    SELECT
      CONVERT(NVARCHAR(36), NEWID()),
      @USER,
      @clsm,
      @DOCMER,
      LTRIM(RTRIM(ISNULL(d.ART, ''))),
      ISNULL(d.CTD, 0),
      ISNULL(d.CTD, 0) * ISNULL(TRY_CONVERT(FLOAT, d.CTO), 0),
      ISNULL(@docFND, GETDATE()),
      GETDATE(),
      CONCAT('MERMA DOC ', @DOCMER),
      '001',
      0,
      @docSuc
    FROM dbo.DET_ART_MERMA d
    WHERE d.DOCMER = @DOCMER
      AND ISNULL(d.BLOQ, 0) <> -1;

    UPDATE a
    SET a.STOCK = ISNULL(a.STOCK, 0) - ISNULL(d.CTD, 0)
    FROM dbo.DAT_ART a
    JOIN dbo.DET_ART_MERMA d
      ON LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
     AND LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @docSuc
    WHERE d.DOCMER = @DOCMER
      AND ISNULL(d.BLOQ, 0) <> -1;

    UPDATE m
    SET m.NARTS = agg.narts,
        m.TOTAL = agg.total,
        m.ESTATS = 'CONTABILIZADO',
        m.ID_ESTATUS = 5,
        m.FCNC = GETDATE(),
        m.USER_A = @USER,
        m.DOC_MB51 = CONVERT(NVARCHAR(50), @docMb51),
        m.FCNM = GETDATE()
    FROM dbo.DOC_CTRL_MERMA m
    CROSS APPLY (
      SELECT
        SUM(CASE WHEN ISNULL(x.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(x.CTD, 0) END) AS narts,
        SUM(CASE WHEN ISNULL(x.BLOQ, 0) = -1 THEN 0 ELSE ISNULL(x.CTD, 0) * ISNULL(x.CTO, 0) END) AS total
      FROM dbo.DET_ART_MERMA x
      WHERE x.DOCMER = m.DOCMER
    ) agg
    WHERE m.DOCMER = @DOCMER;

    DECLARE @negativos INT;
    SELECT @negativos = COUNT(1)
    FROM dbo.DAT_ART a
    JOIN dbo.DET_ART_MERMA d
      ON LTRIM(RTRIM(ISNULL(a.ART, ''))) = LTRIM(RTRIM(ISNULL(d.ART, '')))
     AND LTRIM(RTRIM(ISNULL(a.SUC, ''))) = @docSuc
    WHERE d.DOCMER = @DOCMER
      AND ISNULL(d.BLOQ, 0) <> -1
      AND ISNULL(a.STOCK, 0) < 0;

    COMMIT TRANSACTION;

    SELECT
      DOCMER,
      ESTATS,
      ID_ESTATUS,
      DOC_MB51,
      NARTS,
      TOTAL,
      FCNC,
      ISNULL(@negativos, 0) AS STOCK_NEGATIVO_ITEMS
    FROM dbo.DOC_CTRL_MERMA
    WHERE DOCMER = @DOCMER;
  END TRY
  BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
  END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_merma_anular
  @DOCMER NVARCHAR(50),
  @USER NVARCHAR(100),
  @OBS NVARCHAR(MAX)
AS
BEGIN
  SET NOCOUNT ON;

  IF LTRIM(RTRIM(ISNULL(@OBS, ''))) = ''
    THROW 59050, 'Observacion de anulacion es obligatoria.', 1;

  DECLARE @docEst INT;
  SELECT TOP 1 @docEst = ISNULL(ID_ESTATUS, CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) = 'ABIERTO' THEN 1
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) IN ('PENDIENTE', 'AUTORIZADO') THEN 2
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) IN ('REVISAR', 'REVISION') THEN 4
      ELSE -1
    END)
  FROM dbo.DOC_CTRL_MERMA
  WHERE DOCMER = @DOCMER;

  IF @docEst IS NULL
    THROW 59051, 'Documento no existe.', 1;

  IF @docEst NOT IN (1, 2, 4)
    THROW 59052, 'Solo se puede anular documento ABIERTO/PENDIENTE/REVISAR.', 1;

  UPDATE dbo.DOC_CTRL_MERMA
  SET ESTATS = 'ANULADO',
      ID_ESTATUS = 3,
      USER_A = @USER,
      OBS_ANUL = @OBS,
      FCNM = GETDATE()
  WHERE DOCMER = @DOCMER;

  SELECT TOP 1 * FROM dbo.DOC_CTRL_MERMA WHERE DOCMER = @DOCMER;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_merma_auditar
  @DOCMER NVARCHAR(50),
  @USER NVARCHAR(100),
  @OBS_AUDIT NVARCHAR(MAX),
  @CONFIRM_FISICA BIT = 1
AS
BEGIN
  SET NOCOUNT ON;

  IF ISNULL(@CONFIRM_FISICA, 0) = 0
    THROW 59060, 'Debe confirmar revision fisica.', 1;

  DECLARE @docEst INT;
  SELECT TOP 1 @docEst = ISNULL(ID_ESTATUS, CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATS, '')))) IN ('CONTABILIZADO', 'COTABILIZADO', 'COTIBILIZADO', 'PROCESADO') THEN 5
      ELSE -1
    END)
  FROM dbo.DOC_CTRL_MERMA
  WHERE DOCMER = @DOCMER;

  IF @docEst IS NULL
    THROW 59061, 'Documento no existe.', 1;

  IF @docEst <> 5
    THROW 59062, 'Solo se puede auditar documento CONTABILIZADO.', 1;

  UPDATE dbo.DOC_CTRL_MERMA
  SET ESTATS = 'AUDITADO',
      ID_ESTATUS = 6,
      FCNAUD = GETDATE(),
      USER_AUD = @USER,
      OBS_AUDIT = @OBS_AUDIT,
      FCNM = GETDATE()
  WHERE DOCMER = @DOCMER;

  SELECT TOP 1 * FROM dbo.DOC_CTRL_MERMA WHERE DOCMER = @DOCMER;
END;
GO
