IF COL_LENGTH('dbo.TRAN_EVID', 'DOC') IS NULL
BEGIN
  ALTER TABLE dbo.TRAN_EVID ADD DOC NVARCHAR(20) NULL;
END;

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_TRAN_EVID_DOC'
    AND object_id = OBJECT_ID('dbo.TRAN_EVID')
)
BEGIN
  CREATE INDEX IX_TRAN_EVID_DOC ON dbo.TRAN_EVID (DOC, FCN DESC, ID DESC);
END;
