/*
  Saneamiento facturación después de devoluciones PV
  Fecha: 2026-03-20

  Objetivo:
  - Depurar registros de facturación ligados al folio de devolución (IDFOLDEV),
    ya que no deben existir en FAC_SVR_SHAP/FACT_TICKET_SHP.
  - Re-sincronizar FAC_SVR_SHAP / FACT_TICKET_SHP para folios origen con devolución,
    usando dbo.sp_fact_sync_folio_vf.
  - Procesar únicamente folios elegibles para facturación:
      AUT='VF' y REQF/RQFAC=1.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID('dbo.sp_fact_sync_folio_vf', 'P') IS NULL
  THROW 51080, 'No existe dbo.sp_fact_sync_folio_vf. Ejecute sql/sp_fact_sync_folio_vf_create.sql', 1;

IF OBJECT_ID('dbo.FACT_IDFOLDEV', 'U') IS NULL
  THROW 51081, 'No existe dbo.FACT_IDFOLDEV', 1;

IF OBJECT_ID('dbo.PV_CTR_FOL_ASVR', 'U') IS NULL
  THROW 51083, 'No existe dbo.PV_CTR_FOL_ASVR', 1;

DECLARE @colFolioOrig SYSNAME = NULL;
DECLARE @colFolioDev SYSNAME = NULL;

IF COL_LENGTH('dbo.FACT_IDFOLDEV', 'IDFOLDEV') IS NOT NULL
  SET @colFolioDev = 'IDFOLDEV';

IF COL_LENGTH('dbo.FACT_IDFOLDEV', 'IDFOL_OR') IS NOT NULL
  SET @colFolioOrig = 'IDFOL_OR';
ELSE IF COL_LENGTH('dbo.FACT_IDFOLDEV', 'IDFOLORIG') IS NOT NULL
  SET @colFolioOrig = 'IDFOLORIG';
ELSE IF COL_LENGTH('dbo.FACT_IDFOLDEV', 'IDFOL_ORIG') IS NOT NULL
  SET @colFolioOrig = 'IDFOL_ORIG';

IF @colFolioOrig IS NULL
  THROW 51082, 'FACT_IDFOLDEV no contiene columna de folio origen (IDFOL_OR/IDFOLORIG/IDFOL_ORIG)', 1;

DECLARE @colReqf SYSNAME = NULL;
IF COL_LENGTH('dbo.PV_CTR_FOL_ASVR', 'REQF') IS NOT NULL
  SET @colReqf = 'REQF';
ELSE IF COL_LENGTH('dbo.PV_CTR_FOL_ASVR', 'RQFAC') IS NOT NULL
  SET @colReqf = 'RQFAC';

IF @colReqf IS NULL
  THROW 51084, 'PV_CTR_FOL_ASVR no contiene REQF/RQFAC', 1;

IF OBJECT_ID('tempdb..#FOLIOS_DEV') IS NOT NULL
  DROP TABLE #FOLIOS_DEV;
CREATE TABLE #FOLIOS_DEV (
  IDFOL NVARCHAR(255) NOT NULL PRIMARY KEY
);

DECLARE @detallesDevDepurados INT = 0;
DECLARE @cabecerasDevDepuradas INT = 0;

IF @colFolioDev IS NOT NULL
BEGIN
  DECLARE @sqlDev NVARCHAR(MAX) = N'
  INSERT INTO #FOLIOS_DEV (IDFOL)
  SELECT DISTINCT LTRIM(RTRIM(CONVERT(NVARCHAR(255), D.' + QUOTENAME(@colFolioDev) + N')))
  FROM dbo.FACT_IDFOLDEV D
  WHERE LTRIM(RTRIM(ISNULL(CONVERT(NVARCHAR(255), D.' + QUOTENAME(@colFolioDev) + N'), ''''))) <> '''';';

  EXEC sys.sp_executesql @sqlDev;
END;

IF EXISTS (SELECT 1 FROM #FOLIOS_DEV)
  AND OBJECT_ID('dbo.FACT_TICKET_SHP', 'U') IS NOT NULL
  AND COL_LENGTH('dbo.FACT_TICKET_SHP', 'IDFOL') IS NOT NULL
BEGIN
  DELETE D
  FROM dbo.FACT_TICKET_SHP D
  INNER JOIN #FOLIOS_DEV F
    ON LTRIM(RTRIM(ISNULL(CONVERT(NVARCHAR(255), D.IDFOL), ''))) = F.IDFOL;

  SET @detallesDevDepurados = @@ROWCOUNT;
END;

IF EXISTS (SELECT 1 FROM #FOLIOS_DEV)
  AND OBJECT_ID('dbo.FAC_SVR_SHAP', 'U') IS NOT NULL
  AND COL_LENGTH('dbo.FAC_SVR_SHAP', 'IDFOL') IS NOT NULL
BEGIN
  DELETE H
  FROM dbo.FAC_SVR_SHAP H
  INNER JOIN #FOLIOS_DEV F
    ON LTRIM(RTRIM(ISNULL(CONVERT(NVARCHAR(255), H.IDFOL), ''))) = F.IDFOL;

  SET @cabecerasDevDepuradas = @@ROWCOUNT;
END;

IF OBJECT_ID('tempdb..#FOLIOS_SYNC') IS NOT NULL
  DROP TABLE #FOLIOS_SYNC;
CREATE TABLE #FOLIOS_SYNC (
  IDFOL NVARCHAR(255) NOT NULL PRIMARY KEY
);

DECLARE @sql NVARCHAR(MAX) = N'
INSERT INTO #FOLIOS_SYNC (IDFOL)
SELECT DISTINCT LTRIM(RTRIM(CONVERT(NVARCHAR(255), D.' + QUOTENAME(@colFolioOrig) + N')))
FROM dbo.FACT_IDFOLDEV D
INNER JOIN dbo.PV_CTR_FOL_ASVR F
  ON LTRIM(RTRIM(ISNULL(F.IDFOL, ''''))) = LTRIM(RTRIM(ISNULL(CONVERT(NVARCHAR(255), D.' + QUOTENAME(@colFolioOrig) + N'), '''')))
WHERE LTRIM(RTRIM(ISNULL(CONVERT(NVARCHAR(255), D.' + QUOTENAME(@colFolioOrig) + N'), ''''))) <> ''''
  AND UPPER(LTRIM(RTRIM(ISNULL(F.AUT, '''')))) = ''VF''
  AND TRY_CONVERT(INT, F.' + QUOTENAME(@colReqf) + N') = 1'
  + CASE
      WHEN COL_LENGTH('dbo.FACT_IDFOLDEV', 'TIPOT') IS NOT NULL
        THEN N' AND UPPER(LTRIM(RTRIM(ISNULL(D.TIPOT, '''')))) = ''DF'''
      ELSE N''
    END + N';';

EXEC sys.sp_executesql @sql;

IF OBJECT_ID('tempdb..#SYNC_RESULT') IS NOT NULL
  DROP TABLE #SYNC_RESULT;
CREATE TABLE #SYNC_RESULT (
  IDFOL NVARCHAR(255) NULL,
  AUT NVARCHAR(20) NULL,
  REQF INT NULL,
  SUBTOTAL MONEY NULL,
  IVA MONEY NULL,
  IMPT MONEY NULL,
  ESTATUS NVARCHAR(40) NULL,
  DETAIL_ROWS INT NULL,
  TRAMISION_ROWS INT NULL,
  SYNC_APPLIED BIT NULL,
  EVENTO NVARCHAR(40) NULL,
  ERROR_MSG NVARCHAR(1000) NULL
);

DECLARE @idfol NVARCHAR(255);
DECLARE cur CURSOR LOCAL FAST_FORWARD FOR
  SELECT IDFOL
  FROM #FOLIOS_SYNC
  ORDER BY IDFOL;

OPEN cur;
FETCH NEXT FROM cur INTO @idfol;

WHILE @@FETCH_STATUS = 0
BEGIN
  BEGIN TRY
    INSERT INTO #SYNC_RESULT (
      IDFOL,
      AUT,
      REQF,
      SUBTOTAL,
      IVA,
      IMPT,
      ESTATUS,
      DETAIL_ROWS,
      TRAMISION_ROWS,
      SYNC_APPLIED,
      EVENTO
    )
    EXEC dbo.sp_fact_sync_folio_vf
      @IDFOL = @idfol,
      @EVENTO = 'PV_DEV_REPAIR',
      @FORCE = 0;
  END TRY
  BEGIN CATCH
    INSERT INTO #SYNC_RESULT (IDFOL, ERROR_MSG)
    VALUES (@idfol, ERROR_MESSAGE());
  END CATCH;

  FETCH NEXT FROM cur INTO @idfol;
END;

CLOSE cur;
DEALLOCATE cur;

SELECT
  (SELECT COUNT(1) FROM #FOLIOS_DEV) AS FOLIOS_DEV_IDENTIFICADOS,
  @detallesDevDepurados AS DETALLE_DEV_DEPURADO,
  @cabecerasDevDepuradas AS CABECERA_DEV_DEPURADA,
  (SELECT COUNT(1) FROM #FOLIOS_SYNC) AS FOLIOS_ELEGIBLES,
  COUNT(1) AS FOLIOS_PROCESADOS,
  SUM(CASE WHEN ISNULL(SYNC_APPLIED, 0) = 1 THEN 1 ELSE 0 END) AS FOLIOS_SYNC_APLICADO,
  SUM(CASE WHEN ISNULL(SYNC_APPLIED, 0) = 0 THEN 1 ELSE 0 END) AS FOLIOS_SYNC_NO_APLICADO,
  SUM(CASE WHEN ISNULL(ERROR_MSG, '') <> '' THEN 1 ELSE 0 END) AS FOLIOS_CON_ERROR
FROM #SYNC_RESULT;

SELECT
  TOP (200)
  IDFOL,
  AUT,
  REQF,
  ESTATUS,
  IMPT,
  DETAIL_ROWS,
  SYNC_APPLIED,
  EVENTO,
  ERROR_MSG
FROM #SYNC_RESULT
WHERE ISNULL(ERROR_MSG, '') <> ''
ORDER BY IDFOL;
