/*
  2026-04-19
  Correccion solicitada: usar campo (no tabla) para diferencia economica.
  - Agrega DIFERENCIA_ECONOMICA en dbo.PV_ORD_CAMBIO_MERMA_TMP
  - Migra datos desde dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL (si existe)
  - Elimina dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL
*/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF COL_LENGTH('dbo.PV_ORD_CAMBIO_MERMA_TMP', 'DIFERENCIA_ECONOMICA') IS NULL
BEGIN
  ALTER TABLE dbo.PV_ORD_CAMBIO_MERMA_TMP
    ADD DIFERENCIA_ECONOMICA FLOAT NULL;
END;
GO

IF OBJECT_ID('dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL', 'U') IS NOT NULL
BEGIN
  UPDATE t
  SET t.DIFERENCIA_ECONOMICA = COALESCE(
    t.DIFERENCIA_ECONOMICA,
    TRY_CONVERT(FLOAT, d.DIFERENCIA_ECONOMICA)
  )
  FROM dbo.PV_ORD_CAMBIO_MERMA_TMP t
  INNER JOIN dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL d
    ON UPPER(LTRIM(RTRIM(ISNULL(t.IORD, '')))) = UPPER(LTRIM(RTRIM(ISNULL(d.IORD_ORIG, ''))))
   AND TRY_CONVERT(INT, t.TIPOM) = TRY_CONVERT(INT, d.TIPOM);

  DROP TABLE dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL;
END;
GO
