SET NOCOUNT ON;

DECLARE @Now DATETIME = GETDATE();

WITH SourceFlows AS (
  SELECT
    TRY_CONVERT(FLOAT, ESTA) AS ESTA,
    TRY_CONVERT(BIT, SOLO_EXTERNO) AS SOLO_EXTERNO,
    ISNULL(ORDEN, TRY_CONVERT(INT, TRY_CONVERT(FLOAT, ESTA) * 10)) AS ORDEN
  FROM dbo.DAT_JAO_ORD_FLUJO_VIS
  WHERE UPPER(LTRIM(RTRIM(ISNULL(MODULO, '')))) = 'DAT_JAO_ORD'
    AND UPPER(LTRIM(RTRIM(ISNULL(PANEL_MODE, '')))) = 'OPERATIVO'
    AND UPPER(LTRIM(RTRIM(ISNULL(ROLE_CODE, '')))) = 'ANALISTA_ORD'
    AND ISNULL(ACTIVO, 1) = 1
), TargetRoles AS (
  SELECT 'ANALISTA_INV' AS ROLE_CODE
  UNION ALL
  SELECT 'INVJEF' AS ROLE_CODE
), UpsertSource AS (
  SELECT
    'DAT_JAO_ORD' AS MODULO,
    'operativo' AS PANEL_MODE,
    tr.ROLE_CODE,
    sf.ESTA,
    sf.SOLO_EXTERNO,
    sf.ORDEN
  FROM SourceFlows sf
  CROSS JOIN TargetRoles tr
)
MERGE dbo.DAT_JAO_ORD_FLUJO_VIS AS target
USING UpsertSource AS source
  ON UPPER(LTRIM(RTRIM(ISNULL(target.MODULO, '')))) = UPPER(source.MODULO)
 AND UPPER(LTRIM(RTRIM(ISNULL(target.PANEL_MODE, '')))) = UPPER(source.PANEL_MODE)
 AND UPPER(LTRIM(RTRIM(ISNULL(target.ROLE_CODE, '')))) = UPPER(source.ROLE_CODE)
 AND TRY_CONVERT(FLOAT, target.ESTA) = source.ESTA
WHEN MATCHED THEN
  UPDATE SET
    target.SOLO_EXTERNO = source.SOLO_EXTERNO,
    target.ACTIVO = 1,
    target.ORDEN = source.ORDEN,
    target.FCMOD = @Now
WHEN NOT MATCHED BY TARGET THEN
  INSERT (MODULO, PANEL_MODE, ROLE_CODE, ESTA, SOLO_EXTERNO, ACTIVO, ORDEN, FCREG, FCMOD)
  VALUES (source.MODULO, source.PANEL_MODE, source.ROLE_CODE, source.ESTA, source.SOLO_EXTERNO, 1, source.ORDEN, @Now, @Now);

SELECT
  ROLE_CODE,
  PANEL_MODE,
  ESTA,
  SOLO_EXTERNO,
  ACTIVO,
  ORDEN
FROM dbo.DAT_JAO_ORD_FLUJO_VIS
WHERE UPPER(LTRIM(RTRIM(ISNULL(MODULO, '')))) = 'DAT_JAO_ORD'
  AND UPPER(LTRIM(RTRIM(ISNULL(PANEL_MODE, '')))) = 'OPERATIVO'
  AND UPPER(LTRIM(RTRIM(ISNULL(ROLE_CODE, '')))) IN ('ANALISTA_INV', 'INVJEF')
ORDER BY ROLE_CODE, TRY_CONVERT(FLOAT, ESTA);
