SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

BEGIN TRAN;
DECLARE @lock int;
EXEC @lock=sys.sp_getapplock
  @Resource='DAT_REC_ELIMINAR_OC_PRUEBA_450002277',
  @LockMode='Exclusive',
  @LockOwner='Transaction',
  @LockTimeout=15000;
IF @lock<0 THROW 51000,'No fue posible bloquear la eliminación de la O.C. de prueba.',1;

DECLARE @nped nvarchar(510)=N'450002277';
IF NOT EXISTS(
  SELECT 1 FROM dbo.REC_CAB_PED
  WHERE NPED=@nped AND SUC='DF01' AND ESTATUS='PROCESADO'
)
  THROW 51000,'La O.C. de prueba no existe o ya cambió de estado.',1;

IF EXISTS(
  SELECT 1 FROM dbo.REC_DET_PED
  WHERE NPED=@nped AND (ISNULL(CTDREC,0)<>0 OR DREC IS NOT NULL)
)
  THROW 51000,'La O.C. aún contiene cantidades recibidas o documentos activos.',1;

IF EXISTS(
  SELECT 1 FROM dbo.REC_CTRL_DOC_REC
  WHERE NPED=@nped AND ESTATUS_REC<>'RECHAZADO'
)
  THROW 51000,'La O.C. contiene una recepción que no está rechazada.',1;

DECLARE @docs table(DOCREC nvarchar(510) NOT NULL);
INSERT @docs(DOCREC)
SELECT DOCREC FROM dbo.REC_CTRL_DOC_REC WHERE NPED=@nped;

DELETE dbo.REC_GUIA_PED WHERE DOCREC IN (SELECT DOCREC FROM @docs);
DELETE dbo.REC_INCI_PED WHERE DOCREC IN (SELECT DOCREC FROM @docs);
DELETE dbo.REC_CTO_HIST WHERE DOCREC IN (SELECT DOCREC FROM @docs);
DELETE dbo.AUDIT_LOG
WHERE MODULO='DAT_REC'
  AND (
    ENTIDAD_ID=@nped
    OR ENTIDAD_ID IN (SELECT DOCREC FROM @docs)
  );
DELETE dbo.REC_CTRL_DOC_REC WHERE NPED=@nped;
DELETE dbo.REC_BORRADOR_REC_DET WHERE NPED=@nped;
DELETE dbo.REC_BORRADOR_REC WHERE NPED=@nped;
DELETE dbo.REC_DET_PED WHERE NPED=@nped;
DELETE dbo.REC_CAB_PED WHERE NPED=@nped;

COMMIT;
SELECT @nped NPED_ELIMINADO;
GO
