/*
  Marca de promocion aplicada por renglon en PV_TICKET_LOG.
  Permite separar impresion de ART_GRATIS en ticket independiente.
*/
USE IOELOCAL;
GO

IF COL_LENGTH('dbo.PV_TICKET_LOG', 'IDPROMO') IS NULL
BEGIN
  ALTER TABLE dbo.PV_TICKET_LOG
    ADD IDPROMO INT NULL;
END
GO

IF COL_LENGTH('dbo.PV_TICKET_LOG', 'TIPOPROMO') IS NULL
BEGIN
  ALTER TABLE dbo.PV_TICKET_LOG
    ADD TIPOPROMO NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PV_TICKET_LOG')
    AND name = 'IX_PV_TICKET_LOG_IDFOL_TIPOPROMO'
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_PV_TICKET_LOG_IDFOL_TIPOPROMO
    ON dbo.PV_TICKET_LOG (IDFOL, TIPOPROMO)
    INCLUDE (ID, ART, UPC, DES, CTD, PVTA, PVTAT, ORD, IDPROMO);
END
GO

