IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_DAT_MB51_SUC_FCND_CLSM_ART'
    AND object_id = OBJECT_ID('dbo.DAT_MB51')
)
BEGIN
  CREATE INDEX IX_DAT_MB51_SUC_FCND_CLSM_ART
  ON dbo.DAT_MB51 (SUC, FCND, CLSM, ART)
  INCLUDE (CTDA);
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_sugeridos_calcular
  @SUC NVARCHAR(20),
  @PROV INT = NULL,
  @MARCA NVARCHAR(100) = NULL,
  @TIPO NVARCHAR(80) = NULL,
  @DEPA FLOAT = NULL,
  @SUBD FLOAT = NULL,
  @CLAS FLOAT = NULL,
  @SCLA FLOAT = NULL,
  @SCLA2 FLOAT = NULL,
  @DIAS INT = 90
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @sucNorm NVARCHAR(20) = UPPER(LTRIM(RTRIM(ISNULL(@SUC, N''))));
  DECLARE @sucMov VARCHAR(20) = CONVERT(VARCHAR(20), @sucNorm);
  DECLARE @marcaNorm NVARCHAR(100) = UPPER(LTRIM(RTRIM(ISNULL(@MARCA, N''))));
  DECLARE @tipoNorm NVARCHAR(80) = UPPER(LTRIM(RTRIM(ISNULL(@TIPO, N''))));

  IF @sucNorm = N''
  BEGIN
    THROW 51000, 'La sucursal es requerida para calcular sugeridos.', 1;
  END;

  IF @DIAS IS NULL OR @DIAS <= 0 SET @DIAS = 90;

  DECLARE @fechaHasta DATETIME = CONVERT(DATETIME, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1));
  DECLARE @fechaDesde DATETIME = DATEADD(DAY, -@DIAS, @fechaHasta);

  CREATE TABLE #art_base (
    ART NVARCHAR(510) NOT NULL,
    SUC NVARCHAR(20) NOT NULL,
    TIPO NVARCHAR(510) NULL,
    UPC NVARCHAR(510) NULL,
    DES NVARCHAR(510) NULL,
    BASE NVARCHAR(510) NULL,
    SPH FLOAT NULL,
    CYL FLOAT NULL,
    ADIC FLOAT NULL,
    STOCK_MIN FLOAT NOT NULL,
    ESTATUS NVARCHAR(510) NULL,
    DIA_REABASTO FLOAT NOT NULL,
    PVTA MONEY NULL,
    CTOP MONEY NULL,
    PROV_1 FLOAT NULL,
    CTO_PROV1 MONEY NULL,
    PROV_2 FLOAT NULL,
    CTO_PROV2 MONEY NULL,
    PROV_3 FLOAT NULL,
    CTO_PROV3 MONEY NULL,
    UN_COMP NVARCHAR(510) NULL,
    FACT_COMP FLOAT NOT NULL,
    MARCA NVARCHAR(510) NULL,
    DEPA FLOAT NULL,
    SUBD FLOAT NULL,
    CLAS FLOAT NULL,
    SCLA FLOAT NULL,
    SCLA2 FLOAT NULL
  );

  INSERT INTO #art_base (
    ART, SUC, TIPO, UPC, DES, BASE, SPH, CYL, ADIC, STOCK_MIN, ESTATUS,
    DIA_REABASTO, PVTA, CTOP, PROV_1, CTO_PROV1, PROV_2, CTO_PROV2,
    PROV_3, CTO_PROV3, UN_COMP, FACT_COMP, MARCA, DEPA, SUBD, CLAS, SCLA, SCLA2
  )
  SELECT
    LTRIM(RTRIM(ISNULL(a.ART, N''))) AS ART,
    UPPER(LTRIM(RTRIM(ISNULL(a.SUC, N'')))) AS SUC,
    a.TIPO,
    a.UPC,
    a.DES,
    a.BASE,
    TRY_CONVERT(FLOAT, a.SPH),
    TRY_CONVERT(FLOAT, a.CYL),
    TRY_CONVERT(FLOAT, a.ADIC),
    ISNULL(TRY_CONVERT(FLOAT, a.STOCK_MIN), 0),
    UPPER(LTRIM(RTRIM(ISNULL(a.ESTATUS, N'')))),
    ISNULL(TRY_CONVERT(FLOAT, a.DIA_REABASTO), 0),
    TRY_CONVERT(MONEY, a.PVTA),
    TRY_CONVERT(MONEY, a.CTOP),
    TRY_CONVERT(FLOAT, a.PROV_1),
    TRY_CONVERT(MONEY, a.CTO_PROV1),
    TRY_CONVERT(FLOAT, a.PROV_2),
    TRY_CONVERT(MONEY, a.CTO_PROV2),
    TRY_CONVERT(FLOAT, a.PROV_3),
    TRY_CONVERT(MONEY, a.CTO_PROV3),
    a.UN_COMP,
    CASE WHEN ISNULL(TRY_CONVERT(FLOAT, a.FACT_COMP), 0) <= 0 THEN 1 ELSE TRY_CONVERT(FLOAT, a.FACT_COMP) END,
    a.MARCA,
    TRY_CONVERT(FLOAT, a.DEPA),
    TRY_CONVERT(FLOAT, a.SUBD),
    TRY_CONVERT(FLOAT, a.CLAS),
    TRY_CONVERT(FLOAT, a.SCLA),
    TRY_CONVERT(FLOAT, a.SCLA2)
  FROM dbo.DAT_ART a
  WHERE a.SUC = @sucNorm
    AND ISNULL(a.BLOQ, 0) <> -1
    AND (@marcaNorm = N'' OR UPPER(LTRIM(RTRIM(ISNULL(a.MARCA, N'')))) LIKE N'%' + @marcaNorm + N'%')
    AND (@tipoNorm = N'' OR UPPER(LTRIM(RTRIM(ISNULL(a.TIPO, N'')))) = @tipoNorm)
    AND (@DEPA IS NULL OR TRY_CONVERT(FLOAT, a.DEPA) = @DEPA)
    AND (@SUBD IS NULL OR TRY_CONVERT(FLOAT, a.SUBD) = @SUBD)
    AND (@CLAS IS NULL OR TRY_CONVERT(FLOAT, a.CLAS) = @CLAS)
    AND (@SCLA IS NULL OR TRY_CONVERT(FLOAT, a.SCLA) = @SCLA)
    AND (@SCLA2 IS NULL OR TRY_CONVERT(FLOAT, a.SCLA2) = @SCLA2)
    AND (
      @PROV IS NULL
      OR TRY_CONVERT(INT, a.PROV_1) = @PROV
      OR TRY_CONVERT(INT, a.PROV_2) = @PROV
      OR TRY_CONVERT(INT, a.PROV_3) = @PROV
    );

  CREATE INDEX IX_art_base_art ON #art_base (ART);

  CREATE TABLE #art_keys (
    ART NVARCHAR(510) NOT NULL PRIMARY KEY
  );

  INSERT INTO #art_keys (ART)
  SELECT DISTINCT ART
  FROM #art_base
  WHERE ART <> N'';

  CREATE TABLE #cmov_vtas (
    CLSM FLOAT NOT NULL PRIMARY KEY
  );

  INSERT INTO #cmov_vtas (CLSM)
  SELECT DISTINCT CMOV
  FROM dbo.DAT_CMOV
  WHERE UPPER(LTRIM(RTRIM(ISNULL(RELACION, N'')))) = N'VTAS'
    AND CMOV IS NOT NULL;

  CREATE TABLE #stock (
    ART NVARCHAR(510) NOT NULL PRIMARY KEY,
    STOCK FLOAT NOT NULL
  );

  INSERT INTO #stock (ART, STOCK)
  SELECT
    m.ART,
    SUM(ISNULL(m.CTDA, 0)) AS STOCK
  FROM dbo.DAT_MB51 m
  INNER JOIN #art_keys k ON k.ART = m.ART
  WHERE m.SUC = @sucMov
  GROUP BY m.ART;

  CREATE TABLE #ventas (
    ART NVARCHAR(510) NOT NULL PRIMARY KEY,
    VTA_90 FLOAT NOT NULL
  );

  INSERT INTO #ventas (ART, VTA_90)
  SELECT
    m.ART,
    SUM(ISNULL(m.CTDA, 0) * -1) AS VTA_90
  FROM dbo.DAT_MB51 m
  INNER JOIN #art_keys k ON k.ART = m.ART
  INNER JOIN #cmov_vtas v ON v.CLSM = m.CLSM
  WHERE m.SUC = @sucMov
    AND m.FCND >= @fechaDesde
    AND m.FCND < @fechaHasta
  GROUP BY m.ART;

  ;WITH base AS (
    SELECT
      LTRIM(RTRIM(CONCAT(
        ISNULL(NULLIF(LTRIM(RTRIM(jd.DDEPA)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(js.DSUBD)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(jc.DCLAS)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(jsc.DSCLA)), N'') + N' ', N''),
        ISNULL(NULLIF(LTRIM(RTRIM(js2.DSCLA2)), N''), N'')
      ))) AS DESCRIPCION_LARGA_JERARQUIA,
      a.*,
      ISNULL(s.STOCK, 0) AS STOCK,
      ISNULL(v.VTA_90, 0) AS VTA_90
    FROM #art_base a
    LEFT JOIN #stock s ON s.ART = a.ART
    LEFT JOIN #ventas v ON v.ART = a.ART
    LEFT JOIN dbo.JRQ_DEPA jd ON jd.DEPA = a.DEPA
    LEFT JOIN dbo.JRQ_SUBD js ON js.SUBD = a.SUBD AND js.DEPA = a.DEPA
    LEFT JOIN dbo.JRQ_CLAS jc ON jc.CLAS = a.CLAS AND jc.SUBD = a.SUBD
    LEFT JOIN dbo.JRQ_SCLA jsc ON jsc.SCLA = a.SCLA AND jsc.CLAS = a.CLAS
    LEFT JOIN dbo.JRQ_SCLA2 js2 ON js2.SCLA2 = a.SCLA2 AND js2.SCLA = a.SCLA
  ),
  proveedor AS (
    SELECT b.*, p.NIVEL_PROV, p.NPROV, p.CTO
    FROM base b
    CROSS APPLY (VALUES
      (1, TRY_CONVERT(INT, b.PROV_1), b.CTO_PROV1),
      (2, TRY_CONVERT(INT, b.PROV_2), b.CTO_PROV2),
      (3, TRY_CONVERT(INT, b.PROV_3), b.CTO_PROV3)
    ) p(NIVEL_PROV, NPROV, CTO)
    WHERE p.NPROV IS NOT NULL
      AND p.CTO IS NOT NULL
      AND (@PROV IS NULL OR p.NPROV = @PROV)
  ),
  calc AS (
    SELECT
      p.*,
      ROUND(p.VTA_90 / @DIAS, 4) AS FACT_VTA_P_D,
      CASE WHEN p.VTA_90 <= 0 THEN 0 ELSE ROUND(p.STOCK / NULLIF(p.VTA_90 / @DIAS, 0), 2) END AS DIAS_INV
    FROM proveedor p
  ),
  sugerido AS (
    SELECT
      c.*,
      ROUND(c.DIA_REABASTO - c.DIAS_INV, 2) AS FAC_REAB,
      ROUND(CASE WHEN c.DIA_REABASTO - c.DIAS_INV <= 0 THEN 0 ELSE ((c.DIA_REABASTO - c.DIAS_INV) * c.FACT_VTA_P_D) / c.FACT_COMP END, 2) AS SUG
    FROM calc c
  ),
  final AS (
    SELECT
      *,
      CASE WHEN STOCK_MIN - STOCK <= 0 THEN 0 ELSE CEILING(STOCK_MIN - STOCK) / FACT_COMP END AS PEDIDO,
      CASE
        WHEN ESTATUS = 'NO RESURTIBLE' THEN 0
        WHEN ESTATUS = 'FIJO' THEN CASE WHEN STOCK_MIN - (STOCK / FACT_COMP) <= 0 THEN 0 ELSE CEILING(STOCK_MIN - (STOCK / FACT_COMP)) END
        WHEN FAC_REAB <= 0 THEN 0
        WHEN SUG <= 0 THEN CASE WHEN STOCK >= STOCK_MIN THEN 0 ELSE CEILING(STOCK_MIN - STOCK) END
        ELSE CEILING(SUG)
      END AS CANT_FINAL_COMPRA
    FROM sugerido
  )
  SELECT
    DESCRIPCION_LARGA_JERARQUIA,
    SUC,
    TIPO,
    ART,
    UPC,
    DES,
    BASE,
    SPH,
    CYL,
    ADIC,
    STOCK,
    STOCK_MIN,
    ESTATUS,
    DIA_REABASTO,
    PVTA,
    CTOP,
    NPROV,
    NIVEL_PROV,
    CTO,
    UN_COMP,
    FACT_COMP,
    VTA_90,
    FACT_VTA_P_D,
    DIAS_INV,
    FAC_REAB,
    SUG,
    PEDIDO,
    CANT_FINAL_COMPRA AS PED,
    CANT_FINAL_COMPRA,
    TRY_CONVERT(MONEY, CANT_FINAL_COMPRA * CTO) AS IMPORTE
  FROM final
  WHERE CANT_FINAL_COMPRA > 0
  ORDER BY NPROV, DES, ART
  OPTION (RECOMPILE);
END;
GO
