/* Ajuste 2026-03-23:
   - Visibilidad por rol basada en ESTSEGU (panel operativo/anulados/entregadas)
   - Criterio operativo con ESTATUS=2
   - Estados nuevos/actualizados: 3.1 EDITANDO, 9.2 REGRESADO PARA CAMBIO, 12 GARANTIA
*/

SET NOCOUNT ON;

IF OBJECT_ID('dbo.DAT_EST_ORD', 'U') IS NOT NULL
BEGIN
  UPDATE dbo.DAT_EST_ORD
  SET TIPO = 'EDITANDO'
  WHERE TRY_CONVERT(FLOAT, ESTA) = 3.1;

  IF NOT EXISTS (SELECT 1 FROM dbo.DAT_EST_ORD WHERE TRY_CONVERT(FLOAT, ESTA) = 3.1)
    INSERT INTO dbo.DAT_EST_ORD (ESTA, TIPO) VALUES (3.1, 'EDITANDO');

  UPDATE dbo.DAT_EST_ORD
  SET TIPO = 'REGRESADO PARA CAMBIO'
  WHERE TRY_CONVERT(FLOAT, ESTA) = 9.2;

  IF NOT EXISTS (SELECT 1 FROM dbo.DAT_EST_ORD WHERE TRY_CONVERT(FLOAT, ESTA) = 9.2)
    INSERT INTO dbo.DAT_EST_ORD (ESTA, TIPO) VALUES (9.2, 'REGRESADO PARA CAMBIO');

  UPDATE dbo.DAT_EST_ORD
  SET TIPO = 'ENTREGADA A CLIENTE'
  WHERE TRY_CONVERT(FLOAT, ESTA) = 11;

  UPDATE dbo.DAT_EST_ORD
  SET TIPO = 'GARANTIA'
  WHERE TRY_CONVERT(FLOAT, ESTA) = 12;
END;
GO

/* Normaliza históricos al criterio ESTATUS=2 (pago confirmado en cotización) */
IF OBJECT_ID('dbo.PV_CTR_ORDS', 'U') IS NOT NULL
BEGIN
  UPDATE dbo.PV_CTR_ORDS
  SET ESTATUS = 2
  WHERE TRY_CONVERT(FLOAT, ESTSEGU) IN (2, 3, 3.1, 4, 5, 6, 7, 8, 9, 9.1, 9.2, 10, 11, 12)
    AND TRY_CONVERT(INT, ESTATUS) <> 2;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_ordenes_trabajo_panel
  @IORD NVARCHAR(255) = NULL,
  @IDFOL NVARCHAR(255) = NULL,
  @CLIENT NVARCHAR(255) = NULL,
  @ART NVARCHAR(255) = NULL,
  @TIPO NVARCHAR(255) = NULL,
  @LABOR NVARCHAR(255) = NULL,
  @ESTATUS NVARCHAR(255) = NULL,
  @ESTSEGU NVARCHAR(255) = NULL,
  @FECINI NVARCHAR(30) = NULL,
  @FECFIN NVARCHAR(30) = NULL,
  @ASIGN NVARCHAR(255) = NULL,
  @TIPOM NVARCHAR(255) = NULL,
  @MOTR NVARCHAR(255) = NULL,
  @SUC NVARCHAR(10) = NULL,
  @SEARCH NVARCHAR(255) = NULL,
  @PAGE INT = 1,
  @PAGESIZE INT = 25,
  @IS_ADMIN BIT = 0,
  @ALLOWED_SUCS NVARCHAR(MAX) = NULL,
  @PANEL_MODE NVARCHAR(20) = 'operativo',
  @ROLE_CODE NVARCHAR(50) = NULL
AS
BEGIN
  SET NOCOUNT ON;

  IF @PAGE IS NULL OR @PAGE < 1 SET @PAGE = 1;
  IF @PAGESIZE IS NULL OR @PAGESIZE < 1 SET @PAGESIZE = 25;
  IF @PAGESIZE > 25 SET @PAGESIZE = 25;

  SET @PANEL_MODE = LOWER(LTRIM(RTRIM(ISNULL(@PANEL_MODE, 'operativo'))));
  IF @PANEL_MODE NOT IN ('operativo', 'anulados', 'entregadas')
    SET @PANEL_MODE = 'operativo';

  SET @ROLE_CODE = UPPER(LTRIM(RTRIM(ISNULL(@ROLE_CODE, ''))));

  DECLARE @offset INT = (@PAGE - 1) * @PAGESIZE;

  DECLARE @allowed TABLE (SUC NVARCHAR(10) PRIMARY KEY);
  INSERT INTO @allowed (SUC)
  SELECT DISTINCT UPPER(LTRIM(RTRIM(value)))
  FROM STRING_SPLIT(ISNULL(@ALLOWED_SUCS, ''), ',')
  WHERE LTRIM(RTRIM(ISNULL(value, ''))) <> '';

  DECLARE @allowedStatus TABLE (ESTSEGU FLOAT PRIMARY KEY);
  DECLARE @ALLOW_NULL_ESTSEGU BIT = 0;

  IF @PANEL_MODE = 'anulados'
  BEGIN
    IF @IS_ADMIN = 1 OR @ROLE_CODE IN ('JEF_TALLER', 'TALLER')
      INSERT INTO @allowedStatus (ESTSEGU) VALUES (4);
  END
  ELSE IF @PANEL_MODE = 'entregadas'
  BEGIN
    IF @IS_ADMIN = 1 OR @ROLE_CODE IN ('JEF_TALLER', 'TALLER')
      INSERT INTO @allowedStatus (ESTSEGU) VALUES (11);
  END
  ELSE
  BEGIN
    IF @IS_ADMIN = 1 OR @ROLE_CODE IN ('JEF_TALLER', 'TALLER')
    BEGIN
      INSERT INTO @allowedStatus (ESTSEGU)
      VALUES (2), (3), (3.1), (5), (6), (7), (8), (9), (9.1), (9.2), (10), (12);
      SET @ALLOW_NULL_ESTSEGU = 1;
    END
    ELSE IF @ROLE_CODE IN ('ANALISTA', 'ANALISTA_ORD')
    BEGIN
      INSERT INTO @allowedStatus (ESTSEGU)
      VALUES (2), (3), (3.1), (6), (9.1), (9.2), (10), (12);
      SET @ALLOW_NULL_ESTSEGU = 1;
    END
    ELSE IF @ROLE_CODE IN ('ENC_MAQUILA', 'ENCARGADO_MAQUILA', 'ENC_BISEL', 'ENCARGADO_BISELADO')
      INSERT INTO @allowedStatus (ESTSEGU)
      VALUES (5), (7), (8), (9);
  END;

  WITH base AS (
    SELECT
      o.IORD,
      o.IDFOL,
      o.TIPO,
      o.OPV,
      o.FCNS,
      o.FCNM,
      o.CLIEN,
      o.NCLIENTE,
      o.MAT,
      o.CTD,
      o.ART,
      o.DESCART,
      o.COMAD,
      o.ESTATUS,
      o.ESTSEGU,
      o.ASIGN,
      o.LABOR,
      o.MOTR,
      tipomx.TIPOM,
      reeordx.REEORD,
      docdifx.DOCDIF,
      o.SUC,
      e.TIPO AS ESTSEGU_DESC,
      ROW_NUMBER() OVER (
        ORDER BY ISNULL(o.FCNS, ISNULL(o.FCNMOD, o.FCNM)) DESC, o.IORD DESC
      ) AS RN,
      COUNT(1) OVER () AS TOTAL_COUNT
    FROM dbo.PV_CTR_ORDS o
    OUTER APPLY (
      SELECT TOP 1 TRY_CONVERT(INT, j.[value]) AS TIPOM
      FROM OPENJSON((SELECT o.* FOR JSON PATH, WITHOUT_ARRAY_WRAPPER)) j
      WHERE j.[key] IN ('TIPOM', 'TPOM')
      ORDER BY CASE WHEN j.[key] = 'TIPOM' THEN 0 ELSE 1 END
    ) tipomx
    OUTER APPLY (
      SELECT TOP 1 LTRIM(RTRIM(ISNULL(CAST(j.[value] AS NVARCHAR(255)), ''))) AS REEORD
      FROM OPENJSON((SELECT o.* FOR JSON PATH, WITHOUT_ARRAY_WRAPPER)) j
      WHERE j.[key] IN ('REEORD', 'REOORD')
      ORDER BY CASE WHEN j.[key] = 'REEORD' THEN 0 ELSE 1 END
    ) reeordx
    OUTER APPLY (
      SELECT TOP 1 LTRIM(RTRIM(ISNULL(CAST(j.[value] AS NVARCHAR(255)), ''))) AS DOCDIF
      FROM OPENJSON((SELECT o.* FOR JSON PATH, WITHOUT_ARRAY_WRAPPER)) j
      WHERE j.[key] IN ('DOCDIF', 'DOCIF')
      ORDER BY CASE WHEN j.[key] = 'DOCDIF' THEN 0 ELSE 1 END
    ) docdifx
    LEFT JOIN dbo.DAT_EST_ORD e
      ON TRY_CONVERT(FLOAT, e.ESTA) = TRY_CONVERT(FLOAT, o.ESTSEGU)
    WHERE
      (@IORD IS NULL OR LTRIM(RTRIM(ISNULL(o.IORD, ''))) LIKE '%' + @IORD + '%')
      AND (@IDFOL IS NULL OR LTRIM(RTRIM(ISNULL(o.IDFOL, ''))) LIKE '%' + @IDFOL + '%')
      AND (@CLIENT IS NULL OR CAST(ISNULL(o.CLIEN, '') AS NVARCHAR(255)) LIKE '%' + @CLIENT + '%')
      AND (@ART IS NULL OR LTRIM(RTRIM(ISNULL(o.ART, ''))) LIKE '%' + @ART + '%')
      AND (@TIPO IS NULL OR UPPER(LTRIM(RTRIM(ISNULL(o.TIPO, '')))) LIKE '%' + UPPER(@TIPO) + '%')
      AND (@LABOR IS NULL OR CAST(ISNULL(o.LABOR, '') AS NVARCHAR(255)) = @LABOR)
      AND (@ESTATUS IS NULL OR CAST(ISNULL(o.ESTATUS, '') AS NVARCHAR(255)) = @ESTATUS)
      AND (
        @ESTSEGU IS NULL
        OR (
          UPPER(LTRIM(RTRIM(ISNULL(@ESTSEGU, '')))) = 'NULL'
          AND TRY_CONVERT(FLOAT, o.ESTSEGU) IS NULL
        )
        OR CAST(ISNULL(o.ESTSEGU, '') AS NVARCHAR(255)) = @ESTSEGU
      )
      AND (@ASIGN IS NULL OR UPPER(LTRIM(RTRIM(ISNULL(o.ASIGN, '')))) LIKE '%' + UPPER(@ASIGN) + '%')
      AND (@TIPOM IS NULL OR CAST(ISNULL(tipomx.TIPOM, '') AS NVARCHAR(255)) = @TIPOM)
      AND (@MOTR IS NULL OR CAST(ISNULL(o.MOTR, '') AS NVARCHAR(255)) = @MOTR)
      AND (@SUC IS NULL OR UPPER(LTRIM(RTRIM(ISNULL(o.SUC, '')))) = UPPER(@SUC))
      AND (@FECINI IS NULL OR TRY_CONVERT(DATE, o.FCNS) >= TRY_CONVERT(DATE, @FECINI))
      AND (@FECFIN IS NULL OR TRY_CONVERT(DATE, ISNULL(o.FCNM, o.FCNS)) <= TRY_CONVERT(DATE, @FECFIN))
      AND (
        @SEARCH IS NULL
        OR UPPER(LTRIM(RTRIM(ISNULL(o.IORD, '')))) LIKE '%' + UPPER(@SEARCH) + '%'
        OR UPPER(LTRIM(RTRIM(ISNULL(o.IDFOL, '')))) LIKE '%' + UPPER(@SEARCH) + '%'
        OR UPPER(LTRIM(RTRIM(ISNULL(o.ART, '')))) LIKE '%' + UPPER(@SEARCH) + '%'
        OR UPPER(LTRIM(RTRIM(ISNULL(o.DESCART, '')))) LIKE '%' + UPPER(@SEARCH) + '%'
        OR CAST(ISNULL(o.CLIEN, '') AS NVARCHAR(255)) LIKE '%' + @SEARCH + '%'
      )
      AND (
        @IS_ADMIN = 1
        OR NOT EXISTS (SELECT 1 FROM @allowed)
        OR UPPER(LTRIM(RTRIM(ISNULL(o.SUC, '')))) IN (SELECT SUC FROM @allowed)
      )
      AND TRY_CONVERT(INT, o.ESTATUS) = 2
      AND (
        EXISTS (
          SELECT 1
          FROM @allowedStatus a
          WHERE a.ESTSEGU = TRY_CONVERT(FLOAT, o.ESTSEGU)
        )
        OR (
          @ALLOW_NULL_ESTSEGU = 1
          AND TRY_CONVERT(FLOAT, o.ESTSEGU) IS NULL
        )
      )
  )
  SELECT *
  FROM base
  WHERE RN > @offset
    AND RN <= (@offset + @PAGESIZE)
  ORDER BY RN;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_ordenes_trabajo_autorizar
  @IORD NVARCHAR(255),
  @USER NVARCHAR(255) = NULL,
  @IP NVARCHAR(100) = NULL,
  @IS_ADMIN BIT = 0,
  @ALLOWED_SUCS NVARCHAR(MAX) = NULL,
  @SUC NVARCHAR(10) = NULL
AS
BEGIN
  EXEC dbo.sp_ordenes_trabajo_set_estado
    @IORD = @IORD,
    @ESTSEGU = 3,
    @ESTATUS = 2,
    @USER = @USER,
    @IP = @IP,
    @IS_ADMIN = @IS_ADMIN,
    @ALLOWED_SUCS = @ALLOWED_SUCS,
    @SUC = @SUC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_ordenes_trabajo_entregar
  @IORD NVARCHAR(255),
  @OBS NVARCHAR(255) = NULL,
  @FIRMA_CLIENTE NVARCHAR(MAX) = NULL,
  @USER NVARCHAR(255) = NULL,
  @IP NVARCHAR(100) = NULL,
  @IS_ADMIN BIT = 0,
  @ALLOWED_SUCS NVARCHAR(MAX) = NULL,
  @SUC NVARCHAR(10) = NULL
AS
BEGIN
  EXEC dbo.sp_ordenes_trabajo_set_estado
    @IORD = @IORD,
    @ESTSEGU = 11,
    @ESTATUS = 2,
    @OBS = @OBS,
    @FIRMA_CLIENTE = @FIRMA_CLIENTE,
    @USER = @USER,
    @IP = @IP,
    @IS_ADMIN = @IS_ADMIN,
    @ALLOWED_SUCS = @ALLOWED_SUCS,
    @SUC = @SUC;
END;
GO
