CREATE OR ALTER PROCEDURE dbo.FYS_REPORTE_AJUSTES_WEB
  @SUC INT,
  @QNA VARCHAR(20)
AS
BEGIN
  SET NOCOUNT ON;

  ;WITH base AS (
    SELECT
      TRY_CONVERT(INT, x.SUC) AS SUC,
      CASE
        WHEN ISNULL(TRY_CONVERT(INT, o.OTRASUC), 0) + TRY_CONVERT(INT, x.SUC) = TRY_CONVERT(INT, x.SUC)
          THEN TRY_CONVERT(INT, x.SUC)
        ELSE TRY_CONVERT(INT, o.OTRASUC)
      END AS OSUCDEF,
      UPPER(LTRIM(RTRIM(ISNULL(o.STATUS, '')))) AS STATUS,
      CONVERT(VARCHAR(20), x.QNA) AS QNA,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.VTA), 0) AS VTA,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.SOBR), 0) AS SOBR,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.FALT), 0) AS FALT,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.PAGOFALT), 0) AS PAGOFALT,
      LTRIM(RTRIM(ISNULL(x.CATEG, ''))) AS CATEG
    FROM dbo.FYS_XDIA_SVR3 x
    LEFT JOIN dbo.FYS_OPV_SVR1 o
      ON TRY_CONVERT(INT, o.SUC) = TRY_CONVERT(INT, x.SUC)
     AND TRY_CONVERT(INT, o.OPER) = TRY_CONVERT(INT, x.OPER)
    WHERE TRY_CONVERT(INT, x.SUC) = @SUC
      AND CONVERT(VARCHAR(20), x.QNA) = @QNA
  ), calc AS (
    SELECT *,
      CASE WHEN SOBR < 0 THEN 0 ELSE FALT - PAGOFALT END AS FALTMPAGO,
      CASE WHEN RIGHT(CATEG, 19) = '(Autorización SGPA)' THEN 1 ELSE 0 END AS ES_AUT,
      CASE
        WHEN VTA < 0 THEN FALT - PAGOFALT
        WHEN FALT = 0 THEN 0
        WHEN (FALT - PAGOFALT) - (VTA * 0.00025) < 0 THEN 0
        ELSE (FALT - PAGOFALT) - (VTA * 0.00025)
      END AS FALTREAL
    FROM base
  ), resumen AS (
    SELECT
      SUC, OSUCDEF, STATUS, QNA, COUNT_BIG(*) AS TOTALREG,
      SUM(VTA) AS TVTA,
      SUM(SOBR) AS TSOBR,
      SUM(CASE WHEN FALTMPAGO < 0 THEN FALTMPAGO ELSE 0 END + CASE WHEN ES_AUT = 1 THEN SOBR + PAGOFALT ELSE SOBR END) AS TSOBRREAL,
      SUM(FALT) AS TFALT,
      SUM(FALTREAL) AS TFALTREAL,
      SUM(PAGOFALT) AS TPAGOFALT,
      SUM(CASE WHEN ES_AUT = 1 THEN 0 ELSE PAGOFALT END) AS TPGOFALTREAL,
      SUM(FALTMPAGO) AS TFALTMPAGO,
      SUM(CASE WHEN FALTMPAGO < 0 THEN 0 ELSE FALTMPAGO - FALTREAL END) AS TVENIA
    FROM calc
    GROUP BY SUC, OSUCDEF, STATUS, QNA
  )
  SELECT * FROM resumen ORDER BY SUC, OSUCDEF, STATUS;
END;
GO

CREATE OR ALTER PROCEDURE dbo.FYS_REPORTE_AJUSTES_ACL_WEB
  @SUC INT,
  @QNA VARCHAR(20)
AS
BEGIN
  SET NOCOUNT ON;

  ;WITH acl AS (
    SELECT
      TRY_CONVERT(INT, x.SUC) AS SUC,
      CASE
        WHEN ISNULL(TRY_CONVERT(INT, o.OTRASUC), 0) + TRY_CONVERT(INT, x.SUC) = TRY_CONVERT(INT, x.SUC)
          THEN TRY_CONVERT(INT, x.SUC)
        ELSE TRY_CONVERT(INT, o.OTRASUC)
      END AS OSUCDEF,
      TRY_CONVERT(DATE, CONVERT(VARCHAR(20), x.FCN), 112) AS FCN,
      CONVERT(VARCHAR(20), x.QNA) AS QNA,
      TRY_CONVERT(INT, x.OPER) AS OPER,
      LTRIM(RTRIM(ISNULL(o.NOMBRE, CONCAT('OPV PENDIENTE ', CONVERT(VARCHAR(30), x.OPER))))) AS NOMBRE,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.PAGOFALT), 0) AS PAGOFALT,
      LTRIM(RTRIM(LEFT(ISNULL(x.CATEG, ''), LEN(ISNULL(x.CATEG, '')) - 19))) AS TIPOAUTCAT
    FROM dbo.FYS_XDIA_SVR3 x
    LEFT JOIN dbo.FYS_OPV_SVR1 o
      ON TRY_CONVERT(INT, o.SUC) = TRY_CONVERT(INT, x.SUC)
     AND TRY_CONVERT(INT, o.OPER) = TRY_CONVERT(INT, x.OPER)
    WHERE TRY_CONVERT(INT, x.SUC) = @SUC
      AND CONVERT(VARCHAR(20), x.QNA) = @QNA
      AND LTRIM(RTRIM(ISNULL(x.CATEG, ''))) LIKE '%SGPA)'
  )
  SELECT SUC, OSUCDEF, FCN, QNA, OPER, NOMBRE, PAGOFALT, TIPOAUTCAT
  FROM acl
  ORDER BY TIPOAUTCAT, FCN, OPER;

  ;WITH acl AS (
    SELECT
      TRY_CONVERT(INT, x.SUC) AS SUC,
      LTRIM(RTRIM(LEFT(ISNULL(x.CATEG, ''), LEN(ISNULL(x.CATEG, '')) - 19))) AS TIPOAUTCAT,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.PAGOFALT), 0) AS PAGOFALT
    FROM dbo.FYS_XDIA_SVR3 x
    WHERE TRY_CONVERT(INT, x.SUC) = @SUC
      AND CONVERT(VARCHAR(20), x.QNA) = @QNA
      AND LTRIM(RTRIM(ISNULL(x.CATEG, ''))) LIKE '%SGPA)'
  )
  SELECT SUC, TIPOAUTCAT, SUM(PAGOFALT) AS IMPORTE
  FROM acl
  GROUP BY SUC, TIPOAUTCAT
  ORDER BY TIPOAUTCAT;
END;
GO

CREATE OR ALTER PROCEDURE dbo.FYS_REPORTE_AJUSTES_DETALLE_OPV_WEB
  @SUC INT,
  @QNA VARCHAR(20)
AS
BEGIN
  SET NOCOUNT ON;

  ;WITH base AS (
    SELECT
      TRY_CONVERT(INT, x.SUC) AS SUC,
      CASE
        WHEN ISNULL(TRY_CONVERT(INT, o.OTRASUC), 0) + TRY_CONVERT(INT, x.SUC) = TRY_CONVERT(INT, x.SUC)
          THEN TRY_CONVERT(INT, x.SUC)
        ELSE TRY_CONVERT(INT, o.OTRASUC)
      END AS OSUCDEF,
      UPPER(LTRIM(RTRIM(ISNULL(o.STATUS, '')))) AS STATUS,
      CONVERT(VARCHAR(20), x.QNA) AS QNA,
      TRY_CONVERT(INT, x.OPER) AS OPER,
      LTRIM(RTRIM(ISNULL(o.NOMBRE, CONCAT('OPV PENDIENTE ', CONVERT(VARCHAR(30), x.OPER))))) AS NOMBRE,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.VTA), 0) AS VTA,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.SOBR), 0) AS SOBR,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.FALT), 0) AS FALT,
      ISNULL(TRY_CONVERT(DECIMAL(19,4), x.PAGOFALT), 0) AS PAGOFALT
    FROM dbo.FYS_XDIA_SVR3 x
    LEFT JOIN dbo.FYS_OPV_SVR1 o
      ON TRY_CONVERT(INT, o.SUC) = TRY_CONVERT(INT, x.SUC)
     AND TRY_CONVERT(INT, o.OPER) = TRY_CONVERT(INT, x.OPER)
    WHERE TRY_CONVERT(INT, x.SUC) = @SUC
      AND CONVERT(VARCHAR(20), x.QNA) = @QNA
  ), calc AS (
    SELECT *,
      CASE WHEN SOBR < 0 THEN 0 ELSE FALT - PAGOFALT END AS FALTMPAGO,
      CASE
        WHEN VTA < 0 THEN FALT - PAGOFALT
        WHEN FALT = 0 THEN 0
        WHEN (FALT - PAGOFALT) - (VTA * 0.00025) < 0 THEN 0
        ELSE (FALT - PAGOFALT) - (VTA * 0.00025)
      END AS FALTREAL
    FROM base
  )
  SELECT
    SUC, OSUCDEF, STATUS, QNA, OPER, NOMBRE, COUNT_BIG(*) AS TOTALREG,
    SUM(VTA) AS TVTA,
    SUM(SOBR) AS TSOBR,
    SUM(FALT) AS TFALT,
    SUM(PAGOFALT) AS TPAGOFALT,
    SUM(FALTMPAGO) AS TFALTMPAGO,
    SUM(FALTREAL) AS TFALTREAL,
    SUM(CASE WHEN FALTMPAGO < 0 THEN 0 ELSE FALTMPAGO - FALTREAL END) AS TVENIA
  FROM calc
  GROUP BY SUC, OSUCDEF, STATUS, QNA, OPER, NOMBRE
  ORDER BY OPER;
END;
GO
