/* Ajuste 2026-03-23:
   - Crea módulos front exclusivos para paneles de ORD:
     * DAT_JAO_ORD_ANULADAS
     * DAT_JAO_ORD_ENTREGADAS
   - Los asocia al grupo de JEFE TALLER (o fallback al grupo base de ORD)
*/

SET NOCOUNT ON;

IF OBJECT_ID('dbo.MOD_FRONT', 'U') IS NULL
  OR OBJECT_ID('dbo.GRUPMOD_FRONT', 'U') IS NULL
  OR OBJECT_ID('dbo.GRUPMOD_FRONT_MOD', 'U') IS NULL
BEGIN
  PRINT 'WARN: Tablas MOD_FRONT/GRUPMOD_FRONT/GRUPMOD_FRONT_MOD no disponibles.';
  RETURN;
END;
GO

DECLARE @BaseId INT = (
  SELECT TOP 1 IDMOD_FRONT
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(CODIGO))) = 'DAT_JAO_ORD'
);

IF @BaseId IS NULL
BEGIN
  PRINT 'WARN: No existe modulo base DAT_JAO_ORD. No se aplican inserciones.';
  RETURN;
END;

DECLARE @Depto NVARCHAR(100) = (
  SELECT TOP 1 DEPTO
  FROM dbo.MOD_FRONT
  WHERE IDMOD_FRONT = @BaseId
);

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(CODIGO))) = 'DAT_JAO_ORD_ANULADAS'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_ANULADAS', 'Gestión ORD anuladas', 1, GETDATE(), @Depto);
END;

IF NOT EXISTS (
  SELECT 1
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(CODIGO))) = 'DAT_JAO_ORD_ENTREGADAS'
)
BEGIN
  INSERT INTO dbo.MOD_FRONT (CODIGO, NOMBRE, ACTIVO, FCNR, DEPTO)
  VALUES ('DAT_JAO_ORD_ENTREGADAS', 'Gestión ORD entregadas a cliente', 1, GETDATE(), @Depto);
END;

DECLARE @ModAnulados INT = (
  SELECT TOP 1 IDMOD_FRONT
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(CODIGO))) = 'DAT_JAO_ORD_ANULADAS'
);
DECLARE @ModEntregadas INT = (
  SELECT TOP 1 IDMOD_FRONT
  FROM dbo.MOD_FRONT
  WHERE UPPER(LTRIM(RTRIM(CODIGO))) = 'DAT_JAO_ORD_ENTREGADAS'
);

DECLARE @TargetGroups TABLE (IDGRUPMOD_FRONT INT PRIMARY KEY);

INSERT INTO @TargetGroups (IDGRUPMOD_FRONT)
SELECT g.IDGRUPMOD_FRONT
FROM dbo.GRUPMOD_FRONT g
INNER JOIN dbo.GRUPMOD_FRONT_MOD gm
  ON gm.IDGRUPMOD_FRONT = g.IDGRUPMOD_FRONT
WHERE gm.IDMOD_FRONT = @BaseId
  AND UPPER(LTRIM(RTRIM(ISNULL(g.NOMBRE, '')))) LIKE '%JEFE%'
  AND UPPER(LTRIM(RTRIM(ISNULL(g.NOMBRE, '')))) LIKE '%TALLER%';

IF NOT EXISTS (SELECT 1 FROM @TargetGroups)
BEGIN
  INSERT INTO @TargetGroups (IDGRUPMOD_FRONT)
  SELECT gm.IDGRUPMOD_FRONT
  FROM dbo.GRUPMOD_FRONT_MOD gm
  WHERE gm.IDMOD_FRONT = @BaseId;
END;

IF @ModAnulados IS NOT NULL
BEGIN
  INSERT INTO dbo.GRUPMOD_FRONT_MOD (IDGRUPMOD_FRONT, IDMOD_FRONT)
  SELECT tg.IDGRUPMOD_FRONT, @ModAnulados
  FROM @TargetGroups tg
  WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.GRUPMOD_FRONT_MOD x
    WHERE x.IDGRUPMOD_FRONT = tg.IDGRUPMOD_FRONT
      AND x.IDMOD_FRONT = @ModAnulados
  );
END;

IF @ModEntregadas IS NOT NULL
BEGIN
  INSERT INTO dbo.GRUPMOD_FRONT_MOD (IDGRUPMOD_FRONT, IDMOD_FRONT)
  SELECT tg.IDGRUPMOD_FRONT, @ModEntregadas
  FROM @TargetGroups tg
  WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.GRUPMOD_FRONT_MOD x
    WHERE x.IDGRUPMOD_FRONT = tg.IDGRUPMOD_FRONT
      AND x.IDMOD_FRONT = @ModEntregadas
  );
END;

PRINT 'OK: Módulos front de paneles ORD verificados/creados.';
GO
