/*
  2026-05-10_promociones_configuracion_unificada.sql
  Catálogos + configuración unificada para promociones.
*/
SET NOCOUNT ON;

BEGIN TRY
  BEGIN TRAN;

  IF OBJECT_ID('dbo.PROMO_CAT_T_PROM', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_CAT_T_PROM (
      ID_T_PROM INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_CAT_T_PROM PRIMARY KEY,
      CLAVE NVARCHAR(50) NOT NULL,
      DESCRIPCION NVARCHAR(120) NOT NULL,
      EST INT NOT NULL CONSTRAINT DF_PROMO_CAT_T_PROM_EST DEFAULT (1),
      FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_CAT_T_PROM_FCNR DEFAULT (GETDATE())
    );
    CREATE UNIQUE INDEX UX_PROMO_CAT_T_PROM_CLAVE ON dbo.PROMO_CAT_T_PROM(CLAVE);
  END;

  IF OBJECT_ID('dbo.PROMO_CAT_TIPO_DESC', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_CAT_TIPO_DESC (
      ID_TIPO_DESC INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_CAT_TIPO_DESC PRIMARY KEY,
      CLAVE NVARCHAR(50) NOT NULL,
      DESCRIPCION NVARCHAR(120) NOT NULL,
      EST INT NOT NULL CONSTRAINT DF_PROMO_CAT_TIPO_DESC_EST DEFAULT (1),
      FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_CAT_TIPO_DESC_FCNR DEFAULT (GETDATE())
    );
    CREATE UNIQUE INDEX UX_PROMO_CAT_TIPO_DESC_CLAVE ON dbo.PROMO_CAT_TIPO_DESC(CLAVE);
  END;

  IF OBJECT_ID('dbo.PROMO_CAT_T_BENEFICIO', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_CAT_T_BENEFICIO (
      ID_T_BENEFICIO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_CAT_T_BENEFICIO PRIMARY KEY,
      CLAVE NVARCHAR(50) NOT NULL,
      DESCRIPCION NVARCHAR(120) NOT NULL,
      EST INT NOT NULL CONSTRAINT DF_PROMO_CAT_T_BENEFICIO_EST DEFAULT (1),
      FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_CAT_T_BENEFICIO_FCNR DEFAULT (GETDATE())
    );
    CREATE UNIQUE INDEX UX_PROMO_CAT_T_BENEFICIO_CLAVE ON dbo.PROMO_CAT_T_BENEFICIO(CLAVE);
  END;

  IF OBJECT_ID('dbo.PROMO_CONFIG', 'U') IS NULL
  BEGIN
    CREATE TABLE dbo.PROMO_CONFIG (
      ID_CONFIG BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROMO_CONFIG PRIMARY KEY,
      ID_PROM INT NOT NULL,
      T_BENEFICIO NVARCHAR(50) NOT NULL,
      PRC_DESC DECIMAL(9,4) NULL,
      IMP_DESC MONEY NULL,
      PRECIO_GRATIS MONEY NULL,
      SUC_TODAS INT NOT NULL CONSTRAINT DF_PROMO_CONFIG_SUC_TODAS DEFAULT (1),
      SUC_LIST NVARCHAR(MAX) NULL,
      CLIENTE FLOAT NULL,
      DEPA_LIST NVARCHAR(MAX) NULL,
      SUBD_LIST NVARCHAR(MAX) NULL,
      CLAS_LIST NVARCHAR(MAX) NULL,
      SCLA_LIST NVARCHAR(MAX) NULL,
      SCLA2_LIST NVARCHAR(MAX) NULL,
      GUIA_LIST NVARCHAR(MAX) NULL,
      ART_LIST NVARCHAR(MAX) NULL,
      UPC_LIST NVARCHAR(MAX) NULL,
      ACTIVO INT NOT NULL CONSTRAINT DF_PROMO_CONFIG_ACTIVO DEFAULT (1),
      FCNR DATETIME NOT NULL CONSTRAINT DF_PROMO_CONFIG_FCNR DEFAULT (GETDATE()),
      MOD_POR INT NULL,
      FCMOD DATETIME NULL
    );

    ALTER TABLE dbo.PROMO_CONFIG
      ADD CONSTRAINT FK_PROMO_CONFIG_PROMO_CAB
      FOREIGN KEY (ID_PROM) REFERENCES dbo.PROMO_CAB(ID_PROM);

    CREATE UNIQUE INDEX UX_PROMO_CONFIG_ID_PROM ON dbo.PROMO_CONFIG(ID_PROM);
  END;

  IF NOT EXISTS (SELECT 1 FROM dbo.PROMO_CAT_TIPO_DESC WHERE CLAVE = 'PORCENTAJE')
    INSERT INTO dbo.PROMO_CAT_TIPO_DESC (CLAVE, DESCRIPCION) VALUES ('PORCENTAJE', 'Descuento porcentual');
  IF NOT EXISTS (SELECT 1 FROM dbo.PROMO_CAT_TIPO_DESC WHERE CLAVE = 'IMP_FIJO')
    INSERT INTO dbo.PROMO_CAT_TIPO_DESC (CLAVE, DESCRIPCION) VALUES ('IMP_FIJO', 'Descuento por importe fijo');

  IF NOT EXISTS (SELECT 1 FROM dbo.PROMO_CAT_T_BENEFICIO WHERE CLAVE = 'PORCENTAJE')
    INSERT INTO dbo.PROMO_CAT_T_BENEFICIO (CLAVE, DESCRIPCION) VALUES ('PORCENTAJE', 'Descuento porcentual');
  IF NOT EXISTS (SELECT 1 FROM dbo.PROMO_CAT_T_BENEFICIO WHERE CLAVE = 'IMP_FIJO')
    INSERT INTO dbo.PROMO_CAT_T_BENEFICIO (CLAVE, DESCRIPCION) VALUES ('IMP_FIJO', 'Descuento por importe fijo');
  IF NOT EXISTS (SELECT 1 FROM dbo.PROMO_CAT_T_BENEFICIO WHERE CLAVE = 'ART_GRATIS')
    INSERT INTO dbo.PROMO_CAT_T_BENEFICIO (CLAVE, DESCRIPCION) VALUES ('ART_GRATIS', 'Articulo gratis');

  INSERT INTO dbo.PROMO_CAT_T_PROM (CLAVE, DESCRIPCION)
  SELECT DISTINCT UPPER(LTRIM(RTRIM(T_PROM))), UPPER(LTRIM(RTRIM(T_PROM)))
  FROM dbo.PROMO_CAB
  WHERE LTRIM(RTRIM(ISNULL(T_PROM, ''))) <> ''
    AND NOT EXISTS (
      SELECT 1 FROM dbo.PROMO_CAT_T_PROM x
      WHERE x.CLAVE = UPPER(LTRIM(RTRIM(dbo.PROMO_CAB.T_PROM)))
    );

  INSERT INTO dbo.PROMO_CAT_TIPO_DESC (CLAVE, DESCRIPCION)
  SELECT DISTINCT UPPER(LTRIM(RTRIM(TIPO_DESC))), UPPER(LTRIM(RTRIM(TIPO_DESC)))
  FROM dbo.PROMO_CAB
  WHERE LTRIM(RTRIM(ISNULL(TIPO_DESC, ''))) <> ''
    AND NOT EXISTS (
      SELECT 1 FROM dbo.PROMO_CAT_TIPO_DESC x
      WHERE x.CLAVE = UPPER(LTRIM(RTRIM(dbo.PROMO_CAB.TIPO_DESC)))
    );

  COMMIT;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0 ROLLBACK;
  THROW;
END CATCH;
GO
