/*
  Soporte de desempeño para devoluciones mixtas/prorrata.
  No cambia lógica; agrega índices para consultas por folio origen y formas.
*/

IF OBJECT_ID('dbo.PV_CTR_FOL_ASVR', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR')
    AND name = 'IX_PV_CTR_FOL_ASVR_IDFOLORIG_AUT_IDFOL'
)
BEGIN
  CREATE INDEX IX_PV_CTR_FOL_ASVR_IDFOLORIG_AUT_IDFOL
  ON dbo.PV_CTR_FOL_ASVR (IDFOLORIG, AUT, IDFOL)
  INCLUDE (ESTA, FCN, FCNM, SUC, OPV, OPVM);
END;
GO

IF OBJECT_ID('dbo.PV_CTR_FOL_FORM_SVR', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_FORM_SVR')
    AND name = 'IX_PV_CTR_FOL_FORM_SVR_IDFOL_FORM_AUT'
)
BEGIN
  CREATE INDEX IX_PV_CTR_FOL_FORM_SVR_IDFOL_FORM_AUT
  ON dbo.PV_CTR_FOL_FORM_SVR (IDFOL, FORM, AUT)
  INCLUDE (IMPP, IMPD, FCN);
END;
GO

IF OBJECT_ID('dbo.PV_CTR_FOL_FORM', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PV_CTR_FOL_FORM')
    AND name = 'IX_PV_CTR_FOL_FORM_IDFOL_FORM_AUT'
)
BEGIN
  CREATE INDEX IX_PV_CTR_FOL_FORM_IDFOL_FORM_AUT
  ON dbo.PV_CTR_FOL_FORM (IDFOL, FORM, AUT)
  INCLUDE (IMPP, IMPD, FCN);
END;
GO
