SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

/*
  Evita colisiones de DOCREC con documentos/movimientos legacy y genera IDREC
  con un prefijo propio del módulo de recepción.
*/
DECLARE @definition nvarchar(max)=OBJECT_DEFINITION(OBJECT_ID('dbo.sp_rec_recepcion_fisica'));
DECLARE @oldDocBlock nvarchar(max)=N'SELECT @NEXT=ISNULL(MAX(TRY_CONVERT(bigint,DOCREC)),71000000)+1 FROM dbo.REC_CTRL_DOC_REC WITH(UPDLOCK,HOLDLOCK);';
DECLARE @newDocBlock nvarchar(max)=N'SELECT @NEXT=ISNULL(MAX(NUMERO),71000000)+1
  FROM (
    SELECT TRY_CONVERT(bigint,DOCREC) NUMERO FROM dbo.REC_CTRL_DOC_REC WITH(UPDLOCK,HOLDLOCK)
    UNION ALL SELECT TRY_CONVERT(bigint,DOC) FROM dbo.DAT_CTR_DOC WITH(UPDLOCK,HOLDLOCK)
    UNION ALL SELECT TRY_CONVERT(bigint,DOCP) FROM dbo.DAT_MB51 WITH(UPDLOCK,HOLDLOCK)
  ) documentos
  WHERE NUMERO IS NOT NULL;
  WHILE EXISTS(SELECT 1 FROM dbo.REC_CTRL_DOC_REC WHERE DOCREC=CONVERT(nvarchar(510),@NEXT))
     OR EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WHERE DOC=CONVERT(nvarchar(510),@NEXT))
     OR EXISTS(SELECT 1 FROM dbo.DAT_MB51 WHERE DOCP=CONVERT(nvarchar(510),@NEXT))
    SET @NEXT+=1;';
DECLARE @oldIdBlock nvarchar(max)=N'CONCAT(CONVERT(varchar(12),RN),@DOCREC)';
DECLARE @newIdBlock nvarchar(max)=N'CONCAT(''REC-'',@DOCREC,''-'',CONVERT(varchar(12),RN))';

IF @definition IS NULL THROW 51000,'No existe dbo.sp_rec_recepcion_fisica.',1;
IF CHARINDEX(@oldDocBlock,@definition)>0 OR CHARINDEX(@oldIdBlock,@definition)>0
BEGIN
  IF CHARINDEX(@oldDocBlock,@definition)=0 THROW 51000,'No se encontró el bloque de generación DOCREC esperado.',1;
  IF CHARINDEX(@oldIdBlock,@definition)=0 THROW 51000,'No se encontró el bloque de generación IDREC esperado.',1;
  SET @definition=REPLACE(@definition,@oldDocBlock,@newDocBlock);
  SET @definition=REPLACE(@definition,@oldIdBlock,@newIdBlock);
END
ELSE IF CHARINDEX(@newDocBlock,@definition)=0 OR CHARINDEX(@newIdBlock,@definition)=0
  THROW 51000,'La definición del procedimiento no coincide con la versión esperada.',1;
SET @definition=STUFF(@definition,1,CHARINDEX('PROCEDURE',@definition)-1,N'ALTER ');
EXEC sys.sp_executesql @definition;
GO

/* Repara la recepción afectada sin volver a aplicar cantidades a existencias. */
BEGIN TRAN;
DECLARE @lock int;
EXEC @lock=sys.sp_getapplock
  @Resource='DAT_REC_REPARAR_71002627',
  @LockMode='Exclusive',
  @LockOwner='Transaction',
  @LockTimeout=15000;
IF @lock<0 THROW 51000,'No fue posible bloquear la reparación.',1;

DECLARE @oldDoc nvarchar(510)=N'71002627';
IF EXISTS(
  SELECT 1
  FROM dbo.REC_CTRL_DOC_REC
  WHERE DOCREC=@oldDoc AND NPED=N'450002277'
)
BEGIN
  DECLARE @next bigint;
  SELECT @next=ISNULL(MAX(NUMERO),71000000)+1
  FROM (
    SELECT TRY_CONVERT(bigint,DOCREC) NUMERO FROM dbo.REC_CTRL_DOC_REC WITH(UPDLOCK,HOLDLOCK)
    UNION ALL SELECT TRY_CONVERT(bigint,DOC) FROM dbo.DAT_CTR_DOC WITH(UPDLOCK,HOLDLOCK)
    UNION ALL SELECT TRY_CONVERT(bigint,DOCP) FROM dbo.DAT_MB51 WITH(UPDLOCK,HOLDLOCK)
  ) documentos
  WHERE NUMERO IS NOT NULL;
  WHILE EXISTS(SELECT 1 FROM dbo.REC_CTRL_DOC_REC WHERE DOCREC=CONVERT(nvarchar(510),@next))
     OR EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WHERE DOC=CONVERT(nvarchar(510),@next))
     OR EXISTS(SELECT 1 FROM dbo.DAT_MB51 WHERE DOCP=CONVERT(nvarchar(510),@next))
    SET @next+=1;

  DECLARE @newDoc nvarchar(510)=CONVERT(nvarchar(510),@next);
  DECLARE @map table(OLD_IDREC nvarchar(510) NOT NULL,NEW_IDREC nvarchar(510) NOT NULL);
  INSERT @map(OLD_IDREC,NEW_IDREC)
  SELECT IDREC,CONCAT('REC-',@newDoc,'-',ROW_NUMBER() OVER(ORDER BY POS,IDREC))
  FROM dbo.REC_CTO_HIST
  WHERE DOCREC=@oldDoc;

  INSERT dbo.REC_CTRL_DOC_REC(
    DOCREC,NPED,FCNC,NART,IMPT,ESTATUS_REC,TIPO_RECEPCION,FCN_FISICA,
    USR_RECEPCION,FCN_AUTORIZA,USR_AUTORIZA,TIPO_DOC,FOLIO_DOC,
    OBSERVACIONES,ALMACEN
  )
  SELECT @newDoc,NPED,FCNC,NART,IMPT,ESTATUS_REC,TIPO_RECEPCION,FCN_FISICA,
         USR_RECEPCION,FCN_AUTORIZA,USR_AUTORIZA,TIPO_DOC,FOLIO_DOC,
         OBSERVACIONES,ALMACEN
  FROM dbo.REC_CTRL_DOC_REC
  WHERE DOCREC=@oldDoc;

  UPDATE dbo.REC_GUIA_PED SET DOCREC=@newDoc WHERE DOCREC=@oldDoc;
  UPDATE i SET i.DOCREC=@newDoc,i.IDREC=m.NEW_IDREC
  FROM dbo.REC_INCI_PED i
  LEFT JOIN @map m ON m.OLD_IDREC=i.IDREC
  WHERE i.DOCREC=@oldDoc;
  UPDATE h SET h.DOCREC=@newDoc,h.IDREC=m.NEW_IDREC
  FROM dbo.REC_CTO_HIST h
  JOIN @map m ON m.OLD_IDREC=h.IDREC
  WHERE h.DOCREC=@oldDoc;
  UPDATE dbo.REC_DET_PED SET DREC=@newDoc WHERE DREC=@oldDoc AND NPED=N'450002277';
  UPDATE dbo.AUDIT_LOG SET ENTIDAD_ID=@newDoc
  WHERE ENTIDAD_ID=@oldDoc AND MODULO='DAT_REC' AND ENTIDAD='REC_CTRL_DOC_REC';

  IF NOT EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WHERE DOC=@newDoc)
    INSERT dbo.DAT_CTR_DOC(DOC,CLSMOV,FCND,[USER],STAT)
    SELECT @newDoc,'101',COALESCE(FCN_AUTORIZA,SYSDATETIME()),USR_AUTORIZA,'V'
    FROM dbo.REC_CTRL_DOC_REC WHERE DOCREC=@newDoc;

  INSERT dbo.DAT_MB51(IDPD,[USER],CLSM,DOCP,ART,CTDA,CTOT,FCND,FCNC,TXT,ALMACEN,SUC)
  SELECT h.IDREC,r.USR_AUTORIZA,101,@newDoc,h.ART,ISNULL(h.CTD_ACEP,h.CTD),
         ISNULL(d.CTO,0)*ISNULL(h.CTD_ACEP,h.CTD),
         COALESCE(r.FCN_AUTORIZA,SYSDATETIME()),COALESCE(r.FCN_AUTORIZA,SYSDATETIME()),
         r.NPED,COALESCE(NULLIF(r.ALMACEN,''),'002'),c.SUC
  FROM dbo.REC_CTO_HIST h
  JOIN dbo.REC_CTRL_DOC_REC r ON r.DOCREC=h.DOCREC
  JOIN dbo.REC_CAB_PED c ON c.NPED=r.NPED
  LEFT JOIN dbo.REC_DET_PED d ON d.IDPED=h.IDPED
  WHERE h.DOCREC=@newDoc
    AND ISNULL(h.CTD_ACEP,h.CTD)>0
    AND NOT EXISTS(SELECT 1 FROM dbo.DAT_MB51 m WHERE m.IDPD=h.IDREC);

  DELETE dbo.REC_CTRL_DOC_REC WHERE DOCREC=@oldDoc AND NPED=N'450002277';

  SELECT @oldDoc DOCREC_ANTERIOR,@newDoc DOCREC_NUEVO;
END
COMMIT;
GO
