/*
  2026-05-10_promociones_truncation_guard_patch.sql
  Ajustes de longitudes para evitar abort por truncado al guardar configuracion.
*/
SET NOCOUNT ON;

IF OBJECT_ID('dbo.PROMO_REGLA_CRITERIO','U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.PROMO_REGLA_CRITERIO','SUC') IS NOT NULL
    ALTER TABLE dbo.PROMO_REGLA_CRITERIO ALTER COLUMN SUC NVARCHAR(20) NULL;

  IF COL_LENGTH('dbo.PROMO_REGLA_CRITERIO','GUIA') IS NOT NULL
    ALTER TABLE dbo.PROMO_REGLA_CRITERIO ALTER COLUMN GUIA NVARCHAR(255) NULL;

  IF COL_LENGTH('dbo.PROMO_REGLA_CRITERIO','ART') IS NOT NULL
    ALTER TABLE dbo.PROMO_REGLA_CRITERIO ALTER COLUMN ART NVARCHAR(255) NULL;

  IF COL_LENGTH('dbo.PROMO_REGLA_CRITERIO','UPC') IS NOT NULL
    ALTER TABLE dbo.PROMO_REGLA_CRITERIO ALTER COLUMN UPC NVARCHAR(255) NULL;
END;
GO

IF OBJECT_ID('dbo.PROMO_REGLA_BENEFICIO','U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.PROMO_REGLA_BENEFICIO','T_BENEFICIO') IS NOT NULL
    ALTER TABLE dbo.PROMO_REGLA_BENEFICIO ALTER COLUMN T_BENEFICIO NVARCHAR(50) NOT NULL;

  IF COL_LENGTH('dbo.PROMO_REGLA_BENEFICIO','ART_GRATIS') IS NOT NULL
    ALTER TABLE dbo.PROMO_REGLA_BENEFICIO ALTER COLUMN ART_GRATIS NVARCHAR(255) NULL;

  IF COL_LENGTH('dbo.PROMO_REGLA_BENEFICIO','UPC_GRATIS') IS NOT NULL
    ALTER TABLE dbo.PROMO_REGLA_BENEFICIO ALTER COLUMN UPC_GRATIS NVARCHAR(255) NULL;
END;
GO
