/*
  2026-04-19
  Cambio material / Merma
  - Agrega PVTA_NUEVO a staging temporal (PV_ORD_CAMBIO_MERMA_TMP)
  - Crea/ajusta tabla de control de diferencias (PV_ORD_CAMBIO_MERMA_DIF_CTRL)
  - Ajusta SPs para recibir @PVTA_NUEVO y calcular importes con PVTA capturado
*/

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID('dbo.PV_ORD_CAMBIO_MERMA_TMP', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PV_ORD_CAMBIO_MERMA_TMP (
    IORD NVARCHAR(255) NOT NULL,
    TIPOM INT NOT NULL,
    ART_NUEVO NVARCHAR(255) NULL,
    PVTA_NUEVO FLOAT NULL,
    MOTR INT NULL,
    MOTIVO NVARCHAR(255) NULL,
    LABOR INT NULL,
    DOCDIF NVARCHAR(255) NULL,
    CTD_C_M FLOAT NULL,
    CREAR_NUEVA_ORD BIT NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_TMP_CREAR_NUEVA_ORD DEFAULT (1),
    USER_MOD NVARCHAR(255) NULL,
    FCN_ALT DATETIME NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_TMP_FCN_ALT DEFAULT (GETDATE()),
    FCN_MOD DATETIME NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_TMP_FCN_MOD DEFAULT (GETDATE()),
    CONSTRAINT PK_PV_ORD_CAMBIO_MERMA_TMP PRIMARY KEY (IORD, TIPOM)
  );
END;
GO

IF COL_LENGTH('dbo.PV_ORD_CAMBIO_MERMA_TMP', 'PVTA_NUEVO') IS NULL
BEGIN
  ALTER TABLE dbo.PV_ORD_CAMBIO_MERMA_TMP
    ADD PVTA_NUEVO FLOAT NULL;
END;
GO

IF OBJECT_ID('dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL (
    IORD_ORIG NVARCHAR(255) NOT NULL,
    TIPOM INT NOT NULL,
    IORD_NUEVA NVARCHAR(255) NULL,
    IDFOL NVARCHAR(255) NULL,
    ART_ORIG NVARCHAR(255) NULL,
    ART_NUEVO NVARCHAR(255) NULL,
    CTD_C_M FLOAT NULL,
    PVTA_ORIG FLOAT NULL,
    PVTA_NUEVO FLOAT NULL,
    SUBTOTAL_ORIG FLOAT NULL,
    IVA_ORIG FLOAT NULL,
    TOTAL_ORIG FLOAT NULL,
    SUBTOTAL_NUEVO FLOAT NULL,
    IVA_NUEVO FLOAT NULL,
    TOTAL_NUEVO FLOAT NULL,
    DIFERENCIA_ECONOMICA FLOAT NULL,
    AFECTACION_CONTABLE BIT NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_DIF_CTRL_AFECTACION_CONTABLE DEFAULT (0),
    ESTADO NVARCHAR(30) NULL,
    USER_MOD NVARCHAR(255) NULL,
    FCN_ALT DATETIME NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_DIF_CTRL_FCN_ALT DEFAULT (GETDATE()),
    FCN_MOD DATETIME NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_DIF_CTRL_FCN_MOD DEFAULT (GETDATE()),
    CONSTRAINT PK_PV_ORD_CAMBIO_MERMA_DIF_CTRL PRIMARY KEY (IORD_ORIG, TIPOM)
  );
END;
GO

IF COL_LENGTH('dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL', 'PVTA_NUEVO') IS NULL
BEGIN
  ALTER TABLE dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL
    ADD PVTA_NUEVO FLOAT NULL;
END;
GO
IF COL_LENGTH('dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL', 'ESTADO') IS NULL
BEGIN
  ALTER TABLE dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL
    ADD ESTADO NVARCHAR(30) NULL;
END;
GO
IF COL_LENGTH('dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL', 'FCN_ALT') IS NULL
BEGIN
  ALTER TABLE dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL
    ADD FCN_ALT DATETIME NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_DIF_CTRL_FCN_ALT_2 DEFAULT (GETDATE());
END;
GO
IF COL_LENGTH('dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL', 'FCN_MOD') IS NULL
BEGIN
  ALTER TABLE dbo.PV_ORD_CAMBIO_MERMA_DIF_CTRL
    ADD FCN_MOD DATETIME NOT NULL
      CONSTRAINT DF_PV_ORD_CAMBIO_MERMA_DIF_CTRL_FCN_MOD_2 DEFAULT (GETDATE());
END;
GO

DECLARE @targets TABLE (
  proc_name SYSNAME PRIMARY KEY,
  ctd_signature NVARCHAR(120)
);
INSERT INTO @targets (proc_name, ctd_signature)
VALUES
  ('sp_ordenes_trabajo_cambio_material', '@CTD_C_M FLOAT = 1,'),
  ('sp_ordenes_trabajo_merma', '@CTD_C_M FLOAT = NULL,');

DECLARE @proc SYSNAME;
DECLARE @ctdSignature NVARCHAR(120);
DECLARE @definition NVARCHAR(MAX);
DECLARE @updated NVARCHAR(MAX);
DECLARE @msg NVARCHAR(2000);

DECLARE cur CURSOR LOCAL FAST_FORWARD FOR
SELECT proc_name, ctd_signature
FROM @targets;

OPEN cur;
FETCH NEXT FROM cur INTO @proc, @ctdSignature;

WHILE @@FETCH_STATUS = 0
BEGIN
  SELECT @definition = m.definition
  FROM sys.sql_modules m
  INNER JOIN sys.objects o
    ON o.object_id = m.object_id
  WHERE o.type = 'P'
    AND o.name = @proc
    AND SCHEMA_NAME(o.schema_id) = 'dbo';

  IF @definition IS NULL
  BEGIN
    SET @msg = CONCAT('No existe dbo.', @proc);
    THROW 58130, @msg, 1;
  END;

  SET @updated = @definition;

  IF @updated NOT LIKE '%@PVTA_NUEVO FLOAT%'
  BEGIN
    SET @updated = REPLACE(
      @updated,
      @ctdSignature,
      CONCAT(@ctdSignature, CHAR(13), CHAR(10), '  @PVTA_NUEVO FLOAT = NULL,')
    );
  END;

  IF @updated LIKE '%SET @precioNuevo = ISNULL(@precioOrig, 0);%'
  BEGIN
    SET @updated = REPLACE(
      @updated,
      'SET @precioNuevo = ISNULL(@precioOrig, 0);',
      'SET @precioNuevo = COALESCE(@PVTA_NUEVO, @precioNuevo, @precioOrig, 0);'
    );
  END;

  IF @updated <> @definition
  BEGIN
    SET @updated = REPLACE(@updated, 'CREATE OR ALTER PROCEDURE', 'ALTER PROCEDURE');
    SET @updated = REPLACE(@updated, 'CREATE   PROCEDURE', 'ALTER PROCEDURE');
    SET @updated = REPLACE(@updated, 'CREATE PROCEDURE', 'ALTER PROCEDURE');

    EXEC sp_executesql @updated;
    PRINT CONCAT('Actualizado dbo.', @proc, ' con @PVTA_NUEVO.');
  END
  ELSE
  BEGIN
    PRINT CONCAT('Sin cambios en dbo.', @proc, '.');
  END;

  FETCH NEXT FROM cur INTO @proc, @ctdSignature;
END;

CLOSE cur;
DEALLOCATE cur;
GO
