/* Flujo DAT_REC: Encargado termina en VALIDADO para revisión de Inventarios. */
SET XACT_ABORT ON;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_solicitar
  @DOCREC nvarchar(510),@USR nvarchar(100),@MOTIVO nvarchar(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC);
  EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510),@TIPO nvarchar(20);
  SELECT @ESTATUS=ESTATUS_REC,@NPED=NPED,@TIPO=TIPO_RECEPCION
  FROM dbo.REC_CTRL_DOC_REC WITH(UPDLOCK,HOLDLOCK) WHERE DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS='VALIDADO' BEGIN COMMIT; SELECT @DOCREC DOCREC,@ESTATUS ESTATUS_REC; RETURN; END;
  IF @ESTATUS<>'RECEPCION_FISICA' THROW 51000,'La recepcion no se puede validar en su estado actual.',1;
  IF @TIPO<>'RECHAZO' AND NOT EXISTS(
    SELECT 1 FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND ISNULL(CTD_ACEP,CTD)>0
  ) THROW 51000,'No hay cantidades aceptadas.',1;
  IF EXISTS(
    SELECT 1 FROM dbo.REC_CTO_HIST WHERE DOCREC=@DOCREC AND CALIDAD_ESTATUS='PENDIENTE'
  ) THROW 51000,'Existen validaciones de calidad pendientes.',1;
  UPDATE dbo.REC_CTRL_DOC_REC SET ESTATUS_REC='VALIDADO' WHERE DOCREC=@DOCREC;
  SELECT @SUC=h.SUC FROM dbo.REC_CAB_PED h WHERE h.NPED=@NPED;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'VALIDAR_RECEPCION','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,NULL,SYSDATETIME()
  FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,'VALIDADO' ESTATUS_REC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_autorizar
  @DOCREC nvarchar(510),@USR nvarchar(100),@MOTIVO nvarchar(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC);
  EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510),@ALMACEN varchar(10),@TIPO nvarchar(20);
  SELECT @ESTATUS=r.ESTATUS_REC,@NPED=r.NPED,@ALMACEN=COALESCE(NULLIF(r.ALMACEN,''),'002'),@TIPO=r.TIPO_RECEPCION,@SUC=h.SUC
  FROM dbo.REC_CTRL_DOC_REC r WITH(UPDLOCK,HOLDLOCK)
  JOIN dbo.REC_CAB_PED h WITH(UPDLOCK,HOLDLOCK) ON h.NPED=r.NPED WHERE r.DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS='CONTABILIZADO' BEGIN COMMIT; SELECT @DOCREC DOCREC,@ESTATUS ESTATUS_REC; RETURN; END;
  IF @ESTATUS NOT IN ('VALIDADO','PENDIENTE_AUTORIZACION') THROW 51000,'La recepcion no esta validada para autorizacion.',1;
  IF @TIPO='RECHAZO' THROW 51000,'Una recepcion rechazada no puede contabilizarse.',1;
  IF EXISTS(
    SELECT 1 FROM dbo.REC_CTO_HIST
    WHERE DOCREC=@DOCREC AND CALIDAD_ESTATUS IN ('PENDIENTE','RECHAZADO') AND ISNULL(CTD_ACEP,CTD)>0
  ) THROW 51000,'La calidad no permite contabilizar la recepcion.',1;

  IF NOT EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOCREC)
    INSERT dbo.DAT_CTR_DOC(DOC,CLSMOV,FCND,[USER],STAT) VALUES(@DOCREC,'101',SYSDATETIME(),@USR,'V');

  INSERT dbo.DAT_MB51(IDPD,[USER],CLSM,DOCP,ART,CTDA,CTOT,FCND,FCNC,TXT,ALMACEN,VTAESP,SUC)
  SELECT x.IDREC,@USR,101,@DOCREC,x.ART,ISNULL(x.CTD_ACEP,x.CTD),
         ISNULL(x.CTD_ACEP,x.CTD)*COALESCE(d.CTO,a.CTOP,0),SYSDATETIME(),SYSDATETIME(),@NPED,@ALMACEN,0,@SUC
  FROM dbo.REC_CTO_HIST x
  LEFT JOIN dbo.REC_DET_PED d ON d.IDPED=x.IDPED
  LEFT JOIN dbo.DAT_ART a ON a.SUC=@SUC AND a.ART=x.ART
  WHERE x.DOCREC=@DOCREC AND ISNULL(x.CTD_ACEP,x.CTD)>0
    AND NOT EXISTS(SELECT 1 FROM dbo.DAT_MB51 m WHERE m.IDPD=x.IDREC);

  ;WITH qty AS(
    SELECT ART,SUM(ISNULL(CTD_ACEP,CTD)) CTD FROM dbo.REC_CTO_HIST
    WHERE DOCREC=@DOCREC AND ISNULL(CTD_ACEP,CTD)>0 GROUP BY ART
  )
  UPDATE a SET STOCK=ISNULL(a.STOCK,0)+q.CTD
  FROM dbo.DAT_ART a JOIN qty q ON q.ART=a.ART WHERE a.SUC=@SUC;

  ;WITH qty AS(
    SELECT IDPED,SUM(ISNULL(CTD_ACEP,CTD)) CTD FROM dbo.REC_CTO_HIST
    WHERE DOCREC=@DOCREC AND IDPED IS NOT NULL GROUP BY IDPED
  )
  UPDATE d SET CTDREC=ISNULL(d.CTDREC,0)+q.CTD,
    RECI=CASE WHEN ISNULL(d.CTDREC,0)+q.CTD>=ISNULL(d.CTDPED,0) THEN -1 ELSE 0 END,DREC=@DOCREC
  FROM dbo.REC_DET_PED d JOIN qty q ON q.IDPED=d.IDPED;

  UPDATE dbo.REC_INCI_PED SET ESTATUS='AUTORIZADA',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME()
  WHERE DOCREC=@DOCREC AND ESTATUS='ABIERTA';
  UPDATE dbo.REC_CTRL_DOC_REC
  SET ESTATUS_REC='CONTABILIZADO',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME() WHERE DOCREC=@DOCREC;
  UPDATE dbo.REC_CAB_PED SET
    ESTATUS=CASE WHEN EXISTS(
      SELECT 1 FROM dbo.REC_DET_PED d WHERE d.NPED=@NPED AND ISNULL(d.BLOQ,0)<>-1
        AND ISNULL(d.CTDREC,0)<ISNULL(d.CTDPED,0)
    ) THEN 'PARCIAL' ELSE 'RECIBIDO' END,
    FCNR=CASE WHEN EXISTS(
      SELECT 1 FROM dbo.REC_DET_PED d WHERE d.NPED=@NPED AND ISNULL(d.BLOQ,0)<>-1
        AND ISNULL(d.CTDREC,0)<ISNULL(d.CTDPED,0)
    ) THEN FCNR ELSE SYSDATETIME() END
  WHERE NPED=@NPED;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'AUTORIZAR_CONTABILIZAR','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,
    CONCAT('{"movimiento":101,"almacen":"',STRING_ESCAPE(@ALMACEN,'json'),'"}'),SYSDATETIME()
  FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,'CONTABILIZADO' ESTATUS_REC;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_rechazar
  @DOCREC nvarchar(510),@USR nvarchar(100),@MOTIVO nvarchar(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC);
  EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510);
  SELECT @ESTATUS=r.ESTATUS_REC,@NPED=r.NPED,@SUC=h.SUC
  FROM dbo.REC_CTRL_DOC_REC r WITH(UPDLOCK,HOLDLOCK)
  JOIN dbo.REC_CAB_PED h ON h.NPED=r.NPED WHERE r.DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS='RECHAZADO' BEGIN COMMIT; SELECT @DOCREC DOCREC,@ESTATUS ESTATUS_REC; RETURN; END;
  IF @ESTATUS NOT IN ('RECEPCION_FISICA','VALIDADO','PENDIENTE_AUTORIZACION')
    THROW 51000,'La recepcion no se puede rechazar en su estado actual.',1;
  UPDATE dbo.REC_CTRL_DOC_REC SET ESTATUS_REC='RECHAZADO',USR_AUTORIZA=@USR,
    FCN_AUTORIZA=SYSDATETIME(),OBSERVACIONES=COALESCE(NULLIF(@MOTIVO,''),OBSERVACIONES)
  WHERE DOCREC=@DOCREC;
  UPDATE dbo.REC_INCI_PED SET ESTATUS='RECHAZADA',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME()
  WHERE DOCREC=@DOCREC AND ESTATUS='ABIERTA';
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'RECHAZAR','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,
    CASE WHEN @MOTIVO IS NULL THEN NULL ELSE CONCAT('{"motivo":"',STRING_ESCAPE(@MOTIVO,'json'),'"}') END,SYSDATETIME()
  FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,'RECHAZADO' ESTATUS_REC;
END;
GO
