/*
  Borrador persistente de captura para DAT_REC.
  Conserva cantidades, estatus por artículo y datos documentales antes de
  completar la recepción física.
*/
SET XACT_ABORT ON;
GO

IF OBJECT_ID('dbo.REC_BORRADOR_REC', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.REC_BORRADOR_REC(
    NPED nvarchar(100) NOT NULL CONSTRAINT PK_REC_BORRADOR_REC PRIMARY KEY,
    SUC nvarchar(20) NOT NULL,
    USR nvarchar(100) NOT NULL,
    TIPO_RECEPCION nvarchar(20) NULL,
    TIPO_DOC nvarchar(20) NULL,
    FOLIO_DOC nvarchar(100) NULL,
    GUIA nvarchar(100) NULL,
    PAQUETERIA nvarchar(120) NULL,
    OBSERVACIONES nvarchar(1000) NULL,
    FCNM datetime2(0) NOT NULL CONSTRAINT DF_REC_BORRADOR_REC_FCNM DEFAULT SYSDATETIME()
  );
END;
GO

IF OBJECT_ID('dbo.REC_BORRADOR_REC_DET', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.REC_BORRADOR_REC_DET(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_REC_BORRADOR_REC_DET PRIMARY KEY,
    NPED nvarchar(100) NOT NULL,
    IDPED nvarchar(510) NOT NULL,
    ART nvarchar(510) NOT NULL,
    CTD_REC float NOT NULL CONSTRAINT DF_REC_BORRADOR_REC_DET_CTD_REC DEFAULT 0,
    CTD_ACEP float NOT NULL CONSTRAINT DF_REC_BORRADOR_REC_DET_CTD_ACEP DEFAULT 0,
    ESTATUS nvarchar(20) NULL,
    CONSTRAINT FK_REC_BORRADOR_REC_DET_CAB FOREIGN KEY(NPED)
      REFERENCES dbo.REC_BORRADOR_REC(NPED) ON DELETE CASCADE
  );
  CREATE INDEX IX_REC_BORRADOR_REC_DET_NPED
    ON dbo.REC_BORRADOR_REC_DET(NPED) INCLUDE(ART,CTD_REC,CTD_ACEP,ESTATUS);
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_borrador_guardar
  @NPED nvarchar(100),
  @USR nvarchar(100),
  @TIPO_RECEPCION nvarchar(20)=NULL,
  @TIPO_DOC nvarchar(20)=NULL,
  @FOLIO_DOC nvarchar(100)=NULL,
  @GUIA nvarchar(100)=NULL,
  @PAQUETERIA nvarchar(120)=NULL,
  @OBSERVACIONES nvarchar(1000)=NULL,
  @ITEMS_JSON nvarchar(max)=N'[]'
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  IF ISJSON(@ITEMS_JSON)<>1 THROW 51000,'El borrador de artículos no es JSON válido.',1;

  DECLARE @SUC nvarchar(20);
  SELECT @SUC=UPPER(LTRIM(RTRIM(SUC)))
  FROM dbo.REC_CAB_PED
  WHERE NPED=@NPED;
  IF @SUC IS NULL THROW 51000,'La orden de compra no existe.',1;

  BEGIN TRANSACTION;
  MERGE dbo.REC_BORRADOR_REC WITH(HOLDLOCK) AS target
  USING (SELECT @NPED NPED) AS source ON source.NPED=target.NPED
  WHEN MATCHED THEN UPDATE SET
    SUC=@SUC,USR=@USR,TIPO_RECEPCION=NULLIF(@TIPO_RECEPCION,''),
    TIPO_DOC=NULLIF(@TIPO_DOC,''),FOLIO_DOC=NULLIF(@FOLIO_DOC,''),
    GUIA=NULLIF(@GUIA,''),PAQUETERIA=NULLIF(@PAQUETERIA,''),
    OBSERVACIONES=NULLIF(@OBSERVACIONES,''),FCNM=SYSDATETIME()
  WHEN NOT MATCHED THEN
    INSERT(NPED,SUC,USR,TIPO_RECEPCION,TIPO_DOC,FOLIO_DOC,GUIA,PAQUETERIA,OBSERVACIONES,FCNM)
    VALUES(@NPED,@SUC,@USR,NULLIF(@TIPO_RECEPCION,''),NULLIF(@TIPO_DOC,''),
      NULLIF(@FOLIO_DOC,''),NULLIF(@GUIA,''),NULLIF(@PAQUETERIA,''),
      NULLIF(@OBSERVACIONES,''),SYSDATETIME());

  DELETE dbo.REC_BORRADOR_REC_DET WHERE NPED=@NPED;
  INSERT dbo.REC_BORRADOR_REC_DET(NPED,IDPED,ART,CTD_REC,CTD_ACEP,ESTATUS)
  SELECT @NPED,LTRIM(RTRIM(IDPED)),LTRIM(RTRIM(ART)),
    COALESCE(CTD_REC,0),COALESCE(CTD_ACEP,0),
    CASE WHEN UPPER(LTRIM(RTRIM(ISNULL(ESTATUS,'')))) IN ('APROBADO','RECHAZADO','NO_APLICA')
      THEN UPPER(LTRIM(RTRIM(ESTATUS))) ELSE NULL END
  FROM OPENJSON(@ITEMS_JSON) WITH(
    IDPED nvarchar(510) '$.idped',
    ART nvarchar(510) '$.art',
    CTD_REC float '$.cantidadRecibida',
    CTD_ACEP float '$.cantidadAceptada',
    ESTATUS nvarchar(20) '$.estatus'
  )
  WHERE NULLIF(LTRIM(RTRIM(IDPED)),'') IS NOT NULL
    AND NULLIF(LTRIM(RTRIM(ART)),'') IS NOT NULL;
  COMMIT;
END;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_borrador_eliminar
  @NPED nvarchar(100)
AS
BEGIN
  SET NOCOUNT ON;
  DELETE dbo.REC_BORRADOR_REC WHERE NPED=@NPED;
END;
GO
