/*
  DEV_PROVD - Una sola evidencia por documento.
  La solicitud valida evidencia global y reserva solo los detalles activos.
*/
CREATE OR ALTER PROCEDURE dbo.sp_dev_provd_solicitar
  @DOC NVARCHAR(40), @USR NVARCHAR(100)
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON;
  BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @SUC NVARCHAR(20),@ESTATUS NVARCHAR(30),@LOCK INT,@LOCK_RESOURCE NVARCHAR(255);
    SELECT @SUC=SUC,@ESTATUS=ESTATUS FROM dbo.DEV_DOC_PROVD WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOC;
    IF @ESTATUS IS NULL THROW 59220,'La devolucion no existe.',1;
    IF @ESTATUS='PENDIENTE' BEGIN COMMIT; SELECT @DOC DOC,'PENDIENTE' ESTATUS; RETURN; END;
    IF @ESTATUS<>'BORRADOR' THROW 59221,'Solo se puede solicitar desde BORRADOR.',1;
    SET @LOCK_RESOURCE=CONCAT('DEV_PROVD_RESERVA_',@SUC);
    EXEC @LOCK=sys.sp_getapplock @Resource=@LOCK_RESOURCE,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
    IF @LOCK<0 THROW 59222,'No fue posible bloquear el inventario para validar.',1;
    IF NOT EXISTS(SELECT 1 FROM dbo.DEV_CTRL_PROVD WHERE DOC=@DOC AND ACTIVO=1) THROW 59223,'La devolucion no tiene articulos.',1;
    IF NOT EXISTS(
      SELECT 1 FROM dbo.DEV_EVIDENCIA_PROVD e
      JOIN dbo.DEV_CTRL_PROVD d ON d.IDPD=e.IDPD
      WHERE d.DOC=@DOC AND d.ACTIVO=1
    ) THROW 59224,'La devolucion requiere una evidencia fotografica.',1;
    IF EXISTS(
      SELECT 1 FROM dbo.DEV_CTRL_PROVD d JOIN dbo.DEV_MOTIVO_PROVD m ON m.ID=d.MOV_DEV JOIN dbo.DEV_DOC_PROVD h ON h.DOC=d.DOC
      WHERE d.DOC=@DOC AND d.ACTIVO=1 AND m.REQUIERE_DOCUMENTO=1 AND NULLIF(LTRIM(RTRIM(COALESCE(h.DOC_REC,h.DOC_OC,''))),'') IS NULL
    ) THROW 59225,'El motivo requiere orden de compra o recepcion relacionada.',1;

    IF EXISTS(
      SELECT 1 FROM (SELECT ART,SUM(CTDA_DEV) CTD FROM dbo.DEV_CTRL_PROVD WHERE DOC=@DOC AND ACTIVO=1 GROUP BY ART) s
      LEFT JOIN dbo.DAT_ART a WITH(UPDLOCK,HOLDLOCK) ON a.SUC=@SUC AND a.ART=s.ART
      OUTER APPLY(SELECT SUM(x.CTDA_BLOQ) CTD FROM dbo.DEV_CTRL_PROVD x JOIN dbo.DEV_DOC_PROVD h ON h.DOC=x.DOC WHERE h.SUC=@SUC AND h.ESTATUS='PENDIENTE' AND x.ACTIVO=1 AND x.DOC<>@DOC AND x.ART=s.ART) r
      WHERE a.ART IS NULL OR ISNULL(a.STOCK,0)-ISNULL(r.CTD,0)<s.CTD
    ) THROW 59226,'Existencia disponible insuficiente para reservar.',1;

    UPDATE dbo.DEV_CTRL_PROVD SET CTDA_BLOQ=CTDA_DEV,FCNM=SYSDATETIME() WHERE DOC=@DOC AND ACTIVO=1;
    UPDATE dbo.DEV_DOC_PROVD SET ESTATUS='PENDIENTE',USR_SOLICITA=@USR,FCN_SOLICITA=SYSDATETIME(),FCNM=SYSDATETIME() WHERE DOC=@DOC;
    INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
    SELECT IDUSUARIO,'SOLICITAR_RESERVAR','DEV_PROVD','DEV_DOC_PROVD',@DOC,@SUC,NULL,SYSDATETIME() FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
    COMMIT;
    SELECT @DOC DOC,'PENDIENTE' ESTATUS;
  END TRY
  BEGIN CATCH
    IF XACT_STATE()<>0 ROLLBACK;
    THROW;
  END CATCH
END;
GO
