/*
  2026-03-15_facturacion_reconcile_impt_from_detail.sql

  Objetivo:
  - Corregir diferencias de centavos en facturación ya existente.
  - Alinear FAC_SVR_SHAP.IMPT contra el total derivado del detalle FACT_TICKET_SHP.

  Fórmula alineada con validación de API:
  - total_detalle = SUM( ROUND(PVTAT + ROUND(PVTAT * 0.16, 2), 2) )
  - redondeo final a 2 decimales.

  Alcance:
  - Solo folios con estatus PENDIENTE o CANCELACION PENDIENTE (si existe columna ESTATUS).
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID('dbo.FAC_SVR_SHAP', 'U') IS NULL
  THROW 50001, 'No existe dbo.FAC_SVR_SHAP', 1;
IF OBJECT_ID('dbo.FACT_TICKET_SHP', 'U') IS NULL
  THROW 50002, 'No existe dbo.FACT_TICKET_SHP', 1;

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'IDFOL') IS NULL
  THROW 50003, 'dbo.FAC_SVR_SHAP no contiene IDFOL', 1;
IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'IMPT') IS NULL
  THROW 50004, 'dbo.FAC_SVR_SHAP no contiene IMPT', 1;
IF COL_LENGTH('dbo.FACT_TICKET_SHP', 'IDFOL') IS NULL
  THROW 50005, 'dbo.FACT_TICKET_SHP no contiene IDFOL', 1;
IF COL_LENGTH('dbo.FACT_TICKET_SHP', 'PVTAT') IS NULL
  THROW 50006, 'dbo.FACT_TICKET_SHP no contiene PVTAT', 1;

IF OBJECT_ID('tempdb..#FACT_IMPT_AJUSTES') IS NOT NULL
  DROP TABLE #FACT_IMPT_AJUSTES;

CREATE TABLE #FACT_IMPT_AJUSTES (
  IDFOL NVARCHAR(255) NOT NULL,
  IMPT_ANTERIOR MONEY NULL,
  IMPT_NUEVO MONEY NULL,
  DIFERENCIA MONEY NULL
);

DECLARE @statusWhere NVARCHAR(300) = N'1=1';
DECLARE @sql NVARCHAR(MAX);

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'ESTATUS') IS NOT NULL
BEGIN
  SET @statusWhere = N'UPPER(LTRIM(RTRIM(ISNULL(F.ESTATUS, '''')))) IN (''PENDIENTE'', ''CANCELACION PENDIENTE'')';
END;

SET @sql = N'
;WITH DET AS (
  SELECT
    T.IDFOL,
    ROUND(
      SUM(
        ROUND(ISNULL(TRY_CONVERT(MONEY, T.PVTAT), 0) + ROUND(ISNULL(TRY_CONVERT(MONEY, T.PVTAT), 0) * 0.16, 2), 2)
      ),
      2
    ) AS IMPT_DETALLE
  FROM dbo.FACT_TICKET_SHP T
  GROUP BY T.IDFOL
),
TARGET AS (
  SELECT
    F.IDFOL,
    TRY_CONVERT(MONEY, F.IMPT) AS IMPT_ANTERIOR,
    ISNULL(D.IMPT_DETALLE, 0) AS IMPT_NUEVO,
    ROUND(ISNULL(D.IMPT_DETALLE, 0) - ISNULL(TRY_CONVERT(MONEY, F.IMPT), 0), 2) AS DIFERENCIA
  FROM dbo.FAC_SVR_SHAP F
  INNER JOIN DET D
    ON D.IDFOL = F.IDFOL
  WHERE ' + @statusWhere + N'
)
UPDATE F
SET IMPT = T.IMPT_NUEVO
OUTPUT
  inserted.IDFOL,
  deleted.IMPT,
  inserted.IMPT,
  ROUND(inserted.IMPT - deleted.IMPT, 2)
INTO #FACT_IMPT_AJUSTES (IDFOL, IMPT_ANTERIOR, IMPT_NUEVO, DIFERENCIA)
FROM dbo.FAC_SVR_SHAP F
INNER JOIN TARGET T
  ON T.IDFOL = F.IDFOL
WHERE ABS(ISNULL(T.DIFERENCIA, 0)) >= 0.01;
';

EXEC sys.sp_executesql @sql;

SELECT
  COUNT(1) AS FOLIOS_AJUSTADOS,
  ROUND(SUM(ISNULL(DIFERENCIA, 0)), 2) AS DIFERENCIA_ACUMULADA
FROM #FACT_IMPT_AJUSTES;

SELECT
  IDFOL,
  IMPT_ANTERIOR,
  IMPT_NUEVO,
  DIFERENCIA
FROM #FACT_IMPT_AJUSTES
ORDER BY ABS(ISNULL(DIFERENCIA, 0)) DESC, IDFOL;

