USE IOELOCAL;
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @checkDefinition NVARCHAR(MAX);

SELECT @checkDefinition = cc.definition
FROM sys.check_constraints AS cc
WHERE cc.name = 'CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO'
  AND cc.parent_object_id = OBJECT_ID('dbo.PV_CTR_FOL_ASVR');

IF @checkDefinition IS NULL
  OR @checkDefinition NOT LIKE '%ANULADO%'
  OR @checkDefinition NOT LIKE '%MB51PROCES%'
  OR @checkDefinition NOT LIKE '%CERRADO_PS%'
BEGIN
  IF @checkDefinition IS NOT NULL
  BEGIN
    ALTER TABLE dbo.PV_CTR_FOL_ASVR
    DROP CONSTRAINT CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO;
  END;

  ALTER TABLE dbo.PV_CTR_FOL_ASVR WITH NOCHECK
  ADD CONSTRAINT CK_PV_CTR_FOL_ASVR_ESTA_HOMOLOGADO
  CHECK (ESTA IN ('PENDIENTE', 'PAGADO', 'CERRADO_PS', 'MB51PROCES', 'TRANSMITIR', 'ANULADO'));
END;

GO

CREATE OR ALTER TRIGGER dbo.trg_pv_ctr_fol_asvr_homologacion
ON dbo.PV_CTR_FOL_ASVR
AFTER INSERT, UPDATE
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE t
  SET
    t.AUT = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) = 'PCR' THEN 'CR'
      ELSE UPPER(LTRIM(RTRIM(ISNULL(t.AUT, 'CP'))))
    END,
    t.ESTA = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) IN ('EDITANDO', 'DEV PEND', 'PAGADO2', '') THEN 'PENDIENTE'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'PAGADO%' THEN 'PAGADO'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) IN ('CERRADOPS', 'CERRADO PS') THEN 'CERRADO_PS'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'CERRADO_PS%' THEN 'CERRADO_PS'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) LIKE 'TRANSMIT%' THEN 'TRANSMITIR'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, '')))) = 'MB51PROCES' THEN 'MB51PROCES'
      ELSE UPPER(LTRIM(RTRIM(ISNULL(t.ESTA, ''))))
    END,
    t.IDFOLINICIAL = ISNULL(NULLIF(LTRIM(RTRIM(t.IDFOLINICIAL)), ''), t.IDFOL),
    t.ORIGEN_AUT = CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('DCA', 'CA', 'DC', 'DG') THEN 'CA'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('DVF', 'VF') THEN 'VF'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('PS', 'CP') THEN ISNULL(NULLIF(UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT, '')))), ''), 'CA')
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.AUT, '')))) IN ('AD', 'AP', 'CR', 'PCR') THEN ISNULL(NULLIF(UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT, '')))), ''), 'CA')
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORIGEN_AUT, '')))) IN ('CA', 'VF') THEN UPPER(LTRIM(RTRIM(t.ORIGEN_AUT)))
      ELSE 'CA'
    END
  FROM dbo.PV_CTR_FOL_ASVR t
  INNER JOIN inserted i ON i.IDFOL = t.IDFOL;
END;

GO

UPDATE dbo.PV_CTR_FOL_ASVR
SET ESTA = 'MB51PROCES'
WHERE UPPER(LTRIM(RTRIM(ISNULL(ESTA, '')))) LIKE 'TRANSMIT%'
  AND UPPER(LTRIM(RTRIM(ISNULL(AUT, '')))) NOT IN ('AD', 'AP', 'CR', 'DC', 'DG', 'DP');

GO
