SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRAN;

  -- 1) ROL: agregar IDDEPTO
  IF COL_LENGTH('dbo.ROL', 'IDDEPTO') IS NULL
  BEGIN
    ALTER TABLE dbo.ROL
      ADD IDDEPTO INT NULL;
  END;

  -- 2) Validar orfandad y crear FK ROL.IDDEPTO -> DEPARTAMENTO.IDDEPTO
  IF OBJECT_ID('dbo.FK_ROL_DEPARTAMENTO_IDDEPTO', 'F') IS NULL
  BEGIN
    EXEC sp_executesql N'
      IF EXISTS (
        SELECT 1
        FROM dbo.ROL r
        LEFT JOIN dbo.DEPARTAMENTO d ON d.IDDEPTO = r.IDDEPTO
        WHERE r.IDDEPTO IS NOT NULL
          AND d.IDDEPTO IS NULL
      )
      BEGIN
        THROW 51001, ''Existen registros en ROL con IDDEPTO sin correspondencia en DEPARTAMENTO.'', 1;
      END;
    ';

    EXEC sp_executesql N'
      ALTER TABLE dbo.ROL WITH CHECK
        ADD CONSTRAINT FK_ROL_DEPARTAMENTO_IDDEPTO
        FOREIGN KEY (IDDEPTO)
        REFERENCES dbo.DEPARTAMENTO(IDDEPTO);
    ';
  END;

  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.ROL')
      AND name = 'IX_ROL_IDDEPTO'
  )
  BEGIN
    EXEC sp_executesql N'CREATE INDEX IX_ROL_IDDEPTO ON dbo.ROL(IDDEPTO);';
  END;

  -- 3) Normalizar ROLE_CODE en matriz de visibilidad
  UPDATE dbo.DAT_JAO_ORD_FLUJO_VIS
  SET ROLE_CODE = UPPER(LTRIM(RTRIM(ROLE_CODE)))
  WHERE ROLE_CODE <> UPPER(LTRIM(RTRIM(ROLE_CODE)));

  -- 4) Reasignar aliases legacy a códigos reales existentes en ROL
  DELETE src
  FROM dbo.DAT_JAO_ORD_FLUJO_VIS src
  WHERE UPPER(LTRIM(RTRIM(src.ROLE_CODE))) = 'ANALISTA'
    AND EXISTS (
      SELECT 1
      FROM dbo.DAT_JAO_ORD_FLUJO_VIS tgt
      WHERE UPPER(LTRIM(RTRIM(tgt.MODULO))) = UPPER(LTRIM(RTRIM(src.MODULO)))
        AND LOWER(LTRIM(RTRIM(tgt.PANEL_MODE))) = LOWER(LTRIM(RTRIM(src.PANEL_MODE)))
        AND ROUND(CONVERT(decimal(10,3), tgt.ESTA), 3) = ROUND(CONVERT(decimal(10,3), src.ESTA), 3)
        AND UPPER(LTRIM(RTRIM(tgt.ROLE_CODE))) = 'ANALISTA_ORD'
    );

  UPDATE dbo.DAT_JAO_ORD_FLUJO_VIS
  SET ROLE_CODE = 'ANALISTA_ORD'
  WHERE UPPER(LTRIM(RTRIM(ROLE_CODE))) = 'ANALISTA';

  DELETE src
  FROM dbo.DAT_JAO_ORD_FLUJO_VIS src
  WHERE UPPER(LTRIM(RTRIM(src.ROLE_CODE))) = 'ENCARGADO_BISELADO'
    AND EXISTS (
      SELECT 1
      FROM dbo.DAT_JAO_ORD_FLUJO_VIS tgt
      WHERE UPPER(LTRIM(RTRIM(tgt.MODULO))) = UPPER(LTRIM(RTRIM(src.MODULO)))
        AND LOWER(LTRIM(RTRIM(tgt.PANEL_MODE))) = LOWER(LTRIM(RTRIM(src.PANEL_MODE)))
        AND ROUND(CONVERT(decimal(10,3), tgt.ESTA), 3) = ROUND(CONVERT(decimal(10,3), src.ESTA), 3)
        AND UPPER(LTRIM(RTRIM(tgt.ROLE_CODE))) = 'ENC_BISEL'
    );

  UPDATE dbo.DAT_JAO_ORD_FLUJO_VIS
  SET ROLE_CODE = 'ENC_BISEL'
  WHERE UPPER(LTRIM(RTRIM(ROLE_CODE))) = 'ENCARGADO_BISELADO';

  DELETE src
  FROM dbo.DAT_JAO_ORD_FLUJO_VIS src
  WHERE UPPER(LTRIM(RTRIM(src.ROLE_CODE))) = 'ENCARGADO_MAQUILA'
    AND EXISTS (
      SELECT 1
      FROM dbo.DAT_JAO_ORD_FLUJO_VIS tgt
      WHERE UPPER(LTRIM(RTRIM(tgt.MODULO))) = UPPER(LTRIM(RTRIM(src.MODULO)))
        AND LOWER(LTRIM(RTRIM(tgt.PANEL_MODE))) = LOWER(LTRIM(RTRIM(src.PANEL_MODE)))
        AND ROUND(CONVERT(decimal(10,3), tgt.ESTA), 3) = ROUND(CONVERT(decimal(10,3), src.ESTA), 3)
        AND UPPER(LTRIM(RTRIM(tgt.ROLE_CODE))) = 'ENC_MAQUILA'
    );

  UPDATE dbo.DAT_JAO_ORD_FLUJO_VIS
  SET ROLE_CODE = 'ENC_MAQUILA'
  WHERE UPPER(LTRIM(RTRIM(ROLE_CODE))) = 'ENCARGADO_MAQUILA';

  -- eliminar roles temporales si quedaron sin referencia
  DELETE r
  FROM dbo.ROL r
  WHERE UPPER(LTRIM(RTRIM(r.CODIGO))) IN ('ANALISTA', 'ENCARGADO_BISELADO', 'ENCARGADO_MAQUILA')
    AND NOT EXISTS (
      SELECT 1
      FROM dbo.DAT_JAO_ORD_FLUJO_VIS v
      WHERE UPPER(LTRIM(RTRIM(v.ROLE_CODE))) = UPPER(LTRIM(RTRIM(r.CODIGO)))
    );

  -- 5) FK DAT_JAO_ORD_FLUJO_VIS.ROLE_CODE -> ROL.CODIGO
  IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.DAT_JAO_ORD_FLUJO_VIS')
      AND name = 'IX_DAT_JAO_ORD_FLUJO_VIS_ROLE_CODE'
  )
  BEGIN
    CREATE INDEX IX_DAT_JAO_ORD_FLUJO_VIS_ROLE_CODE
      ON dbo.DAT_JAO_ORD_FLUJO_VIS(ROLE_CODE);
  END;

  IF OBJECT_ID('dbo.FK_DAT_JAO_ORD_FLUJO_VIS_ROLE_CODE_ROL', 'F') IS NULL
  BEGIN
    IF EXISTS (
      SELECT 1
      FROM dbo.DAT_JAO_ORD_FLUJO_VIS v
      LEFT JOIN dbo.ROL r
        ON r.CODIGO = v.ROLE_CODE
      WHERE r.IDROL IS NULL
    )
    BEGIN
      THROW 51002, 'Existen ROLE_CODE en DAT_JAO_ORD_FLUJO_VIS sin correspondencia en ROL.CODIGO.', 1;
    END;

    ALTER TABLE dbo.DAT_JAO_ORD_FLUJO_VIS WITH CHECK
      ADD CONSTRAINT FK_DAT_JAO_ORD_FLUJO_VIS_ROLE_CODE_ROL
      FOREIGN KEY (ROLE_CODE)
      REFERENCES dbo.ROL(CODIGO);
  END;

  COMMIT TRAN;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRAN;
  THROW;
END CATCH;
