/*
  2026-03-23_facturacion_reset_cfdi40108_pending.sql

  Objetivo:
  - Dejar en estado operativo de reintento los folios de facturación que
    quedaron con error CFDI40108.
  - Solo aplica a registros con ESTATUS='PENDIENTE'.
  - No modifica importes ni detalle de FACT_TICKET_SHP.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID('dbo.FAC_SVR_SHAP', 'U') IS NULL
  THROW 50001, 'No existe dbo.FAC_SVR_SHAP', 1;

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'IDFOL') IS NULL
  THROW 50002, 'dbo.FAC_SVR_SHAP no contiene IDFOL', 1;
IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'ESTATUS') IS NULL
  THROW 50003, 'dbo.FAC_SVR_SHAP no contiene ESTATUS', 1;
IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_STATUS') IS NULL
  THROW 50004, 'dbo.FAC_SVR_SHAP no contiene CFDI_STATUS', 1;
IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'CFDI_ERROR_MSG') IS NULL
  THROW 50005, 'dbo.FAC_SVR_SHAP no contiene CFDI_ERROR_MSG', 1;

IF OBJECT_ID('tempdb..#FACT_RESET_CFDI40108') IS NOT NULL
  DROP TABLE #FACT_RESET_CFDI40108;

CREATE TABLE #FACT_RESET_CFDI40108 (
  IDFOL NVARCHAR(255) NOT NULL,
  ESTATUS NVARCHAR(80) NULL,
  CFDI_STATUS_ANTERIOR NVARCHAR(80) NULL,
  ERROR_MSG_ANTERIOR NVARCHAR(MAX) NULL
);

UPDATE F
SET
  CFDI_STATUS = 'PENDIENTE',
  CFDI_ERROR_MSG = NULL
OUTPUT
  inserted.IDFOL,
  inserted.ESTATUS,
  deleted.CFDI_STATUS,
  deleted.CFDI_ERROR_MSG
INTO #FACT_RESET_CFDI40108 (IDFOL, ESTATUS, CFDI_STATUS_ANTERIOR, ERROR_MSG_ANTERIOR)
FROM dbo.FAC_SVR_SHAP F
WHERE UPPER(LTRIM(RTRIM(ISNULL(F.ESTATUS, '')))) = 'PENDIENTE'
  AND UPPER(LTRIM(RTRIM(ISNULL(F.CFDI_STATUS, '')))) = 'ERROR'
  AND (
    ISNULL(F.CFDI_ERROR_MSG, '') LIKE '%CFDI40108%'
    OR ISNULL(F.CFDI_ERROR_MSG, '') LIKE '%importe registrado en el campo no es igual al redondeo%'
  );

SELECT
  COUNT(1) AS FOLIOS_RESET
FROM #FACT_RESET_CFDI40108;

SELECT
  IDFOL,
  ESTATUS,
  CFDI_STATUS_ANTERIOR
FROM #FACT_RESET_CFDI40108
ORDER BY IDFOL;
