SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF OBJECT_ID('dbo.DAT_FORM', 'U') IS NULL
    THROW 52001, 'No existe dbo.DAT_FORM. Ejecute sql/DAT_FORM_schema_alter.sql', 1;

  IF EXISTS (
    SELECT 1
    FROM dbo.DAT_FORM
    WHERE UPPER(LTRIM(RTRIM(ISNULL(FORM, '')))) = 'TARJETA CREDITO'
  )
  BEGIN
    UPDATE dbo.DAT_FORM
    SET
      ASPEL = 4,
      NOM = COALESCE(NULLIF(LTRIM(RTRIM(ISNULL(NOM, ''))), ''), 'TARJETA CREDITO'),
      ESTADO = 1
    WHERE UPPER(LTRIM(RTRIM(ISNULL(FORM, '')))) = 'TARJETA CREDITO';
  END
  ELSE
  BEGIN
    INSERT INTO dbo.DAT_FORM (ASPEL, FORM, NOM, ESTADO)
    VALUES (4, 'TARJETA CREDITO', 'TARJETA CREDITO', 1);
  END

  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
