/*
  DAT_REC: cierre definitivo de la O.C. al contabilizar.
  - La recepción y la cabecera de la O.C. quedan CONTABILIZADO.
  - Los faltantes permanecen en REC_DET_PED/REC_CTO_HIST como evidencia.
  - Regulariza todas las cabeceras PARCIAL que ya tienen una recepción
    CONTABILIZADO, sin modificar cantidades ni movimientos de inventario.
*/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.sp_rec_recepcion_autorizar
  @DOCREC nvarchar(510),@USR nvarchar(100),@MOTIVO nvarchar(1000)=NULL
AS
BEGIN
  SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION;
  DECLARE @lock int,@lock_resource nvarchar(255)=CONCAT('DAT_REC_DOC_',@DOCREC);
  EXEC @lock=sys.sp_getapplock @Resource=@lock_resource,@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=15000;
  IF @lock<0 THROW 51000,'No fue posible bloquear la recepcion.',1;
  DECLARE @ESTATUS nvarchar(30),@NPED nvarchar(510),@SUC nvarchar(510),@ALMACEN varchar(10),@TIPO nvarchar(20);
  SELECT @ESTATUS=r.ESTATUS_REC,@NPED=r.NPED,@ALMACEN=COALESCE(NULLIF(r.ALMACEN,''),'002'),@TIPO=r.TIPO_RECEPCION,@SUC=h.SUC
  FROM dbo.REC_CTRL_DOC_REC r WITH(UPDLOCK,HOLDLOCK)
  JOIN dbo.REC_CAB_PED h WITH(UPDLOCK,HOLDLOCK) ON h.NPED=r.NPED WHERE r.DOCREC=@DOCREC;
  IF @ESTATUS IS NULL THROW 51000,'La recepcion no existe.',1;
  IF @ESTATUS='CONTABILIZADO' BEGIN COMMIT; SELECT @DOCREC DOCREC,@ESTATUS ESTATUS_REC; RETURN; END;
  IF @ESTATUS NOT IN ('VALIDADO','PENDIENTE_AUTORIZACION') THROW 51000,'La recepcion no esta validada para autorizacion.',1;
  IF @TIPO='RECHAZO' THROW 51000,'Una recepcion rechazada no puede contabilizarse.',1;
  IF EXISTS(
    SELECT 1 FROM dbo.REC_CTO_HIST
    WHERE DOCREC=@DOCREC AND CALIDAD_ESTATUS IN ('PENDIENTE','RECHAZADO') AND ISNULL(CTD_ACEP,CTD)>0
  ) THROW 51000,'La calidad no permite contabilizar la recepcion.',1;

  IF NOT EXISTS(SELECT 1 FROM dbo.DAT_CTR_DOC WITH(UPDLOCK,HOLDLOCK) WHERE DOC=@DOCREC)
    INSERT dbo.DAT_CTR_DOC(DOC,CLSMOV,FCND,[USER],STAT) VALUES(@DOCREC,'101',SYSDATETIME(),@USR,'V');

  INSERT dbo.DAT_MB51(IDPD,[USER],CLSM,DOCP,ART,CTDA,CTOT,FCND,FCNC,TXT,ALMACEN,VTAESP,SUC)
  SELECT x.IDREC,@USR,101,@DOCREC,x.ART,ISNULL(x.CTD_ACEP,x.CTD),
         ISNULL(x.CTD_ACEP,x.CTD)*COALESCE(d.CTO,a.CTOP,0),SYSDATETIME(),SYSDATETIME(),@NPED,@ALMACEN,0,@SUC
  FROM dbo.REC_CTO_HIST x
  LEFT JOIN dbo.REC_DET_PED d ON d.IDPED=x.IDPED
  LEFT JOIN dbo.DAT_ART a ON a.SUC=@SUC AND a.ART=x.ART
  WHERE x.DOCREC=@DOCREC AND ISNULL(x.CTD_ACEP,x.CTD)>0
    AND NOT EXISTS(SELECT 1 FROM dbo.DAT_MB51 m WHERE m.IDPD=x.IDREC);

  ;WITH qty AS(
    SELECT ART,SUM(ISNULL(CTD_ACEP,CTD)) CTD FROM dbo.REC_CTO_HIST
    WHERE DOCREC=@DOCREC AND ISNULL(CTD_ACEP,CTD)>0 GROUP BY ART
  )
  UPDATE a SET STOCK=ISNULL(a.STOCK,0)+q.CTD
  FROM dbo.DAT_ART a JOIN qty q ON q.ART=a.ART WHERE a.SUC=@SUC;

  ;WITH qty AS(
    SELECT IDPED,SUM(ISNULL(CTD_ACEP,CTD)) CTD FROM dbo.REC_CTO_HIST
    WHERE DOCREC=@DOCREC AND IDPED IS NOT NULL GROUP BY IDPED
  )
  UPDATE d SET CTDREC=ISNULL(d.CTDREC,0)+q.CTD,
    RECI=CASE WHEN ISNULL(d.CTDREC,0)+q.CTD>=ISNULL(d.CTDPED,0) THEN -1 ELSE 0 END,DREC=@DOCREC
  FROM dbo.REC_DET_PED d JOIN qty q ON q.IDPED=d.IDPED;

  UPDATE dbo.REC_INCI_PED SET ESTATUS='AUTORIZADA',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME()
  WHERE DOCREC=@DOCREC AND ESTATUS='ABIERTA';
  UPDATE dbo.REC_CTRL_DOC_REC
  SET ESTATUS_REC='CONTABILIZADO',USR_AUTORIZA=@USR,FCN_AUTORIZA=SYSDATETIME() WHERE DOCREC=@DOCREC;
  UPDATE dbo.REC_CAB_PED
  SET ESTATUS='CONTABILIZADO',FCNR=COALESCE(FCNR,SYSDATETIME())
  WHERE NPED=@NPED;
  INSERT dbo.AUDIT_LOG(IDUSUARIO,ACTION,MODULO,ENTIDAD,ENTIDAD_ID,SUC,METADATA_JSON,FCNR)
  SELECT IDUSUARIO,'AUTORIZAR_CONTABILIZAR','DAT_REC','REC_CTRL_DOC_REC',@DOCREC,@SUC,
    CONCAT('{"movimiento":101,"almacen":"',STRING_ESCAPE(@ALMACEN,'json'),'"}'),SYSDATETIME()
  FROM dbo.USUARIO WHERE UPPER(USERNAME)=UPPER(@USR);
  COMMIT; SELECT @DOCREC DOCREC,'CONTABILIZADO' ESTATUS_REC;
END;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
  BEGIN TRANSACTION;

  IF EXISTS(
    SELECT 1
    FROM dbo.REC_CAB_PED h WITH(UPDLOCK,HOLDLOCK)
    WHERE UPPER(LTRIM(RTRIM(ISNULL(h.ESTATUS,''))))='PARCIAL'
      AND NOT EXISTS(
        SELECT 1 FROM dbo.REC_CTRL_DOC_REC r
        WHERE r.NPED=h.NPED
          AND UPPER(LTRIM(RTRIM(ISNULL(r.ESTATUS_REC,''))))='CONTABILIZADO'
      )
  ) THROW 51000,'Existen O.C. PARCIAL sin recepcion contabilizada; no se aplico la regularizacion.',1;

  DECLARE @actualizados int;
  UPDATE h
  SET ESTATUS='CONTABILIZADO',FCNR=COALESCE(h.FCNR,SYSDATETIME())
  FROM dbo.REC_CAB_PED h
  WHERE UPPER(LTRIM(RTRIM(ISNULL(h.ESTATUS,''))))='PARCIAL'
    AND EXISTS(
      SELECT 1 FROM dbo.REC_CTRL_DOC_REC r
      WHERE r.NPED=h.NPED
        AND UPPER(LTRIM(RTRIM(ISNULL(r.ESTATUS_REC,''))))='CONTABILIZADO'
    );
  SET @actualizados=@@ROWCOUNT;

  IF EXISTS(
    SELECT 1 FROM dbo.REC_CAB_PED
    WHERE UPPER(LTRIM(RTRIM(ISNULL(ESTATUS,''))))='PARCIAL'
  ) THROW 51000,'Persisten O.C. PARCIAL despues de la regularizacion.',1;

  COMMIT;
  SELECT @actualizados AS ORDENES_ACTUALIZADAS,'CONTABILIZADO' AS NUEVO_ESTATUS;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT>0 ROLLBACK;
  THROW;
END CATCH;
GO
