/*
  Indices para acelerar deteccion de promociones por renglon.
*/
USE IOELOCAL;
GO

IF OBJECT_ID('dbo.PROMO_CAB', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PROMO_CAB')
    AND name = 'IX_PROMO_CAB_EST_FECHAS_PRIO'
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_PROMO_CAB_EST_FECHAS_PRIO
    ON dbo.PROMO_CAB (EST, FCN_INI, FCN_TER, PRIORIDAD, ID_PROM)
    INCLUDE (SUC, T_PROM, ACUMULABLE);
END
GO

IF OBJECT_ID('dbo.PROMO_REGLA_CRITERIO', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PROMO_REGLA_CRITERIO')
    AND name = 'IX_PROMO_REGLA_CRITERIO_LOOKUP'
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_PROMO_REGLA_CRITERIO_LOOKUP
    ON dbo.PROMO_REGLA_CRITERIO (
      ID_PROM, EST, SUC, CLIENTE, DEPA, SUBD, CLAS, SCLA, SCLA2, GUIA, ART, UPC
    );
END
GO

IF OBJECT_ID('dbo.PROMO_REGLA_BENEFICIO', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PROMO_REGLA_BENEFICIO')
    AND name = 'IX_PROMO_REGLA_BENEFICIO_LOOKUP'
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_PROMO_REGLA_BENEFICIO_LOOKUP
    ON dbo.PROMO_REGLA_BENEFICIO (ID_PROM, EST, T_BENEFICIO, ID_BENEFICIO)
    INCLUDE (PRC_DESC, IMP_DESC, PRECIO_GRATIS);
END
GO

IF OBJECT_ID('dbo.DAT_ART', 'U') IS NOT NULL
AND NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.DAT_ART')
    AND name = 'IX_DAT_ART_SUC_ART_UPC_PROMO'
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_DAT_ART_SUC_ART_UPC_PROMO
    ON dbo.DAT_ART (SUC, ART, UPC)
    INCLUDE (PVTA, DEPA, SUBD, CLAS, SCLA, SCLA2, DES);
END
GO

