/*
  2026-05-04
  Politica front por usuario:
  - Crea tabla dbo.USR_GRUPMOD_FRONT para asignar grupos front por usuario.
  - Prioridad esperada en API:
      1) Si usuario tiene filas activas en USR_GRUPMOD_FRONT, usar esas.
      2) Si no, fallback a ROL_GRUPMOD_FRONT.
*/

SET NOCOUNT ON;

IF OBJECT_ID('dbo.USR_GRUPMOD_FRONT', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.USR_GRUPMOD_FRONT
  (
    IDUSUARIO        INT          NOT NULL,
    IDGRUPMOD_FRONT  INT          NOT NULL, -- 0 = acceso total
    ACTIVO           BIT          NOT NULL CONSTRAINT DF_USR_GRUPMOD_FRONT_ACTIVO DEFAULT (1),
    FCNR             DATETIME2(0) NOT NULL CONSTRAINT DF_USR_GRUPMOD_FRONT_FCNR DEFAULT (SYSDATETIME()),
    CONSTRAINT PK_USR_GRUPMOD_FRONT PRIMARY KEY (IDUSUARIO, IDGRUPMOD_FRONT)
  );
END;
GO

IF OBJECT_ID('dbo.FK_USR_GRUPMOD_FRONT_USUARIO', 'F') IS NULL
BEGIN
  ALTER TABLE dbo.USR_GRUPMOD_FRONT
    ADD CONSTRAINT FK_USR_GRUPMOD_FRONT_USUARIO
    FOREIGN KEY (IDUSUARIO) REFERENCES dbo.USUARIO(IDUSUARIO);
END;
GO

IF OBJECT_ID('dbo.FK_USR_GRUPMOD_FRONT_GRUPO', 'F') IS NOT NULL
BEGIN
  ALTER TABLE dbo.USR_GRUPMOD_FRONT
    DROP CONSTRAINT FK_USR_GRUPMOD_FRONT_GRUPO;
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.USR_GRUPMOD_FRONT')
    AND name = 'IX_USR_GRUPMOD_FRONT_USUARIO_ACTIVO'
)
BEGIN
  CREATE INDEX IX_USR_GRUPMOD_FRONT_USUARIO_ACTIVO
    ON dbo.USR_GRUPMOD_FRONT (IDUSUARIO, ACTIVO);
END;
GO

PRINT 'OK: dbo.USR_GRUPMOD_FRONT listo.';
