SET DATEFORMAT dmy;
SET NOCOUNT ON;
SET XACT_ABORT ON;

DECLARE @FechaInicio DATE = '01/01/2026';

-- limpieza de tablas temporales de proceso
DELETE FROM FACT_NOAGRE;
DELETE FROM FACT_FORM_MES_TMP;
DELETE FROM FACT_FORM_SAT_TMP;
DELETE FROM FACT_FOL_DEV;
DELETE FROM FACT_DEV;

-- 1) folios faltantes en FAC_SVR_SHAP segun criterio de consulta base
INSERT INTO FACT_NOAGRE (IDFOL, SUC, FCN)
SELECT
  A.IDFOL,
  A.SUC,
  TRY_CONVERT(DATETIME, A.FCNM) AS FCN
FROM dbo.PV_CTR_FOL_ASVR A
LEFT JOIN dbo.FAC_SVR_SHAP F
  ON F.IDFOL = A.IDFOL
WHERE TRY_CONVERT(DATETIME, A.FCNM) >= @FechaInicio
  AND TRY_CONVERT(INT, A.REQF) IN (1, -1)
  AND F.IDFOL IS NULL
  AND LTRIM(RTRIM(ISNULL(A.IDFOL, ''))) <> ''
  AND LTRIM(RTRIM(ISNULL(A.SUC, ''))) <> '';

-- 2) staging de formas de pago de folios faltantes
INSERT INTO FACT_FORM_MES_TMP
(
  IDF, IDFOL, FCN, FORM, IMPA, IMPP, IMPC, IMPD, AUT, FCNS, M, A
)
SELECT
  F.IDF,
  F.IDFOL,
  F.FCN,
  F.FORM,
  F.IMPA,
  F.IMPP,
  F.IMPC,
  F.IMPD,
  F.AUT,
  CONCAT(DAY(F.FCN), MONTH(F.FCN), YEAR(F.FCN)) AS FCNS,
  MONTH(F.FCN) AS M,
  YEAR(F.FCN) AS A
FROM FACT_NOAGRE N
INNER JOIN dbo.PV_CTR_FOL_FORM F
  ON F.IDFOL = N.IDFOL;

;WITH FormasRank AS (
  SELECT
    T.IDFOL,
    UPPER(LTRIM(RTRIM(ISNULL(T.FORM, '')))) AS FORM,
    NULLIF(LTRIM(RTRIM(ISNULL(T.AUT, ''))), '') AS AUT,
    ABS(TRY_CONVERT(MONEY, COALESCE(T.IMPP, T.IMPD, T.IMPA, T.IMPC, 0))) AS IMPMAX,
    ROW_NUMBER() OVER (
      PARTITION BY T.IDFOL
      ORDER BY ABS(TRY_CONVERT(MONEY, COALESCE(T.IMPP, T.IMPD, T.IMPA, T.IMPC, 0))) DESC, T.IDF DESC
    ) AS RN
  FROM FACT_FORM_MES_TMP T
)
INSERT INTO FACT_FORM_SAT_TMP (IDFOL, NAUT, IMPMAX, ASPEL)
SELECT
  R.IDFOL,
  R.AUT AS NAUT,
  ISNULL(R.IMPMAX, 0) AS IMPMAX,
  COALESCE(NULLIF(LTRIM(RTRIM(DF.ASPEL)), ''), R.FORM) AS ASPEL
FROM FormasRank R
LEFT JOIN dbo.DAT_FORM DF
  ON UPPER(LTRIM(RTRIM(ISNULL(DF.FORM, '')))) = R.FORM
WHERE R.RN = 1;

-- 3) importes devueltos por folio faltante (para ajustar IMPT de cabecera)
;WITH ImporteDevuelto AS (
  SELECT
    N.IDFOL,
    SUM(
      CASE
        WHEN ISNULL(S.IVA_INTEGRADO, 1) = -1
          THEN ISNULL(T.CTDDF, 0) * ISNULL(T.PVTA, 0)
        ELSE (ISNULL(T.CTDDF, 0) * ISNULL(T.PVTA, 0)) * 1.16
      END
    ) AS IMPTD
  FROM FACT_NOAGRE N
  INNER JOIN dbo.PV_CTR_FOL_ASVR A
    ON A.IDFOL = N.IDFOL
  LEFT JOIN dbo.DAT_SUC S
    ON S.SUC = A.SUC
  LEFT JOIN dbo.PV_TICKET_LOG T
    ON T.IDFOL = N.IDFOL
  WHERE ISNULL(T.CTDDF, 0) > 0
  GROUP BY N.IDFOL
)
INSERT INTO FACT_FOL_DEV (IDFOLDEV, IMPTD)
SELECT
  D.IDFOL,
  ISNULL(D.IMPTD, 0) AS IMPTD
FROM ImporteDevuelto D;

-- 4) insercion de detalle de articulos en facturacion para folios faltantes
DELETE T
FROM FACT_TICKET_SHP T
INNER JOIN FACT_NOAGRE N
  ON N.IDFOL = T.IDFOL;

INSERT INTO FACT_TICKET_SHP
(
  IDD, IDFOL, UPC, NoIdentificacion, Descripcion, Cantidad,
  ValorUnitario, PVTAT, ORD, IDDEV, CTDD, CTDDF,
  ClaveProdServ, Unidad, ObjetoImp, IvaTasa
)
SELECT
  T.ID AS IDD,
  T.IDFOL,
  T.UPC,
  T.ART AS NoIdentificacion,
  T.DES AS Descripcion,
  (ISNULL(T.CTD, 0) - ISNULL(T.CTDDF, 0)) AS Cantidad,
  CASE
    WHEN ISNULL(S.IVA_INTEGRADO, 1) = -1 THEN ISNULL(T.PVTA, 0) / 1.16
    ELSE ISNULL(T.PVTA, 0)
  END AS ValorUnitario,
  CASE
    WHEN ISNULL(S.IVA_INTEGRADO, 1) = -1
      THEN (ISNULL(T.PVTA, 0) / 1.16) * (ISNULL(T.CTD, 0) - ISNULL(T.CTDDF, 0))
    ELSE ISNULL(T.PVTA, 0) * (ISNULL(T.CTD, 0) - ISNULL(T.CTDDF, 0))
  END AS PVTAT,
  T.ORD,
  T.IDDEV,
  T.CTDD,
  T.CTDDF,
  A.CLAVESAT AS ClaveProdServ,
  A.UNIMEDSAT AS Unidad,
  '2' AS ObjetoImp,
  '.16' AS IvaTasa
FROM FACT_NOAGRE N
INNER JOIN dbo.PV_TICKET_LOG T
  ON T.IDFOL = N.IDFOL
LEFT JOIN dbo.DAT_SUC S
  ON S.SUC = N.SUC
LEFT JOIN dbo.DAT_ART A
  ON A.ART = T.ART
 AND A.SUC = N.SUC
WHERE (ISNULL(T.CTD, 0) - ISNULL(T.CTDDF, 0)) > 0;

-- 5) insercion de cabecera faltante en FAC_SVR_SHAP
INSERT INTO FAC_SVR_SHAP
(
  SUC, IDFOL, CLIEN, FCN, FCNS, FormaPago, TarjetaUltimos4Digitos,
  TIPOVTA, REQF, RazonSocialReceptor, RfcReceptor, RfcEmisor, UsoCfdi,
  Tipofact, ESTATUS, IMPT, MetodoDePago, [MOD]
)
SELECT
  P.SUC,
  P.IDFOL,
  P.CLIEN,
  TRY_CONVERT(DATETIME, P.FCNM) AS FCN,
  CONCAT(
    DAY(TRY_CONVERT(DATETIME, P.FCNM)),
    MONTH(TRY_CONVERT(DATETIME, P.FCNM)),
    YEAR(TRY_CONVERT(DATETIME, P.FCNM))
  ) AS FCNS,
  FS.ASPEL AS FormaPago,
  FS.NAUT AS TarjetaUltimos4Digitos,
  P.AUT AS TIPOVTA,
  TRY_CONVERT(INT, P.REQF) AS REQF,
  C.RazonSocialReceptor,
  C.RfcReceptor,
  C.RfcEmisor,
  C.UsoCfdi,
  CASE
    WHEN EXISTS (
      SELECT 1
      FROM dbo.PV_CTR_FOL_FORM F
      WHERE F.IDFOL = P.IDFOL
        AND UPPER(LTRIM(RTRIM(ISNULL(F.FORM, '')))) = 'CREDITO'
    ) THEN 'CREDITO'
    WHEN UPPER(LTRIM(RTRIM(ISNULL(P.AUT, '')))) = 'VF' THEN 'INDIVIDUAL'
    ELSE 'CREDITO'
  END AS Tipofact,
  CASE
    WHEN (ISNULL(P.IMPT, 0) - ISNULL(D.IMPTD, 0)) > 0 THEN 'PENDIENTE'
    ELSE 'VTA DEV'
  END AS ESTATUS,
  (ISNULL(P.IMPT, 0) - ISNULL(D.IMPTD, 0)) AS IMPT,
  CASE
    WHEN UPPER(LTRIM(RTRIM(ISNULL(P.AUT, '')))) = 'VF' THEN 'PUE'
    ELSE 'PPD'
  END AS MetodoDePago,
  CASE
    WHEN ISNULL(D.IMPTD, 0) > 0 AND (ISNULL(P.IMPT, 0) - ISNULL(D.IMPTD, 0)) <= 0
      THEN CONCAT('DEV TOTAL ', CONVERT(VARCHAR(50), ISNULL(P.IMPT, 0)))
    WHEN ISNULL(D.IMPTD, 0) > 0
      THEN CONCAT('DEV PARCIAL IMPT ANT ', CONVERT(VARCHAR(50), ISNULL(P.IMPT, 0)))
    ELSE ''
  END AS [MOD]
FROM FACT_NOAGRE N
INNER JOIN dbo.PV_CTR_FOL_ASVR P
  ON P.IDFOL = N.IDFOL
LEFT JOIN FACT_FOL_DEV D
  ON D.IDFOLDEV = P.IDFOL
LEFT JOIN FACT_FORM_SAT_TMP FS
  ON FS.IDFOL = P.IDFOL
LEFT JOIN dbo.FACT_CLIENT_SHP C
  ON C.IDC = P.CLIEN;

-- 6) control de transmision de la corrida
INSERT INTO CTROL_TRAMISIONES (FNCT, TIP_TRANS, N_REG)
VALUES
(
  GETDATE(),
  'FACT',
  (SELECT COUNT(*) FROM FACT_NOAGRE)
);

-- 7) resumen final
SELECT
  @FechaInicio AS FECHA_INICIO,
  (SELECT COUNT(*) FROM FACT_NOAGRE) AS FOLIOS_FALTANTES_PROCESADOS,
  (SELECT COUNT(*) FROM FACT_TICKET_SHP T INNER JOIN FACT_NOAGRE N ON N.IDFOL = T.IDFOL) AS DETALLES_INSERTADOS,
  (SELECT COUNT(*) FROM FAC_SVR_SHAP F INNER JOIN FACT_NOAGRE N ON N.IDFOL = F.IDFOL) AS CABECERAS_INSERTADAS;
