IF OBJECT_ID('dbo.DAT_ART_MASIVA_TMP', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DAT_ART_MASIVA_TMP (
    ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_DAT_ART_MASIVA_TMP PRIMARY KEY,
    LOTE_ID UNIQUEIDENTIFIER NOT NULL,
    RENGLON INT NOT NULL,
    SUC NVARCHAR(5) NULL,
    TIPO NVARCHAR(255) NULL,
    ART NVARCHAR(10) NULL,
    UPC NVARCHAR(15) NULL,
    CLAVESAT FLOAT NULL,
    UNIMEDSAT NVARCHAR(255) NULL,
    DES NVARCHAR(255) NULL,
    STOCK FLOAT NULL,
    STOCK_MIN FLOAT NULL,
    ESTATUS NVARCHAR(255) NULL,
    DIA_REABASTO FLOAT NULL,
    PVTA MONEY NULL,
    CTOP MONEY NULL,
    PROV_1 FLOAT NULL,
    CTO_PROV1 MONEY NULL,
    PROV_2 FLOAT NULL,
    CTO_PROV2 MONEY NULL,
    PROV_3 FLOAT NULL,
    CTO_PROV3 MONEY NULL,
    UN_COMP NVARCHAR(255) NULL,
    FACT_COMP FLOAT NULL,
    UN_VTA NVARCHAR(255) NULL,
    FACT_VTA FLOAT NULL,
    BASE NVARCHAR(255) NULL,
    SPH FLOAT NULL,
    CYL FLOAT NULL,
    ADIC FLOAT NULL,
    DEPA FLOAT NULL,
    SUBD FLOAT NULL,
    CLAS FLOAT NULL,
    SCLA FLOAT NULL,
    SCLA2 FLOAT NULL,
    UMUE FLOAT NULL,
    UTRA FLOAT NULL,
    UNIV FLOAT NULL,
    UFRE FLOAT NULL,
    BLOQ INT NULL,
    MARCA NVARCHAR(255) NULL,
    MODELO VARCHAR(MAX) NULL,
    USUARIO_CARGA NVARCHAR(100) NULL,
    ESTADO NVARCHAR(20) NOT NULL CONSTRAINT DF_DAT_ART_MASIVA_TMP_ESTADO DEFAULT ('PENDIENTE'),
    ERROR_DETALLE NVARCHAR(500) NULL,
    CREADO_EN DATETIME2(0) NOT NULL CONSTRAINT DF_DAT_ART_MASIVA_TMP_CREADO_EN DEFAULT (SYSUTCDATETIME()),
    PROCESADO_EN DATETIME2(0) NULL
  );
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.DAT_ART_MASIVA_TMP')
    AND name = 'IX_DAT_ART_MASIVA_TMP_LOTE_ESTADO'
)
BEGIN
  CREATE INDEX IX_DAT_ART_MASIVA_TMP_LOTE_ESTADO
    ON dbo.DAT_ART_MASIVA_TMP (LOTE_ID, ESTADO, ID);
END
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.DAT_ART_MASIVA_TMP')
    AND name = 'IX_DAT_ART_MASIVA_TMP_LOTE_KEY'
)
BEGIN
  CREATE INDEX IX_DAT_ART_MASIVA_TMP_LOTE_KEY
    ON dbo.DAT_ART_MASIVA_TMP (LOTE_ID, SUC, ART, UPC, ID);
END
GO
