IF OBJECT_ID('dbo.DAT_ALMACEN', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DAT_ALMACEN (
    ALMACEN VARCHAR(255) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    ACTIVO BIT NULL,
    FCNR DATETIME NULL,
    CONSTRAINT PK_DAT_ALMACEN PRIMARY KEY (ALMACEN)
  );
END;
GO
