USE IOELOCAL;
SET NOCOUNT ON;
SET XACT_ABORT ON;

/*
  Script de aplicacion directa (one-shot):
    - Recalcula DAT_ART.STOCK desde DAT_MB51 por SUC + ART.
    - Si un articulo/sucursal no existe en DAT_MB51, STOCK queda en 0.
    - Normaliza llaves (TRIM + UPPER) para evitar fallas por formato.
*/

IF OBJECT_ID('tempdb..#MB51_SUM') IS NOT NULL
  DROP TABLE #MB51_SUM;

SELECT
    SUC_NORM = UPPER(LTRIM(RTRIM(CONVERT(nvarchar(50), M.SUC))))
  , ART_NORM = UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100), M.ART))))
  , STOCK_CALCULADO = SUM(CONVERT(float, ISNULL(M.CTDA, 0)))
INTO #MB51_SUM
FROM dbo.DAT_MB51 AS M WITH (READCOMMITTEDLOCK)
GROUP BY
    UPPER(LTRIM(RTRIM(CONVERT(nvarchar(50), M.SUC))))
  , UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100), M.ART))));

CREATE UNIQUE CLUSTERED INDEX CX_MB51_SUM
  ON #MB51_SUM (SUC_NORM, ART_NORM);

BEGIN TRAN;

  UPDATE A
     SET A.STOCK = ISNULL(S.STOCK_CALCULADO, 0)
  FROM dbo.DAT_ART AS A
  OUTER APPLY (
    SELECT
        SUC_NORM = UPPER(LTRIM(RTRIM(CONVERT(nvarchar(50), A.SUC))))
      , ART_NORM = UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100), A.ART))))
  ) AS K
  LEFT JOIN #MB51_SUM AS S
    ON S.SUC_NORM = K.SUC_NORM
   AND S.ART_NORM = K.ART_NORM
  WHERE ISNULL(A.STOCK, 0) <> ISNULL(S.STOCK_CALCULADO, 0);

  DECLARE @rows_updated bigint = @@ROWCOUNT;

COMMIT TRAN;

SELECT
    ROWS_UPDATED = @rows_updated
  , ROWS_MB51_AGG = (SELECT COUNT_BIG(1) FROM #MB51_SUM)
  , ROWS_DAT_ART = (SELECT COUNT_BIG(1) FROM dbo.DAT_ART);

/*
  Validacion de ejemplo:

  SELECT A.SUC, A.ART, A.STOCK, ISNULL(M.STOCK_CALCULADO, 0) AS STOCK_MB51
  FROM dbo.DAT_ART A
  LEFT JOIN #MB51_SUM M
    ON M.SUC_NORM = UPPER(LTRIM(RTRIM(CONVERT(nvarchar(50), A.SUC))))
   AND M.ART_NORM = UPPER(LTRIM(RTRIM(CONVERT(nvarchar(100), A.ART))))
  WHERE A.ART = '3000009'
  ORDER BY A.SUC;
*/
