/*
  fact_unificacion_schema.sql

  Objetivo:
  - Asegurar estructura mínima para unificación/reversa de facturación.
  - Mantener ejecución idempotente en SQL Server.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID('dbo.FAC_SVR_SHAP', 'U') IS NULL
  THROW 51100, 'No existe dbo.FAC_SVR_SHAP', 1;

IF OBJECT_ID('dbo.FAC_CTRL_GRUP_MASV', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.FAC_CTRL_GRUP_MASV (
    GRUPMAS NVARCHAR(255) NOT NULL,
    FCNCREA DATETIME NULL,
    NFAC FLOAT NULL,
    ESTATUS NVARCHAR(255) NULL,
    CONSTRAINT PK_FAC_CTRL_GRUP_MASV PRIMARY KEY CLUSTERED (GRUPMAS)
  );
END;

IF COL_LENGTH('dbo.FAC_CTRL_GRUP_MASV', 'GRUPMAS') IS NULL
  ALTER TABLE dbo.FAC_CTRL_GRUP_MASV ADD GRUPMAS NVARCHAR(255) NULL;
IF COL_LENGTH('dbo.FAC_CTRL_GRUP_MASV', 'FCNCREA') IS NULL
  ALTER TABLE dbo.FAC_CTRL_GRUP_MASV ADD FCNCREA DATETIME NULL;
IF COL_LENGTH('dbo.FAC_CTRL_GRUP_MASV', 'NFAC') IS NULL
  ALTER TABLE dbo.FAC_CTRL_GRUP_MASV ADD NFAC FLOAT NULL;
IF COL_LENGTH('dbo.FAC_CTRL_GRUP_MASV', 'ESTATUS') IS NULL
  ALTER TABLE dbo.FAC_CTRL_GRUP_MASV ADD ESTATUS NVARCHAR(255) NULL;

IF COL_LENGTH('dbo.FAC_CTRL_GRUP_MASV', 'GRUPMAS') IS NOT NULL
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM sys.key_constraints
    WHERE parent_object_id = OBJECT_ID('dbo.FAC_CTRL_GRUP_MASV')
      AND [type] = 'PK'
  )
  BEGIN
    ALTER TABLE dbo.FAC_CTRL_GRUP_MASV
      ALTER COLUMN GRUPMAS NVARCHAR(255) NOT NULL;

    ALTER TABLE dbo.FAC_CTRL_GRUP_MASV
      ADD CONSTRAINT PK_FAC_CTRL_GRUP_MASV PRIMARY KEY CLUSTERED (GRUPMAS);
  END;
END;

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'GRUPMASI') IS NULL
  ALTER TABLE dbo.FAC_SVR_SHAP ADD GRUPMASI NVARCHAR(255) NULL;

IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'GRUPMASI') IS NOT NULL
   AND COL_LENGTH('dbo.FAC_SVR_SHAP', 'IDFOL') IS NOT NULL
   AND NOT EXISTS (
     SELECT 1
     FROM sys.indexes
     WHERE object_id = OBJECT_ID('dbo.FAC_SVR_SHAP')
       AND name = 'IX_FAC_SVR_SHAP_GRUPMASI_IDFOL'
   )
BEGIN
  CREATE NONCLUSTERED INDEX IX_FAC_SVR_SHAP_GRUPMASI_IDFOL
    ON dbo.FAC_SVR_SHAP (GRUPMASI, IDFOL);
END;

IF COL_LENGTH('dbo.FAC_CTRL_GRUP_MASV', 'ESTATUS') IS NOT NULL
   AND NOT EXISTS (
     SELECT 1
     FROM sys.indexes
     WHERE object_id = OBJECT_ID('dbo.FAC_CTRL_GRUP_MASV')
       AND name = 'IX_FAC_CTRL_GRUP_MASV_ESTATUS'
   )
BEGIN
  CREATE NONCLUSTERED INDEX IX_FAC_CTRL_GRUP_MASV_ESTATUS
    ON dbo.FAC_CTRL_GRUP_MASV (ESTATUS, FCNCREA);
END;

