IF OBJECT_ID('dbo.JA_NVO_ART_CON', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.JA_NVO_ART_CON (
    BatchId UNIQUEIDENTIFIER NOT NULL,
    RowNum INT NOT NULL,
    Status NVARCHAR(20) NOT NULL CONSTRAINT DF_JA_NVO_ART_CON_Status DEFAULT ('PENDING'),
    ErrorMsg NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2(0) NOT NULL CONSTRAINT DF_JA_NVO_ART_CON_CreatedAt DEFAULT (SYSUTCDATETIME()),

    SUC NVARCHAR(5) NULL,
    TIPO NVARCHAR(255) NULL,
    ART NVARCHAR(10) NULL,
    UPC NVARCHAR(15) NULL,
    CLAVESAT NVARCHAR(50) NULL,
    UNIMEDSAT NVARCHAR(255) NULL,
    DES NVARCHAR(255) NULL,
    STOCK NVARCHAR(50) NULL,
    STOCK_MIN NVARCHAR(50) NULL,
    ESTATUS NVARCHAR(255) NULL,
    DIA_REABASTO NVARCHAR(50) NULL,
    PVTA NVARCHAR(50) NULL,
    CTOP NVARCHAR(50) NULL,
    PROV_1 NVARCHAR(50) NULL,
    CTO_PROV1 NVARCHAR(50) NULL,
    PROV_2 NVARCHAR(50) NULL,
    CTO_PROV2 NVARCHAR(50) NULL,
    PROV_3 NVARCHAR(50) NULL,
    CTO_PROV3 NVARCHAR(50) NULL,
    UN_COMP NVARCHAR(255) NULL,
    FACT_COMP NVARCHAR(50) NULL,
    UN_VTA NVARCHAR(255) NULL,
    FACT_VTA NVARCHAR(50) NULL,
    BASE NVARCHAR(255) NULL,
    SPH NVARCHAR(50) NULL,
    CYL NVARCHAR(50) NULL,
    ADIC NVARCHAR(50) NULL,
    DEPA NVARCHAR(50) NULL,
    SUBD NVARCHAR(50) NULL,
    CLAS NVARCHAR(50) NULL,
    SCLA NVARCHAR(50) NULL,
    SCLA2 NVARCHAR(50) NULL,
    UMUE NVARCHAR(50) NULL,
    UTRA NVARCHAR(50) NULL,
    UNIV NVARCHAR(50) NULL,
    UFRE NVARCHAR(50) NULL,
    BLOQ NVARCHAR(20) NULL,
    MARCA NVARCHAR(255) NULL,
    MODELO NVARCHAR(MAX) NULL
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.JA_NVO_ART_CON')
    AND name = 'IX_JA_NVO_ART_CON_Batch_Row'
)
BEGIN
  CREATE INDEX IX_JA_NVO_ART_CON_Batch_Row
    ON dbo.JA_NVO_ART_CON (BatchId, RowNum);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.JA_NVO_ART_CON')
    AND name = 'IX_JA_NVO_ART_CON_Batch_Status'
)
BEGIN
  CREATE INDEX IX_JA_NVO_ART_CON_Batch_Status
    ON dbo.JA_NVO_ART_CON (BatchId, Status);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.JA_NVO_ART_CON')
    AND name = 'IX_JA_NVO_ART_CON_Batch_UPC'
)
BEGIN
  CREATE INDEX IX_JA_NVO_ART_CON_Batch_UPC
    ON dbo.JA_NVO_ART_CON (BatchId, UPC);
END;
GO
