IF OBJECT_ID('dbo.PV_DEV_DET_TMP', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PV_DEV_DET_TMP (
    ID NVARCHAR(36) NOT NULL,
    IDFOLDEV NVARCHAR(255) NOT NULL,
    IDFOLORIG NVARCHAR(255) NOT NULL,
    IDLINE_ORIG NVARCHAR(255) NULL,
    ART NVARCHAR(255) NULL,
    UPC NVARCHAR(255) NULL,
    DES NVARCHAR(255) NULL,
    CTD FLOAT NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_CTD DEFAULT (0),
    PVTA MONEY NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_PVTA DEFAULT (0),
    PVTAT MONEY NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_PVTAT DEFAULT (0),
    ORD NVARCHAR(255) NULL,
    CTDDF FLOAT NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_CTDDF DEFAULT (0),
    DIFD FLOAT NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_DIFD DEFAULT (0),
    CTDD FLOAT NULL,
    FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_FCNR DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT PK_PV_DEV_DET_TMP PRIMARY KEY CLUSTERED (ID)
  );
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'IDFOLDEV') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD IDFOLDEV NVARCHAR(255) NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_IDFOLDEV DEFAULT ('');
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'IDFOLORIG') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD IDFOLORIG NVARCHAR(255) NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_IDFOLORIG DEFAULT ('');
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'IDLINE_ORIG') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD IDLINE_ORIG NVARCHAR(255) NULL;
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'ART') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD ART NVARCHAR(255) NULL;
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'UPC') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD UPC NVARCHAR(255) NULL;
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'DES') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD DES NVARCHAR(255) NULL;
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'CTD') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD CTD FLOAT NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_CTD_V2 DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'PVTA') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD PVTA MONEY NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_PVTA_V2 DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'PVTAT') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD PVTAT MONEY NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_PVTAT_V2 DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'ORD') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD ORD NVARCHAR(255) NULL;
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'CTDDF') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD CTDDF FLOAT NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_CTDDF_V2 DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'DIFD') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD DIFD FLOAT NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_DIFD_V2 DEFAULT (0);
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'CTDD') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD CTDD FLOAT NULL;
END;
GO

IF COL_LENGTH('dbo.PV_DEV_DET_TMP', 'FCNR') IS NULL
BEGIN
  ALTER TABLE dbo.PV_DEV_DET_TMP ADD FCNR DATETIME2(0) NOT NULL CONSTRAINT DF_PV_DEV_DET_TMP_FCNR_V2 DEFAULT (SYSUTCDATETIME());
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PV_DEV_DET_TMP')
    AND name = 'IX_PV_DEV_DET_TMP_IDFOLDEV'
)
BEGIN
  CREATE INDEX IX_PV_DEV_DET_TMP_IDFOLDEV
  ON dbo.PV_DEV_DET_TMP (IDFOLDEV)
  INCLUDE (IDFOLORIG, IDLINE_ORIG, ART, ORD, DIFD, CTDD);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE object_id = OBJECT_ID('dbo.PV_DEV_DET_TMP')
    AND name = 'IX_PV_DEV_DET_TMP_IDFOLORIG'
)
BEGIN
  CREATE INDEX IX_PV_DEV_DET_TMP_IDFOLORIG
  ON dbo.PV_DEV_DET_TMP (IDFOLORIG);
END;
GO
