USE [IOELOCAL];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE [dbo].[sp_cont_sync_captura_conteo]
  @SUC  NVARCHAR(5),
  @CONT NVARCHAR(255)
AS
BEGIN
  SET NOCOUNT ON;
  SET XACT_ABORT ON;

  DECLARE @updatedRows INT = 0;
  DECLARE @insertedRows INT = 0;

  ;WITH cap AS (
    SELECT
      UPPER(LTRIM(RTRIM(c.ART))) AS ART_KEY,
      SUM(CASE WHEN c.ALMACEN = '001'  THEN c.CANT ELSE 0 END) AS CAP001,
      SUM(CASE WHEN c.ALMACEN = '002'  THEN c.CANT ELSE 0 END) AS CAP002,
      SUM(CASE WHEN c.ALMACEN = 'M001' THEN c.CANT ELSE 0 END) AS CAPM1,
      SUM(CASE WHEN c.ALMACEN = 'T001' THEN c.CANT ELSE 0 END) AS CAPT1
    FROM dbo.DAT_CONT_CAPTURA c
    WHERE c.SUC = @SUC
      AND c.CONT = @CONT
    GROUP BY UPPER(LTRIM(RTRIM(c.ART)))
  )
  UPDATE det
     SET
      [001] = ISNULL(cap.CAP001, 0),
      [002] = ISNULL(cap.CAP002, 0),
      M001 = ISNULL(cap.CAPM1, 0),
      T001 = ISNULL(cap.CAPT1, 0),
      TOTAL = ISNULL(cap.CAP001, 0) + ISNULL(cap.CAP002, 0) + ISNULL(cap.CAPM1, 0) + ISNULL(cap.CAPT1, 0),
      DIF_01 = ISNULL(cap.CAP001, 0) - ISNULL(det.MB52_01, 0),
      DIF_02 = ISNULL(cap.CAP002, 0) - ISNULL(det.MB52_02, 0),
      DIF_M1 = ISNULL(cap.CAPM1, 0) - ISNULL(det.MB52_M1, 0),
      DIF_T1 = ISNULL(cap.CAPT1, 0) - ISNULL(det.MB52_T1, 0),
      DIF_T = (ISNULL(cap.CAP001, 0) + ISNULL(cap.CAP002, 0) + ISNULL(cap.CAPM1, 0) + ISNULL(cap.CAPT1, 0)) - ISNULL(det.MB52_T, 0),
      DIF_CTOP = (
        (ISNULL(cap.CAP001, 0) + ISNULL(cap.CAP002, 0) + ISNULL(cap.CAPM1, 0) + ISNULL(cap.CAPT1, 0)) - ISNULL(det.MB52_T, 0)
      ) * ISNULL(det.CTOP, 0)
  FROM dbo.DAT_DET_SVR det
  LEFT JOIN cap
    ON cap.ART_KEY = UPPER(LTRIM(RTRIM(det.ART)))
  WHERE det.SUC = @SUC
    AND det.CONT = @CONT;

  SET @updatedRows = @@ROWCOUNT;

  ;WITH cap AS (
    SELECT
      UPPER(LTRIM(RTRIM(c.ART))) AS ART_KEY,
      MAX(LTRIM(RTRIM(c.ART))) AS ART_VALUE,
      SUM(CASE WHEN c.ALMACEN = '001'  THEN c.CANT ELSE 0 END) AS CAP001,
      SUM(CASE WHEN c.ALMACEN = '002'  THEN c.CANT ELSE 0 END) AS CAP002,
      SUM(CASE WHEN c.ALMACEN = 'M001' THEN c.CANT ELSE 0 END) AS CAPM1,
      SUM(CASE WHEN c.ALMACEN = 'T001' THEN c.CANT ELSE 0 END) AS CAPT1
    FROM dbo.DAT_CONT_CAPTURA c
    WHERE c.SUC = @SUC
      AND c.CONT = @CONT
    GROUP BY UPPER(LTRIM(RTRIM(c.ART)))
  )
  INSERT INTO dbo.DAT_DET_SVR (
    SUC, CONT, ART, UPC, DES, CTOP, TOTAL, MB52_T, DIF_T, DIF_CTOP,
    [001], [002], M001, T001, MB52_01, MB52_02, MB52_M1, MB52_T1, DIF_01, DIF_02, DIF_M1, DIF_T1
  )
  SELECT
    @SUC AS SUC,
    @CONT AS CONT,
    cap.ART_VALUE AS ART,
    artRef.UPC,
    artRef.DES,
    ISNULL(artRef.CTOP, 0) AS CTOP,
    (ISNULL(cap.CAP001, 0) + ISNULL(cap.CAP002, 0) + ISNULL(cap.CAPM1, 0) + ISNULL(cap.CAPT1, 0)) AS TOTAL,
    0 AS MB52_T,
    (ISNULL(cap.CAP001, 0) + ISNULL(cap.CAP002, 0) + ISNULL(cap.CAPM1, 0) + ISNULL(cap.CAPT1, 0)) AS DIF_T,
    0 AS DIF_CTOP,
    ISNULL(cap.CAP001, 0) AS [001],
    ISNULL(cap.CAP002, 0) AS [002],
    ISNULL(cap.CAPM1, 0) AS M001,
    ISNULL(cap.CAPT1, 0) AS T001,
    0 AS MB52_01,
    0 AS MB52_02,
    0 AS MB52_M1,
    0 AS MB52_T1,
    ISNULL(cap.CAP001, 0) AS DIF_01,
    ISNULL(cap.CAP002, 0) AS DIF_02,
    ISNULL(cap.CAPM1, 0) AS DIF_M1,
    ISNULL(cap.CAPT1, 0) AS DIF_T1
  FROM cap
  OUTER APPLY (
    SELECT TOP (1)
      a.UPC,
      a.DES,
      a.CTOP
    FROM dbo.DAT_ART a
    WHERE a.SUC = @SUC
      AND UPPER(LTRIM(RTRIM(a.ART))) = cap.ART_KEY
    ORDER BY a.UPC ASC
  ) artRef
  WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.DAT_DET_SVR det
    WHERE det.SUC = @SUC
      AND det.CONT = @CONT
      AND UPPER(LTRIM(RTRIM(det.ART))) = cap.ART_KEY
  );

  SET @insertedRows = @@ROWCOUNT;

  SELECT
    @SUC AS SUC,
    @CONT AS CONT,
    @updatedRows AS UPDATED_ROWS,
    @insertedRows AS INSERTED_ROWS,
    COUNT(*) AS CAPTURAS_TOTAL,
    COUNT(DISTINCT UPPER(LTRIM(RTRIM(ART)))) AS ARTICULOS_CAPTURADOS,
    SUM(CASE WHEN ALMACEN = '001'  THEN CANT ELSE 0 END) AS CAP_001,
    SUM(CASE WHEN ALMACEN = '002'  THEN CANT ELSE 0 END) AS CAP_002,
    SUM(CASE WHEN ALMACEN = 'M001' THEN CANT ELSE 0 END) AS CAP_M1,
    SUM(CASE WHEN ALMACEN = 'T001' THEN CANT ELSE 0 END) AS CAP_T1,
    SUM(CANT) AS CAP_TOTAL
  FROM dbo.DAT_CONT_CAPTURA
  WHERE SUC = @SUC
    AND CONT = @CONT;
END;
GO
