SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE dbo.sp_fact_backfill_fcnf
AS
BEGIN
  SET NOCOUNT ON;

  IF OBJECT_ID('dbo.FAC_SVR_SHAP', 'U') IS NULL
  BEGIN
    RAISERROR('No existe tabla dbo.FAC_SVR_SHAP', 16, 1);
    RETURN;
  END

  IF COL_LENGTH('dbo.FAC_SVR_SHAP', 'FCNF') IS NULL
  BEGIN
    RAISERROR('No existe columna FCNF en dbo.FAC_SVR_SHAP', 16, 1);
    RETURN;
  END

  UPDATE f
    SET f.FCNF = ISNULL(f.CFDI_F_TIMBRADO, GETDATE())
  FROM dbo.FAC_SVR_SHAP f
  WHERE UPPER(LTRIM(RTRIM(ISNULL(CAST(f.ESTATUS AS NVARCHAR(255)), '')))) = 'FACTURADO'
    AND f.FCNF IS NULL;

  SELECT @@ROWCOUNT AS UPDATED_ROWS;
END
GO
